### ISSUE TITLE
Broken Wide Tables

### ISSUE THREAD

**Issue by ReknPts11** [naturalcrit/homebrewery#1024]
So I'm trying to add weapons for my homebrewed campaign setting (don't test me, it's my campaign) and it absolutely **refuses** to let me make it in a wide table. It asks me to close it so I do, and this happens.

![hkycjf gvbnihktvybgjcfnr frdykgvblnt cifbl ](https://user-images.githubusercontent.com/70123396/91000335-8c4a0780-e58e-11ea-9091-99d6a013b837.png)

If I leave it unclosed, it looks fine in the editor, but looks the same as the above picture when exported to pdf. What do I do?

**Comment by Mikle103** [comment]
remove the greater than symbol at start of each line.

**Comment by Mikle103** [comment]
Hi I have been playing around trying to find a solution for you.

Add the following to your style block
`.phb {
  	column-count: 1;
  }`

And remove your  div's and leave you grater than symbols in 

Look at link in first comment for result.
Here is a copy of exported PDF 
[test.pdf](https://github.com/naturalcrit/homebrewery/files/5122118/test.pdf)

**Comment by ericscheid** [comment]
There are various bugs to do with embedding markdown within html block elements and mixing block elements with markdown code .. which is what you're achieving with the `>` codes inside `div`.

We're looking to fix all these with a revamp of the renderer in #1093.

----

Those `>` line prefixes are markdown syntax for creating a blockquote .. is that really what you are wanting to do here though? Remove them if not, and this will stop triggering this bug too.

If you really do want to do that, there is a way of simulating a `<blockquote>` by styling up a `<div>`, and that will work with HB.

**Comment by ericscheid** [comment]
An interim fix should be possible by extending this code that is markdown.js to also do the same for any `<blockquote>` blocks.

This is just layering another bandaid on top of another bandaid though (and even _marked.js_ knows they have a problem with processing block html that differs from CommonMark, so any fix we do might get mangled by a fix they do).

Leaving this as a possible Tweak for a volunteer.

```
//Processes the markdown within an HTML block if it's just a class-wrapper
renderer.html = function (html) {
	if(_.startsWith(_.trim(html), '<div') && _.endsWith(_.trim(html), '</div>')){
		const openTag = html.substring(0, html.indexOf('>')+1);
		html = html.substring(html.indexOf('>')+1);
		html = html.substring(0, html.lastIndexOf('</div>'));
		return `${openTag} ${Markdown(html)} </div>`;
	}
	return html;
};
```

**Comment by calculuschild** [comment]
Wide tables should work totally fine in V3 by wrapping tables in the new curly syntax: `{{wide... `
