### ISSUE TITLE
[request] command-line interface without need starting Chrome 

### ISSUE THREAD

**Issue by ttpro1995** [naturalcrit/homebrewery#1035]
I suggest making an standalone app that does not depend on Chrome thing, Something similar to Latex. It can run from command line without starting any server. 

like this: 
```
homebrewery input.md output.pdf 
```

Because I can write stuff on file system (markdown file with text editor) and integrate with .git easily without need to copy and paste stuff from file to Chrome every time I build.

**Comment by RKuerten** [comment]
There's this homebrewery app built on electron: https://github.com/noahlange/homebrewery-electron. It is basically what you're requesting.

**Comment by AlexeySachkov** [comment]
Duplicate of #802?

**Comment by dbolack-ab** [comment]
Going to close this as effectively duplicate of #802 as noted.
