### ISSUE TITLE
Nmp Vitrium hang up on install

### ISSUE THREAD

**Issue by Fireballin17** [naturalcrit/homebrewery#1056]
Hi all, 

Having an issue trying an npm install for the offline version of home-brewery, continues to hang when trying to extract vitrium and locks, 

Any ideas?

**Comment by calculuschild** [comment]
Do you mean npm install is not able to complete?

**Comment by Fireballin17** [comment]
Yes, the npm install is unable to complete, hanging (Freezing and locking) whenever it gets to the vitrium libraries.

**Comment by calculuschild** [comment]
What if you run `npm install github:calculuschild/vitreum#21a8e1c9421f1d3a3b474c12f480feb2fbd28c5b`

**Comment by Fireballin17** [comment]
Let me try and I'll get back to you

**Comment by Fireballin17** [comment]
npm is v 6.14.8

And if I run the command I get errors

**Comment by Fireballin17** [comment]
I do have a log file
[2020-10-21T19_51_44_897Z-debug.log](https://github.com/naturalcrit/homebrewery/files/5418412/2020-10-21T19_51_44_897Z-debug.log)

**Comment by calculuschild** [comment]
Ok, interesting. Can you paste the errors up here so I can check what's
going on?

**Comment by Fireballin17** [comment]
Sure,

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/calculuschild/vitreum.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by calculuschild** [comment]
Hmmmmmm.... do you happen to have Git installed? That might be the reason. I use a custom version of Vitreum that installs directly from Github instead of the usual NPM package store.

**Comment by Fireballin17** [comment]
I don't have git installed, I'll get that now. Give me a moment.

**Comment by Fireballin17** [comment]
Tried again and this time its not an instant error,

The progress bar flashes up for a split second then the errors arrive, heres the log.

[2020-10-21T20_09_57_685Z-debug.log](https://github.com/naturalcrit/homebrewery/files/5418477/2020-10-21T20_09_57_685Z-debug.log)

**Comment by Fireballin17** [comment]
Though hold the phone, just tried a standard install and got this as a result.

[2020-10-21T20_12_06_681Z-debug.log](https://github.com/naturalcrit/homebrewery/files/5418481/2020-10-21T20_12_06_681Z-debug.log)
[2020-10-21T20_11_37_915Z-debug.log](https://github.com/naturalcrit/homebrewery/files/5418482/2020-10-21T20_11_37_915Z-debug.log)

**Comment by calculuschild** [comment]
This looks like Git still isn't installed properly. If it is, you should be able to run GIT commands from the command line. For example, just typing "git" should come up with a bunch of options.

Depending how you installed, you may have seen this screen:
![image](https://user-images.githubusercontent.com/5878534/96777997-09400480-13b9-11eb-8e5d-223a11df84ea.png)

You need to select the option to allow running git on the command prompt. I'm assuming you're on Windows? If not there are other steps.

**Comment by Fireballin17** [comment]
I did select that, I was suspicious the command line hadn't loaded GIT, a quick restart later and its mostly working?

Complains about optional dependencies and skipping them but it has installed

**Comment by calculuschild** [comment]
Ok. The optional dependencies shouldn't be an issue. At this point you can probably run the app.

**Comment by Fireballin17** [comment]
Seems to be working. Though I cant connect to the localhost

**Comment by Fireballin17** [comment]
Keeps sending invalid responses

**Comment by calculuschild** [comment]
You may need to set the ENV variable to 'local', which you may need to do each time you close the command prompt. 
The steps are in the main page of the Homebrewery.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Fireballin17
