### ISSUE TITLE
Google Drive metadata not saving

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1083]
Includes view count, version, published, etc.

**Comment by ericscheid** [comment]
https://www.reddit.com/r/homebrewery/comments/jjz03d/last_changed_is_wrong_when_sync_with_google_drive/

**Comment by calculuschild** [comment]
The fix for this is ready and live on the staging site. https://homebrewery-stage.herokuapp.com/

Gives Google files the ability to save metadata, including view counts which now properly increase when the share page is visited.

Only thing that doesn't work is "published" google files will not show up if another user views your profile. This is because we need to know the Google Drive ID of that user to scan for their Homebrewery files and currently that data is not saved in our databases. They will still display as "published" when logged in to your own profile however.

**Comment by calculuschild** [comment]
Fixed with #1118
