### ISSUE TITLE
Improve page size and load speed

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1087]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fhomebrewery.naturalcrit.com%2F

- [x] Compress Javascript & CSS bundles
- [x] Remove unused code (entire "welcome" page is sent with EVERY request)
- [x] Compress images
- [x] Cache resources as much as possible

**Comment by ericscheid** [comment]
Those timings are weird .. 21.1s to interactive ?1?

But yes, gzipping static resources at a minimum.

As well as setting caching for those static resources (but deffo not the /edit/mumbles page)

**Comment by calculuschild** [comment]
PR #1098 compresses the static .js and .css bundles. Total size from 3.68 MB to 971 KB.

**Comment by ericscheid** [comment]
The images for border treatments of snippets and the red `hr` are all sourced via a data URI - nothing to cache there.

The favicon.ico image is cached.

The googleDrive.png and googleDriveMono.png images are not cached — they should be. 
They can also be compressed (306K → 62K, 18K → 2.4K)

The bundle.css and bundle.js files are not cached — they should be, but in a manner that can be easily invalidated.

**Comment by AlexeySachkov** [comment]
>  Cache resources as much as possible

I will take a look at that. I've got something working locally, but it needs a bit of adjustment and prettifying before being published as a PR

**Comment by calculuschild** [comment]
Each of the checklist items has been handled. Probably room for further improvement but we've improved quite a bit just with this. Closing.
