### ISSUE TITLE
API or route to produce CSS resource

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1097]
Due to some (many?) browsers being particularly persnicketty about cross-domain requests, it's getting increasingly harder to reference a CSS style sheet resource from a 3rd party domain.

This would normally be done with 

```
<style>
   @import url("https://3rdparty.com/my_wonderful_brew.css");
</style>
```
However, unless that resource is hosted by a server that knows to issue the correct media-type, the receiving browser will reject due to cross-domain concerns.

What would be handy would be for a HomeBrewery user is that they create a HB document into which they type all their CSS code (without wrapping with `<style>` and `</style>`), and then in their other brews they can write an @import to the same-domain resource (e.g. `@import url("/css/mumblecode")`.

The HB server mostly only needs to respond to `/css/:id` requests with just the brew content, no metadata, no UI chrome; and with the http header of `Content-Type: text/css`. It probably should do some sanitizing, just in case.

**Comment by ericscheid** [comment]
Hmm .. what are the security issues here? Could someone craft a particular CSS resource, attach it via a brew via @import, and then publish the /share/:id for that brew and somehow hurt visitors to the that shared brew?

Can JS be embedded inside CSS, for example?

**Comment by ericscheid** [comment]
Oh, nevermind, here comes IE ... 

https://dougrathbone.com/blog/2013/10/30/executing-javascript-inside-css-another-reason-to-whitelist-and-encode-user-input

**Comment by calculuschild** [comment]
I don't know... A separate CSS page was something @stolksdorf had originally planned and it would be nice to have. We already allow custom CSS directly within the main brew text, so I don't know that allowing a separate CSS import from a Homebrewery document would be any worse. We can prevent loading if the browser is IE. We can sanitize other input to some extent.

What do you think? If this would be a security issue, it seems we already have this problem because people could make a malicious document and share it via the existing share/:id links, right?

**Comment by ericscheid** [comment]
Good points. I was assuming the render of the brew is sanitized, including any `<style>` elements — the basic proposal here was for the raw brew to be served out. That doesn't have to be the case — the brew content could be sanitized on the `/css/:id` route too.

I've not tested what happens with `@import url(/source/:id)` .. there's a hidden bit of html served up that might confuse browsers into thinking it isn't actually css.

**Comment by Gazook89** [comment]
I'm all for this, but have nothing more to contribute than that...Was just searching to find out why a .css file hosted on my github was not loading on homebrewery.

**Comment by ericscheid** [comment]
Quite some time has passed, and we now have a separate editor pane for CSS. 

The contents of which are stored however in the same mongo document as the brew contents, not a separate document.

I think a `/css/:id` route for returning only the css part of a brew would still be helpful for shared/reusable css stylesheets (for the reasons above, i.e. avoiding cross-domain requests).

I would suggest though that it only returns the css document part, and not scan thru the brew for any `<style/>` chunks to include. That way a standardised stylesheet can be used (and re-used) without lumbering it with any brew-specific css. Plus, much simpler to code.

**Comment by 5e-Cleric** [comment]
I would love to be able to have common CSS between files, and be able to edit them all at the same time while watching the brew.
I realise this sounds very tricky, just wanted to throw it in.

**Comment by ericscheid** [comment]
Probably not that tricky.

This is how `/download/:id` is handled, and `/css/:id` would just be a variant of this, changing just line 205 and line 208.

https://github.com/naturalcrit/homebrewery/blob/52dcc3b53cbd197b92ebe0f9d314f3d9d08d9eba/server/app.js#L188-L209

**Comment by G-Ambatte** [comment]
My first thought is that if the two are that similar, we might be able to create a unified function to avoid code duplication.

**Comment by calculuschild** [comment]
> I think a /css/:id route for returning only the css part of a brew would still be helpful for shared/reusable css stylesheets (for the reasons above, i.e. avoiding cross-domain requests).

This is stepping on the toes of Custom Themes, which is the preferred approach to common CSS. Adding a `/css` route and using `@import` raises the question of potentially dangerous transclusion issues. From Gitter:

> We would want to ensure it's done in a way that doesn't trigger massive api calls. I could see a lot of potential grief from users including multiple nested layers of brews/circular dependencies that trigger dozens of brew fetches with each view.
For instance with custom user Themes, we will likely only allow one level of theme nesting (my brew imports a User theme, which cannot itself import a second User theme.) - calculuschild

**Comment by ericscheid** [comment]
The browser will resolve circular dependencies via caching. 😁

Themes are excellent, though they are a sledgehammer solution. Sometimes an author just wants something lighter, some common css bits and bobs. For example, I'd want to copy in some simple css for easily doing better `<dl>` stuff in whichever theme I'm currently using.

**Comment by 5e-Cleric** [comment]
> Sometimes an author just wants something lighter, some common css bits and bobs.

You're talking about custom snippets, #1722.

**Comment by ericscheid** [comment]
I have a mish mash of tweaks I add to brews, usually as I need them, to align with a preferred house style. Things like boxed text, nested lists using disc/circle/square bullets, nested lists not being so heavily indented, blockquotes, and more I've forgotten I've written (usually until about 5 minutes after re-inventing the wheel, yet again).

The pain I'm identifying is having to add in each custom snippet into my Style Editor tab for each new brew as the need is identified, along with knowing that if I tweak or fix for one brew I would need to go back and edit many multiple older brews. That and finding the older brew in which I did indeed already solve the problem so I can then copy/paste the Style Editor snippet. Was it this brew? Or does this one have the up to date version?

**Comment by calculuschild** [comment]
I know you don't like it, but this sounds like the exact use case for Custom Themes.

**Comment by ericscheid** [comment]
> I may be missing something, but this sounds like the exact use case for Custom Themes.

Not quite. I want to extend standard themes with a small set of tweaks and extensions.

Unless custom themes are designed to layer over the top of an existing theme, and not completely swap in replace? That is, I can have one custom theme for my house extensions, and then apply that to brews that use the PHB or DMG (or whatever) theme as their base.

**Comment by Gazook89** [comment]
Yeah, custom themes are built with a hierarchy. That’s why there is a Base theme, which PHB builds off of. You can see it in the themes folder…a json that includes a property whose value indicates which existing theme you are appending to.

**Comment by ericscheid** [comment]
I thought the built-in hierarchy of built-in themes is a separate thing from author managed custom themes. 

From the author's p.o.v., they select select a built-in theme (with the built-in hierarchy all managed behind the scenes, it's just code), and optionally also specify a share :id of a brew to use as a custom theme extension, which gets transcluded into the source such that it is applied after the selected brew theme but before the brew style editor css. Is that how it works? If I specify a custom theme it _doesn't_ unload the underlying main theme (and it's base theme)?

**Comment by calculuschild** [comment]
The way it is designed now, a custom theme would be a brew layered onto an HB theme. So you have:

1) blank theme
2) base theme (PHB)
3) selected HB theme (DMG)
4) custom theme stuff (lives in the style tab)

So when a user wants to use that custom theme in another brew, they select the shareId of that brew, and the current brew now has:

1) blank theme
2) base theme (PHB)
3) selected HB theme (DMG)
4) custom theme from other brew
5) current brew style tab

**Comment by calculuschild** [comment]
So Custom themes are inherently tied to a base theme and a main theme. You want to be able to import custom CSS that isn't tied to any specific base theme?

**Comment by ericscheid** [comment]
> So Custom themes are inherently tied to a base theme and a main theme. You want to be able to import custom CSS that isn't tied to any specific base theme?

I'd want to supply a reference to a custom collection of css rules that get applied to a document after that document's base theme has been applied, but before that document's brew.style. So .. I could then import the same custom CSS into brews that use a different base theme. This is particularly useful for e.g. PHB theme vs DMG theme, which are nearly identical .. othewise I'd need to create a "Custom Theme (PHB version)" alongside a "Custom Theme (DMG version)" [etc].

**Comment by dbolack-ab** [comment]
> Due to some (many?) browsers being particularly persnicketty about cross-domain requests, it's getting increasingly harder to reference a CSS style sheet resource from a 3rd party domain.
> 
> This would normally be done with
> 

I think the User Brew-based themes solve for this problem. Where it doesn't/can't, we could look at using the same code that #3501 uses to abstract proxy CSS loading.
