### ISSUE TITLE
[Feature Request] Save/Export CSS only

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1132]
Thinking more about saving/exporting features, it might be useful to have an option to save or export (to .css) the CSS definitions of a brew, separate from the content.  Basically just save what is inside any <style> tags, ignoring element-specific style='n'.  I think using external stylesheets is a little fuzzy right now (I couldn't get it to work, using a stylesheet uploaded to my github account), but if that is firmed up in the future then it would be handy to quickly grab the style definitions of a brew in progress and create a .css file from it that can then be uploaded somewhere.

**Comment by calculuschild** [comment]
Eventually we are going to have a second editor tab just for css, and they will be saved as two separate documents, so you can save a style sheet to your account and then reuse it elsewhere without needing two copies of your style.

This would even let users share style sheets with each other and support swapping style sheets (phb vs DMG vs whatever) a little easier.

So yes, we can add a download for that, but it will likely come after we have that second editor panel. This is a good idea.

**Comment by ericscheid** [comment]
See also https://github.com/naturalcrit/homebrewery/issues/1097

**Comment by Gazook89** [comment]
I think this can be closed with the addition of few things since this was opened:
- [x] Separate Style Editor window
- [x] Clone to New
- [ ] likely future addition of tags or folders

With these three things, it seems easy enough to separate out the CSS from the content, save the entire brew as a "Theme", and give it a "Theme" label/tag/folder for organization, then allow other users to find and clone it.  Even without tags, the current functionality covers the original issue.

Will leave it to someone else to close, though, in case I'm jumping the gun.
