### ISSUE TITLE
[Feature Request] UX Improvements around Saving

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1133]
There are a couple of improvements to the user interface that  I suggest in another issue thread but agree it's a good idea to create a new thread.  
____
UX
---
1. If brew is linked to Google Drive, some indicator that a Save is done to the the Drive.  This could be the current "Saved." element instead saying "Saved to [Drive icon] Drive".  Or a hover tool-tip that says the same.  If the brew is not linked to Google Drive, a message to the effect of "Saved to HB" with perhaps a tool-tip that recommends an alternate backup or suggestion to Link to Drive.

2. A pop-up after "Create New Brew" is clicked from the intro screen that suggests turning on Google Drive link, and that this is an "opt-in" feature for EACH brew.

**Comment by Gazook89** [comment]
One more: If the Google Drive button is toggled off, meaning it is no longer linker, alert the user that the brew is no longer linked and can be found in their Drive trash.

**Comment by calculuschild** [comment]
@Gazook89 I've pushed an update that I think partially handles this issue (maybe part 1). Would you take a look? It's a new popup window when you click the google icon button.

**Comment by Gazook89** [comment]
Looks good, I think it's clear enough.
