### ISSUE TITLE
Long url links do not wrap text properly

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1136]
See https://homebrewery.naturalcrit.com/share/1cvV9nZNB1RF0rwy7Vp-lWLR9OJ1AmjgXWBmY6wY85Q-J

![image](https://user-images.githubusercontent.com/5878534/101184860-31a95880-361f-11eb-9f11-4c9b69fa05de.png)

**Comment by ericscheid** [comment]
Long words, whether inside links or not, don't get wrapped by default in Chrome.

You can however add `.phb { overflow-wrap: break-word; }` inside a `<style>` block.

Here are some long words to test with

- Pneumonoultramicroscopicsilicovolcanoconiosis
- Hippopotomonstrosesquippedaliophobia
- Supercalifragilisticexpialidocious
- Pseudopseudohypoparathyroidism
- Floccinaucinihilipilification
- Antidisestablishmentarianism
- Honorificabilitudinitatibus
- Thyroparathyroidectomized
- Dichlorodifluoromethane
- Incomprehensibilities

(ref: https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/)

**Comment by calculuschild** [comment]
Wanna make the PR for this? I'm *assuming* this fix would be safe for existing  brews? I don't think anyone intentionally has words going off the page... right?

**Comment by ericscheid** [comment]
The danger here is this will make some columns longer. All it takes is for one letter currently overflowing (i.e. barely visible to casual viwer) to instead break wrap to a new line.

It would be a breaking change.

**Comment by calculuschild** [comment]
Mmmmmmmmmm.... Good point. Ok, let's save it for v3 then.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
