### ISSUE TITLE
Only page break when \page occurs alone at beginning of a line

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1147]
I would really appreciate the ability to use code blocks to prevent any parsing from happening within.  The example that made me open this is issue is typing `\page` inside code elements (\`\page\`) still creates a page break, when in fact I just want to type out that little bit in a new "how to" brew.  Not allowing markdown or html inside code blocks to be parsed would help with a lot of other guides I have made (or will be making).  

Not sure where this is on an easy/hard scale for implementation, but I understand it would likely need to be a Version 3 thing.

**Comment by ericscheid** [comment]
Text within code blocks is not rendered to html via the markedown library.

What is happening is that after _md→html_ rendering occurs we have a post-process that substitutes looks for `\page` and slices that html into pages.

Detecting that that `\page` text occurs within a `<pre><code>...</code></pre>` section of the rendered html will be tricky.

**Comment by calculuschild** [comment]
We could possibly do it via regex... By that could get slow and dangerous.

I think we might have two easier options.

1) In v3, require \page to occur isolated at the beginning of a line. Then if you have \page anywhere else it won't trigger the page split.

2) if \page has another backslash in front, don't trigger the page split. And then \\page will just render as '\page'

Or some mix of the two.

**Comment by ericscheid** [comment]
With 2, the non-hidden code block will render as `\\page`, that is the extra backslash will appear (why wouldn't it?).

Handling the escaped-backslash just for that one directive inside code blocks sounds like a wonky edge case patch.

Option 1 is sounding much much better. 

Are admins able to do a global brew search for `[^\n]\\page` to find how many brews have `\page` not at the begginning of a line?

**Comment by calculuschild** [comment]
> With 2, the non-hidden code block will render as \\page, that is the extra backslash will appear (why wouldn't it?).

We would have to add in a second processing step after the pages are split to then remove the extra slash. Which would be obnoxious.

No, the text of the brews is not searchable, unfortunately. And I suspect there are more than a few who have a random space or something there. This would have to be part of v3 as a breaking change most likely.

**Comment by ericscheid** [comment]
Would also integrate well with #629

**Comment by calculuschild** [comment]
This is already integrated as part of the legacyRenderer branch.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
