### ISSUE TITLE
[Resolved] Site Down - Thursday Dec 10th 22:40 UTC

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1149]
Edit:  The site is now backup...not sure if you want the Issue still "Open" in order to look at logs or anything.  Close it if you want.
___

The NaturalCrit site is down.  As is Reddit, so couldn't report it there.

Here is the error:

 ```
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail
```

**Comment by calculuschild** [comment]
I didn't see anything particular in the logs, so I just rebooted and it seems to be alive again.

There is an ongoing issue with Herokus servers for the last 6 hours ago and that may have triggered something, but I'm not sure.

We haven't posted any changes for a few days so I don't think it's anything we did, but I appreciate the quick notice so I could fix it.
