### ISSUE TITLE
[UI Suggestion] Have the version # in the top toolbar link to github repository

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1166]
I noticed that the "link" from the toolbar where the version number is given doesn't actually go anywhere.  It might be helpful to have that lead to this github repository, or to the changelog.  Or, with the new version coming up, possibly a dialog that offers to migrate a brew to the new version, explaining that it might/likely will break some formatting.

I see now that the Welcome page has a link to the Changelog on it, labelled as such, but that link is not in the normal Editing page.

**Comment by calculuschild** [comment]
Good idea. My instinct says it would make the most sense to link to the changelog, but we do already have a link to that. Maybe some other people can weigh in on what would be most useful.

**Comment by Gazook89** [comment]
Maybe make that go to the changelog, and change the existing changelog link to "GitHub". This would make a lot of sense on the welcome page.

**Comment by AlexeySachkov** [comment]
> Maybe make that go to the changelog, and change the existing changelog link to "GitHub". This would make a lot of sense on the welcome page.

+1, plus the changelog by itself can additionally refer to GitHub as to "full history of changes"

**Comment by ericscheid** [comment]
Just for clarity in discussion, this is what we currently have:

**HomeBrewery home page:**
![HomeBrewery home page](https://user-images.githubusercontent.com/2605467/104443548-b1492080-55ea-11eb-9442-6a1dcac04956.png)

**Change log**
![Change log](https://user-images.githubusercontent.com/2605467/104443611-c625b400-55ea-11eb-8829-4f38a60771b6.png)

**User home page**
![User home page](https://user-images.githubusercontent.com/2605467/104443716-e3f31900-55ea-11eb-9304-0b28b56fe5a9.png)

**Brew edit page**
![Brew edit page](https://user-images.githubusercontent.com/2605467/104444007-4c41fa80-55eb-11eb-9db9-107d0d43a77a.png)

**Brew share page**
![Brew share page](https://user-images.githubusercontent.com/2605467/104443882-1d2b8900-55eb-11eb-8a8a-30c6a759c1cf.png)

**Notes:**

* Link to Change Log only appears on the HB home page
* The version number appears on every page
* The changelog page is the same as any Brew Share page.
* The Brew Edit page is getting crowded.
* The Change Log page content could also directly link to GitHub
* We don't have Report Issue on the Brew Share page - we have seen issues reported regarding the Share page
* We don't have Report Issue on the User home page - we have seen issues reported regarding the User page
* We don't have Report Issue on the Change Log page - I doubt we've seen or will see issues regarding this

**Comment by AlexeySachkov** [comment]
Based on summary from @ericscheid I think that we can turn version number into a dropdown, where we have links to both regular changelog and GitHub. The version link itself should point to the regular changelog (I suppose it is preferable way of reading about changes for regular users)

Also I suggest that we put "Report Issue" button on every page, as it seems important - a bug can occur in any part of the app, apparently.

**Comment by calculuschild** [comment]
What about putting the github link instead as a dropdown under "report issue" (users can choose to post to reddit or to github)? Maybe with a change to the wording there ("Contact Us" -> "Ask a Question" (Reddit), "Report a bug" (Github) )

Another alternative, is to identify which links are not needed during normal use of the website (changelog? Reddit page, Github) and just put those on the Home page intro with very obvious icons.

**Comment by AlexeySachkov** [comment]
> What about putting the github link instead as a dropdown under "report issue" (users can choose to post to reddit or to github)? Maybe with a change to the wording there ("Contact Us" -> "Ask a Question" (Reddit), "Report a bug" (Github) )

From what I've seen in the issues, there are tons of low-quality reports that don't include share links or any other forms of reproducers, so, I would like to avoid dealing with those on GitHub and I think it is better to use the subreddit as a first-tier bug tracker (ok, not a tracker, but just a huge box for them): most of our users are likely to browse through Reddit rather than through GitHub so they could help each other there; it is easier, I guess, to find someone who is willing to help answering questions on Reddit rather than on GitHub (i.e. work as a moderator)

**Comment by G-Ambatte** [comment]
Just a thought: it would be simple to make the version number link to the latest release on GitHub via https://github.com/naturalcrit/homebrewery/releases/latest; the only downside is that the current latest release according to GitHub is v2.9.2, whereas the Homebrewery page currently reports v2.10.6 - it appears that while changes have been recorded in the changelog, they aren't reflected in the GitHub releases.

**Comment by ericscheid** [comment]
Linking to GitHub will confuse many users.

Compromise: the `Change Log` link goes to `/changelog` and then in the content of that page there is an explanatory preamble which links to GitHub for all the gory details.

**Comment by AlexeySachkov** [comment]
> it appears that while changes have been recorded in the changelog, they aren't reflected in the GitHub releases.

GItHub releases are documented tags in git. They are not created automatically and someone need to explicitly push a tag or press a button in the UI to make release happen

**Comment by calculuschild** [comment]
Yes I have been lazy about that. Stolksdorf never really tagged things and I started doing it retroactively once I had commit privileges, but haven't done it again for a while. Wouldn't be a huge issue to mark the newer versions with a tag.

**Comment by Gazook89** [comment]
See PR #1592
