### ISSUE TITLE
/source method does not escape &

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1188]
From the share page view of any brew (https://homebrewery.naturalcrit.com/share/:id), the `Source </>` button fetches a page view of the brew revealing the source for copy/paste (https://homebrewery.naturalcrit.com/source/:id).

This "source" view is actually the brew text presented within a `<code><pre>` block (probably because some browsers do content sniffing and might treat the response payload as html despite the response header saying it is text/plain).

The HB code thus converts any `<` or `>` to `&lt;` and `&gt;` so they'll _display_ as `<` and `>` in the browser.

The same escaping should occur for `&`, being html-escaped as `&amp;`, and consequently _displayed_ as `&`. 

It doesn't, and while generally this wouldn't matter much (brew source of `&times;` will get displayed as `×`, which when copy/pasted works just fine).

There are however edge cases that will cause problems. For example, brew source `&#42;hello;&#42;` will display as `*hello*` .. but when _that_ is copy/pasted it will get interpreted and displayed as *`hello`* (i.e. in italics).

A simple fix on two lines. PR incoming.

**Comment by ericscheid** [comment]
Lines 76 and 86 of server.js, btw.

**Comment by G-Ambatte** [comment]
Funnily enough, I was just looking at the same section of code for a completely different reason. Due to the duplication of code (in that exact same lines appear in duplicate places in `server.js`, it may be beneficial to push this to a separate function/module, so that corrections like this only need to be made once.

**Comment by ericscheid** [comment]
This is now fixed via both Source and Download methods.
