### ISSUE TITLE
[Issue] Overlapping text in metadata dropdown menu

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1193]
Minor issue, and don't think I've seen it before, but in the production version of homebrewery I've noticed that there is a little overlapping text in the menu where you change the title.  Picture included.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/58999374/104539881-0afa1c80-55e4-11eb-9d00-edc6e3c06430.png">

Edit: it actually only occurs when the editor pane has a small width.

**Comment by ericscheid** [comment]
The `<div>` containing the `<button>` and the `<small>` has been allocated a 15px margin-bottom, and then the `<small>` text is being absolutely positioned with bottom: -15px. 

When narrow, 15px is not enough height for the text, and thus it intrudes above.

Solution: insert a `<br>` between `<button>` and `<small>`, and remove the `position` and `bottom` css rules.

![hax](https://user-images.githubusercontent.com/2605467/104545588-87d9d480-567e-11eb-8c33-a83030ba401d.png)

Under extreme squishiness circumstances the left edge won't align with other elements, but this is true for the other items too (see SYSTEMS in OP image).
