### ISSUE TITLE
Add Search and Search/Replace in the Brew Editor?

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1201]
CodeMirror has built in options for doing search and search/replace .. looks pretty simple to turn on (famous last words).

https://codemirror.net/demo/search.html

**Comment by lucastucious** [comment]
Add a screenshot here for suggestion on UI overhaul
![image](https://user-images.githubusercontent.com/28046122/141188794-69cab2cc-501e-4766-9a3d-03db70e66a82.png)

**Comment by jeddai** [comment]
Doing some more digging that appears to be the find/replace box in the code editor Ace, while this project uses CodeMirror. 

I'm pretty sure we can re-style it and create our own find/replace box, but for the initial setup of it I'm focusing on getting search/replace functioning. Thanks for posting the screenshot!

**Comment by calculuschild** [comment]
Added via #1819  (use CTRL + F for just find, CTRL + SHIFT + F for replace)

**Comment by davideghz** [comment]
what's the shortcut on Mac?
