### ISSUE TITLE
Some CodeMirror tweaks

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1202]
Some options available in CodeMirror for consideration:

- https://codemirror.net/demo/activeline.html - highlights the line the cursor is on
- https://codemirror.net/demo/closetag.html - auto-inserts closing tags, handy when you type `<style>` or `<div>`
- https://codemirror.net/demo/trailingspace.html - highlights those pesky md-significant trailing spaces
- https://codemirror.net/demo/theme.html - would require UI for selecting theme, so .. meh

**Comment by calculuschild** [comment]
Added via #1819
