### ISSUE TITLE
Opportunity to reduce amount of information transferred between client and server

### ISSUE THREAD

**Issue by AlexeySachkov** [naturalcrit/homebrewery#1203]
I've been writing some tests for `/api` POST route and I discovered that in response to newly created homebrewery document, server sends its gzip-ed content back to the client as well as the rest of metadata. However in `newPage` we immediately redirect user to edit page without even using this information:

https://github.com/naturalcrit/homebrewery/blob/ba600f5da6e21905d4862a9237968a57f3ec3076/client/homebrew/pages/newPage/newPage.jsx#L108-L123

I don't think that this is an issue with huge impact, because most likely users press save on new brew page earlier than entering a lot of content in there, but still it makes sense to clean up our code

**Comment by 5e-Cleric** [comment]
Given that we want to merge new and edit, i'd say this should keep sending the brew back. Keeping it for when we finally merge the two. 

Linking #1800 as it tracks the unification of the two pages. Closing this.
