### ISSUE TITLE
Homebrewery is not able to properly autogenerate the brew title in all cases

### ISSUE THREAD

**Issue by AlexeySachkov** [naturalcrit/homebrewery#1205]
If a brew is only consist of a single line without trailing `\n`, the title will only contain `# ` without the text after it. We should check if `ending` is `-1` and use the whole string in that case:

https://github.com/naturalcrit/homebrewery/blob/ba600f5da6e21905d4862a9237968a57f3ec3076/server/homebrew.api.js#L13-L17

**Comment by calculuschild** [comment]
There's a PR for this from almost a year ago, but I don't think it quite for resolved. #859

**Comment by calculuschild** [comment]
This is fixed with #1214
