### ISSUE TITLE
Headers at the top of the columns seemingly not aligned

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1218]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/58999374/105939553-10f9ef80-601f-11eb-821b-7f228368a153.png">

[As reported on this reddit thread](https://www.reddit.com/r/homebrewery/comments/l5kn30/the_page_columns_are_always_slightly_misaligned/),  there is some issue with headers being slightly offset at the top of columns, when by all appearances they should be aligned perfectly.  In the screenshot I have added an absolutely positioned blue line to make that clear.  It was reported with the h3 header, and I've looked at h3 and h4.

Here is a [link to a copy of the original test brew](https://homebrewery.naturalcrit.com/edit/1mXeSOBN5WnJFmb1G6IPufWlr42zu0aGI64iiZkPRLaUn) showing the issue.  

Note, original user had a "vertical spacing" div included, presumably to break the column rather than using a normal column break...**if a column break was used (double set of triple ticks ` ``` `) this alignment issue would be fixed.**

But an alternative fix is to change the h3 styling (and other headers)...currently, it features a top and bottom margin of .2em.  If the top-margin was changed to top-padding, the issue would be fixed.  For some reason, that top margin isn't registered at the top of a column.

**Comment by calculuschild** [comment]
This isn't a new issue since I applied v2.10.7 is it? I'm pretty sure the fix for Box-Shadows breaking across columns didn't move anything around.

I guess I'm not surprised the columns would have weird behavior without the manual column breaks. For v3 we should see if we can get consistent behavior whether the user inserts a column-break or not, perhaps with the padding method you mentioned.

**Comment by ericscheid** [comment]
Not a new thing, I remember seeing it before.

At the time I reasoned it was the bottom-margin of the `h1` across the top of the page only applying to the first element in the following code (which would make it a chrome rendering bug).

IIRC, the four-ticks column break would also insert a bit of spacing, which would (accidentally) disguise the effect.

**Comment by G-Ambatte** [comment]
I've been experimenting a little, it seems that the removal of `margin-top` is the key. Switching to `padding-top` preserves the current spacing for any existing brews.

**Comment by Gazook89** [comment]
Old issue here, but seems like with version 3 it still isn't fixed (and problem has changed slightly).  Version 3 allows for breaking paragraph elements now, so the example link above doesn't demonstrate the issue any more.  [Here is a new example link](https://homebrewery-stage.herokuapp.com/share/H4AcefQm2JPF).

<img width="774" alt="image" src="https://user-images.githubusercontent.com/58999374/130296966-ad7b1220-85f0-4973-b3c7-746c68da7f7d.png">

The h3 header has the same issue in v3 of not being aligned.   Before the problem was because the header had a small positive margin-top value.  Now, the h3 header specifically has a small negative margin-top value.

```
.page h3 {
    margin-top: -0.1cm;
    margin-bottom: .1cm;
    font-size: .575cm;
    border-bottom: 2px solid #c9ad6a;
}
```

Removing the margin-top property fixes this mis-alignment. Unfortunately, padding can't be negative...so if this tiny adjustment is necessary for something else, then I'm not sure how to replace it (easily).

**Comment by Gazook89** [comment]
Looks like this is fixed, as long as `display:inline-block` holds up in terms of the other issue (`min-width`) we've discussed in Gitter.

Closing this.
