### ISSUE TITLE
Google Brews show no author(s) in metadata

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1219]
Brews that are stored in Google Drive do not show any author information in the file metadata on the `/edit` page.

Reproduction steps:
1. Open the `/edit` page of any brew stored on Homebrewery
2. Check the metadata and confirm the author information exists
3. Switch to Google Drive, confirm move
4. Refresh the page
5. Check the metadata, author information is no longer shown

The reverse also holds true: removing a brew from Google to Homebrewery will cause the author information to be shown.

**Comment by G-Ambatte** [comment]
A quick perusal of `googleActions.js` shows that the term `authors` only shows up on three lines: 125, 245, and 299 (on my local copy, apologies if I've edited this and changed the line numbers slightly). 

125: `authors     : [req.account.username],	//TODO: properly save and load authors to google drive`  - `listGoogleBrews()`
245: `authors     : [],` - in `newGoogleBrew()`
299: `authors     : [],` - in `readFileMetadata()`

So it appears that the author information isn't actually being written to or read from Google. However it seems should be fairly simple to correct, as `systems` is also an array that gets saved to/read from Google, so it may just be a case of duplicating how `systems` is handled.

**Comment by Gazook89** [comment]
I don't believe this is an issue anymore, after the work on the stubs likely.  I followed your steps to reproduce and didn't get the same error on a few brews.  And now authors are stored in stubs, not on gdrive at all.

@G-Ambatte, confirm and then this can be closed out.

**Comment by G-Ambatte** [comment]
I'll test it today, but I suspect that there's still an issue here, based on [this line of code](https://github.com/naturalcrit/homebrewery/blob/7c93e5879c40ca334aa34771c1f3960cca6ae442/server/googleActions.js#L254).

**Comment by G-Ambatte** [comment]
Looks like it's working, I suspect that `authors` being an empty list in the object returned GoogleActions.js is a non-issue because `authors` is handled in the stub which is stored locally in MongoDB.

![image](https://user-images.githubusercontent.com/19826659/201738350-c9d30a89-83a8-4710-8413-43e90986d5ee.png)
