### ISSUE TITLE
Columns within a Note do not appear in the correct position

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1224]
See Reddit thread: [Columns within a Note](https://redd.it/l8pg9n)

Columns within a note are appearing in the incorrect position since the change from v2.10.6 to v.2.10.7 Using Chrome's Inspect Element tool shows the highlighted block in the correct position; however this is not where the text appears.

[Reproduction](https://homebrewery.naturalcrit.com/edit/1xt91dCxDGIY5e5QZHINI6bYECktrq9NNRHk6fFAbVNdM)

---

Investigating the changes included in this version change, it appears that the inclusion of `-webkit-transform: translateZ(0);` is what is causing the change in behaviour. This change was originally intended to resolve issue #1179 but the solution has broken any existing columns in blockquotes.

So far, the only solution I've been able to find is to remove the `-webkit-transform: translateZ(0);` line completely. :(

**Comment by calculuschild** [comment]
Ok, we can undo this then. That's a shame.

On the other hand, for V3 we can apply this to the blockquotes:
```
display: inline-block;
margin-top: 10px;
```

It gives a margin so the top shadow/border doesn't get cut off, but it does shift the block down compared to what it is today, so it had a good chance of ruining existing brews positioning.

**Comment by Gazook89** [comment]
Why not just get rid of blockquote notes in favor of note bracket/divs? 

One class that is "note", then others that are names of different styles like "green" "monster" "descriptive" etc. So a normal green note is {{note,green here is my text}}

Let blockquotes be blockquotes. Maybe a style that is actually like a blockquote. And then use a multipurpose class system for notes.

**Comment by calculuschild** [comment]
Well, yes, they will be Divs, but I think they have the same problem with the top borders getting cut off.

**Comment by ericscheid** [comment]
> Ok, we can undo this then. That's a shame.
> 
> On the other hand, for V3 we can apply this to the blockquotes:
> 
> display: inline-block;
> margin-top: 10px;
> It gives a margin so the top shadow/border doesn't get cut off, but it does shift the block down compared to what it is today, so it had a good chance of ruining existing brews positioning.
> 

Alternatively, there is usually space inside the bottom of the block quote that can be removed. Technically, it is space at the bottom of the `.phb blockquote > :last-child`, either padding or margin (depending on the element). 

That space could be removed and added to the top. Some users (i.e. me) already have, so leave this to V3.

**Comment by calculuschild** [comment]
For sure, we need to standardize our margins/padding/spacings between elements. We have a lot of "margin-bottom after this element", but then "negative margin-top for the next element" but then "negative margin for this element ONLY if directly after the first element, but then positive in this other special case." Lots of conflicting bandaids patched over and over when we really just need one consistent number for most cases.

**Comment by G-Ambatte** [comment]
Closing this as the root issue has been resolved by reverting the relevant commit.
