### ISSUE TITLE
Quoted CSS values get HTML-escaped

### ISSUE THREAD

**Issue by kara-ryli** [naturalcrit/homebrewery#124]
**Browser Type/Version**: Chrome 50.0

**Operating System**: OS X

**Issue Description**: 

Quoted values in inline `<style>` blocks are getting mangled by HTML-escaping them.

This worked as of [three days ago](https://www.reddit.com/r/UnearthedArcana/comments/4llk7k/5eresource_the_homebrewery_v2_released/d3p9xya), but appears to have stopped working since. 

**Brew code to reproduce**: 

```
<style>
.phb .footnote::after {
  content: "Test";
}
</style>
<div class="footnote"></div>
```

**Rendered HTML**:

```
<div class="pages" data-reactid="117"><div class="phb" data-reactid="118"><p><style>
.phb .footnote::after {
  content: &quot;Test&quot;;
}
</style></p>
<div class="footnote">  </div></div></div>
```

**Comment by stolksdorf** [comment]
Looking into this I'm really not sure what's happening. The code being injected into the page is fine and not "escaped" but upon rendering it, it looks like React is escaping for some reason. It seems to only be within style tags  as well (I tested it on some other tags). Worse yet, it's not consistent. Occasionally when testing it would start rendering fine with actual quotes and fine randomly jump back.

I'll leave this open, but it seems like a really weird bug with a pretty low impact on the general user. I'm hoping someone can help me out and maybe provide a bit of insight on what's happening.

**Comment by Artefact2** [comment]
Workaround:

~~~
<style>
.phb .footnote::after {
  content: "Test";
}
</style>

<div class="footnote"></div>
~~~

The linebreak is important.
