### ISSUE TITLE
Spell List snippet is missing 1st level spells

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1274]
Using the `Spell List` snippet from the `PHB` menu auto-generates a random spell list .. but never has any spells for "1st level".

Not a huge issue, as it is assumed that editors would simply use this as a template for writing their own actual spell list. 

Would be nice if there was a heading/group for "1st level" though.

This just needs a tweak to one line of the magic.gen.js files

https://github.com/naturalcrit/homebrewery/blob/a1bf8ca945c2cd1c8f570fc92b6018e3fd194d82/client/homebrew/editor/snippetbar/snippetsLegacy/magic.gen.js#L54

https://github.com/naturalcrit/homebrewery/blob/a1bf8ca945c2cd1c8f570fc92b6018e3fd194d82/client/homebrew/editor/snippetbar/snippets/magic.gen.js#L60

**Comment by Gazook89** [comment]
Not exactly same issue, but another tweak for the spell list:   make the default be "no column spanning" and only 2 columns itself.  Then adding the "wide" class makes it wide, and increases column count to 4.  

Here is the change to CSS:
```
<style>
  
  .phb .spellList {
  	column-span:unset;
  	columns:2;
  }
  
  .phb .spellList.wide {
  	column-span:all;
  	columns:4;
  }
  
</style>
```

**Comment by ericscheid** [comment]
See PR #1479

**Comment by Gazook89** [comment]
Was pushed through on PR #1480 (relevant code was mistakenly included on this PR).  Closing.
