### ISSUE TITLE
Add a Comment Selection editor action

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1303]
Suggestion: add an option to the Editor menu to wrap any selection with `<!--` and `-->` (with line breaks if selection includes one or more line breaks).

This is useful for temporarily removing brew content from the render, and for adding editorial comments for work-in-progress.

Possibly not worth the trouple of getting the code to detect if the selection is inside a `<style />` block (and thus using `/*` and `*/` instead)

**Comment by Gazook89** [comment]
Was going to close this issue as PR #1492 was merged, adding an html comment snippet and hotkeys for converting existing selected text....but now that the Styles are separated into their own pane, i don't think it should be too hard to detect which editor frame is open and adjust the comment style accordingly?  For both the hotkeys and the snippet.

### Hotkey code:
[codeEditor.jsx](https://github.com/naturalcrit/homebrewery/blob/53de59940f11251e7f7093dc69ee4d5ceef16022/shared/naturalcrit/codeEditor/codeEditor.jsx#L93-L100)
```
	makeComment : function() {
		const selection = this.codeMirror.getSelection(), t = selection.slice(0, 4) === '<!--' && selection.slice(-3) === '-->';
		this.codeMirror.replaceSelection(t ? selection.slice(4, -3) : `<!-- ${selection} -->`, 'around');
		if(selection.length === 0){
			const cursor = this.codeMirror.getCursor();
			this.codeMirror.setCursor({ line: cursor.line, ch: cursor.ch - 4 });
		}
	},
```

### Snippet Code
[snippets.js](https://github.com/naturalcrit/homebrewery/blob/53de59940f11251e7f7093dc69ee4d5ceef16022/client/homebrew/editor/snippetbar/snippets/snippets.js#L116-L122)  (v3)
```
			{
				name : 'Add Comment',
				icon : 'fas fa-code',  /* might need to be fa-solid fa-comment-code --not sure, Gazook */
				gen  : dedent`\n
					<!-- This is a comment that will not be rendered into your brew. Hotkey (Ctrl/Cmd + /). -->
					`
			},
```

Now I say "should" be easy...but I created a branch to do just this (only the hotkeys) and couldn't figure it out, but I'm hoping someone who isn't like a week into JS would have an easier time.  I may give the Snippet side of things a shot tonight.

**Comment by calculuschild** [comment]
If you want, open your branch for the split snippets, and then make a new branch based on that one. Then you don't have to wait for me to merge your splitting pr first

**Comment by Gazook89** [comment]
Good idea...I was thinking of using the current html comment snippet but just having it detect the editor and adjusting the syntax...but now i realize that the "Editor" snippet menu only appears in the Text editor, not the Style editor.  

I'll go ahead and branch now and write the snippet.

I'll attempt the hotkey side of things later....but wouldn't be upset if someone passes me up on doing it.
