### ISSUE TITLE
One and two-character italicizations in bold fail

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1321]
Issue reproduction: https://homebrewery.naturalcrit.com/share/Ssz5Qe5w-kUd

Source code:
```
## Underscores

**Test one data: _1_ is a single character italicization.**  
**Test two data: _12_ is a two character italicization.**  
**Test three data: _123_ is a three character italicization.**  


## Asterisks

**Test one data: *1* is a single character italicization.**  
**Test two data: *12* is a two character italicization.**  
**Test three data: *123* is a three character italicization.**  
```

Using italics inside a section of bold text fails, but only when using underscores. Using single asterisks to achieve the same effect works in the above test cases.

**Comment by G-Ambatte** [comment]
It appears that this issue has already been resolved in v3, and so is only applicable to the Legacy editor.

**Comment by calculuschild** [comment]
It's not just inside bold. Any 1 or 2 character italics using underscores don't work. This is an issue in the version of marked the Legacy branch uses (v0.3.19). We cannot fix this without changing the marked.js version, which unfortunately breaks many many other things. Hence the v3 branch needing to have an entirely separate rendering engine from Legacy.

**Comment by Mikle103** [comment]
I know this may be messing but this works

## Underscores

**Test one data: _1&nbsp;_ is a single character italicization.**  
**Test two data: _12&nbsp;_ is a two character italicization.**  
**Test three data: _123_ is a three character italicization.**

**Comment by G-Ambatte** [comment]
On a similar note, inserting a `zero-width character` works correctly:

```
**This _is_ test data.**  
**This _is&#8203;_ test data.**
```

**Comment by Gazook89** [comment]
If this is corrected in v3 already, and "can't be fixed in legacy", can it just be closed?

**Comment by calculuschild** [comment]
Just for clarification, *all* issues with this tag "can't be fixed in legacy" either in case the question comes up.

I'm keeping them open just for my reference until we can open up v3 to the public in beta form. Until the users can actually access the fix I don't want people seeing these as "Closed" and wondering why it's still not working on the website.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
