### ISSUE TITLE
Revised Cover Page Snippet

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1334]
Here is an option for a revised Cover Page snippet, with a little more zest than the current option.  Could be applied to current version, and converting to v3 mustache brackets would be easy.

https://homebrewery.naturalcrit.com/share/1LdvVfUDcBnR-28yl_qneJWMEZnodgdkILcErMxnObyHx

You can change the background image by changing the URL in this: <div class='cover dice' style='background-image:url(https://i.imgur.com/flT4pS7.jpg)'>

You can change dice to dragon or guild for slightly different variations.

**Comment by 5e-Cleric** [comment]
done in #2649
