### ISSUE TITLE
[FEATURE]: Multiple pages preview  /  popout preview

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1379]
Would be nice to quickly toggle a Fit to Screen option for easy screen shots of whole single pages. As is, typically it requires using the browser zoom.

To an extreme, it could be possible to fit multiple pages to a screen using either float, css flex box, or css grid. Zoom buttons within the preview pane would set to "full size", fit page to screen, 2 pages per screen, 4 pages to screen, or 9 pages to screen (which could be used to display "trading cards") and this would be responsive sizing, not necessarily strict dimensions.

**Comment by G-Ambatte** [comment]
Further to this, there is a request today in the sub-Reddit to add a BrewRenderer zoom level (https://redd.it/yu6fig). As mentioned there, functionally, this can be achieved by setting an inline style on the `<div class='pages'>` BrewRenderer element of `transform: scale(X%);` and the appropriate UI elements to adjust the value of X.

I would envisage Fit to Screen using the same functionality, but calculating a value of X determined by comparing page height to viewport height.

**Comment by Gazook89** [comment]
I'm not 100% sure this would be the best method.  Here is what `.pages { transform: scale(.5); } looks like with a red background also applied to .pages for illustration:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/58999374/201570862-87385315-6e01-4dc2-93e0-afab1d25c782.png">

I think ideally the container for each `.page` (which is currently `.pages`) should continue to span the preview window, rather than be transformed itself.   If ever we wanted to shrink the pages so that pages could be shown in a different layout (*e.g.* side-by-side) it would be....difficult/weird.

Here is an old brew from Legacy that is probably the best I can get it just using the Styling within the brewRenderer:

https://homebrewery.naturalcrit.com/share/sye35rCW30Kq

<img width="848" alt="image" src="https://user-images.githubusercontent.com/58999374/201572590-2276339a-65cb-42c1-b39a-0d4bd3ba367b.png">

**Comment by Gazook89** [comment]
How far-fetched is allowing the preview frame to be popped-out into it's own window and continuing to edit it?  Is that *thing*?

**Comment by G-Ambatte** [comment]
> How far-fetched is allowing the preview frame to be popped-out into it's own window and continuing to edit it? Is that _thing_?

Pretty difficult, I think - I suspect it's basically a separate tab/window and then needs to subscribe to events from the editing page... I suspect CM6 might make this a lot easier, but right now, it would be a pretty huge undertaking.

> I think ideally the container for each .page (which is currently .pages) should continue to span the preview window, rather than be transformed itself.

I don't disagree, it was the first place that I went looking to apply scaling controls. Unfortunately scaling `page` doesn't scale margins, so the gaps between pages become (relatively) enormous, whereas scaling `pages` scales the margins and keeps everything a constant spacing.

**Comment by 5e-Cleric** [comment]
Fit to screen is here, both in width and height(actually whatever is longest).

Multiple pages can still be tracked through this issue, as well as popping out the preview.

**Comment by Gazook89** [comment]
I'm sitting on a [branch that extends the new toolbar to include a toggle for different viewing modes](https://github.com/Gazook89/homebrewery/tree/View-Modes): "Single", "Facing", and "Flow".  Especially the last one, the names may change.  But basically:

- Single: The current default view, shows just one page at a time, stacked on top of each other.
- Facing: Two pages side by side, like a book. At time of writing, this also sets the first page to be displayed on the *right* side (so there is an empty space in the first 'slot') to accommodate a Cover page which generally doesn't have a 'facing' page.  I'm working on a checkbox input to disable this in case a user doesn't want to include their cover page.
- Flow:  Sets the whole `.pages` div to just be a `flex` container, so pages flow to fill to the width of the brewRenderer and then wrap to the next row.  Works well with the new zoom feature-- you can get a quick look at many pages, and is a good way to present smaller pages (like *cards*). 


https://github.com/user-attachments/assets/721aee60-1514-4d84-8b73-9c347a34b097

I'm hoping to get the checkbox for the facing pages thing figured out soon (trying to resist a detour into our 'fancy popups' we use on the Saving button).
