### ISSUE TITLE
Saving results in a generic error and reporting returns a 404 error

### ISSUE THREAD

**Issue by NancokPS2** [naturalcrit/homebrewery#1396]
## Description

Saving simply does not work, the button turns rand and says "OOPS!" as well as a small popup appearing below and saying "Looks like there was a problem saving.
Report the issue here."
Pressing the link in "here" sends me to this page: [Link](https://github.com/naturalcrt/naturalcrit/issues/new?body=Error%3A%20Internal%20Server%20Error%0A%0A%60%60%60%0A%7B%0A%20%20%22status%22%3A%20500%2C%0A%20%20%22method%22%3A%20%22PUT%22%2C%0A%20%20%22url%22%3A%20%22%2Fapi%2Fupdate%2FEg3QYgFNgGzH%22%0A%7D%0A%60%60%60)
This happens with all my brews, apparently indiscriminately, but here is the code of one in case it helps:

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div class='wide'>

# Not Enough Races (Pack 2) v0.1

</div>
## Korosci
-*"They are an omen i tell you, first and last time i saw one, Julius kicked the bucket the very next day."*  
 -*"What are you talking about? They just bought some rations and Julius was 87 years old, i was there with you, remember?"*  
-*"Omen i say!"*  
**-Two peasants discussing the sighting of a Korosci**

#### Lore
Their rarity, shadow-like appereance and high death rate bring a whole set of difficulties for Korosci. They depend on light to live and quickly loose strength and die whenever they are in the darkness, while contemporary Korosci have an easier time than their older ancestors, they don't have it easy.
##### History
Korosci have come a long way since their early existance of struggling to survive each night. Their ancestors where cursed with the inhability to live without light, which lead to small groups of them forming up to ensure survival during nights where campfires could go out at any moment or that a creature could attack them in the middle of the night. Their ancestors where also notable different, back then they where also known as breeze drifters due to their ability to become light as a feather and maleable as air to follow the wind currents or scurry trough small spaces. Their older characteristics where traded with reducing the intensity of their curse which then lead to the Korosci that exist today, who have lost most of these abilities but also become capable to survive in darkness.  
##### Appearance  
They have a humanoid shape and are dark like night clouds, their facial features almost blend in with the rest of their face. Due to lack of any real musculature, their entire body is less defined and has less sharp features.

#### Features
**Ability Score Increase:** WIS +2 DEX +1  
**Age:** They reach adulthood at the age of 6 and tend to live at least more than 180 years where the mortality rate varies wildly all the way to 230 years.  
**Alignment:** Korosci alignment is usually some form of lawful due to the aversion to conflict which they have carried trough generations.  
**Size:** They usually are taller than 5,5 ft. and have a maximum documented height of 6,3 ft. Your size is medium.  
**Speed:** Your base walking speed is 30 ft.  
**Malleable:** You can move through a space as narrow as 1 inch wide without squeezing.   
  
**Incorporeal:** You can reduce the density of your physical form to reduce harm. As a reaction, you gain resistance to non-magical bludgeoning, slashing and piercing damage until the start of your next turn, but your STR and DEX scores are halved (down to a minimum of 8) until the END of your next turn. You can use this feature a number of times equal to half your proficiency bonus (rounded down).  
**Light Sustenance:** You require light to live. Being in pitch darkness for more than 5 minutes causes 1 level of exhaustion until you are exposed to sunlight. Being in bright light for at least 1 minute also removes this exhaustion.   
**Shadow-like:** You have advantage on stealth checks to hide in darkness.  
**Light Storage:** You can cast the Light cantrip without using components. At 5th level you can also cast the Daylight spell with a range of self (the spell moves with you and is not blocked by your armor or clothing) once per long rest. You cannot cast either of these spells if you have any exhaustion levels.  

## Tuhul
*"We should advance to the south avoiding that Tuhul castle to the east as much as possible, we don not want to tip them off about our prescence until the other battalions are here with the bigger siege weaponry, otherwise they will either beat us in a war of attrition or chase us down as we retreat."*  
**-Hobgoblin General.**

#### Lore 
Tuhul are humanoids with bovine-like features. They are known for their resilient constructions and fortifications with most of their civilization living behind walls, despite this, they are not bad combatants, Tuhul combat tactics involve their ability to attain high speeds and their capacity to mantain knowledge from previous generations.  

##### History
Their origins make a big contrast with their reputation, in different times, Tuhul used to live unprotected in huts with not even a fence to keep their villages secure. With time, as civilizations progressed and their laid back nature made them seen as a easy targets, they started dedicating a lot of effort on fortifications which they eventually perfected over the years. Even the smallest of their villages have solid defenses and security, both inside and outside the walls. 

##### Appearance  
They have noticeably different features from other humanoids, having hooves, raised ankles, small horn protrusions in the head and vertically slit pupils. Hair growth is prevalent not inly in the head, but in their upper back, behind the ears and in the legs. Eye coloring ranges from yellow to reddish-orange. Hair is either completely grey or brown, no exceptions.
\page
#### Features
**Ability Score Increase:** INT +2 STR +1   
**Age:** They reach adulthood at the age of 19 and tend to live around 120 years.  
**Alignment:** Tuhul are comfortable with order but not with being deprived of their freedoms. They do not have any special tendency outside from favoring less chaotic alignments.  
**Size:** They can easily reach 6,1 ft. and be up to 7 ft. tall. Your size is medium.  
**Speed:** Your base walking speed is 30 ft.  
**Structural Proficiency:** You gain proficiency with either carpenter's tools or mason's tools.  
**Improved Dash:** While not particularly fast on the start up, you can reach considerably high speeds when you get a running start. When performing the dash action, your movement speed is doubled.  
**Ancestral Memories:** Sometimes, flashes from the memories of early generations flashes trough your mind when you truly need it. Once per long rest, you can gain advantage on a single History skill check.  
**Inherited Practice:** Some things just come naturally to you, as if you had practiced them your whole life. You choose to gain one of the following sets of proficiencies:  
- 1 languages and 1 tool
- 2 languages
- 1 martial weapon
- shields
- 1 skill
- light armor
- medium armor (if you are already proficient with light armor)

## Mantada
-*"Did you see him? the whole barn was on fire and he didn't look alarmed in the slightest nor feared the wrath from the farmer that hired him, if that does not scream suspicious i do not know what would."*  
-*"Sir, they are all like that, if anything, it would have been more suspicious if it had fled in panic."*  
-**A witness and a guard discussing a report.**
#### Lore
Errant and joyous. Mantada's are known for their ability to turn the other cheek at fate and make do with what life throws at them. Mantada settlements are exceptionally rare and most live on the move. Wherever they go, their attitude and looks tend to draw attention.  
##### History  
There is no confirmed information about the origin of their race, the speculations are so many and varied that the topic itself has been regarded meaningless by most historians. Since the only records from ancient history merely talk about their travels and personal lives, but not about things of their race as a whole.  
```
```

##### Appearance  
Mantada are stout and colorful with their back naturally hunched. Their skin color can vary to any of the rainbow and tend to have circular spots of darker shades lumped in seemingly random parts of their body. Their hair tends to be considerably long and is always a darker shade of their skin color, even reaching pure black coloring. Their ears and nose are fairly pointy.  

#### Features  
**Ability Score Increase:** CHA +2   
**Age:** They reach adulthood at the age of 15 and tend to live around 200 years.  
**Alignment:** Mantada can have any alignment although good alignments tend to be more common.  
**Size:** Their hunched back and lacking size nets them a range of height that goes from 3 ft. to 3,6 ft. Your size is small.  
**Speed:** Your base walking speed is 25 ft.  
**Resolve:** Whenever a roll against you would match an opposing contest roll or stat from you like a save, a STR contest or an attempt to beat one of your scores, the opponent's roll is a failure/your roll automatically succeeds. This includes rolls against your AC, grapple checks, etc. (This rule does NOT allow you to ignore critical failures or successes, but ignores the rule of roller's advantage)

### Subraces
Their varying color and unusual appereance makes their subraces hard to differentiate for the untrained eye.  

#### Clawed Mantada  
Differentiated by their sharper and harder nails, the clawed kind can harden their entire body if they so chose and heal at an accelerated rate.  
**Ability Score Increase:** +1 CON  
**Chitinous Plates:** You can form plates of armor in your body to protect yourself from harm. Your unarmored AC is 13 + CON modifier or 13 + DEX modifier (whichever is higher), if wearing armor that would give you less AC than your unarmored AC, you use the unarmored AC provided by this feature instead. Shields benefits apply normaly as usual.  
**Retractable Claws:** You have claws that extend or retract at will. You have natural weapons that can replace your normal unarmed damage, whenever you roll for unarmed attack damage, you can change the damage to 1d4 + STR modifier slashing damage.  
**Natural Regeneration:** Whenever you are lacking hit points and at least 10 minutes have passed since you lost those hit points, you can roll a hit dice of your choice and recover the rolled amount as hit points. You can only use this feature a number of times equal to your proficiency modifier, and only once every 10 minutes.  
  
#### Charged Mantada  
The notable difference is their grey hair, as well as their attunement to magic.   
**Ability Score Increase:** INT +1  
**High Spirits:** You have advantage with CHA saving throws against magical effects.  
**Magically Charged:** You gain a 1st level spell  slot and learn a single 1st level wizard spell.  
  \page

## Caradus 
*"While there, i advise against doing your usual betting and swindling, because if you happen to be caught red handed, we won't be coming back togheter."*  
**-Trader lecturing a crew member before arriving at a Caradus settlement**
#### Lore
Sea faring and crustacean looking creatures. Having a peaceful history with Tritons, Caradus lived and often fought alongside them during their attempts at protecting the world from underwater treaths. Unlike Tritons, however, their civilization remained rather tribal. Caradus revolve around the trust that their or other's words carry. In their society, the worth of someone is measured by their ability to live up to their boasts and agreements.
##### History
While initially being comprised of un-friendly tribes constantly under war, they eventually struck a friendship with the Triton folk who managed to sway them of their chaotic behaviours and mediated peace between tribes. Despite this uplifting, they maintained their tribal culture for a long time. The biggest remnants of their culture are their underwater vaults of treasure which they usualy collected for spiritual purposes, trading or mere trophies. They are usually well hidden in the depths of the sea. More modern Caradus tend to set up their homes into less deep areas as to make floating platforms in which to trade, turning into big collections of rafts filled with markets and inns in the bigger communities.  
##### Appearance
They sport a hard carapace that covers their entire body laid in plates that has can have varying shades of brown.
Their eyes are covered to a plate of carapace each, which close like a trap door and hide their eyes in the process, this serves the same purpose blinking would on other creatures.  
The face has 2 black eyes, no nose or ears visible and a mouth that is made out of mobile plates of carapace. Also have 4 antennas, 2 face sized ones in their forehead and 2 small ones where their nose would be.
They have 6 limbs total, 2 main arms with 4 fingers, 2 extra arms at abdomen level with only 3 pointy fingers that are smaller and less agile, and finally 2 legs with 3 pointy connection points (work like toes) to the ground, 2 pointing forward and 1 pointing backwards like a heel.  
#### Features  
**Ability Score Increase:** STR +2, CON +1  
**Age:** They reach adulthood at the age of 10 and tend to live around 75 years, unlike other creatures, they do not weaken with age.  
**Alignment:** Caradus rarely stray from their own code of conduct and choose lawful alignments more often than not.  
**Size:** Their size is similar to human's if in the lower side. Your size is medium.  
**Speed:** Your base walking is 30 ft.  
**Swim Speed:** Your base swimming speed is 20 ft.
**Amphibious:** You can breath air and water.  
**Darkvision:** You can see in dim light within 30 feet of you as if it were bright light and in darkness as if it were dim light. You can't discern color in darkness, only shades of gray.  
**Carapace:** Your body is encased in a thick carapace. Your unarmored AC is 13 + DEX modifier, if your armor would provide less AC than this, you use your unarmored defense instead.  
**Anntennae:** Your antennas allow you to pick up on nearly vibrations in the air. You gain blind sight of 15 ft. which lets you see anything that happens to move.  
**Extra Arms:** You have 2 extra arms, that while not dexterous nor strong enough for most actions, they can still server various purposes. You can use these to grab and hold items, perform basic actions like turning a door knob or point at someone. They are NOT suitable for attacking with weapons, casting spells with somantic components (but they do for holding casting focuses) nor performing grapples.

## Eraldi 
"You see, there is no better subject to hunt down an Eraldi than another Eraldi. after all, once they find each other, their desire to fight will fuel each other into a battle so fierce, that it would be incredibly rare for both to walk out alive from it."  
-**Town Guard Captain voicing his train of tought at hiring an Eraldi for a head-hunting contract.**

#### Lore  
A war mongering race of sea borne creatures, their presence usually accompanies violence in some way. There's nothing that drives an Eraldi to action more than the promise of combat and as such make for excellent troops, hunters and mercenaries. However, there are rare cases of the opposite, with Eraldi that value peace above all else, their kind is often split between this being a birth defect or merely a side effect of having too much violence for a life time, most trust the former theory.  
Despite this, Eraldi are not midless war machines, they merely enjoy combat over most things, but they know when to hold back or when to flee to fight another day. 
  \page

##### History  
Eraldi are common in tales of sailors and horror stories for anyone within few miles of an ocean, older villages of Eraldi where more of arenas than anything, after their coming of age, offspring would be tested in terms of battle prowess to determine wheter they should stay or be cast out. Villagers would usually prepare scavenging parties to gather resources, regardless of who they belonged to while the rest protected the settlements. They favored marine caves or rocky beaches.   
With time, most Eraldi decided to abandon this format in favor of living in other civilizations (which was a slow and difficult process) and their original hostile behaviours whaned in the process.
  
##### Appearance  
Eraldi have a somewhat cylindrical and grey arched body that can reach black colorings, their abdominal area is of a lighter gray and they lack any sort of hair. Their eyes are beady black, mouth has small grey lips and a pronounced snout, they possess a hole in the top of their heads that they use as a secondary breathing method. Their nose is barely a bump with nostrils and their ears slits at their sides.  
Their extremities blend with their torso in such a way that it's hard to tell where the limbs start and the torso ends. 
They have fins that expand from the gaps within their extremities and fingers and they can control at will.  

#### Features  
**Ability Score Increase:** STR +2, DEX +1  
**Age:** They reach adulthood at the age of 15 and tend to live around 80 years.  
**Alignment:** Eraldi do not care much for codes of conduct and tend towards neutral alignments.  
**Size:** Their size is similar to the one of humans. Your size is medium.  
**Speed:** Your base walking is 30 ft.  
**Swim Speed:** Your base swimming speed is 30 ft.  
**Water Glands:** You can store up to 1 gallon of water for later use, if you happen to spend too long without drinking water, it will automatically be taken from these reserves to satisfy your thirst, if you don't get water the DC to prevent exhaustion becomes 20 instead of 15
Store and spray water?

</pre></code></details>

**Comment by calculuschild** [comment]
Is this still happening? We just pushed out a very small bugfix so you may have run into this right as the server was restarting. I can't see the error on my end.

**Comment by marhiin** [comment]
Unfortunately it is still happening. Got the same problem.

**Comment by calculuschild** [comment]
Give it a try now. There was a small additional bug that the first bugfix created. Thanks so much for reporting this!

**Comment by marhiin** [comment]
it works!
