### ISSUE TITLE
Style not applied when printing from New

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1409]
When using the "Get PDF" link to print a brew that has not been saved (and thus is on the `/new` page), any custom CSS information is not loaded.

It appears that in `printPage.jsx:componentDidMount()`,  `text` data is fetched from localStorage but the style data is not, so it is only applied if the brew is saved. It may be as simple as duplicating the existing `brewText` functionality for a new `brewStyle`.

**Comment by calculuschild** [comment]
Fixed by #1401
