### ISSUE TITLE
Integration with Fantasia Archive

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1414]
New free and open source project Fantasia Archive is a World Building database tool a la World Anvil. Reddit post here: https://reddit.com/r/worldbuilding/comments/o8eu4k/im_developing_a_100_free_local_oss_and_crossos/

The developer Elvanos is open to integrations and while not currently a feature it could be possible to export individual pages of the organizer to JSON and then converted to Homebrewery snippets for quick monster blocks, class descriptions, etc.

Currently it can export individual pages to Markdown but only in a very standard non fancy format.

**Comment by G-Ambatte** [comment]
I've looked into API integration a small amount already; there are notes buried in the GitHub issues and comments about pushing a `brew` data object to the `/api` endpoint to automatically generate a Homebrewery document. At this stage, I have not been able to find any documentation of it being implemented for online usage, but initial experimentation with a local install has shown promise.

**Comment by ericscheid** [comment]
A 3rd-party source via API of JSON encoded data that HB might ingest, you say?

Noting for attention of [#1400 Variables in Brews](https://github.com/naturalcrit/homebrewery/discussions/1400#discussioncomment-3640459)
