### ISSUE TITLE
[Feature Request] Custom class names in Page element

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1421]
Would be nice to be able to give each page a custom class, such that the custom class name would be included here:

```<div class="phb page" id="p1"></div>```

This would allow for quickly tagging a page as the "cover", "toc", "credits", etc.  Currently, the method I would use is to create my own div with class/id="title" and then put the entirety of that pages contents inside that div...but that is a needless div.

Just to throw something at the wall, it might look like this:

```
\page -cover-
```

or

```
\page -toc blue-
```

which would translate into the following, respectively:
```<div class="phb page cover" id="p1"></div>```

```<div class="phb page toc blue" id="p1"></div>```

**Comment by ericscheid** [comment]
How would you apply a class to the first page?

**Comment by G-Ambatte** [comment]
> How would you apply a class to the first page?

It might be a little clunky, but if a `\page` appeared on the first line of `brew.text` (perhaps even `brew.text.startsWith('\page ')`), then the rest of the line could be applied to the first `<div class="phb page">`.

**Comment by Gazook89** [comment]
Might not need it on the first page; since the first page is always the first page, it's easy to reference it without a custom class name. Or, always give the first page a class name of "first" or similar, not user defined. 

I have to think about it a little more though.

**Comment by G-Ambatte** [comment]
If I recall correctly, in the BrewRenderer.jsx file, the `brew.text` is `.split()` using "\page" as the separator, then each chunk of that data is passed to a `renderPage()` function which returns `<div className='phb page' id={`p${index + 1}`} dangerouslySetInnerHTML={{ __html: MarkdownLegacy.render(pageText) }} key={index} />;`  
So currently the className attribute is static; to implement this, we would need to come up with a way to extract and dynamically add the className information.

My current thinking is that if the `brew.text` is split using a "\page" separator, then class name to be applied to the page would be the content from the start of the split text data to the first instance of "\n". This could also be validated by some sort of identifying syntax, such as the suggested wrapping in hyphens, as per @Gazook89's suggestion.
With this operation, if the first line of `brew.text` contained the hyphen-wrapped class name, it would be applied to the first page's class, as the beginning of the text data would be treated like the start of any other split.

**Comment by ericscheid** [comment]
I'm uncertain the `-classes list-` syntax is helpful.

Just our luck there will be someone with a brew containing such a string adjacent to `\page` already.

Currently, `PREFIX\pageSUFFIX` renders with "PREFIX" at the end of the prior page, and "SUFFIX" at the start of the next page. If we can detect that a brew predates the version where we do `\page list of classes` then we can `s/\\page */\\n&\\n/gi` and bump the saved engine reference version.

Oh my, that regex is ugly. I mean: just wrap every instance of "\page" with new-lines.

**Comment by Gazook89** [comment]
I don't think we'd need to add this feature to legacy, just v3, IMO.  However, the syntax could be changed to anything else too, including something a little less like to naturally occur.  `\page [[page phb cover]]` or something.  

Also, this could be tied into #629 Collapsible Sections.  If collapsible sections are implement, it would be beneficial to be able to see some sort of identifier in the "non collapsed" portion so that you don't just see 

```
\page
\page
\page
\page
...
```

when all of those pages are collapsed.  instead you could have something like:

```
\page [[section-1]]
\page [[section-1]]
\page [[section-1]]
\page [[section-2]]
...
```

**Comment by ericscheid** [comment]
See issue #1488 and #1489 for general solutions that uses `{curly-injection}`
