### ISSUE TITLE
[Feature Request] Hijack 'alt-text' portion of Markdown Images for html ID/Class

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1425]
The standard Markdown image is written as such:

```![Alt text](https://i.imgur.com/yU7FKTD.png "a title")```

Which generates this html:

```<img src="https://i.imgur.com/yU7FKTD.png" alt="Alt text" title="a title">```

It would be helpful to be able to get an ID or Class in these elements.  Maybe finding a way to co-opt the alt-text so it can be used as an ID/Class would work?  For example, the below would output html like the following:

```
![tiger blue top](https://i.imgur.com/yU7FKTD.png "a title")

<img class="tiger blue top" src="https://i.imgur.com/yU7FKTD.png" alt="tiger blue top" title="a title">
```

This would get myself closer to using strictly markdown formatting for images, rather than exclusively html tags.

**Comment by calculuschild** [comment]
I actually have something in the works for this.

**Comment by Gazook89** [comment]
I believe this is taken care of by #1476.  Closing.
