### ISSUE TITLE
Sanitize style tab contents

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1437]
It's possible to execute javascript via the style tab, because we aren't running it through the sanitizer that the main markdown text does. This will need to be fixed before we allow importing custom themes from other brews.

**Comment by G-Ambatte** [comment]
Looks like this is all the sanatize (sic) function does:

![image](https://user-images.githubusercontent.com/19826659/192684442-e127642d-65a7-4529-9ea0-ad5f4088ef2b.png)
