### ISSUE TITLE
Save error

### ISSUE THREAD

**Issue by FoxMicchan** [naturalcrit/homebrewery#1439]
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

**Comment by calculuschild** [comment]
Can you provide any more details? What were you doing, I what page were you on, which browser, etc?

**Comment by FoxMicchan** [comment]
Sorry, I am new to Homebrewery and now I think I shouldn't have reported it... I was editing a homebrew and when the autosave started, I got the error and report button. But it soon got back to normal, so I guess it was just internet instability? I was using Google Chrome on an old MacBook Pro

**Comment by calculuschild** [comment]
I see. No worries. We probably need to provide better instruction on the error report button anyway.

Glad its working now though!
