### ISSUE TITLE
homebrewey failed to save

### ISSUE THREAD

**Issue by Serunios** [naturalcrit/homebrewery#1460]
Error: Service Unavailable

```
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/9xMdNhEPW0E0"
}
```

**Comment by calculuschild** [comment]
Give it a try again. Everything looks fine now so you may have just hit a temporary hiccup.

**Comment by Gazook89** [comment]
CalculusChild reset the server yesterday, no new downtime since. closing
