### ISSUE TITLE
CSS Tweak:  Multi-level Ordered Lists

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1463]
I can't find any examples of multi-level ordered lists in the PHB, so this isn't a big deal, but I think it would make sense to tweak the phb stylesheet to change the list-style for at least three levels of ordered lists, so we get Numbers, Upper-case Roman Numerals, then Lower-case Roman Numerals.  Here is the CSS:

```
.page ol li ol li {
	list-style:upper-roman;
}

.page ol li ol li ol li {
	list-style:lower-roman;
}
```

https://github.com/naturalcrit/homebrewery/blob/a71dca1487d2b5e4a9064a19e7e586ed135d67ae/themes/5ePhb.style.less#L83

**Comment by calculuschild** [comment]
I think I may have seen nested lists in one of the other sourcebooks. If anyone can track down an example we can try to follow that.

**Comment by Gazook89** [comment]
So I asked on the Discord of Many Things server if anyone knew of any examples from 5e sourcebooks, and I quickly got an example that I wasn't expecting:  The equipment lists from the classes.  They look like this:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/58999374/133318005-a3c1cc4b-5ee4-4c52-9e54-80ab22b6f6b2.png">

That's not really what I had in mind, though it technically fits the definition of "list within a list".  Obviously, it's not hard for a user to do this manually so I don't think we really need to pursue adopting this, but just for giggles:

```
# Equipment
-  
	- Sword
	- Shield
	- Helm
- 
	- Bow
	- Crossbow
	- Tunic
	
<style>
.page ul ul {
	display:flex;
}

.page ul ul li {
	list-style:lower-alpha;
	padding-left:0px;
	margin-right:16px
}
	
</style>
```

<img width="300" alt="image" src="https://user-images.githubusercontent.com/58999374/133319152-4bbaed0c-c60f-4610-b178-048eafc5fb22.png">

**Comment by Gazook89** [comment]
I think this can be closed out and left to individual users if they so desire.  Especially since v3 has been out for awhile and any css change would impact existing brews.  I did put another request on the Discord of Many Things for any eamples in the source books of nested lists so if a good one comes up, we can re-open.
