### ISSUE TITLE
Source dropdown on Change Log page doesn't work

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1467]
On the `/changelog` page, there is a drop down menu item titled "Source", which features options like "View", "Download", and "Clone to New". However none of these options actually work.

**Comment by ericscheid** [comment]
Neither does the Get PDF link. They all have "undefined" as the share id.

These lines need to be conditional on `this.processShareId()` not being `undefined`.

https://github.com/naturalcrit/homebrewery/blob/d35769dcebedddb60fbfb15aad02f227261adb1c/client/homebrew/pages/sharePage/sharePage.jsx#L91-L97

**Comment by G-Ambatte** [comment]
See draft PR #1468 which addresses both of these concerns.

**Comment by calculuschild** [comment]
Fixed by #1468 .
