### ISSUE TITLE
Unclosed elements in Code/Pre blocks cause errors

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1473]
v3/Chrome

I am surprised that elements are checked for closing tags inside code and pre blocks:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/58999374/127345477-09e22d5c-57fe-460b-80b1-2d53a05e72b2.png">

It might just be spans and divs?

**Comment by calculuschild** [comment]
Oh gosh. Yep it's never been a problem before because the code blocks were not enabled before now. I'll try to make a fix for this.

**Comment by Gazook89** [comment]
Here is what that looks like:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/58999374/127361954-a76dbf20-9910-48d0-8407-ca9dce0b58f0.png">

I don't think it is causing an opened tag error, but it's rendering the div rather than plain text.

**Comment by Gazook89** [comment]
I take that back, it does cause an error when i refresh.

**Comment by calculuschild** [comment]
New temporary workaround, since this will probably not be a quick fix.

Use `<code>` rather than backticks, and then replace `<` with `&lt;`

`What was once done with <code>&lt;div></code>'s can now be done as such:`

**Comment by Gazook89** [comment]
This definitely works for me, as I was thinking it would be nice to style some spans in code blocks (highlight relevant pieces).

**Comment by Gazook89** [comment]
I believe this can be closed, based on this quick test:
<img width="1238" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/58999374/71bfcf46-fdf7-4504-85b2-1be040c0cf81">


I'm going to close it.  Someone can reopen if they can prove me wrong.
