### ISSUE TITLE
New BookInsanityRemake font has error in quotation marks

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1474]
v3/Chrome 92/macOS

BookInsanityRemake seems to have new glyphs for the double and single quotation mark characters and they are "side specific", rather than uniform regardless of opening or closing as they were previously.  Now, when typing it seems the opening mark is not correct.  

<img width="470" alt="image" src="https://user-images.githubusercontent.com/58999374/127363306-0d4d6b5f-3812-435a-8d63-56127696b34f.png">

This may be a macOS issue though?  I looked at [this question/answer on the apple forums](https://discussions.apple.com/thread/7287561) for help and tried turning off "smart quotes" feature, to no avail.  I also did `option ]` and I did get the correct glyph.  So perhaps the glyph exists in the font set, but just isn't coded right?

Ugh, i've tried figuring out how font metadata works using FontForge but not with much success...

----
Edit for anyone in the future who might need it:
| Keyboard Entry | Result |
|:----------------|:------:|
| `option` `[`       |  “  *(opening)*      |
| `option` `shift` `[`   | ”    *(closing)*    |
| `option` `]` | ‘ *(opening)*  |
| `option` `shift` `]` |   ’  *(closing)*  |

**Comment by calculuschild** [comment]
I believe there's actually a setting in Marked.js to be state the correct glyph for us. I'll take a look.

**Comment by calculuschild** [comment]
Pushed an update to fix this.
