### ISSUE TITLE
[Minor] New Document should load with "Legacy" renderer radio button checked

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1478]
This is really a small thing, but when creating a New document, the renderer choice is not indicated in the radio buttons from the beginning.  I'm not sure if when v3 rolls out whether the v3 renderer is going to be default or not, but regardless it should indicate which is turned on from the beginning.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/58999374/127497960-a5b9a6d5-01f0-48e3-af85-ba2da3346b83.png">

**Comment by ericscheid** [comment]
See also #1498

**Comment by ericscheid** [comment]
The default for `Legacy` to at least be selected is now in effect (tested in not-chrome browser, tested in fresh incognito browser).

Issue #1498 is being addressed separately.

Closing.
