### ISSUE TITLE
v3 Span syntax doesn't work at beginning of lines

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1481]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/58999374/127545984-7e348041-dc18-4716-9a56-d8378faa10bf.png">

With the moustache spans, it doesn't seem they work when at the beginning of a new line.  Adding anything before it fixes it.  Even adding a hashtag before it to create a header fixes it.

It seems to add a line break between the first two brackets, breaking the syntax.  The below is copied from the inspector directly:
```
<p>{
{color=”red” here is some text}} </p>} 
```
Though it shows in the inspector as a single space:
```
<p>{ {color=”red” here is some text}} </p>
```

Tried in chrome and FF on the staging app.

**Comment by calculuschild** [comment]
Should work now with #1484 .
