### ISSUE TITLE
Indentation in Monster Stat Blocks

### ISSUE THREAD

**Issue by Sennsationalist** [naturalcrit/homebrewery#149]
**Browser Type/Version**: Google Chrome Version 51.0.2704.103 m

**Operating System**: Windows 8.1

**Issue Description**: Not sure if a bug or lack of feature, but the default formatting for the (wide) monster stat block doesn't seem to follow the Monster Manual style for indentation or spacing between lines in a few niche cases. The first is the 'Spellcasting' or 'Innate Spellcasting' feature where the new lines between spell lists per level of spell aren't single-spaced, and the line breaks  don't indent (See Drow spellcaster stat blocks on MM p129 for the proper style). The second is in 'Legendary Actions' where the new lines between legendary actions aren't single-spaced, and the line breaks don't indent (See Unicorn stat block on MM p293 for the proper style). Example images also included below.

I was able to format one stat block myself by pasting in empty characters, but this was a huge pain in the butt. A second solution was to use '___' before the lines that needed this sort of formatting, and ' - ' before each paragraph (which has the desired effect _outside_ of a stat block, but inside of a stat block this also creates an undesired horizontal bar due to the markup that monster blocks use. Below is my code with one example of 'fixed' Innate Spellcasting feature and one example of an improperly styled one, as well as one example of a normal set of Legendary Actions and one example of a 'fixed' set of Legendary Actions with an undesired horizontal bar.

**Brew code to reproduce**: http://homebrewery.naturalcrit.com/share/rJF1tDpI

```
___
___
> ## Black Unicorn
>*Large monstrosity, chaotic neutral*
> ___
> - **Armor Class** 12
> - **Hit Points** 47 (9d10 + 18)
> - **Speed** 50ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|18 (+4)|14 (+2)|15 (+2)|11 (+0)|17 (+3)|16 (+3)|
>___
> - **Damage Immunities** poison
> - **Condition Immunities** charmed, paralyzed, poisoned
> - **Senses** darkvision 120 ft., passive Perception 16
> - **Languages** Celestial, Elvish, Sylvan, telepathy 120ft.
> - **Challenge** 5 (1,800 XP)
> ___
> ***Charge. *** If the black unicorn moves at least 20 feet straight toward target and then hits it with a horn attack on the same turn, the target takes an extra 9 (2d8) piercing damage. If the target is a creature, it must succeed on a DC 15 saving throw or be knocked prone.
>
> ***Innate Spellcasting. *** The black unicorn's innate spellcasting ability is Charisma (spell save DC 14). The black unicorn can innately cast the following spells, requiring no components:
>
> At will: *detect evil and good, druidcraft, pass without      trace*                                                                                                                             
>1/day each: *calm emotions, dispel evil and good,      entangle*
>
> ***Innate Spellcasting. *** The black unicorn's innate spellcasting ability is Charisma (spell save DC 14). The black unicorn can innately cast the following spells, requiring no components:
>
> At will: *detect evil and good, druidcraft, pass without trace* 
>
>1/day each: *calm emotions, dispel evil and good, entangle*
>
> *** Magic Resistance. ***The black unicorn has advantage on saving throws against spells and other magical effects.
>
> ***Magic Weapons.*** The black unicorn's weapons are considered magical.
>
> ### Actions
> ***Multiattack.*** The black unicorn makes two attacks: one with its hooves and one with its horn.
>
> ***Hooves.*** *Melee Weapon Attack:* +7 to hit, reach 5ft., one target. *Hit* 11 (2d6 + 4) bludgeoning damage.
>
> ***Horn.*** *Melee Weapon Attack:* +7 to hit, reach 5ft., one target. *Hit* 8 (1d8 + 4) piercing damage.
>
> ***Healing Touch (3/day).*** The black unicorn touches another creature with its horn. The target magically gains 11 (2d8 + 2) hit points. In addition, the touch removes all diseases and neutralizes all poisons afflicting the target.
>
> ***Teleport (1/day).*** The black unicorn magically teleports itself and up to three willing creatures it can see within 5 feet of it, along with any equipment they are wearing or carrying, to a location the unicorn is familiar with, up to 1 mile away.
>
> ### Legendary Actions
> The black unicorn can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The unicorn regains spent legendary actions at the start of its turn.
>
>**Hooves.** the black unicorn can make one attack with its hooves.
>
>**Shimmering Shield (Costs 2 Actions).** The black unicorn creates a shimmering, magical field around itself or another creature it can see within 60 feet of it. The target gains a +2 bonus to  AC until the end of the black unicorn's next turn.
>
>**Heal Self (Costs 3 Actions).** The black unicorn magically regains 11 (2d8 + 2) hit points.
>
___
> - **Hooves.** the black unicorn can make one attack with its hooves.
> - **Shimmering Shield (Costs 2 Actions).** The black unicorn creates a shimmering, magical field around itself or another creature it can see within 60 feet of it. The target gains a +2 bonus to  AC until the end of the black unicorn's next turn.
> - **Heal Self (Costs 3 Actions).** The black unicorn magically regains 11 (2d8 + 2) hit points.
```

**Related Images** : 
![Homebrewery v. Monster Manual (Round 1)](http://i.imgur.com/nltVe52.png)

**Comment by stolksdorf** [comment]
Great error report! I'll look at this this weekend.

**Comment by stolksdorf** [comment]
The problem I can see is that there's no agnostic way to detect if you want the indent or not. In the example from the MM, "Shimmering Shield" is indented, but later on "spellcasting" is not. I have used the horizontal rule element `___` in spells to trigger this behaviour, but within monster blocks that element is rendered as the red triangle divider. There just ins;t enough markup to go around.

If you can suggest a solution that wouldn't break other parts of the markup, I'd be happy to implement. I just haven't been able to figure it out on my own.

**Comment by Sennsationalist** [comment]
Could you re-assign one of the `##` elements (header elements?) to Legendary Action blocks? Then make things under that block behave like the MM formatting. You'd probably need to add Legendary Action blocks into your examples if you did it this way, to show people how to achieve the desired formatting.

Alternatively, could you use another element that isn't used within monster stat blocks to tell the following lines to indent after wrapping text, and to single-space lines?

I'm sorry that I can't be more helpful, I only know a little about coding, and almost nothing about Markup! Hope you can figure out a way to do this :)



P.S. Would it be possible for you to make a page with documentation of your version of Markup? I have some skills in this area, enough to figure out how to do things that I want to do, but many people would struggle to out how to make some of the elements that they are looking for.

**Comment by tarper24** [comment]
There doesn't look to be an easy way for him to do this. Even the MM is pretty much all over the place on this issue.

![Image of Adult Copper Dragon entry in the Monster Manual](http://i.imgur.com/X0QKER6.png)

That being said, here is my fix:

I simply change your markdown horizontal rule `___` to an HTML horizontal rule and hid it. 

```HTML
<hr style='display:none;' />
```

You also need to have a blank line immediately following this code, or it does NOT work.

Another issue is that this causes it to change the text color. NOTE: the MM does not do this. To override this, add the following style block into your sheet:

```HTML
<style>
.phb hr+blockquote hr+ul {
	color:inherit;
}
</style>
```

I found this to be an adequate solution, and I hope you do too! Sometimes a global fix cannot be applied. When that happens only the best hack shall survive.
http://homebrewery.naturalcrit.com/share/B1Zwq4xNF

print(closing);
print("~tarper24);


Full code for the shown indentation:

```HTML
> ### Legendary Actions
> The black unicorn can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The unicorn regains spent legendary actions at the start of its turn.
>
<hr style='display:none;' />

> - **Hooves.** the black unicorn can make one attack with its hooves.
> - **Shimmering Shield (Costs 2 Actions).** The black unicorn creates a shimmering, magical field around itself or another creature it can see within 60 feet of it. The target gains a +2 bonus to  AC until the end of the black unicorn's next turn.
> - **Heal Self (Costs 3 Actions).** The black unicorn magically regains 11 (2d8 + 2) hit points.

<style>
.phb hr+blockquote hr+ul {
	color:inherit;
}
</style>
```
