### ISSUE TITLE
Hanging Indents/Definition Lists not working in Monster blocks on Mac

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1496]
On my macbook, Chrome 92, v3:   The use of Definition Lists to create a "list" with hanging indents is not working, only while inside monster stat blocks.  The two blocks below are the same, and there is no extra styling anywhere in the document, but the stats do not render the same.  

Chatted with @calculuschild about it already, and he does not have the same issue.  I do not have the issue in Firefox, only Chrome.  The Calculated values in Chrome inspector show the same values.  Tried a hard refresh (shift + reload on mac).  Recreated the issue across multiple new documents (making sure that v3 was checked).

Bizarro.

```
{{monster,frame
**Condition Immunities** :: buzzed
**Senses**               :: darkvision 60 ft., passive Perception 8 plus a million bucks
**Languages**            :: None
**Challenge**            :: 12 (4558 XP)
}}

{{test
**Condition Immunities** :: buzzed
**Senses**               :: darkvision 60 ft., passive Perception 8, Plus 100 hundred billion
**Languages**            :: None
**Challenge**            :: 12 (4558 XP)
}}
```
<img width="381" alt="image" src="https://user-images.githubusercontent.com/58999374/127757562-11aa4ccc-dbb7-430a-9ee6-ff27367656bb.png">

**Comment by ericscheid** [comment]
Looks like a Chrome(Mac) bug. Appears to be triggered if the `<dd>` does not contain italic text and the line height has been set near to 1.2em.

Toggling off the css rule of `.page .monster dl { line-height: 1.2em; }` in the inspector makes the issue go away.

![image](https://user-images.githubusercontent.com/2605467/127761428-e1f6c02f-e1cb-4237-b525-c544c72b4855.png)

**Comment by calculuschild** [comment]
Fixed by #1505 

Turns out we had two separate commands setting the line height and I guess Mac Chrome doesn't like the redundant styles.

**Comment by ericscheid** [comment]
Or possibly the greater specificity of the extra rule.

**Comment by calculuschild** [comment]
In this case it seems like it was literally the same rule as far as I could tell:

```
.page .monster dl{
  line-height : 1.2em;
}
```

And 

```
.page .monster dl{
     line-height : 1.2em;
}
```

The way I had the .less written out it generated the same rule twice.

In any case this seems to be fixed now.

**Comment by Gazook89** [comment]
There is a style in the monster block that seems odd:

```
.page dl+* {
    margin-top: .28cm;
}
```

It is creating this odd spacing:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/58999374/130307385-4ff6a743-e46a-43cf-bb1d-abf002022293.png">

I'm assuming the spacing is there for a reason, but likely should be removed in `.monster`?  For example:

```
.page dl:not(.monster)+* {
    margin-top: .28cm;
}
```
