### ISSUE TITLE
Reloading a cloning will overwrite any changes done

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1499]
When cloning a brew the browser is sent to `/new/:id` where changes can be made.

Hitting reload or similar will cause the cloning to re-occur, overwriting any changes made in that `/new` editor.

What should happen is that after the cloning the `/:id` should be stripped out of the browser location.

**Comment by ericscheid** [comment]
This is tricky. Usually, in web architecture, a POST to a generic url is often responded with a HTTP 302 response with a specific url pointing to a newly minted resource. In our case a request for `/new/:id` needs to eventuate with a browser location of `/new` only, but we can't do that by 302 redirecting `/new/:id` to `/new` because the editor localStorage hasn't been set up.

We'll need do finagle the browser location via `history.replaceState(stateObj, title, [url])` on load somewhere.

**Comment by ericscheid** [comment]
If the user truly wants to reclone the original brew, they can go to that original brew and clone it.

**Comment by G-Ambatte** [comment]
One option would be for `/new/:id` to load the contents of the brew to `localStorage`, and then immediately redirect to `/new`. Of course, if the user had anything that was only saved in localStorage, it would be lost...
An alternative is that we were discussing a programmatic option the other day to create a Brew that a user could then save to their account, e.g. `/template?title=MY%20NEW%20BREW&text=data_goes_here`. Cloning could use such a template brew by loading the content of the source brew's title/text/style/whatever to the URL without touching localStorage.

**Comment by ericscheid** [comment]
Forcing a 2nd request to the server seems excessive. But also possibly necessary, as the page itself contains the cloned brew content and reloading that might have the same result as banging `/new/:id`. Will have to test.

**Comment by G-Ambatte** [comment]
> We'll need to finagle the browser location via `history.replaceState(stateObj, title, [url])` onload somewhere.

I randomly thought of this issue this morning, and this is the simplest solution to the problem. We now set the content of local storage on page load, so the issue of whether we should wipe the user's local content is now resolved, as it already happens.

So in  `./client/homebrew/pages/newPage/newPage.jsx` at the end of the `componentDidMount` function, add a line or three that checks the current URL and if NOT `/new`, perform a `history.replaceState()`.

**Comment by dbolack-ab** [comment]
@ericscheid Does this PR solve this issue to your liking?

**Comment by ericscheid** [comment]
> @ericscheid Does this PR solve this issue to your liking?

Looks good to me. A manual refresh or a subsequent navigation refresh (from hitting the back-button on some future navigation) would cause the browser to reload the resource from the document.location url (and not the actual original resource).

👍

**Comment by 5e-Cleric** [comment]
This is solved.
