### ISSUE TITLE
microdata on user page?

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1511]
Could we get the actual value of `brew.updatedAt` expressed into the html of the page as an html attribute?

Something like this:
```
<span class="updatedAt" title="8:14pm on July 12th, 2018" datetime="2018-07-12T20:14:13Z">
  ...
</span>
```

This line here, I think:
https://github.com/naturalcrit/homebrewery/blob/6f6c4acf7efc02b32a77291081851c1b0bec0c68/client/homebrew/pages/userPage/brewItem/brewItem.jsx#L116-L118

----

And while we're at it, express the `brew.createdAt` value into the page as another span, but use CSS to hide that by default.

```html
<span class="createdAt" title="8:14pm on July 12th, 2018" datetime="2018-07-12T20:14:13Z">
  ...
</span>
```

```css
.userPage .brewItem .info .createdAt { display: none; }
```

----

No immediate need, but it will enable some creative hacking, and possibly some accessibility improvedments.

The `title=<human-readable-moment>` will enable a tooltip on the html element.

**Comment by ericscheid** [comment]
Also, put classnames on each of the meta data spans inside the `<div class="info">` for good measure.

**Comment by Gazook89** [comment]
Class names on the published vs unpublished divs too. Class names all the way down.

**Comment by G-Ambatte** [comment]
> The title=<human-readable-moment> will enable a tooltip on the html element.

I like this, I've pushed it onto the `BrewItem` so anywhere over the item gives you the tooltip, and then populated the tooltip with the Created and Updated date information.
However, it appears that the Google Brews are returning invalid data for the Created Date, so the ordering system replaces it with the current time and date... So Google Brews are always considered the most recently created.

Still investigating; I'll update if/when I discover more.

**Comment by G-Ambatte** [comment]
I pushed the `googleBrews` object to the console from `server.js`, which showed me the following:

![image](https://user-images.githubusercontent.com/19826659/128584985-c3c886d2-1604-4e33-8f32-ba87692f5d64.png)

I tried messing with the Google permissions, which resulted in "Error Listing Google Brews: Error: Insufficient Permission: Request had insufficient authentication scopes." Changing it back got the Brews listing again, but for some reason, the `brew.createdAt` (set by `file.createdTime` ) returns `undefined`.

**Comment by G-Ambatte** [comment]
Got it, `createdTime` wasn't included in the `fields` list of `listGoogleBrews`.
