### ISSUE TITLE
Logout on Naturalcrit redirects to http

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1515]
![image](https://user-images.githubusercontent.com/5878534/129069254-c9dfc69b-6f7d-4937-9503-bb76898a32d4.png)

We need to get Naturalcrit.com to force ssl like HB does. In the mean time, direct all users to https://www.naturalcrit.com instead of just www.naturalcrit.com until this is fixed so they can log in properly.

**Comment by 5e-Cleric** [comment]
Fixed by https://github.com/naturalcrit/naturalcrit/pull/33
