### ISSUE TITLE
I would like to delete my account on homebrewery/naturalcrit

### ISSUE THREAD

**Issue by ADubhlaoich** [naturalcrit/homebrewery#1520]
Hello!

I'm aware this is definitely not the place for it, but there does not appear to be any kind of contact form or mechanism on the actual website, I have similarly not found any kind of contact e-mail address for the maintainers of this project, and do not possess a reddit account - so here I am.

I would like my account on homebrewery/naturalcrit to be deleted. What details do I need to provide?

**Comment by calculuschild** [comment]
Give me a username and detail on any of your brews (titles, etc) so I can make sure it's the right account.

Do you want all the documents deleted as well?

**Comment by ADubhlaoich** [comment]
The username is 'UnfetteredPanopticon'. There is zero content attached to the account.

**Comment by calculuschild** [comment]
Your account is now deleted. 👍

**Comment by nwfinancesolved** [comment]
Is there a different way that I can contact you to delete my account?

**Comment by calculuschild** [comment]
> Is there a different way that I can contact you to delete my account?

Send a message to me /u/calculuschild on Reddit.

**Comment by pact-wheeler** [comment]
I do not have a reddit

**Comment by calculuschild** [comment]
@pact-wheeler 

You can visit us on our Gitter page and sign in using your GitHub account. Click on my name and you can send me a private message.

https://gitter.im/naturalcrit/Lobby
