### ISSUE TITLE
Save to google failed

### ISSUE THREAD

**Issue by justin-hoops** [naturalcrit/homebrewery#1521]
Error: Service Unavailable

```
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
First thing to try is to logout on the www.naturalcrit.com/login page, and then log back in using the login Google option. See if that fixes it. @calculuschild can take it from there if that doesn't work.

**Comment by ericscheid** [comment]
> ### 503 Service Unavailable
> The _HTTP 503 Service Unavailable_ server error response code indicates that the server is not ready to handle the request.
>
>Common causes are a server that is down for maintenance or that is overloaded. This response should be used for temporary conditions and **the Retry-After HTTP header should, if possible, contain the estimated time for the recovery of the service.**
>
>> Note: together with this response, a user-friendly page explaining the problem should be sent.
>
>Caching-related headers that are sent along with this response should be taken care of, as **a 503 status is often a temporary condition** and responses shouldn't usually be cached.

Does the Google API sent the Retry-After HTTP header? Might be hard to know without encountering a 503 response.

If that json response (above) is simpy echoed by HB, we could try echoing the headers too and wait for a user to encounter it.

We'd then know if we could then be in the position to do something smarter (e.g. briefly wait and retry, or throw a message).


----
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After

**Comment by calculuschild** [comment]
The 503 is coming from our own server, not Google.

According to Google we haven't had any 500-level errors in the last month. The *only* errors Google has reported are from "drive.files.get" when a user retrieves a brew (or tries to detect the presence of their Homebrewery folder in google drive), and those all seem to be 404 Not Found errors. I may be missing something but I think it's entirely on our end.

**Comment by calculuschild** [comment]
Just looking at the Heroku logs, we get occasional errors from Google like this:

`Error Listing Google Brews: Error: Insufficient Permission: Request had insufficient authentication scopes.` Which means the user's credentials are expired/invalid. I'm not sure what that means when they re-log-in and it still doesn't work.

**Comment by ericscheid** [comment]
Ah yes, I see our browser code now .. 

```
return request.post('/api/newGoogle/').send(this.state.brew)["catch"](function(err) {
      console.log(err.status === 401 ? 'Not signed in!' : 'Error Transferring to Google!');
```

Alos
> When the user's credentials are bad, we don't get any file back from Google with a 403, and then in the next line our server crashes because it expects data to be there, and then our server ends up sending a 503 because we crashed.

OK, that is buggy code on our plate.

**Comment by calculuschild** [comment]
Yes. See #1516 . We should maybe create a central issue to handle this bug, and then we can close these duplicate ones out when the users specific case is handled (by logging out and back in our when we don't hear back from them, etc).

**Comment by justin-hoops** [comment]
I figured out the issue, I wasn't correctly logged in / didn't give the required permissions to my drive. So it was user error, but the error messaging was not helpful in figuring out the problem.

**Comment by Gazook89** [comment]
There were a lot of user reports of this same issue likely due to Google Drive integration going live a year ago, and the credentials being valid for only a year without signing out and back in. In believe the error message has been updated so your report to be more helpful going forward.

**Comment by ericscheid** [comment]
The messaging for HTTP 403 has been improved. Any other error is unexpected and messaging is generic "report this on github".

Closing.
