### ISSUE TITLE
{curly-injector} on block elements leaves an empty `<p/>`

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1535]
This markdown 
```
##### curly-inject this block element
{borders}
```

.. creates this html:
```
<h5 class=" borders" id="curly-inject-this-block-element">curly-inject this block element</h5>
<p></p>
```

.. which creates a blank line in the render (unless hidden by some other css)
![image](https://user-images.githubusercontent.com/2605467/128687699-edbb322d-af46-45d4-8efa-c0fe2b0116c2.png)

This is noticeable if the following element is a table, but not if it is a paragraph of text — the extra `<p/>` is hidden but still there:
![image](https://user-images.githubusercontent.com/2605467/128688181-b2ff73c4-77f0-43af-aa4d-d228eacddd26.png)

**Comment by Gazook89** [comment]
@ericscheid I don't think this is an issue anymore, but can you double check on your side?  I see `<p>&nbsp;</p>` but not empty tags.  And i think the non-break-spaces is to fix an empty column problem (maybe).

<img width="447" alt="image" src="https://user-images.githubusercontent.com/58999374/192124962-192c078d-6aa8-431b-83a6-6c1b9841b67f.png"> 
<img width="447" alt="image" src="https://user-images.githubusercontent.com/58999374/192124970-ae92b060-6593-4d33-b2ca-f94047a6a131.png">

**Comment by dbolack-ab** [comment]
@ericscheid Is this still occurring for you?

**Comment by ericscheid** [comment]
It looks to be fixed.

Yes, the `>p?&nbsp;</p>` is there for column filling reasons.
