### ISSUE TITLE
Safari not working due to unsupported RegEx

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1545]
Completely changing this Issue to better reflect the problem as a reddit user posted:   Safari is no longer working as it has before.  Still an unsupported browser, but issue stems from regex "look behind" indicator that is unsupported in Safari, implemented in v3 tables.  

Reddit post:  https://old.reddit.com/r/homebrewery/comments/p1rel1/issue_homebrewery_not_working_on_apple_safari/

**Comment by calculuschild** [comment]
Fixed with https://github.com/naturalcrit/homebrewery/commit/a48c74b2e714e769c0fe714c189ea785990458f8
