### ISSUE TITLE
Error message on save attempts.

### ISSUE THREAD

**Issue by LoreAndOrderDND** [naturalcrit/homebrewery#1552]
Off the top of my head, I'm guessing that you never expected some madman to write an entire D&D adventure on your software, and that 1200 lines of input is a little too much. If that's not the case, however, you might want to look into it.

In the meantime, I'm going to break up my adventure into a separate homebrew for each chapter, and go from there.

Thanks so much for your utility. It's amazing, and will absolutely be credited in the final product!

Error: Service Unavailable

```
{
  "status": 503,
  "method": "PUT",
  "url": "/api/updateGoogle/gGhpT8VJwP29"
}
```

**Comment by calculuschild** [comment]
Thanks for the report!

We actually have people making hundred-page documents on here pretty regularly; this is something new, an you're also not the first. See #1516 for a workaround and our current progress on getting this fixed.
