### ISSUE TITLE
Cannot Save my files

### ISSUE THREAD

**Issue by iamjokarman** [naturalcrit/homebrewery#1564]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Try logging out at https://www.naturalcrit.com/login and then logging back in with your Google credentials.  Should reset your credentials.

**Comment by iamjokarman** [comment]
> Try logging out at https://www.naturalcrit.com/login and then logging back in with your Google credentials. Should reset your credentials.

I did this and was brought to a blank page, no way to log out.

**Comment by Gazook89** [comment]
Hmm, should have this, with the option at the bottom:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/58999374/129294022-2ba7e851-8e4f-4f7f-bcab-be3e502d58c8.png">

If that is showing a blank page for you, then likely need to get the big guns out (@calculuschild )

**Comment by iamjokarman** [comment]
> Hmm, should have this, with the option at the bottom:
> 
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/58999374/129294022-2ba7e851-8e4f-4f7f-bcab-be3e502d58c8.png">
> 
> If that is showing a blank page for you, then likely need to get the big guns out (@calculuschild )

Right, I don't see that.

I see this:
![Screenshot_1](https://user-images.githubusercontent.com/88865015/129298801-52e9fbb9-53e5-4025-84fb-ee7ae8dbfde1.jpg)

I might try logging out of my google account, thought when I signed in on another browser it did the same thing.

**Comment by calculuschild** [comment]
Your screenshot shows the wrong address. You need https://www.naturalcrit.com/login not https://homebrewery.naturalcrit.com/login

**Comment by Gazook89** [comment]
@iamjokarman are you still having issues with this, after trying the correct link as mentioned above?  

Closing as duplicate for now, #1580, but can re-open if needed.

**Comment by iamjokarman** [comment]
I'm not sure if this will attach to this thread now that it has been closed, but my issue was never resolved. Even after logging out, logging back in, creating a new account, clearing my cookies, trying a different browser, I could not for the life of me get a file to save to my profile and the original document I created shows up every time I try to click new.

**Comment by calculuschild** [comment]
You might just have something in your Google account that is preventing it from fully linking. Let me know your username and I'll detach it from Google. Then you can proceed to set it up with just a plain username and password (don't link to a google this time) and try saving a document that way.

**Comment by iamjokarman** [comment]
> @iamjokarman You might just have something in your Google account that is preventing it from fully linking. Let me know your username and I'll detach it from Google. Then you can proceed to set it up with just a plain username and password (don't link to a google this time) and try saving a document that way.

My username attached to a google account is "jokarman"

I did create an account without attaching it to a google account and it did the same thing, though maybe detaching the first account could help.

**Comment by calculuschild** [comment]
@iamjokarman Ok, I have reset it. Go ahead and visit https://www.naturalcrit.com/login and sign up for a "new account" just using the same username and password and it should let you log in. If you are able to save, you can just leave it at that and be on your way, or you can go back and link to Google and we can see what happens then.

**Comment by iamjokarman** [comment]
Praise Melora, that worked!

Thanks for all the help and patience!

**Comment by calculuschild** [comment]
No problem. Glad we got it solved!
