### ISSUE TITLE
Injection Brackets:  Cannot Target List Items well.

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1585]
In v3, targeting individual list items is inconsistent:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/58999374/129817148-2b4112e5-367a-4907-a314-b30566836a46.png">

In the above, I would expect that the line with blue injection would not render a new line in the preview window; that it would just target the previous list item, apply it's attributes, and do nothing else.  

Alternatively, I would expect that the injection brackets are picked up and applied to the list item.  Right now, it appears they are not shown as plain text (which is good), but I don't see them applying to any element (and confirmed in the DOM inspector):
<img width="542" alt="image" src="https://user-images.githubusercontent.com/58999374/129817436-9d87f5ba-1fef-4bee-8b12-edd6a91a4c87.png">

A style can be applied to an entire list, as expected:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/58999374/129817514-ae9e3675-8802-443e-b9c0-0b298cc5a142.png">

This is super minor and I'm only opening the issue in case it's something that would bother you and is an easy fix.

**Comment by ericscheid** [comment]
In the first example the injection is being done to a `<p />` which is the content of the `li`. The first item is simply `<li>first item</li>` and thus no `<p>` and thus no `.page p {margin-bottom: 0.8em;}`

In the second example the injection has no preceding adjacent sibling, and so is a no-op. The injection does not apply to the parent, only an adjacent sibling.

At no point was the injection being done to actual `<li>` elements.

A workaround is to not use injects but instead use a curly-span

```
- one
- {{color:red two}}
- three
```

This workaround is not useful if you want to apply a list-item specific styling to that specific list-item.

```
- one
- {{list-style-type:circle nope: the span is injected}}
- three
- nope: a newly minted paragraph is injected
{list-style-type:circle }
```

**Comment by Gazook89** [comment]
Good point on spans. I think this can be closed.
