### ISSUE TITLE
I could not save my file, and cannot find a way to change the name of the file

### ISSUE THREAD

**Issue by Avarice-fist** [naturalcrit/homebrewery#1602]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71831:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72140:10)
{
  "status": 503,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

I'm not sure what to do to change it.

**Comment by Gazook89** [comment]
See discussion #1580 for a solution regarding saving. To change the title, go to the meta data editor, which can be found in the snippet bar, furthest icon to the right. 

If the linked discussion doesn't fix the issue, let us know

**Comment by Avarice-fist** [comment]
I clicked the little tab for the title and description of the document and entered the title. It appeared in the top bar, but did not allow it to save.
![image](https://user-images.githubusercontent.com/40610244/130717757-6940fcbd-868e-4941-bc59-047a63d3b2c5.png)

**Comment by calculuschild** [comment]
@Avarice-fist Did you take a loot at Discussion #1580 for the saving issue? Renaming your document won't have any effect if you don't resolve the saving issue first by refreshing your Google Drive credentials.

**Comment by Avarice-fist** [comment]
I signed in again with Google, checked my Google Drive and signed into it again. This hasn't solved the problem either.

**Comment by calculuschild** [comment]
Did you make sure to fully log out before signing in again? It may be helpful to clear your cookies as well before trying.

If it still doesn't work I can try something else.

**Comment by Avarice-fist** [comment]
I'll try that. Though it might be a minute before I do so.

**Comment by Gazook89** [comment]
@Avarice-fist just want to check back on this and see if you are all good to go, or if need to keep this open and take a second look?

**Comment by Gazook89** [comment]
Will close this issue due to no response, but it can be re-opened if the above steps did not help and still having issues.
