### ISSUE TITLE
even/odd footers flipped on /print vs /share pages

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1612]
> https://homebrewery.naturalcrit.com/share/n_qEpe-cH__4
> 
> I have a bit of an issue. When I attempt to save my homebrewery document as a pdf, it seems to either insert or remove a phantom page, and completely messes up the page count. [The footer graphic that] had once been on the left side of the page is now on the right and vice versa. This doesn't appear while viewing the document on the Homebrewery, only when printing to PDF.

**Comment by Gazook89** [comment]
Could this also be related to why Firefox renders a blank page at the start of a brew when going to Print to PDF?  I don't think it is...but mentioning it just in case it is.  I've always had Firefox generate an extra blank page in the Print dialog (but not on the /print/ page).  No issue with Chrome.
