### ISSUE TITLE
Drop-Shadow applied to all images

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1642]
In one of the last updates, drop-shadow was applied to all `.page img` elements and I don't think this is correct.   For example, the default "image" snippet now shows a drop-shadow......and when combined with the addition of `mix-blend-mode:multiply;` to the default snippet it obviously doesn't look right.

https://github.com/naturalcrit/homebrewery/blob/16076d1481cbd15db58eaad4b2c1aea552f56791/themes/5ePhb.style.less#L358-L362

<img width="400" alt="image" src="https://user-images.githubusercontent.com/58999374/132250489-537a6085-fc00-401f-90ca-889ea3399a4c.png">

**Comment by calculuschild** [comment]
Fixed by #1651
