### ISSUE TITLE
Misc fixes to V3 style before release

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1647]
From Gitter:

- [x] Remove old styles (hr + etc.)
  - *There was a last rule for `hr + ul` for spell lists that is now gone. Can't find any more...*
  
- [x] Clarify in V3 intro that legacy things wont convert directly to v3
- [x] Make .descriptive full width
- [x] should spellList span 2 columns by default? (it currently is)
  Or change it so that the snippet is `<div class="spellList wide">`. The latter option helps build consistency between things that span 2 columns, and it can be difficult to "undo" the column spanning

- [x] Large spacing that seems off. Basically, the descriptive box has a rule .descriptive + * {margin-top: __em} which means that if a header follows, the __em is going to be quite large.
  - *Need to make all margins use cm instead of em for stability. At least for margin-top spacings between elements.*

- [x] Related: .note + * has margin-top: 1.3em and .descriptive + * has 1.4em.

- [x] https://files.gitter.im/5b92953ad73408ce4fa74346/7Mly/image.png If you turn off .page .block {-webkit-transform: translateZ(0);}, you get this: https://files.gitter.im/5b92953ad73408ce4fa74346/xOWp/image.png Doesn't happen with .descriptive
  - *Solution is going to be: Make all blocks `display: inline-block` (also fixes issues with 2n'd column having different top spacing), Make all blocks `width: 100%` so they still fill the column when empty, Make all blocks that have an outset border have a `margin-top: X` where X is the amount of offset, so borders aren't being cut off on column breaks.*
  - [x] .descriptive
  - [x] .note
  - [x] .monster
  - [x] .classTable
  - [x] pre code
  - [ ] others?

- [x] .descriptive has display: inline-block, .note doesn't
(.note also hasposition: relative` but doesn't affect this)

- [x] differences between .descriptive and .note https://files.gitter.im/5b92953ad73408ce4fa74346/2ySA/image.png

- [x] Why is the note border done via .page .note::before and not simply in the .page .note ?

- [x] Drop-shadow should not be applied to all images #1642

**Comment by ericscheid** [comment]
- [ ] `{curly-inject}` on line alone renders a `<p></p>` which can mess up styling because of `.page p+* { margin-top: .27cm; }`. (Maybe add `:not(:first-child)` to selector ?

![image](https://user-images.githubusercontent.com/2605467/132331446-5dacde35-6ed5-4a9b-94c9-28ca8972ee8c.png)
