### ISSUE TITLE
[v3] Increase/Add padding for .page pre code { }

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1668]
In v3, I suggest adding a small bit of padding to the `pre` blocks:

```
.page pre code {
	padding:5px
}
```
Here is the current situation:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/58999374/132951993-be029d1e-d717-4ef1-993a-1a85427404ba.png">

Here is with padding:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/58999374/132952003-6a95a60d-0950-4918-8ddc-5f49aaaa507e.png">

**Comment by calculuschild** [comment]
Fixed with a3b50efe78bfca7a477d01a22640d093f23e14b0
