### ISSUE TITLE
Save and return to previous cursor position when switching editors

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1669]
Currently, switching between text and style editors resets the cursor position/viewport so if jumping from one to make a small tweak in the other you lose your place.  It can be annoying on long brews.  If the cursor position can be saved on exit that would be helpful.

**Comment by calculuschild** [comment]
I agree.

**Comment by Gazook89** [comment]
This is all fixed with PR #1763 which was merged awhile ago.  Closing this issue :)
