### ISSUE TITLE
[v3]  Additional markdown highlighting for injection syntax

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1670]
I don't have strongly formed thoughts about what it should look like, but I think we need to add some markdown highlighting for injection brackets, *and/or* for image syntax?   Here is an example of something that just doesn't stand out from the text:

<img width="452" alt="image" src="https://user-images.githubusercontent.com/58999374/132952618-530c5ee5-98e3-4148-bd27-185bcb0347f8.png">

I don't have strong feelings about this, so feel free to dismiss and close.   But it bothered me just enough to raise it as a possible issue.

**Comment by calculuschild** [comment]
Yes, we should have some highlighting for injection curlies. Any color preference? Don't want to confuse it with divs and spans. For some reason I was thinking like orange?

**Comment by Gazook89** [comment]
Hot pink.  The hotter the better.  

(no preference).
