### ISSUE TITLE
Page Layouts

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1673]
There are a handful of generic page layouts that are commonly used by brewers for which Homebrewery could offer templates, either through snippets or possibly some other means.  I'm opening this issue to coalesce a few older issues and collect new ones so there can be some unity in approach.  

### Possible Layouts
- [x] Cover Page  #640, #1334
- [x] Back Page
- [x] Credits
- [x] Single Column Half Page (left and right):  Image on one side, single column of text on the other
- [x] Half Top/Bottom:  Image on top, text on bottom, and vice versa.  
- [x] "Part" or "Section" pages as found in the PHB 5e  #781 , [reddit](https://old.reddit.com/r/homebrewery/comments/pd7qqa/how_to_do_a_cover_for_parts_like_in_the_phb/)

This list could also include "Card" templates as well.  #212, #1167

### Considerations
1. Having the ability to style the `.page` element itself via snippets would be great, as discussed in #1489.   This would reduce additional divs being used.
2. In the "Half Page" layouts
  a. the precise dividing line between image and text should be easily adjusted within the snippet.
  b. the text background should be useable with any page background, rather than only specific backgrounds (such as how people normally use /u/flamable-concretes stains).  [This can be done using css mask-image.](https://homebrewery.naturalcrit.com/share/aasPjdU7stq6).  Have to watch out for browser compatibility or fall backs. 
3. the layouts should extended 1/2 inch beyond the largest dimension (Letter or A4) of the page to allow for possible future addition of page margins.
4. Doesn't necessarily *have* to be done with snippets, but it's probably the easiest method with the tools we have now.

**Comment by 5e-Cleric** [comment]
Most of these are done by now, except cards and credit page.
Half pages are easily done with the watercolor masks.

Mixing watercolor masks, even other combinations work great:

|vertical and horizontal|horizontal and corner|
|:-:|:-:|
|<img width="200" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/3809c295-a3e4-44ad-aba9-61105d0b64d5">|<img width="200" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/65ad210d-def4-4b68-9947-7a1a77854c20">|

**Comment by 5e-Cleric** [comment]
linking #3783 here because it is somewhat related

**Comment by 5e-Cleric** [comment]
#3692 added more page sizes, closing this.
