### ISSUE TITLE
tweak position of sort-container on user page

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1675]
The `sort-container` on the user page isn't properly centered.
![image](https://user-images.githubusercontent.com/2605467/133012285-3eda4583-d93d-4386-ab13-e8d829488297.png)

The position is determined by `.userPage .sort-container { left: calc(50vw - 408px); `.

Change this to `.userPage .sort-container { left: calc(50vw - 400px); `.

![image](https://user-images.githubusercontent.com/2605467/133012506-c7fe873f-24ab-4fe3-bc0f-9b3e0f927d01.png)

**Comment by ericscheid** [comment]
`.userPage .sort-container {left: unset; margin-left: -56px;}`

**Comment by calculuschild** [comment]
> The sort-container on the user page isn't properly centered.

This actually looks fine to me:
![image](https://user-images.githubusercontent.com/5878534/133320772-20438460-4355-4d12-ab0c-210f88519647.png)

Changing it to -400px makes it worse:
![image](https://user-images.githubusercontent.com/5878534/133320828-6e478c31-7752-46f1-80de-d10d27f70c82.png)

Is this a Mac vs Windows thing or has something else changed?

**Comment by calculuschild** [comment]
At least for me, it looks like that offset is due to the width of the scrollbar on the right of the page throwing off the "center". Removing the scrollbar fixes this. This is probably enough of a size difference between browsers to be noticeable.

**Comment by ericscheid** [comment]
Confirmed — it is the browser scroll bar screwing things up.

![image](https://user-images.githubusercontent.com/2605467/133340416-bd5560fe-86ea-4cae-a5fa-e92c1040d029.png)


Also confirmed: positioning via `margin-left: -56px;` works both with and without a scroll bar intruding.
