### ISSUE TITLE
Unable to save in Homebrewery

### ISSUE THREAD

**Issue by Guiding-Creations** [naturalcrit/homebrewery#1682]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
@Guiding-Creations are you still having issues with this? Sorry for delayed response-- if still running into this issue, checkout discussion #1580 and see if the steps there don't help. Going to close this for now as a duplicate but it can be reopened if the problem persists.

**Comment by Guiding-Creations** [comment]
Yes. I am still having issues.

I do get the error that my credentials have expired however, I have signed
out, closed the tab, opened a new tab and signed back in. I still get the
same error. I have connected my account via google.

**Comment by calculuschild** [comment]
@Guiding-Creations Are you making sure to sign back in with the "sign in with google" button? Signing in with just username and password will not send the request to Google to refresh your credentials and the Homebrewery will continue to use your outdated ones.

You can also try clearing your browser cache while logged out. This may help to flush out anything that's refusing to get renewed.

**Comment by Guiding-Creations** [comment]
Yes

**Comment by calculuschild** [comment]
In that case, you can send me your username and I can manually unlink you from Google completely. This will make sure when you "sign in with google" there is absolutely no old data sitting around and Google *has* to send you a fresh key. Do you want to give that a try?

**Comment by Guiding-Creations** [comment]
Sure thing.

Username: ZavierB

**Comment by calculuschild** [comment]
Alright, you are now unlinked from Google. Go ahead and try logging out and back in using the "sign in with google" button now.

**Comment by Guiding-Creations** [comment]
I can finally save, thank you!
