### ISSUE TITLE
Feature suggestion: transclusion of pages

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1711]
From [reddit](https://www.reddit.com/r/homebrewery/comments/prwqt7/import_other_hombrewery_pages/)

> Could you add a feature that lets you import specific pages from another doc `\import Page#1 "Doc link"`
> 
> This would be usefull for allowing people to break up documents over multiple books for editing purposes and allowing editors acess to only specific books, and would make their code and creations more secure.
> 
> So the main idea here is to import specific pages from another hombrewery that you own or that is open so that you can make lots of little documents from one big document and re-arrange stuff and that way you only have to edit the main doc and then change what pages are imported to maintain the smaller docs. This is useful if you want to make a dumbed down version of your rule book where it has less pages and there for the person only reads what is in the book and doesn't get confused.

**Comment by ericscheid** [comment]
Likely will be complicated.

For example, if a brew is open for editing, how often is the referenced sub-brews fetched for transclusion? Or only on load/reload?

**Comment by 5e-Cleric** [comment]
I think this is a bad idea altogether, it will also cause problems with the CSS, will it be imported? no?
Either way, it is a very complicated feature, in a very old issue, closing this for now, we can reopen if we want to take yet another very complex issue.

**Comment by ericscheid** [comment]
Certainly would be complicated.

Another quirk is will the transclusion be done server-side, or resolved client-side? There are pros and cons to both.
