### ISSUE TITLE
Not able to save

### ISSUE THREAD

**Issue by HuMpED004** [naturalcrit/homebrewery#1713]
Error: Bad Request

```
Request/<@https://homebrewery.naturalcrit.com/homebrew/bundle.js:71824:19
require<[5]</Emitter.prototype.emit@https://homebrewery.naturalcrit.com/homebrew/bundle.js:1764:20
require<.superagent</Request.prototype._end/xhr.onreadystatechange@https://homebrewery.naturalcrit.com/homebrew/bundle.js:72133:10

{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Checkout the steps in discussion #1580 for a resolution. Let us know if that doesn't work.

**Comment by Gazook89** [comment]
going to close this as a duplicate-- if the steps in #1580 haven't helped get your google credentials reset then come back here and we can re-open the Issue and see else needs to be done.  Thanks for the report!
