### ISSUE TITLE
Error: Homebrewery doesn't save

### ISSUE THREAD

**Issue by Memearchpriest99** [naturalcrit/homebrewery#1715]
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

```
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at Request.crossDomainError (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72027:13)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72130:19)

**Comment by G-Ambatte** [comment]
This is an unusual error; is this still happening for you?

**Comment by Memearchpriest99** [comment]
No, it stopped after a few hours, and I agree, it is quite weird. But
thanks anyways :)

‫בתאריך יום א׳, 3 באוק׳ 2021 ב-22:17 מאת ‪G.Ambatte‬‏ <‪
***@***.***‬‏>:‬

**Comment by Gazook89** [comment]
Closing Issue, resolved per user.
