### ISSUE TITLE
There has been an Error

### ISSUE THREAD

**Issue by BichFace** [naturalcrit/homebrewery#1718]
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

```
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at Request.crossDomainError (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72027:13)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72130:19)

**Comment by G-Ambatte** [comment]
This is an unusual error; is this still happening for you?

**Comment by Gazook89** [comment]
Going to close this issue due to no response, but it *is* an unusual error that hasn't been reported before-- if it's still occurring let us know and we can reopen this and try to figure out what is going on.
