### ISSUE TITLE
Bug Report: ToC Fails to render as links when saved as PDF, other links work fine.

### ISSUE THREAD

**Issue by rjbprime** [naturalcrit/homebrewery#1749]
## Bug Report 

I just tried to render my brew to PDF for my upcoming campaign. FInalised it with a ToC on page 2 of the brew by clicking on the "Text Editor > Table of Contents" snippet, but when saving to PDF in Chromium-based MS Edge version 94.0.992.47, the print preview doesn't render the ToC links as links, but renders URL links correctly. Not sure if this is a Browser issue, or V3 code issue.

Unable to reproduce in Chromium Dev, as version 97 seems to crash on print preview.

**Share Link** :  [my brew](https://homebrewery.naturalcrit.com/share/0fwzMIM5sEFS)

**Comment by ericscheid** [comment]
This is not specific to the Homebrewery, nor specific to the browser.

That is, I can reproduce with simple html files, and can reproduce with other html-viewing tools printing to PDF.

On MacOS, tested with both printing by the browser and via _Print via System Dialog_ options.

**Comment by rjbprime** [comment]
Are you referring to the Chromium Dev ver.97 print preview issue, or that the homebrewery V3 ToC code does not render as links?

If it is the former, then I ran the Chromium Dev ver.97 on a Windows 10 21h1 19043.1237 x64 device (my primary), and the print preview closes after 1-2 seconds. If it is the latter, I've just tested it with a Legacy-based code I converted to, to see if it renders correctly, in Ungoogled-Chromium ver.89.0.4389.114. The Legacy ToC code does indeed work, so it seems that the V3 ToC code is the issue here.

**Comment by ericscheid** [comment]
In my copy of Chrome, choosing random pages on the internet (e.g. even this github page) .. Chrome will linkify some cases, not others. It is maddeningly inconsistent.

**Comment by calculuschild** [comment]
Yes, there was a similar report (having trouble finding it now) showing that the links generated by the Legacy TOC always work, but V3's don't, and I can replicate that pretty easily. 

The only difference is the Legacy link is in the form:

```
<strong>
  <a href="#p1" target="_self">1 Hello</a>
</strong>
```

While the V3 link is:

```
<h3 id="hello1">
  <a href="#p1" target="_self">
    <span class="inline-block ">Hello</span>
    <span class="inline-block ">1</span>
  </a>
</h3>
```

I'm not sure why Chrome would treat one differently than the other or what combination of elements triggers the different behavior (requires investigation).

**Comment by lucastucious** [comment]
For some reason, adding `.page .toc a { display: inline; }` fix the issue. So maybe adding it to the default theme ?
