### ISSUE TITLE
Feature Request: Better navigation for large brews

### ISSUE THREAD

**Issue by RealPendragon** [naturalcrit/homebrewery#1756]
If you have a brew with a lot of pages it's easy to lose track, what would help a lot would be a way to jump to certain places easily. Some possible ways would be:

- Having a page display like [ 5 / 31 ] like most PDF readers where you can change the first number to jump to the specified rendered page.
- Being able to click on the rendered headers to jump to the place where they are in the code.
- Having a mini ToC or book mark toggle that let's you jump to headers in both code and rendered version of the brew.

But anything that makes navigation easier would be appreciated. Maybe even a way to cascade pages to hide them temporarily in the code.

**Comment by snctfd** [comment]
I agree that this would be an excellent addition, as it is a feature that most TeX and Markdown editors have already, e.g. Overleaf, TeXstudio, etc. I certainly noticed that it was missing as soon as my document got larger than a single page.

**Comment by lucastucious** [comment]
Is a Search/Replace tool in editor something considered as "better navigation" or it need its own issue ?

**Comment by calculuschild** [comment]
@lucastucious You can make a separate ticket if you want.

**Comment by Gazook89** [comment]
Search and replace is already considered and may come soonish.

**Comment by G-Ambatte** [comment]
Find/Replace already exists as an issue in #1201. @jeddai has made some progress on this recently, hopefully it will reach testing/implementation/release phases soon.

**Comment by G-Ambatte** [comment]
I came up with these notes while between other projects today, recording them here for inclusion in a later PR.

---

Moving the brew preview programmatically:

1. Add the id 'BrewRenderer' to the brew rendering `iFrame`.
2. Move the brew in the iFrame: `document.getElementById('BrewRenderer').src='#pX'` where X is the page number to move to
3. Update the brew URL: `window.location.hash='pX'`

---

Moving the source code programmatically:

1. In the CodeMirror document, call `setCursor({line, 1})` to move to the first character of the selected `line`.

**Comment by calculuschild** [comment]
See also https://github.com/naturalcrit/homebrewery/issues/241

**Comment by ericscheid** [comment]
> 3. Update the brew URL: window.location.hash='pX'

This won't scroll the preview pane because the preview pane is an `<iframe>`

You might be able to `element.ScrollIntoView(true)` instead.
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView

**Comment by G-Ambatte** [comment]
Step 2 moves the Brew, step 3 updates the URL so a refresh will bring the user back to the same position.

**Comment by ericscheid** [comment]
> Step 2 moves the Brew, step 3 updates the URL so a refresh will bring the user back to the same position.

Ah, of course. Yep, step 2 will work. 

You'll also need a step 4 that gets `window.location.hash` on page load and then does that step 2.

**Comment by G-Ambatte** [comment]
Ah right, of course that's not working. Should probably either drop that step then, or implement it.

**Comment by G-Ambatte** [comment]
`window.frames['BrewRenderer'].contentDocument.getElementById('pX').scrollIntoView({behaviour: 'auto', block: 'start'});`
