### ISSUE TITLE
saving

### ISSUE THREAD

**Issue by Nemo-Illusionist** [naturalcrit/homebrewery#1781]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71842:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72151:10)
{
  "status": 403,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Nemo-Illusionist** [comment]
did not help

**Comment by Nemo-Illusionist** [comment]
Old work is saved, not works with new

**Comment by Nemo-Illusionist** [comment]
It was necessary to add a "TITLE"

**Comment by Nemo-Illusionist** [comment]
Please add a normal error message.

**Comment by G-Ambatte** [comment]
Thanks for the report! We'll look into that - it absolutely shouldn't be necessary to add a title to your brew in order to save to Google Drive.

**Comment by Gazook89** [comment]
going to close this as the initial issue is solved.  However, issue #1848 has been opened (and PR #1849 submitted) to bring attention to better capturing of google errors.
