### ISSUE TITLE
Class Table decorative circles are rendered above the classTable in Chrome Print to PDF

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1784]
Issue raised on reddit -- The class table decorative circles are moved from behind the class table to in front when going to print to pdf.  

<img width="927" alt="image" src="https://user-images.githubusercontent.com/58999374/139601201-5b5914b7-8774-4715-8a26-6910585479a4.png">

Happens using Chrome dialog or System dialog.  MacOS for me.  Does not happen on Firefox.

**Comment by calculuschild** [comment]
Oh good grief. This is obnoxious. Sent in a bug report to Google. Star it to gain more traction!

https://bugs.chromium.org/p/chromium/issues/detail?id=1265296

**Comment by G-Ambatte** [comment]
According to the current tags, it is targeted for fix in Chrome v97. Given current version is 95.0, it may be some time before a fix is live.

**Comment by Gazook89** [comment]
Added a fresh comment on the chrome bug report just indicating this is still an issue in Version 99.0.4844.51 (Official Build) (x86_64).
