### ISSUE TITLE
Saving to GDrive resets Page Views counter, and unpublishes brew

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1790]
If you have a local-storage published brew with some views, the view count is reset and the brew marked unpublished when you choose to later save it to Google Drive.

Ideally, the view count is preserved and added to any new view count, whether switching from local to Drive, or Drive to local.  Same with publish status.

**Comment by calculuschild** [comment]
This is another thing we already fixed a while ago. If it's broken again.... Something is up...

**Comment by G-Ambatte** [comment]
The only thing I can think of is that transferring to Google needs to pass View Count and Published states, which may only exist in memory as it was at the time the Brew was opened. While this was fixed for Brew saving, it may not be the case for brew transfers...We may need to specifically load the current state of the brew, merge it with any unsaved data in the edit session, then push that brew object through the transfer process. ---- On Wed, 03 Nov 2021 12:50:14 +1300  ***@***.***  wrote ----
This is another thing we already fixed a while ago. If it's broken again.... Something is up...

**Comment by calculuschild** [comment]
@Gazook89 are you saying the view count resets to 0 or just to a previous value?

**Comment by Gazook89** [comment]
to zero

**Comment by Gazook89** [comment]
If I go the other direction, Drive => Local, my views are not impacted and the brew remains published.

If I then take that same brew which i just moved TO local storage, and send it back to Drive, the views and published status are both lost.

**Comment by calculuschild** [comment]
@Gazook89 New question: Is this on *any* brew being converted to GDrive or only on brews that are switched to Local and back in the same session?

**Comment by Gazook89** [comment]
On any brew, sorry my last response probably muddied those waters.

On any local storage brew, if I convert to GDrive I lose views and published status.

On any GDrive brew, if I convert to local storage, the views and published status remain.

**Comment by Gazook89** [comment]
This doesn't occur any longer.  So maybe I was just making it up or something changed since last november.  Closing!
