### ISSUE TITLE
[UserPage] Add Page Count to sorting options

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#1796]
Now that Page Count has been added to the data displayed on the User Page, it could be added to the sorting options.

It should be as simple as adding one line to the UserPage mapping function, in the same manner as the current `brew.views` line

![image](https://user-images.githubusercontent.com/19826659/140197507-ca960c80-63ab-41e4-a087-dd3fec9e5219.png)

and adding an extra button to the `renderSortOptions` function, which is again in the same manner as `views`.

![image](https://user-images.githubusercontent.com/19826659/140197741-2d28796f-81e2-4290-913f-f2deff476589.png)

This should be all that is required to add Page Count to the ordering options.

**Comment by calculuschild** [comment]
I guess the question we need to answer before spending the effort on a PR, is *is this useful*? Do we have room to put this in the sorting menu, and if we do, does the benefit outweigh the added clutter to the menu?

**Comment by G-Ambatte** [comment]
Excellent questions. It's been suggested from the subreddit, and it would be simple to implement.
Personally, I don't immediately see the usefulness of it, but I tend to have lots of short brews, so my particular use case may not be that of the target audience of this change.

**Comment by Gazook89** [comment]
Could change the filter options to a drop down menu.  Choose your filter and go. 

More compact, less clutter, and personally I think the spacing of the options as-is is not great. 

In the future their may be tags to filter by, and more, so using the whole bar to show these current filters seems unwieldy

**Comment by Gazook89** [comment]
An old Issue, but is one of the last checkboxes on the UserPage Minor Fixes issue; maybe we can finish that list and close an issue at the same time.

At this point, my vote is "no" on whether to add a sort by **page count**.   I just personally can't imagine using that as a method to find one of my brews.  About the only utility of such a sort is as a matter of curiosity-- "how long are my brews?".  I'm not sure that is worth the extra clutter.

**Comment by calculuschild** [comment]
I agree we probably don't need to do this. I vote to just close it.

**Comment by Gazook89** [comment]
Closing this.

**Comment by G-Ambatte** [comment]
> At this point, my vote is "no" on whether to add a sort by **page count**. I just personally can't imagine using that as a method to find one of my brews.

I think that with filtering by name, description, and/or tags being functional now, finding brews is so much easier now. Having to sort the entire collection of brews by descending page count so that your magnum opus is at the top of the list is just not required, when you could filter by it's name, or any of the tags, or even the description.

It's entirely possible that we could add page count to the mapping options without exposing it via the UI - so if someone **_really_** wanted it _because reasons_, they could modify the URL to `sort=pages&dir=desc`.
But I see nothing wrong with waiting for an observable quantity of user demand before committing any time to it.
