### ISSUE TITLE
Bug when rendering a brew with different page sizes

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#1805]
I realised, if you put a big page at the beggining of your brew, the pdf renderer(chrome) goes crazy and does not read correctly the page size, as you can see here:

FISRT PAGE:

![image](https://user-images.githubusercontent.com/91662974/140491053-3c4b7d1d-afc7-43e6-a6c8-749f70a6929b.png)

SECOND PAGE:

![image](https://user-images.githubusercontent.com/91662974/140491115-b6410a85-2b2f-4ca5-9ed4-1c0b08b01e92.png)

In order to see this bug, just create a two pages brew and make the first page wider.

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

.page#p1{
	width:1500px;
}

</pre></code></details>

**Comment by 5e-Cleric** [comment]
it actually confuses me, i tried with a page with content, not even the first page comes fully rendered, it's about 2/3rds of the actual page.

**Comment by G-Ambatte** [comment]
I suspect that this is an issue with the PDF printer page size, rather than a Homebrewery issue - it's not uncommon to find that the PDF printer has defaulted to Letter or A4, regardless of what size the Homebrewery content is.

**Comment by 5e-Cleric** [comment]
In this case the size was letter, but didn't matter at all, and yes i guess makes sense for this to be a pdf printer issue.

**Comment by calculuschild** [comment]
I don't think the chrome pdf printer supports more than one page size at a time.

**Comment by Gazook89** [comment]
Going to close this as it's not possible with browser pdf saving to have multiple page sizes, and not something we can fix.  Most likely solution is to find a third party pdf creator that supports that functionality.
