### ISSUE TITLE
When trying to print a clone document, prints my new brew instead

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#1806]
This is very weird, but it get that is a bug due to the fact that i have two unsaved brews at the same time, even though one of them is closed.

I'm on chrome.

So, as title says, i was trying to recreate a bug that a redditor had  about spacing before a table, and so created my new brew, then incapable of getting to the problem, got their share link and made a clone to new, and when trying to render it, i get the rendering of my new brew instead.

I'll temporary fix this by saving one, but it should be known.

**Comment by G-Ambatte** [comment]
This behaviour derives from two things:
- A cloned brew is not saved to local storage until it is edited.
- When the print button is pressed, it redirects to a different page, which loads the saved information from local storage. 

So hitting the Print button on a cloned Brew that has not been changed will result in the contents of local storage being loaded instead. This could be a completely different Brew that had been created in `/new` prior to the Brew being cloned.
