### ISSUE TITLE
Drop Caps get sliced between multiple successive wide blocks

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#1808]
![image](https://user-images.githubusercontent.com/91662974/140661176-74539393-adf9-4ec7-be90-7ce30bd304d4.png)

share link: https://homebrewery.naturalcrit.com/share/1ALqs9ttmc0-it5XVCSO4qQeRzmemhZTU769QGVVpXipY

**Comment by calculuschild** [comment]
Yes, unfortunately this is a symptom of the way column-spanning is handled in CSS. If the paragraph that contains the Drop Cap is not tall enough to fit the whole Drop Cap, it just gets cut off.

If you don't have enough text in the paragraph to be the same height as the Drop Cap, the best workaround for now is to just insert `::::::::` spacers as needed to artificially expand the paragraph height until the whole Drop Cap is visible.

**Comment by 5e-Cleric** [comment]
just saw this again, wouldn't a fix for this be to add a minimum height to p elements after h1, equal to the height of a drop cap letter?

of course this could cause some brews to change, specially those who deactivate the drop cap.

I'll give it a try and update

**Comment by Gazook89** [comment]
I think such a change would add more confusion and adds one more thing to explain when questions come up. Not to mention another style to undo _if you are removing the drop cap._

in my opinion this is just one of those things that is weird, but likely doesn’t actually cause anyone problems once they type a few sentences.

**Comment by calculuschild** [comment]
Is this even an issue still? I can't seem to reproduce this.

**Comment by 5e-Cleric** [comment]
> Is this even an issue still? I can't seem to reproduce this.

Doesn't seem to be, although, i get this now, trying to reproduce it:

<img width="225" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/6beebff8-0de4-4f9a-9688-d968bfa0a518">
<img width="228" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/7157f4ce-702a-4a08-96e4-6242e1517bfd">


And to separate that second header, you need to add two separate lines of colons to make it, adn the drop cap still goes very low:

<img width="208" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/6d37b26d-e120-446b-b60d-6310a1d228c3">
<img width="234" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/411bdcc3-9da2-44b8-985f-76b0f6ffb6fb">


Okay, the lower letter is just not caps, and it should be Caps whether you want it or not, so applying that text transform uppercase should be done.

With all this considered, i would close the issue, as all users should know how to use vertical spacing.

There is still the issue as to why multiple colons do not work before h1:

### Without Colons
<img width="178" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/702a91f6-27b7-4721-9d81-d270d096e77f">
<img width="178" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/d937918a-2347-4258-8f44-c84e0c58efbe">

### With Colons
<img width="187" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/5c4e87e1-a84d-4d2c-9091-485aecdfe7c9">
<img width="187" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/0b4bdfc8-e9f4-4a78-a58a-0382eaa13b2a">


It actually reduces the spacing.

Brew to see it: https://homebrewery.naturalcrit.com/share/C7TTm5yprUcy

**Comment by ericscheid** [comment]
Note that a H1 is a wide element, which will cause the previous section of content to reflow into both columns. The spacings in the last example have not been reduced, they have been re-distributed into two columns.

**Comment by 5e-Cleric** [comment]
That makes sense, but i still don't get why one single colon actually pulls the header upwards
closing issue
