### ISSUE TITLE
Can't save a legacy project cut and pasted from a different legacy file 

### ISSUE THREAD

**Issue by Teddy-Maz** [naturalcrit/homebrewery#1814]
Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:71842:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72151:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Checkout discussion #1580. Those steps should clear up the issue

**Comment by Teddy-Maz** [comment]
Does that method work if I've never logged in with Google before? Moreover, how would I, say, go about logging out? There's nothing on the My Brews page, nor the main page or the Natural Crit site itself. Should I delete my cookies and try logging in with Google?

**Comment by calculuschild** [comment]
@Teddy-Maz The fact that the error shows `"url": "/api/newGoogle/"` is evidence that the Homebrewery has a Google Drive account linked with your username. 

>Moreover, how would I, say, go about logging out?
Check out discussion #1580 for how to log out

**Comment by Gazook89** [comment]
@Teddy-Maz -- did #1580 get this resolved for you?   Going to close this issue for now and assume so, but if not we can definitely reopen it and see what else needs to be done.
