### ISSUE TITLE
Cmd-P/Ctrl-P hotkey of google saved brew loads hb print url

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1815]
1. From here: 
https://www.reddit.com/r/homebrewery/comments/qgh7br/homebrewery_export_issue/hk077vf/

2. I clicked thru to here: 
https://homebrewery.naturalcrit.com/share/1Bi_Y3ZIDi2Wsf96kE6edbqm6vAY-XE4bBYkH_7v0-Mau

3. I hit cmd-P to print, landed here: 
https://homebrewery.naturalcrit.com/print/BYkH_7v0-Mau?dialog=true

4. Which says
`Can not find brew`

5. Back to the brew, clicked the Get PDF button: 
https://homebrewery.naturalcrit.com/print/1Bi_Y3ZIDi2Wsf96kE6edbqm6vAY-XE4bBYkH_7v0-Mau?dialog=true

**Comment by calculuschild** [comment]
Error is here:

https://github.com/naturalcrit/homebrewery/blob/fb52618ce95ae25a33edeb7fea64c9d08b420288/client/homebrew/pages/sharePage/sharePage.jsx#L44

Needs to be run through the `processShareId()` function same as https://github.com/naturalcrit/homebrewery/blob/fb52618ce95ae25a33edeb7fea64c9d08b420288/client/homebrew/pages/sharePage/sharePage.jsx#L66
