### ISSUE TITLE
Bug: Open Sans not recognized when using Font-family and blocks [V3]

### ISSUE THREAD

**Issue by Anonymister** [naturalcrit/homebrewery#1820]
In version 3, Open Sans doesn't like the curly brackets, I think that this is due to the space in Open Sans. I am not sure why the block isn't working for the Open Sans class either since the span works (although it probably is the same issue).

I am using the latest update of Google Chrome (95.0.4638.69) in the case that this is not reproducible. 

<details><summary>Brew code to reproduce</summary><code><pre>

<style>
	
.page {
	font-size:18pt;
	}
	
.page .os {
  	font-family: 'Open Sans';
  }

.page .sb {
  	font-family: 'SolberaImitationRemake';
  }
</style>

{{font-family:Open Sans, 
Not Open Sans
}}

:

{{font-family:Open Sans, Not Open Sans}}
:

{{os, Open Sans}}

:

{{os,
Not Open Sans?
}}

:
{{sb, 
Solberry
}}

{{sb, Solberry}}

{{font-family:SolberaImitationRemake, 
Solberry
}}

{{font-family:SolberaImitationRemake, Solberry}}

:

#### Not Open Sans
{font-family:Open Sans,}

#### Open Sans
{os}
:

#### Solberry
{sb}

#### Solberry
{font-family:SolberaImitationRemake,}

</pre></code></details>

**Comment by calculuschild** [comment]
Two things:

1) If your property had a space, you need to put quotes around it : `"Open Sans"`
2) if you end your list of properties with a comma, this is considered invalid syntax.  `{{os,`. It might be a little more lenient for the Spans, but it's still bad syntax.

**Comment by Anonymister** [comment]
Gotcha, that works! Then I suppose this becomes a feature request of eliminating the space since none of the other font-families have spaces :) (but obviously no real need for it since there's an easy workaround).
