### ISSUE TITLE
Metadata lost on moving brew to gdrive

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1840]
Situation: I have a brew created quite some time ago. It has non-zero views. It is stored in hb/mongo.

![image](https://user-images.githubusercontent.com/2605467/142450319-6bb15a48-0b92-47cb-ba47-479f117b352c.png)

If I move that brew to gdrive storage, the views get reset to zero, and the Created Date is changed to now.
![image](https://user-images.githubusercontent.com/2605467/142450759-cfc0eb83-920c-4652-aca6-7a899d21ab85.png)

Also:
- the Published flag is also reset back to "unpublished" — when I refreshed my userpage I did not see "Campaign Outline" listed in my Published Brews (that gave me quite the scare). Fortunately, the brew had simply slipped down the page into the roiling cesspit of My Unpublished Brews, and a quick edit saw to it being published again.
- the Systems metadata also got cleared
- the Renderer selection was successfully carried across to gdrive

----

Going the other way, from gdrive back to hb/mongo went from this:
![image](https://user-images.githubusercontent.com/2605467/142451593-b8ad590b-f469-439b-98de-ccc918b948a4.png)

to this:
![image](https://user-images.githubusercontent.com/2605467/142451885-d993feda-5a70-472b-ace3-a02e1bc09874.png)

Which is to say .. the metadata that was stored in gdrive (views, createdAt, systems, published) was successfully reinstated into hb/mongo. The old (original) metadata (e.g. views) was not reinstated (I didn't expect it to, I know the code fully deletes the mongo entry on moving to gdrive).

----

(Also, the `/edit` and `/share` links changed via the round-trip. Understandable from how the code is, but could be a separate issue for some users who have shared those links and accidentally moved/un-moved a brew to gdrive).

**Comment by ericscheid** [comment]
See also #1506, #1083, #406.

**Comment by ericscheid** [comment]
Things to fix:

- [ ] move brew.views to gdrive too
- [ ] move brew.createdAt to gdrive too
- [ ] move brew.published to gdrive too

Separate issue for another day .. can be addressed by "store stubs in mongo when moving to gdrive"
- [ ] ~~roundtrip destroys original `/edit` `/share` links~~

**Comment by dbolack-ab** [comment]
Some of these things look like they may have been fixed to my eye. 

Is that the case?

**Comment by 5e-Cleric** [comment]
Just tested this, no metadata of my brew was lost, closing, as this is fixed.
