### ISSUE TITLE
Google Drive Error Handling

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1848]
I couldn't find another issue that addressed the frequent 'Save to Google Drive' errors and resulting Github Issues; if I missed it, let me know.

Right now it seems we only have logic to give a descriptive error message for '403' errors, and nothing for '503' or the less common '400'.  And we have still received github issues for '403's, so I think possibly the error handler isn't configured correctly?   Here is the relevant set of lines from the editPage:

https://github.com/naturalcrit/homebrewery/blob/0d685acfca27a68cd8384b350505e77eb89d7e32/client/homebrew/pages/editPage/editPage.jsx#L352-L359

Should `.reason == 'insufficientPermissions'` instead be `.reason == 'insufficientFilePermissions'`?  I am looking [at this error code description](https://developers.google.com/drive/api/v3/handle-errors#resolve_a_403_error_the_user_does_not_have_sufficient_permissions_for_file_fileid) on the Google Developers site.

And to capture the other error codes, possibly just remove the need for a matching `.reason` entirely, and then go based strictly off the code number (inserting '503' and '400' into the first check)?  That is, if we are okay with the same error message and call to action for all three errors:

```js
if(this.state.errors.status == ('403' || '503' || '400')){
```

Thoughts?  This is something I don't know how to test on my local install, just fyi.

**Comment by calculuschild** [comment]
I think maybe we instead need to check based on the url in the error:


```
"url": "/api/newGoogle/"
```

At least for catching Google drive errors, because at this point we know they all are solved by the same solution, even if the error codes are different.
