### ISSUE TITLE
Cannot save brewery, create PDF or see saved projects

### ISSUE THREAD

**Issue by Arelsen** [naturalcrit/homebrewery#1856]
Since this morning (22/11/2021 or 11/22/2021 for americans) I have the problems listed in the title. Tonight (I stopped at 2 AM ) it was working fine.
I tried deleting cookies and logging in again but the problem persisted, and actually got worse, now I can't see past projects.
Fortunately I always do a backup on my local storage.

I tried looking on the Issue tracker and discussions but I can't see anything similar. I tried looking for discussions online but the only tip I found was to delete cookies and login again, which didn't work.

Thanks.

__________________________________________________________________________________________________________________________________________

Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72168:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72477:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Generally this is due to expired Google credentials. I know you said you cleared cookies etc, and may have already seen discussion #1580, but check that out if you haven't and see if the steps there don't help-- this is a pretty common issue and generally these steps resolved it. 

If not, swing back here

**Comment by Arelsen** [comment]
Thanks, that resolved the issue. I didn't see that discussion when looking for a solution, sorry.
