### ISSUE TITLE
update window.location when using filters on user page

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1858]
Now we have a simple text filter on the user page, it sure would be helpful if that could persist through a reload or history traversal. Additionally, it would be useful for the window.location to reflect same, such that we now have a custom link we can share.

![a filtered user page](https://user-images.githubusercontent.com/2605467/143176070-d47d7a84-bfb3-4aa7-ae40-ac7d4ed16af0.png)

- [ ] update window.history via `history.replaceState()` when search box typed into
- [ ] user page detects `?q=criteria` in browser.location on page load: stuff that into the search box, do the search
- [ ] also do this for tags, when we get around to having tags

**Comment by G-Ambatte** [comment]
The PrintPage has a query parameter passed in as a prop - [see here](https://github.com/naturalcrit/homebrewery/blob/65bac929ca72b502ea38ec6d9df41f95eb783676/client/homebrew/homebrew.jsx#L50) - so we should be able to use that as a working example.

There's also a working example of `history.replaceState` in the EditPage brew transfer function, and also the `_.debounce` function is there as well.

If the URL query is added using `?filter=criteria` then it should be simple to extend in the future, e.g. to `?filter=filter_criteria&tag=tag_criteria`.

---

So I see the required actions as follows:
- [ ] implement UserPage URL query via modification of the Route in `homebrew.jsx`
- [ ] implement a UserPage prop that populates the filter, set by the query parameter `f`/`filter`
- [ ] implement a UserPage prop that selects the Sort Option and Sort Direction, set by query parameters `s`/`sort` and `d`/`direction`
- [ ] add a debounced URL update to UserPage, triggered when options are changed

**Comment by ericscheid** [comment]
Barely worth bothering with debounce if we are using history.replaceState() — it doesn't trigger anything.

More actions required though, as there are essentially two sides to this problem:

- [ ] consume options in url on page load `url → page`
- [ ] update url bar when widgets in page are interacted with `page → url`
