### ISSUE TITLE
Having an issue saving a file

### ISSUE THREAD

**Issue by Ydesince2** [naturalcrit/homebrewery#1872]
Not sure if the following was supposed to be there, but I left it...
Anyway, went to work on an older file, and it told me it couldn't find the brew. I pasted an older text file that I had saved before the last update and now it's not letting me save it.
Thanks
Yves

Error: Bad Request

```
Error: Bad Request
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72168:19)
    at Request.Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1768:20)
    at XMLHttpRequest.xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:72477:10)
{
  "status": 400,
  "method": "POST",
  "url": "/api/newGoogle/"
}
```

**Comment by Gazook89** [comment]
Generally saving issues are due to expired Google drive credentials registered with the Homebrewery site. Follow the steps in Discussion #1580 for how to refresh your credentials to be able to save again. If those steps don't work, swing back here and we can dig deeper.

**Comment by Gazook89** [comment]
going to close this for now, but this issue can be reopened if the steps in #1580 didn't resolve it.
