### ISSUE TITLE
Suggestion: scrollable/shorter recent brews dropdown menu

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#1881]
Suggestion: recent brews dropdown with it's own scroll function

Why? because i am experiencing a chrome bug, that when i put my mouse over the right part of the recent brews button, the dropdown opens, and it is larger than the page, so it creates another scroll bar at the right of the page, therefore moving everything, including the bottom, which suddently i'm not over.

All that activates and deactivates the hover effect, and weirds the page until you move your mouse.

[video](https://imgur.com/a/DDihHRf)

it is a minor inconvenience, but easily sorted by either decreasing the number of recent brews, or making the dropdown menu scrollable by itself.

**Comment by ericscheid** [comment]
Easy CSS fix

```
homebrew nav .recent.navItem .dropdown {
  overflow: scroll;
  height: 100vh;
}
```

Add those two CSS declarations to this file:

https://github.com/naturalcrit/homebrewery/blob/dd93c4cdd4e4183d340188ae570bed3ac78e4542/client/homebrew/navbar/navbar.less#L70-L77
