### ISSUE TITLE
Active Line Highlight is more of a hinderance than anything else

### ISSUE THREAD

**Issue by JackWeighill** [naturalcrit/homebrewery#1905]
The new line highlighting is far too bright and hides the cursor. Please either reduce opacity or change its color to a darker grey, preferably both.

**Comment by calculuschild** [comment]
Thanks for the feedback! We are looking at changing this.

Out of curiosity, we set the color to a pretty faint blue which should already be darker than the rest of the white editor. Are you using a dark mode or something that is conflicting with this?

**Comment by ericscheid** [comment]
I'm not seeing any garish colouring...

![image](https://user-images.githubusercontent.com/2605467/146691104-9397994d-1573-451f-a8d2-9dbd6421f81d.png)

**Comment by JackWeighill** [comment]
> Thanks for the feedback! We are looking at changing this.
> 
> Out of curiosity, we set the color to a pretty faint blue which should already be darker than the rest of the white editor. Are you using a dark mode or something that is conflicting with this?

My mistake, I have a Stylus script that's so old I forgot that it even existed 😅

I've done a good bit of digging into Inspect Element and I cannot for the life of me find the name of the class/attribute for the colour of the Active Line Selection

**Comment by calculuschild** [comment]
@JackWeighill The classname is `CodeMirror-activeline-background`.

**Comment by JackWeighill** [comment]
Thanks!
