### ISSUE TITLE
Smarter code folding snippets?

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1907]
A suggested tweak - when pages are folded, limit the excerpted snippet/gloss to just the first heading through to the first `\n`. Otherwise it's just a wall of text.

Thus, for this brew it would be

```
↤ # Combat Maneuvers ↦
↤ # Combat Actions  ↦
↤ ## Movement ↦
↤ ## Defense ↦
↤ ## Special Targeting ↦
↤ # Footnotes on source rules ↦
↤ ### Parry Defence ↦
↤ ## Other options/wrinkles ↦
↤ ### Weapon Length and Positioning ↦
↤ ## Damage-type Maneuvers ↦
↤ ## No Quarter <small>Combat manevers - for fight... ↦
```

![image](https://user-images.githubusercontent.com/2605467/146691256-47510b85-909a-4395-9b10-00f12fa07bee.png)

**Comment by ericscheid** [comment]
I'm looking at these lines...

https://github.com/naturalcrit/homebrewery/blob/aba2f58fc42efe088f9d4d721400910427d49b3b/shared/naturalcrit/codeEditor/codeEditor.jsx#L146-L162

**Comment by ericscheid** [comment]
Hmm .. (given that a page might not commence with a heading) .. maybe at line 160 have something like

```
    if ( text[0] == '#' && text.indexOf('\n') )
        text = text.substring(text.indexOf('\n')-1);
```

That way it will either be an excerpt of whatever text, or will be just the heading text (including the leading `#`).

**Comment by G-Ambatte** [comment]
I had a quick look at this - how do this look?


Folded:
![image](https://user-images.githubusercontent.com/19826659/192123715-69641c9a-9ed2-49cd-b685-b4e154e59958.png)

Brew Source:
```
# Combat Maneuvers
\page
# Combat Actions
\page
## Movement
\page
## Defense
\page
## Special Targeting
\page
# Footnotes on source rules
\page
### Parry Defence
\page
## Other options/wrinkles
\page
### Weapon Length and Positioning
\page
## Damage-type Maneuvers
\page
## No Quarter <small>Combat manuevers - for fighting</small>
\page





\page

This is a test page.
This is the second line.

\page

This is a test page.
This is the second line.

### Header later on


\page

```

**Comment by Gazook89** [comment]
That is spot on to what I would prefer--- showing only the first header to appear on a page, unless no headers exist.  Would be eager to hear from others though.

**Comment by G-Ambatte** [comment]
I'll put the code changes into a Draft PR for further discussion.

**Comment by ericscheid** [comment]
Looks great. Very usable. Maybe tone down the brightness of the blue?

Those headings look familiar :-)

**Comment by G-Ambatte** [comment]
I've added a color setting in the LESS to change the fold-markers to grey, but leave the heading text as blue.

![image](https://user-images.githubusercontent.com/19826659/192132135-61a926da-1579-4c3a-9ed2-6c20e0958f26.png)
