### ISSUE TITLE
No template for Spellcasting table of archetypes

### ISSUE THREAD

**Issue by lorddarkhan** [naturalcrit/homebrewery#191]
**Suggestion, not a bug report**

There is no template in place for putting together the Spellcasting table for an archetype who is a half-caster (like the Arcane Trickster or the Eldritch Knight).  I'm surprised this isn't implemented already, or perhaps there's a way to get the table set up, but I can't find one.

The main issues are the smaller line spacing of the Spellcasting table, and the fact that the top row of the column is strangely set up with some column-spanning.

![image](https://cloud.githubusercontent.com/assets/21132903/18429917/f445797a-788a-11e6-99dd-f3eac6161dce.png)

**Comment by vorpalhex** [comment]
I can't imagine this being accomplished with markdown, it's going to have to be pure html (or a very tortured markdown template). Alternatively, move the "Spell Slots per Spell Level" outside the table and set it as a right-aligned h4, then you should be able to use a normal table.

I think the main issue here is the weird colspan double header.

**Comment by lorddarkhan** [comment]
Ya, following that logic, I found a reasonable workaround.  It would be really nice if there was a way to reduce the font size in a table.  Is there a reasonably simple way to make the font size the same as the normal text (instead of the larger table text size)?

**Comment by michaeltlombardi** [comment]
To make this look pretty in markdown would probably require support for grid tables ([example project](https://github.com/tj/terminal-table) like this:

```
+------------+--------+
|     Cheatsheet      |
+------------+--------+
| Word       | Number |
+------------+--------+
| One        | 1      |
| Two        | 2      |
| Three      | 3      |
+------------+--------+
```

**Comment by stolksdorf** [comment]
Good idea on the wiki @lorddarkhan, I'll mark this as resolved, but leave it opened as a reminder to create a wiki of "Protips" and to just generally improve the project's docs. I get _a lot_ of repeat questions about fonts/images/spacing/backgrounds etc. that I should collect somewhere and point people towards.

**Comment by ericscheid** [comment]
Added to epic #1096.
