### ISSUE TITLE
Update the Issue Template 'contributing guidelines' link

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1915]
The link to the contributing guidelines has never been updated from stolksdorf's repo:

```
## Before you submit

- Support questions are better asked on the subreddit [r/homebrewery](https://www.reddit.com/r/homebrewery/)
- Read the [contributing guidelines](https://github.com/stolksdorf/homebrewery/blob/master/contributing.md).
- If it's an issue, please make sure it's reproducible
- Ensure the issue isn't already reported.
```

I'm assuming it doesn't differ at all from NaturalCrit/Homebrewery repo, but just happened to notice it right now and seems easy enough to fix (@calculuschild)

**Comment by dbolack-ab** [comment]
If this is referring to the content in the README.md, this appears to have been updated at some point since this was reported.

**Comment by Gazook89** [comment]
I checked and agree. I’ll close, thanks
