### ISSUE TITLE
Gitter Lobby down?

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1920]
For several hours now I am getting `500` errors from Naturalcrit/lobby on Gitter.  Just wondering if others are seeing the same.  No problem getting to gitter.im  or even gitter.im/naturalcrit.

**Comment by calculuschild** [comment]
Yep it's a known issue but Gitter hasn't officially responded yet.

https://gitlab.com/gitterHQ/webapp/-/issues/2817
