### ISSUE TITLE
Improve the "Can't get that" error page for missing brews

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1924]
Hitting a blank white page with only "can't get that" as the error is frustrating, ugly, and confusing for users.  We should improve that error page.

- [ ] Look pretty
- [ ] Emit (and display) a relevant error code instead of just 500
- [ ] Provide instructions to direct the user to the next step
- [ ] A button to optionally remove the brew from "Recent brews"

**Comment by G-Ambatte** [comment]
On "Look Pretty", we could push the error code & description into the text of a brew and display it through the Share page - it would be a pretty simple way to make it more visually appealing.
However, this may be too visually similar to the expected non-error result, and confuse the user when an error occurs.

**Comment by calculuschild** [comment]
I agree I think it would be confusing to style it as a brew. My opinion is it should be clearly visually distinct as an error page. Although I'm not opposed to keeping the rest of the navigation bar and stuff around. The error could appear full-width across the page where the editor and brew preview usually appear.

Or, style it like the NaturalCrit pages with the same white background but more professional-looking.

**Comment by G-Ambatte** [comment]
This seems like a prime candidate to build a solution for #2049, then leverage that work to create an ErrorPage.
