### ISSUE TITLE
umlautes in headings font

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#1925]
The font used for headings don't have all the special characters for umlauted characters: ä ë ï ö ü ÿ Ä Ë Ï Ö Ü Ÿ

.. and there's a distinct difference between V3 and Legacy. (This is due to a different font being used).

## V3 Render
![V3 render, with some caps not dotted](https://user-images.githubusercontent.com/2605467/147310332-f33fffe2-0603-4e68-a27a-22ef84dd1861.png)

## Legacy Render
![legacy render, with some caps wrong character entirely](https://user-images.githubusercontent.com/2605467/147310436-988cd225-3cec-4cb7-9f71-41550b5480c6.png)

**Comment by calculuschild** [comment]
From gitter:

> They use different versions of the fonts with slightly different sizes and spacings which would throw off Legacy. We could always do the work of manually filling in the legacy version of the fonts with any missing characters.
> 
> But this was one of the big efforts for V3: redoing all the fonts to be more error-free, consistently-sized, add missing characters, etc. It was never a priority to also add missing characters to the old broken font.

In favor of closing as a duplicate of #116?

**Comment by ericscheid** [comment]
#116 is the appropriate issue .. however is currently closed. Re-opening that.
