### ISSUE TITLE
Add some indicator of renderer version outside of Meta panel

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1928]
It might be nice to have some visual cue as to the renderer version that is more apparent than the checkbox in the metadata panel.  I was thinking that maybe the "text editor" menu in the snippet menu could read "V3 Text Editor" or "Legacy Text Editor"?

Or just "V3" or "Legacy" written anywhere on the screen.

This idea came up when trying to troubleshoot another users brew from a posted screenshot, and just wondering which editor they were using.  Based on the fact they had some html tags, I'm assuming it's Legacy, but that may not necessarily be the case.  If the screenshot doesn't happen to include wherever this renderer indicator is located, then i'll be out of luck anyway, but it would have a higher chance of being included than the metadata panel.

I also think it would just be more clear to users as they work.

**Comment by G-Ambatte** [comment]
My first thought is that we could modify the BrewRenderer.jsx to add a `<div className='rendererVersion'>${this.props.renderer}</div>`, and then add the class to BrewRender.less to give it `position:fixed` so it floats above the rendered brew. We could also add the class `visibility:hidden` to `@media print` or some other form of hiding on print detection so that it does not appear on the PrintPage.

**Comment by Gazook89** [comment]
I created a branch for this, just adding the renderer down by the page counter.  

<img width="312" alt="image" src="https://user-images.githubusercontent.com/58999374/191401308-e468cf24-0247-40c9-9b90-fe7d92e18615.png">

It shows on the Share page, too, which I'm not sure is desirable.

Another option is show it in the snippet bar above the editor:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/58999374/191404155-453b6c68-cf1e-48e1-bcce-87e85dd89b59.png">

Finally, if either is approved, is it a good idea to make it a toggle button between legacy and v3?

**Comment by ericscheid** [comment]
> and just wondering which editor they were using

sometimes you can spot this from the content:
in V3, single apostrophes are rendered as curly, in Legacy they remain raw straight.

**Comment by Gazook89** [comment]
Yeah, and sometimes it's just clear from how it 'feels'.  And going forward, since it is now the default renderer, my presumption is going to be mostly v3.  But it's still nice to have an indicator on the screen because we still get reports with "i dunno" in the "Renderer?" field.

Also, I think the HB version can be confusing:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/58999374/191406202-5f4f2128-c674-4978-9b32-7a07a360e753.png">

**Comment by calculuschild** [comment]
Bottom right corner looks fine to me. :+1:

**Comment by Gazook89** [comment]
Do you think it should be a bit grayed out, to indicate it can't be changed by clicking there?  

Or alternatively, *should* it be possible to change renderer down in the pageInfo?

**Comment by calculuschild** [comment]
I lean towards not having it changeable from there. We can treat it as just an info panel. I don't think it needs to be grayed out either.

**Comment by Gazook89** [comment]
Okay, will submit the PR in a few minutes.
