### ISSUE TITLE
Need to fix `comopnentWillMount` is deprecated warning

### ISSUE THREAD

**Issue by AlexeySachkov** [naturalcrit/homebrewery#1936]
When launching local Homebrewery instance I see the following warning:

```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: Homebrewery
    in Homebrewery
```

I made a local experiment with replacing `componentWillMount` with `componentDidMount` and it seems to work, but I barely tested it, so I can't be sure

**Comment by calculuschild** [comment]
I think `componentdidmount` should work in almost every case instead of `componentwillmount`. I've only noticed a couple of spots where it didn't work as expected when I changed a couple of spots in an earlier update. If it seems to work fine, feel free to make a PR about it.

**Comment by G-Ambatte** [comment]
`componentDidMount` is called AFTER rendering, whereas `componentWillMount` is called before. This isn't normally much of an issue, but is visible in the `version` element of the NavBar - it will display `VUNDEFINED` when the global declaration is shifted to `componentDidMount`.

The solution appears to be to shift those global declarations to `getInitialState`, which also triggers BEFORE rendering.
