### ISSUE TITLE
Google Drive only retrieves 100 most recent brews

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#1943]
We have users with surprisingly more than 100 brews on Google Drive, and they can only see the most recent 100 in their user page, which gives people a scare about lost data. Should be a pretty simple tweak to change the max number of files Google retrieves at once.

See https://www.reddit.com/r/homebrewery/comments/rv7unz/issue_my_brews_continuously_disappear_off_my_page/hr91fs2/?context=3

**Comment by G-Ambatte** [comment]
The 100 file limit appears to be set [here](https://github.com/naturalcrit/homebrewery/blob/e74800916e2bbcca41feeb225aae7ff20060f982/server/googleActions.js#L99).

Reading through the [Google Drive API documentation](https://developers.google.com/drive/api/v3/reference/files/list#pageSize), it appears that this is the default value for pageSize. However, from the API documentation, the value can be increased to a maximum value of 1000.

Remediation options:
1. Increase `pageSize` to 1000. This will alleviate the immediate issue, but may make fetching large numbers of Google files take a long time. The issue will return if/when users have more than 1000 Google brews.

2. Develop and implement a paging system for the UserPage, based on the value of [nextPageToken](https://developers.google.com/drive/api/v3/reference/files/list#nextPageToken). If this token exists, there are more Google brews to be retrieved than could fit in the current `pageSize`.

---

My current thinking is that we should implement solution 1 immediately to alleviate the issue for affected users, and add solution 2 to the roadmap as the permanent solution.

**Comment by calculuschild** [comment]
For future reference, there may be some nuance with what `pageSize` actually means: it is a "maximum" rather than an absolute value, so it is possible that Google has a hiccup and stops before getting the complete set of `pageSize`, and using nextPageToken may be necessary at a certain point. If that issue comes up we can implement more a more involved solution.

The docs: 
> The maximum number of files to return per page. **Partial or empty result pages are possible even before the end of the files list has been reached**. Acceptable values are 1 to 1000, inclusive. (Default: 100)

Stackoverflow: 
https://stackoverflow.com/questions/42592125/list-request-page-size-being-ignored

Google API Github
https://github.com/googleapis/google-api-nodejs-client/issues/722

**Comment by G-Ambatte** [comment]
From the [documentation](https://developers.google.com/drive/api/v3/reference/files/list#incompleteSearch), `incompleteSearch` will be set to `true` if the search did not complete. I think we could implement a looping function if `nextPageToken` and throw a warning on `incompleteSearch`.

**Comment by ericscheid** [comment]
> My current thinking is that we should implement solution 1 immediately - it is literally adding a single `0` to one line of `googleActions.js` - to alleviate the issue for affected users, and add solution 2 to the roadmap as the permanent solution

This issue has indeed risen again — see #2408.
