### ISSUE TITLE
Config object is created several times through the codebase

### ISSUE THREAD

**Issue by AlexeySachkov** [naturalcrit/homebrewery#1960]
We have the following piece of code copied at least three times:

https://github.com/naturalcrit/homebrewery/blob/279352377bbd533f1062af29f8328dc9a618c1ad/server.js#L74-L78

https://github.com/naturalcrit/homebrewery/blob/279352377bbd533f1062af29f8328dc9a618c1ad/server/googleActions.js#L6-L10

https://github.com/naturalcrit/homebrewery/blob/279352377bbd533f1062af29f8328dc9a618c1ad/server/token.js#L4-L8

This doesn't looks good and might lead to errors if we decide to update the way config is loaded.

What I would like to do is to load the config once in the entry point file `server.js` and then pass it as an argument to every module/function where it is used.

I'm submitting an issue do discuss such refactoring first, because it might complicate the code a bit: one extra argument will be passed around some code paths. Please let me know what do you think about the suggested approach

**Comment by calculuschild** [comment]
Would your app test script also end up duplicating this since you plan to pass the config in as a parameter to the app?

**Comment by G-Ambatte** [comment]
In a [recent PR on my NC fork](https://github.com/G-Ambatte/naturalcrit/tree/addLocalSupport), I had to pass the `NODE_ENV` config item from `server.js` down through multiple levels to get it to `account.actions.js`, in order for that sub-module to be able to identify the current operating environment and modify the returned cookie content to reflect. This would take that to the next logical step and pass the entire configuration, so any config item can be checked/confirmed/acted against in any sub-module.

**Comment by AlexeySachkov** [comment]
> Would your app test script also end up duplicating this since you plan to pass the config in as a parameter to the app?

That's a good point, I haven't realized that I will need config there as well, because it will be mandatory for the app

> In a recent PR on my NC fork, I had to pass the NODE_ENV config item from server.js down through multiple levels to get it to account.actions.js, in order for that sub-module to be able to identify the current operating environment and modify the returned cookie content to reflect. This would take that to the next logical step and pass the entire configuration, so any config item can be checked/confirmed/acted against in any sub-module.

I did a local prototyping myself as well, but the result doesn't look fancy: there is quite a number of places where extra argument would be required together with some refactoring.

However, a bit later I realized that we could create a separate wrapper module around `nconf`, which would encapsulate all the options we pass to `nconf` there - going this way the config parameters will be stored in a single file, which can be directly included in every place its needed.

This way with a separate config wrapper module I like more, because it will make code simpler than with passing config around everywhere and it will allow to nicely re-use config in tests as well.

**Comment by AlexeySachkov** [comment]
FYI: I've implemented my idea with separate module in #1981
