### ISSUE TITLE
Mechanism for differentiating server errors is needed

### ISSUE THREAD

**Issue by AlexeySachkov** [naturalcrit/homebrewery#1984]
A bit of backstory to better explain what I mean by the title: I'm working on HTTP tests for `source/:id` route and one of the tests there is to check that the app returns an error on attempt to request a source of a non-existing brew.

Due to implementation details of the server, all IDs with length more than 12 are considered to be stored in Google Drive. So, even though the test is passing, console output contains the following:
```
console.log
      Error loading from Google

      at server/googleActions.js:264:12

    console.error
      GaxiosError: Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.

TENS OF LINES HERE WITH RESPONSE OBJECT DUMP
```

Apparently, we shouldn't be actually sending requests to external server in our tests, so I've implemented a mock `googleActions` module, which for now simply does nothing and returns `null` from each and every function there and the output from tests has changed (the test still passes):

```
  console.error
      Can not find brew

console.error
      TypeError: Cannot convert undefined or null to object
          at sanitizeBrew naturalcrit\homebrewery\server\app.js:41:2)
          at _callee$ naturalcrit\homebrewery\server\app.js:30:9)
          at tryCatch naturalcrit\homebrewery\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)
          at Generator.invoke [as _invoke] naturalcrit\homebrewery\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:274:22)
          at Generator.prototype.<computed> [as next] naturalcrit\homebrewery\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:97:21)
          at asyncGeneratorStep naturalcrit\homebrewery\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
          at _next naturalcrit\homebrewery\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
```

Apparently, those messages are being printed by the generic error handler middleware we have:
https://github.com/naturalcrit/homebrewery/blob/179d5e63124b388ed9eaa67d9c4b4e405134412b/server/app.js#L289-L293

While this is certainly useful for some errors like error messages from Google Drive API to be able to quickly debug what went wrong on the server, it doesn't make sense to print an error message about each and every missing brew, because that is basically a user error.

I'm not 100% sure that it will always be clear which category an error belongs to, but at high-level, I think that there should be at least two categories:
1. An expected exception, when something goes wrong due to incorrect user inputs. For example, user mistyped share id or the corresponding brew was deleted - in that case we shouldn't print anything to logs (at least by default, we can implement different levels of logging), but should report an error in a user-friendly way
2. An unexpected exception, when something fundamental goes wrong like we wasn't able to connect to a database or we wasn't able to reach Google API, because our token has expired, etc. Additionally, this category will additionally be populated by improperly handled exceptions from the previous category. An example of such exception is that `sanitizeBrew` doesn't expect the first argument to be `null` - it could be a bad example, because my `googleActions` mock most likely doesn't follow the expected contract of communicating "no brew was found" error, but we still shouldn't report that in a way we report that now, see #1983 

The motivation for reducing amount of logs printed on server side is the following:
- In production environment, this will reduce the server load, because it won't have to print useless information
- In test environment, this will reduce amount of "garbage" output intermixing with test results, producing cleaner reports

A local environment might suffer from this, because during development it could be useful to have more information printed by the app, but this can be fixed as well by implementing different logging levels for different environments. Note: I don't want to simply hide all errors in `test` environment, I would prefer to avoid them from appearing by properly handling them.

**Comment by 5e-Cleric** [comment]
A bit of an update on this, i believe most errors mentioned are using our errorpage component now, at least 404 errors in source both chrome and hb's.

We still should catch better some errors, like version mismatch errors (that we don't know the cause of) and tell the user the brew has been saved in another device, even if there is no other device.

**Comment by calculuschild** [comment]
We do now have a method of differentiating server errors, via the "HBErrorCode" property in custom errors. This gives us more granularity between different status 500 errors for example, and which we already use for both page request errors (displays an error page), and API errors (displays a popup message on the client).

So this feature is in place, and already used. There can always be further breakdown of more specific errors if we want, and we can adjust what is logged for each error, but I think those can be their own issues as we become aware of new error cases to be added, or old error cases to be tweaked. I think this can be closed.

The version mismatch error then, can be examined further in its own issue.
