### ISSUE TITLE
v3 - .classTable.decoration is above (layer-wise) any text that precedes it.

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#1985]
The decorative circle behind a v3 classTable  overlaps any text around it (namely, text that precedes it).  Was reported on [reddit today](https://www.reddit.com/r/homebrewery/comments/sbvwvj/problem_with_decorative_class_table/?utm_source=share&utm_medium=web2x&context=3).

Example text:

```md
## This is my header
{{classTable,decoration
....
}}
```

The decoration can be seen overlapping the header.  It could be plain text, too.

To adjust the z-index of the decoration, the whole classTable needs to be adjusted down:

```css
.page .classTable.decoration {
	z-index: -1;
	position:relative;
}
```

I haven't done extensive checks to see if this has any major downsides.

**Comment by calculuschild** [comment]
Is there ever a case where the class table needs to be above other elements?I don't think so, so this solution should be fine. Good catch. Anyone feel free to make a PR for this.

**Comment by Gazook89** [comment]
The only thing I can think of is it should likely be above images...but images are likely going to be absolutely positioned anyway.
