### ISSUE TITLE
Brew Renderer and Editor divider is not based on percentage of the screen

### ISSUE THREAD

**Issue by RKuerten** [naturalcrit/homebrewery#2020]
## Description
This is a minor UI issue.

When changing the divider's position, it saves its position as a px value, not as % value.

On one of my PCs, I'm using two monitors: one is 1366x768, the other one is 1920x1080. In the 1920x1080 monitor, I setted the divider roughly on the middle of the screen. When changing the tab back to the 1366x768 monitor, the editor occupies roughly 70% of the screen. 

Here are some screenshots to make it clear:

1920x1080 screen:
![image](https://user-images.githubusercontent.com/30464993/153661441-2028cf0e-7bba-4148-9d8c-87f9c294d1b2.png)

1366x768 screen:
![image](https://user-images.githubusercontent.com/30464993/153661476-4deb4fec-b0cd-487b-9af7-8f4fe2549140.png)

**Comment by calculuschild** [comment]
I guess it depends what behavior is most desirable. I could argue that the current behavior preserves the editor size so switching between monitors does not change line positions, etc., which might be preferable.

**Comment by G-Ambatte** [comment]
> To be fair, though, a max % could be set so this never happens.

Or a menu option to change the position - 0% (BrewRender only), 50% (normal), 100% (Editor only).

**Comment by G-Ambatte** [comment]
@calculuschild Do you think we can close this one as well, based on the merging of #2055?

**Comment by RKuerten** [comment]
I've just tested this in the same PC where I faced the issue, and the screen division keeps the % instead of the px, so I'm closing this one.
