### ISSUE TITLE
`tableRows.matchAll ( )` not a function

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#2039]
On an older iPad with [Safari 12.1 on iOS 12.5](https://www.whatismybrowser.com/w/67XELL6), the editor chokes when rendering a V3 brew containing tables.

![image](https://user-images.githubusercontent.com/2605467/155051236-bcc5b435-73e2-4500-9e40-adac3c1343c1.png)
```
[Error] TypeError: tableRow.matchAll is not a function. (In 'tableRow.matchAll(/(?:[^|\\]|\\.?)+(?:\|+|$)/g)', 'tableRow.matchAll' is undefined)
Please report this to https://github.com/markedjs/marked.
Please report this to https://github.com/markedjs/marked.
    marked (bundle.js:67434)
    renderPage (bundle.js:74649)
    renderPage
    arrayMap (bundle.js:48251)
    map (bundle.js:57220)
    renderPages (bundle.js:74668)
    renderPages
    (anonymous function) (bundle.js:74687)
```

This can be tested with this minimal brew:
```
## test for ipad	
| d10 | Damage Type |
|:---:|:------------|
|  1  | Acid        |
|  2  | Cold        |
|  3  | Fire        |
|  4  | Force       |
|  5  | Lightning   |
```

This exception/crash only happens with V3 brews with tables, not with Legacy brews, and appears to be in our custom table extension code.

It would appear that Babel is not transpiling/polyfilling the `string.matchAll()` function to what would work in that earlier browser.

**Comment by ericscheid** [comment]
The breaking line is here:

https://github.com/naturalcrit/homebrewery/blob/d3359991f04be1403ec5f3b37c6d01e9fe7bbc87/shared/naturalcrit/markdown.js#L373

**Comment by Gazook89** [comment]
I don't get this error in Safari (Version 15.0 (16612.1.29.41.4, 16612)), macbook 11.6 big sur.  Nor do I see any issue in Chrome or FF.  Used the same brew as above and from the snippet.

**Comment by ericscheid** [comment]
This is a Safari version issue - older hardware is limited to what iOS they can upgrade to, and Safari is limited by the iOS to what version it can upgrade to. The only upgrade path is obtaining newer hardware. 

(Hmm .. this iPad is still doing well for hardware that was purchased 2018-02-06)

https://caniuse.com/mdn-javascript_builtins_string_matchall

![image](https://user-images.githubusercontent.com/2605467/155064096-0e369705-5512-40df-9aa7-83445cddc4dd.png)

**Comment by calculuschild** [comment]
For anyone who wants to tackle this: We use Babel to transpile/polyfill newer syntax to work on older browsers. There is a setting we can change somewhere in `package.json` to expand which code features are converted.

**Comment by 5e-Cleric** [comment]
The longer we wait to fix this issue the less issue it becomes, last comment is from 1 year and 363 days ago, a fix is not likely, closing, and we are very sorry for our old IOS machines users.
