### ISSUE TITLE
[UI] Reset divider position on logout

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2054]
This issue is to track the addition of code to reset the divider position when a signed in user logs out.

This is related to but separate from #2053.

**Comment by ericscheid** [comment]
To support users not signed in, maybe on the Account Diagnostics page #2043 have buttons to <kbd>log out</kbd>, <kbd>clear notification flags</kbd>, <kbd>clear _Recently Edited_ menu</kbd>, <kbd>clear _Recently Viewed_ menu</kbd>, etc.

**Comment by G-Ambatte** [comment]
The Account page of #2043, as it currently stands, displays information that is stored in the cookie about the currently signed in user's account. However clearing or changing the values in the local storage keys does not actually require a logged in user, so my first thought is that it should be a separate menu item - ACCOUNT and LOCAL SETTINGS (although one could certainly make an argument for combining them into two sections or tabs of a single page).

But with either option, I believe it should start with the UIPage (#2049).
