### ISSUE TITLE
[UI] Add social links to Share Page

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2067]
Reddit link - https://redd.it/tcynbw

As mentioned in the Reddit link, the capability to add the author's Social Links already exists. If we include a system where this is simplified, we can ensure that the social and donation links employ a style that is visually distinct from the Homebrewery UI, to reinforce that these links are not affiliated with Homebrewery and/or the development team.

**Comment by G-Ambatte** [comment]
I believe that the solution to this will require that the following issues are already resolved:

#1908 User Settings framework
#2049 UI Page style
 
Once these two are in place, it should be relatively simple to store the required data in the UserInfo framework, and allow this data to be set by the Users via a UI page.

**Comment by Gazook89** [comment]
Yeah, I think we can close this (and I will do so).  I don't see this as being a priority, nor is the lack of it causing any big problems.  Users can add whatever links they want in their brews.
