### ISSUE TITLE
Publish button z index

### ISSUE THREAD

**Issue by JosefUtbult** [naturalcrit/homebrewery#2068]
In the [SwappableThemes-ReorganizeFolderStructure](https://github.com/naturalcrit/homebrewery/tree/SwappableThemes-ReorganizeFolderStructure), when adding a third theme, the Publish button renders on top of the dropdown.

In [this image](https://imgur.com/a/GRRomF2) I've added opacity to the button, so that you can see that another instance in the menu appears behind the button.

**Comment by calculuschild** [comment]
Fixed with #2070 . Thanks for the report! @JosefUtbult
