### ISSUE TITLE
Browser history deletion caused me to not log straight back into my saved work

### ISSUE THREAD

**Issue by KMLucas** [naturalcrit/homebrewery#207]
**If you are suggestting a feature or improvement**, delete everything here and just write your idea.

If you are reporting a bug, please fill out the details. If you don't, I will most likely just close the issue asking for more detail.

---

**Browser Type/Version**: Chrome

**Issue Description**: Did a browser history deletion and lost my brewcode

Not sure how to get the work I've done back again

Is there any way for me to find it again?

Cheers

Karl

**Comment by lasseborly** [comment]
I would not think that you would be able to retrieve it since as far as my knowledge goes there is no other storage than your own local storage. Sorry.

**Comment by stolksdorf** [comment]
Your brews are saved to the server, however if you never bookmarked or can't find either the edit link or the share link then your brew is lost.

**Comment by KMLucas** [comment]
Hmmm. That's a crying shame. But thanks for explaining. 

Presumably it's my computer that remembers the brewcodes I'm allowed access to  and a cookie/browser history delete got rid of that info.

**Comment by vorpalhex** [comment]
Could we move to emailing links or some sort of optional user account? (OAuth based, optional. Something similar to HumbleBundle's system)

**Comment by stolksdorf** [comment]
User accounts are notoriously tricky to implement well and usually have a vast feature set. I have no interest in building or maintaining an account system unless there's a good pay-off for the work. Currently, most of the benefit of having this system is achieved by just bookmarking a link. The homebrewery already does a lot to mitigate lost work; saving continuously to server and local storage, remembering which brews you have visited or edited, but I can't control for all cases.

**Comment by vorpalhex** [comment]
Agreed it's a non-trivial task... unless you go the route of only having OAuth, don't keep user profiles beyond what email address goes to what links, and therefore aren't worried about any security aspect of it (Oauth for you means no passwords, no hashing, no lost or retrieving passwords, etc). 

At that point it's sign-in, and token management, which Passport or similar will handle quite nicely. 

Given that homebrewery is probably up to a few hundred regular users, that seems an appropriate investment vs. usage, plus it opens the door to future features while still keeping overhead low.

(Downside being that it is about 4 to 6 hours of work, and requires people who want to use the feature to have some sort of Google/Facebook/Whatever account)

**Comment by calculuschild** [comment]
The initial issue was addressed, and we now support OAuth login via Google Drive.

Closing.
