### ISSUE TITLE
Snippet bar items overlap when width reduced

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#2076]
Another cosmetic thing I've noticed is that the Editor buttons in the snippet bar overlap the snippet menus when the width is reduced beyond a certain point.  The main issue is that it just looks a little sloppy, and could be more responsive.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/58999374/158198477-83937b14-b013-4c88-93ad-e1ba0cb4672b.png">

[Here is a link to a branch on my fork](https://github.com/Gazook89/homebrewery/tree/flexbox-snippets-bar) with some adjustments, including:
- add a wrapper div `.snippets` around the Snippet menus, similar to how the 'undo/redo' various editors are contained by `.editors`
- add flexbox properties to the outer snippetbar div and the elements within them.
- Still need to figure out some stuff like preventing text/element wrapping at a certain point, and what to do with the tooltip on the editor icons.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/58999374/158198729-4541e748-bff9-4c52-9f1a-2ecc5608d653.png">

<img width="488" alt="image" src="https://user-images.githubusercontent.com/58999374/158198903-6eb27702-fc33-4566-a919-f4ec1d95a6eb.png">

------

This could be made simpler, and likely better, if the Editors portion didn't need to be right-aligned in the bar.  And to that point, it might make more sense to move the Editors/Undo-Redo portion to the *left side* of the snippet bar, since they don't change based on context, and then followed by the snippet menus.

**Comment by Gazook89** [comment]
I created another branch to try a new configuration of the snippet bar.  IMHO, it looks nice, and while I think it will feel odd to long time users at first, will make sense over time.  And if Swappable Themes is pushed through I think it will work better with custom snippet groups; the persistent editor icons are always in the same place and snippet menus can be added into infinitum.  But I may be grasping at straws to justify the time I spent on this.

Single line tool bar:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/58999374/158214322-d7ad85ad-64a5-4d60-bf3d-b0f9d3be63ae.png">

Squished to two lines:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/58999374/158214500-3b2ea983-6612-4bf6-98ab-2ebef6eac9cf.png">

An action gif:
<img width="579" alt="a gif of the snippetbar" src="http://www.giphy.com/gifs/GuPjXU5tGDmCSAgle9">

At this point the tooltip for the editor buttons goes off screen but I think that can be easily remedied (and in fact i'll probably work on that now) because the Editors and the "undo/redo" buttons have been separated into their own groups.  The undo/redo is in a wrapper `.tools`.   And so the tooltip can be duplicated and one will land on the left side of group, and the other land on the right side of it's group.

**Comment by calculuschild** [comment]
I am ok with the 2-layered thing, but I still like having a gap between the snippets and the tabs. Is there any magical way you can preserve the that?

**Comment by Gazook89** [comment]
I couldn't think of any pure CSS way of keeping that gap when it's a single row, but not having it look funny when it goes to second row.   Flexbox doesn't know when it is wrapping, so I can't say "if you are flexing to another row, suddenly start doing this".  I tried to think of ways using empty divs and such but as far as I can remember there were trade-offs or just didn't work.  

I'll ruminate on it as I make/eat dinner.

**Comment by ericscheid** [comment]
A bit late to chime in, but another approach is to have the snippet bar items collapse to just their icons once space is cramped (with the flyout lables we use for the edit/mode buttons).

**Comment by Gazook89** [comment]
I had thought about that too but only if it was narrowed even further after reducing to two rows. But abandoned that idea after thinking it'd be silly to shrink the editor that small and still think you were going to be doing editing. 

But dropping the two row idea and instead switching to just icons at a certain point would also work. My one concern though is the menus and icons don't have enough recognition among users, not enough that they are understood without their accompanying text. And this would be a much bigger problem once we start having alternate snippets as allowed by the SwappableThemes branch.

**Comment by Gazook89** [comment]
@ericscheid 

> have the snippet bar items collapse to just their icons once space is cramped 

Also, I don't think this is possible with just CSS, until Container Queries become a thing.  It could be done with JS, but with my concern in my previous comment and my sketchy JS skillz, I don't think I could submit for a PR for it.  And I don't want to add another thing to other people's plates until the bigger stuff is done if it can be avoided.  

IMO, this can get pushed through to fix an obvious graphical problem, and incremental changes can be made later as schedules allow since it's UI related, and doesn't need to be backwards compatible or 'perfect' on the first try.

**Comment by calculuschild** [comment]
> I tried to think of ways using empty divs and such but as far as I can remember there were trade-offs or just didn't work.

Can you use something like `justify-content: space-between`?

**Comment by Gazook89** [comment]
The first option I put forth in this thread (part of the original post) uses space-between, but I see I didn't include an image of what it looked like on a single line.  To recap, here is that first option (my branch [flexbox-snippets-bar](https://github.com/Gazook89/homebrewery/tree/flexbox-snippets-bar)):

![giphy](http://www.giphy.com/gifs/mPzxAbiWicABn77cCi.gif)

I just don't like it because of the weird right-alignment when it goes to the second row.  And with just CSS I don't think there is a way to switch it to some other alignment only once it goes to a second row.

**Comment by Gazook89** [comment]
Okay, how about this?

## `flexbox-snippet-bar` branch
![giphy](https://media.giphy.com/media/TrqOKVojrOPYkL2nIR/giphy.gif)

*(ignore the messed up icons, recorded in FF which blocks fontawesome)*

## `reorder-snippet-bar` branch
![giphy](https://media.giphy.com/media/GuPjXU5tGDmCSAgle9/giphy.gif)

Those are my two options.   I prefer the reordering option, but am satisfied with either.

**Comment by ericscheid** [comment]
@Gazook89 commented [5 hours ago](https://github.com/naturalcrit/homebrewery/issues/2076#issuecomment-1068266286)

> > have the snippet bar items collapse to just their icons once space is cramped
> 
> Also, I don't think this is possible with just CSS, until Container Queries become a thing. It could be done with JS

We currently have a bit of JS that runs when the snippet bar changes size. More specifically, a bit of JS that runs when the divider bar is dragged, and correspondingly sets the size of the editor pane (and thus the snippet bar).

Setting/removing a flag class on the snippet bar should be pretty easy there. I'll look into this.

**Comment by 5e-Cleric** [comment]
I offer a fix for this with #3635, a container query to change the flow.
