### ISSUE TITLE
Generated PDF does not match preview when \column used

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#2083]
In both Legacy and v3, and I believe in GMB as well (though I haven't confirmed it myself), columns inside non-`.page` *wide* elements are not printing to PDF correctly.  `.page`'s *might* be working because they have a specific height set, whereas the others generally don't?  I noticed this without realizing it probably on March 15th.

Here is a wide monster stat block with a `\column` inside of it:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/58999374/158914399-b7a9587c-69cc-46d8-ac32-f1983fe145e7.png">

Here is a stripped down 'wide' block with a column in it:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/58999374/158914468-3151ff61-717e-4513-b162-5db63dfef7ef.png">

The [Share link for the above v3 brew](https://homebrewery.naturalcrit.com/share/1VSu19Zgp83iY6_3fXr7ymjCR3xaftau_ZHALAmpJ1l2w) and just the code:

```
<style>
.hi {
	background:#CCC;
	columns: 2;
}

.page {
	overflow: unset;  /* just to illustrate the "bottom edge" of the "hi" element */
}
</style>


{{hi,wide
here is some text

\column

and here is some more text
}}
```

And another bonus image of the above brew, this time with the "Scale" in the print dialog set to 50%:
<img width="987" alt="image" src="https://user-images.githubusercontent.com/58999374/158914674-26eb70a2-15f9-443a-96a1-4e9656c799b1.png">

**Comment by calculuschild** [comment]
I tested as far back as Chrome 87 (Nov 2020) and it was still an issue. Might have been around the whole time.
Reported the issue to Chrome here: https://bugs.chromium.org/p/chromium/issues/detail?id=1307609

Star it to help it gain traction!

**Comment by calculuschild** [comment]
Closing. This was fixed with Chrome v108.
