### ISSUE TITLE
Auto-indent in html mode is problematic

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#2092]
If a brew has some html container (e.g. `<div> ... </div>`) and a new line is entered (e.g. breaking a paragraph into two) then the a <kbd>TAB</kbd> character is added at the front of the line.

Unfortunately, this clashes with markdown processing of that content, with either the line now being rendered as within `<code>...</code>`, or unexpected indenting of bullet point lists.

This is fixable in editing of course — just delete the unnecessary <kbd>TAB</kbd>. Annoying and tedious, also not always obvious for the case of bullet lists.

Recommendation: turn off the auto-indent option for html mode.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/2605467/160221909-aae50588-cebc-4768-abd0-06734a2b9bb6.png">

**Comment by calculuschild** [comment]
I agree with this. :+1: Probably an easy PR if someone wants to find the relevant CodeMirror option.

**Comment by ericscheid** [comment]
This was the image we used to indicate a tabbed space.

[![image.png](https://files.gitter.im/5b92953ad73408ce4fa74346/2Kd6/thumb/image.png)](https://files.gitter.im/5b92953ad73408ce4fa74346/2Kd6/image.png)

It was not well received by the community. "Too much clutter".

It might work better as a 1 character wide arrow, with the rest of the width being transparent.

Would also be good to have some kind of toggle for "show invisibles" in the snippet bar, possibly as a toggle button adjacent to the undo/redo buttons. (We could later put other editor-ui-toggle widgets there too, e.g. something to invoke find/replace).

**Comment by calculuschild** [comment]
Previous PR that did this for reference: https://github.com/naturalcrit/homebrewery/pull/1819

**Comment by calculuschild** [comment]
I think this might be the line to change auto-indent (and any press of `tab`) to spaces: https://github.com/naturalcrit/homebrewery/blob/9a60d60b6dc21411dbf8fcd628516b5a12adefbc/shared/naturalcrit/codeEditor/codeEditor.jsx#L100

**Comment by ericscheid** [comment]
No, the behavour of the editor inserting a tabs when the <kbd>TAB</kbd> is pressed is not the issue.

It's the insertion of a `TAB` character when the <kbd>ENTER</kbd> key is pressed which is the problem.

A possible solution: https://discuss.codemirror.net/t/how-to-remove-indentation-on-newline/1538

> Q: Does anyone know how to remove indentation on newline event?
> A: Bind `Enter` to a command like `cm => cm.replaceSelection("\n")` rather than the default, the `newlineAndIndent` command.

**Comment by ericscheid** [comment]
This might also be relevant: https://github.com/codemirror/codemirror5/issues/988#issuecomment-14915679

> Q: When using the "cm.replaceSelection"-solution, it is no longer possible to indent code by marking multiple lines and pressing "Tab". [Which is very handy for indenting a block of bullet points.] Is there a workaround or code sample that shows how to keep that (very useful) functionality, while still enabling insertion to be spaces instead of a tab?
> A: > Sure there is! A bit of fiddling with the API:
> 
> ```js
> function betterTab(cm) {
>   if (cm.somethingSelected()) {
>     cm.indentSelection("add");
>   } else {
>     cm.replaceSelection(cm.getOption("indentWithTabs")? "\t":
>       Array(cm.getOption("indentUnit") + 1).join(" "), "end", "+input");
>   }
> }
> 
> CodeMirror.fromTextArea(document.getElementById("the-editor"), {
>   extraKeys: { Tab: betterTab }
> });
> ```

----

And this too, to handle `Shift-TAB` to effect un-indenting (when deconstructing deeply nested lists).

**Comment by calculuschild** [comment]
Perhaps instead of removing auto-indent completely, it might be worth just limiting it to auto-indent *to match the previous-line indentation*? Obviously in your example where it indents inside of the HTML `div`s is obnoxious, but I would still like to keep auto-indent for Markdown lists, for example. Is there a way we can do that?

> No, the behavour of the editor inserting a tabs when the TAB key is pressed is not the issue.

I do think this still reveals a related issue though. The tab appears as wide as 2 spaces, but is being parsed as 4 for the purposes of Markdown, which is why the bulleted lists are showing up oddly in your example above. In addition to handling auto-indent, we could potentially replace tabs with spaces to address confusion for users ("why is this bulleted list turning into code but this one remains a list? The whitespace looks the same!")

**Comment by ericscheid** [comment]
Yes, matching previous line indentation works nicely, and inserting indents as spaces would also work (but insert a `TAB` if the `TAB` key is pressed and no text is currently selected)

1. press `TAB` with no text selected → insert a `TAB` character
1. press `TAB` while text is selected → indent the selected lines one level
2. press `SHIFT-TAB` while text is selected → un-indent the selected lines one level
4. press `ENTER` → insert `\n`, and indent to match the now previous line indentation

With (4), the indent should likely match the characters used to indent the previous line.

Or something like that. I'm sure I'm missing something.
