### ISSUE TITLE
Cache buster missing on (some?) homepage CSS

### ISSUE THREAD

**Issue by lgarczewski** [naturalcrit/homebrewery#2108]
After the recent update, the homepage CSS was messed up (see image in link below).

A hard refresh fixed the issue. This happened both to me aand the author of the linked reddit thraed.

Based on this I assume there's a cachebuster missing on one or more CSS files used by the homepage

Link (with screenshot): https://www.reddit.com/r/homebrewery/comments/trp617/firefoxwindowsv3_having_a_weird_bug_with_my_list/

**Comment by 5e-Cleric** [comment]
I think given how little we change pages, it is okay for the browser to cache most of it, giving faster load times. Not sure this is even still and issue.

@dbolack-ab @calculuschild does the homepage load a theme now? therefore with caching of the theme disabled?

If so, this issue should be closed.

**Comment by 5e-Cleric** [comment]
Confirmed myself that homepage loads a static theme, which is incredibly fast anyway, this issue is being closed for the already mentioned reasons, homepage is barely changed if at all.
