### ISSUE TITLE
Card Mode

### ISSUE THREAD

**Issue by ryantheleach** [naturalcrit/homebrewery#212]
It would be awesome to have a "card mode" which could create Magic The Gathering sized cards that can fit into sleeves, and print to letter/A4

Homebrewery is so good, if it could just easily create cards from a template it would beat the absolute pants off of anything in existence.

**Comment by stolksdorf** [comment]
Cool idea! Design the template and I can add it.

**Comment by ryantheleach** [comment]
I'm not that great of a designer, when you say design the templates do you mean the CSS? 
some mockups?
Or do you think creating some form of actual templating substitution, then loading from a datasource would be relevant to the project?

**Comment by wrdclark** [comment]
Here's some ideas I've just played with. Lots of CSS work to be done (standard monster stat blocks don't work, as it looks like the blockquote isn't being parsed), but it's a start!

**Comment by ryantheleach** [comment]
@wrdclark That's a great start, but for cards I think it would be more flexible that instead of hard coding font's in cm that it used relative font sizes.

This would make it a lot easier for people to edit the default card template in case they wanted different sized cards (playing card vs MTG size sleeves) or printing onto index cards.

**Comment by vlos** [comment]
Looks intereseting - side note, you may want to switch to landscape. Think you could get 2 rows of 4?

**Comment by Gazook89** [comment]
I know this thread was opened 4 years ago, but wanted to thank @wrdclark for the idea to put cards inside the .phb div.  I had played with cards previously but was only thinking about turning the .phb div into individual cards, which resulted in bad pdfs.  I still like this method for just creating stuff online, but obviously if you are designing cards then you likely want to be able to print them too.  [These cards are set to "Tarot" dimensions.   
](https://homebrewery.naturalcrit.com/share/RjaYiyOc9RJQ) 

Creating the cards within the normal pages means no issue with printing.  Also, it means a table of contents could be created on the first page using the normal method (however...not sure if the ToC generator snippet even existed 3 years ago).

[My new cards are styled to match Magic the Gathering](https://homebrewery.naturalcrit.com/share/1UzpGWTa0WpKYlUCpuP6DnzIN0A2nHAVp7dsPYDGtTDEq), and likely can't be easily modified to do DnD cards (I don't know what that would even look like as it seems to me there is too much possible info/text needed on a card).  It could also be said that my method relies too much on divs to be considered "general use".  But posting here in case it helps.

**Comment by AlexeySachkov** [comment]
Tagging @G-Ambatte here since we have card snippet being developed in #1167. @Gazook89, your feedback and suggestions to the PR would be helpful as well

**Comment by calculuschild** [comment]
Blocked on #1899

**Comment by Gazook89** [comment]
@calculuschild, could a theme be built now that includes the necessary stylesheet and custom snippets for this?

**Comment by calculuschild** [comment]
Yes... You would determine what theme to base it off of (for example the PHB or just the "blank" theme), then just copy one of the existing theme folders, update the "settings.json" appropriately to have the correct base theme and snippets.

**Comment by G-Ambatte** [comment]
[This](https://homebrewery.naturalcrit.com/share/6_6kXKXpScKG) is a brew I made of a magic item card, using the best "standard" trading card sizing I could find online (2.5"x3.5"). It still needs some work, for example, the header ribbon is just a placeholder graphic right now, but in terms of layout and styling, I think it covers the main bases.

So the million dollar question: is this actually what we want the Homebrewery "Card" theme to look like? And if not, what changes need to be made?

![image](https://github.com/naturalcrit/homebrewery/assets/19826659/d44254d0-e883-4b75-8680-2bb5b8b14f4d)

**Comment by 5e-Cleric** [comment]
Once #3085 is closed and #3321 merged, this should be closed.

**Comment by 5e-Cleric** [comment]
Feel obliged to mention, even with that PR, the user will need to have a brew with a card page styling ready in their account, then use that as a theme.

Here some brews that have a card theme for users to clone:

- [Test Card Template](https://homebrewery.naturalcrit.com/share/6_6kXKXpScKG)
- [D&D Quick Reference Cards](https://homebrewery.naturalcrit.com/share/2TxUsWf9mqw-)
