### ISSUE TITLE
New Framed Monster Statblock Background Color?

### ISSUE THREAD

**Issue by Kaiburr-kath-hound** [naturalcrit/homebrewery#2123]
I *think* this is the right place to post this, but I was messing around with a PHB theme, and I found that **#F2E5B5** seems a bit more accurate (and to me, more pleasing to look at) than the current **#EEDBAB**. It has slightly less contrast and is a little more parchment-y, I think. 

This is obviously pretty low priority, and only my opinion, but I figured I'd mention it.

**Comment by calculuschild** [comment]
This does look a bit better I think. Feel free to make a PR.
