### ISSUE TITLE
User Page retrieves whole brews instead of details only

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2147]
We need to update the user page to not retrieve the entire brew contents when filling out the `brewItem` boxes. Turns out some of our users like to embed giant base64 images into their text, and when they make 50 copies of that brew, suddenly the HB is trying to fetch 550 MB of data all at once. This kills the crab.

(and crashes the HB due to low memory, and hangs the Mongo database while the search tries to complete, eventually also crashing due to low memory)

https://github.com/naturalcrit/homebrewery/blob/156abe3b9e820b3a680e0cfa6dd4252903a62cee/server/homebrew.model.js#L55-L66

We just use projection to filter out which fields we actually want to fetch:

```

const project: { title : 1, description : 1 ....}

Homebrew.find(query, {projection: project}).lean().exec((err, brews)=>{ //lean() converts results to JSObjects
			if(err) return reject('Can not find brew');
			return resolve(brews);
		});
```

**Comment by G-Ambatte** [comment]
Relevant docs: https://www.mongodb.com/docs/manual/tutorial/project-fields-from-query-results/#return-the-specified-fields-and-the-_id-field-only

**Comment by G-Ambatte** [comment]
Looks like we should be able to do the same for Google brews: https://developers.google.com/drive/api/guides/fields-parameter

**Comment by G-Ambatte** [comment]
Actually, on closer inspection, the returned `text` field in the Google Brew API is already set to `text: ''` for the `listGoogleBrews` function used by the UserPage, so it seems that this is already in place.
