### ISSUE TITLE
Problems with Chrome

### ISSUE THREAD

**Issue by AntAgu95** [naturalcrit/homebrewery#2169]
Hi everyone,
i've started a new project on The Homebrewery, but i use to code in Firefox and I use Chrome just to export pdfs.

Right now, I have two problems to solve, and both of them happen just when I use Chrome.

**First one** is that I have an unwanted space between a table and the upper text.
This is the screenshot and the code.
[Screenshot](https://i.imgur.com/MjwAaNe.png)
And [Code](https://i.imgur.com/8zsuCvY.png).

**Second** issue is about the tables. I'm using the simple ones to make the Ideals/Bond/Flaws features, just like in the PHB, but i've noted that **just in chrome** the format has a problem when I write too much, and the first column starts to became narrow.
This is the screenshot and the code.
[Screenshot](https://i.imgur.com/bkDg3W6.png)
And [Code](https://i.imgur.com/c3X1dgh.png).

Can you guys please help me?
Thank you!

**Comment by ericscheid** [comment]
The second issue can be addressed with a bit of css, something like `.page table td:first-child { width: 3em; }`

For the first issue it would be easier to diagnose if you could provide a share link so we can clone the brew.

**Comment by AntAgu95** [comment]
> The second issue can be addressed with a bit of css, something like `.page table td:first-child { width: 3em; }`
> 
> For the first issue it would be easier to diagnose if you could provide a share link so we can clone the brew.

Thanks man!
You fixed one of my problems!

As you asked, here is a published brew with just the issued page.
[Brew](https://homebrewery.naturalcrit.com/share/1W1LmTheN6cQa3v24xJ187iAKY7Pl0XnKDVMz02EW7G01) and [Code](https://homebrewery.naturalcrit.com/source/1W1LmTheN6cQa3v24xJ187iAKY7Pl0XnKDVMz02EW7G01)

**Comment by ericscheid** [comment]
OK, thanks for source. I see you are using the Legacy renderer .. a long-standing issue with that renderer was the columns handling and flowing was sometimes wonky, which is what you're seeing here (the first column of the text above the table has it's height calculated by the browser render as including both paragraphs, but then paints the 2nd paragraph in column 2).

I suggest and recommend switching to the V3 renderer. Click on the `(i)` icon, and then `V3` option.

<img width="869" alt="image" src="https://user-images.githubusercontent.com/2605467/167624156-2aca3ebe-69aa-4f0b-88ad-279069ad2c80.png">

You will need to tweak your brew source though - there's a new renderer that does columns much better, the base PHB style/theme got heavily tweaked, and we introduced a new syntax to make demarcating blocks and spans much easier than mucking about with html code. (And did something we call curly-injectors too).

Class tables are now written with the curly-block syntax, like this:

```
{{classTable,wide,frame,decoration
> table goes here <
}}
```

The frame around the table is invoked by the `frame` classname, and the fancy thaumaturgic circle symbol underneath the table is invoked by the `decoration` classname. You can remove that by the obvious means.

The new curly-block syntax is much easier than mucking about with html divs. In brief, you can replace 

`<div class="myClass another-class" id="FancyBox" style="background-color:pink">` 
with 
`{{myClass,another-class,#FancyBox,background-color:pink`

.. i.e. settings are comma delimited, classnames are unadorned, the `id` attribute has a `#` prefixed, css properties are indicated via `:` (and any css-property with spaces needs to be wrapped in "quotes").

For css-properties you're usually better off assigning a class-name and defining that css-class in the styling pane. The `property:value` syntax is useful for one-offs though.

Check the changelog at https://homebrewery.naturalcrit.com/changelog for more details of V3 syntax.

Also, all the brew editor snippet menus will insert V3 version snippets, so you can learn from those too.

----

I would also recommend adding `.page p { text-align:justify; }` to your brew.style .. that way every paragraph is justified without having to wrap each in a `<div>`.

**Comment by ericscheid** [comment]
Last comment .. highly recommend asking these brew-formatting questions in the sub-reddit. https://www.reddit.com/r/homebrewery/

**Comment by AntAgu95** [comment]
> OK, thanks for source. I see you are using the Legacy renderer .. a long-standing issue with that renderer was the columns handling and flowing was sometimes wonky, which is what you're seeing here (the first column of the text above the table has it's height calculated by the browser render as including both paragraphs, but then paints the 2nd paragraph in column 2).
> 
> I suggest and recommend switching to the V3 renderer. Click on the `(i)` icon, and then `V3` option.
> 
> <img alt="image" width="869" src="https://user-images.githubusercontent.com/2605467/167624156-2aca3ebe-69aa-4f0b-88ad-279069ad2c80.png">
> 
> You will need to tweak your brew source though - there's a new renderer that does columns much better, the base PHB style/theme got heavily tweaked, and we introduced a new syntax to make demarcating blocks and spans much easier than mucking about with html code. (And did something we call curly-injectors too).
> 
> Class tables are now written with the curly-block syntax, like this:
> 
> ```
> {{classTable,wide,frame,decoration
> > table goes here <
> }}
> ```
> 
> The frame around the table is invoked by the `frame` classname, and the fancy thaumaturgic circle symbol underneath the table is invoked by the `decoration` classname. You can remove that by the obvious means.
> 
> The new curly-block syntax is much easier than mucking about with html divs. In brief, you can replace
> 
> `<div class="myClass another-class" id="FancyBox" style="background-color:pink">` with `{{myClass,another-class,#FancyBox,background-color:pink`
> 
> .. i.e. settings are comma delimited, classnames are unadorned, the `id` attribute has a `#` prefixed, css properties are indicated via `:` (and any css-property with spaces needs to be wrapped in "quotes").
> 
> For css-properties you're usually better off assigning a class-name and defining that css-class in the styling pane. The `property:value` syntax is useful for one-offs though.
> 
> Check the changelog at https://homebrewery.naturalcrit.com/changelog for more details of V3 syntax.
> 
> Also, all the brew editor snippet menus will insert V3 version snippets, so you can learn from those too.
> 
> I would also recommend adding `.page p { text-align:justify; }` to your brew.style .. that way every paragraph is justified without having to wrap each in a `<div>`.

> Last comment .. highly recommend asking these brew-formatting questions in the sub-reddit. https://www.reddit.com/r/homebrewery/

Thank you very much for your help!
Next time I'll post on reddit!

Anyway, switching to V3 rn is kinda a pain in the ass. I've currently done 50 pages and yeah... Back to work, I guess.
Thank you again, #ericscheid!
