### ISSUE TITLE
Columns not displaying correctly on Chrome 102.0.5005.63

### ISSUE THREAD

**Issue by GE0NE** [naturalcrit/homebrewery#2195]
## Environment

**Browser(s):** Chrome Version 102.0.5005.63 (Official Build) (64-bit)

**Operating System:** Windows 10 (x64)

**Legacy or v3 Renderer:** v3 Renderer

## Description

Manual column breaks are rendered with too much spacing and are pushed off the page on Chrome 102.0.5005.63 but not on earlier versions.

## Images

[Chrome 101.0.4951.67](https://i.imgur.com/gKY8d44.png)

[Chrome 102.0.5005.63](https://i.imgur.com/q21LTWZ.png)

**Share Link** :

https://homebrewery.naturalcrit.com/share/19O72H7NrXlGJ17rXmBXZ13QkDBSNGyw0fd5PofH4aTmO

**Comment by GE0NE** [comment]
A few other users on the subreddit have noticed this issue as well [\[1\]](https://www.reddit.com/r/homebrewery/comments/uyk6j1/please_help/) [\[2\]](https://www.reddit.com/r/homebrewery/comments/uyrnni/columns_arent_working_to_much_space_in_between/).

Considering this breaks many existing brews, I think it should be considered high priority (P1)

**Comment by calculuschild** [comment]
Thanks for the report! It looks like Chrome did indeed change the handling of column breaks a little in Chrome 102. Our `columnSplit` element that gets inserted when typing `\column` had rules to split the column before and after it. Previously Chrome would see both and ignore one. Now it seems to apply both, so we now get two column breaks.

Removing `break-before: column` seems to solve the problem, with the added bonus of removing some odd spacing that would occur around `wide` blocks. Just need to make sure we aren't accidentally breaking something else.
