### ISSUE TITLE
Deduplicate pagination functions in Editor and BrewRenderer

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2198]
As per [this comment](https://github.com/naturalcrit/homebrewery/pull/2162#discussion_r869850180) on PR #2162, with the merging of that PR, the pagination function in the BrewRenderer will be duplicated in the Editor.

It should be possible to use `React.cloneElement` to add props to the `this.props.children` (as identified in [this comment](https://github.com/naturalcrit/homebrewery/pull/2162#discussion_r884207224)) being handled in `SplitPane.jsx` to pass a unified pagination function as a prop to both child elements.

**Comment by 5e-Cleric** [comment]
I am not sure if the current toolbar even gives a third page navigation function. Should check.

**Comment by dbolack-ab** [comment]
Is this still an issue with the Intersection Observer?

**Comment by calculuschild** [comment]
I think this was handled somewhere around #3729 or #3484
