### ISSUE TITLE
Bottom decoration on Half Class Table disappears when table is short.

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2207]
See https://www.reddit.com/r/homebrewery/comments/v63m5f/comment/ibj6mv6/?utm_source=share&utm_medium=web2x&context=3

The bottom decoration probably gets nudged out when it starts to overlap the top one.

**Comment by Gazook89** [comment]
Not every class table in the PHB has the exact same positioning of that ring, though, right?  If that's right, I don't think this is much of an issue.  More ideally the decoration would be randomly placed at some point around the table, but obviously CSS won't do that, so HB just places them where it does.

Maybe i'm wrong about my initial assumption though.

**Comment by calculuschild** [comment]
They are more or less consistent at least on the "half" class tables. At a minimum, there should be two decorations, one at the top and one at the bottom. The problem is the bottom decoration doesn't appear at all when the table is too short.
