### ISSUE TITLE
Add "spellcasting ability" to the Class Features snippet

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2215]
The small bit of formatting for "spellcasting ability" seems to trip people up. We can include it into the Class Features snippet:

<pre><code>
## Class Features
As a fletcher, you gain the following class features
#### Hit Points

**Hit Dice:**                    :: 1d10 per fletcher level
**Hit Points at 1st Level:**     :: 10 + your Constitution modifier
**Hit Points at Higher Levels:** :: 1d10 (or 6) + your Constitution modifier per fletcher level after 1st

#### Proficiencies

**Armor:**   :: Medium armor, Shields, Heavy armor
**Weapons:** :: Martial weapons, Squeegee
**Tools:**   :: Artian's tools, Thieve's tools

**Saving Throws:** :: Intelligence, Dexerity
**Skills:**        :: Choose two from Perception, Deception, Nature, Acrobatics

<b>#### Spellcasting Ability

{{text-align:center
**Spell save DC** = 8 + your proficiency bonus + your Charisma modifier
:
**Spell attack modifier** = your proficiency bonus + your Charisma modifier  
}}</b>
</code></pre>

**Comment by jlgraves** [comment]
Okay, I'm pretty new at this - but this seemed like a nice place to get my feet wet contributing.

I've made this change to both `classfeature.gen.js` on the `snippets` and `snippetsLegacy` folders.   They seem to work on my end; I added some randomization similar to the other elements.

If this looks OK, I can submit a pull request from my fork. 


```
return dedent`
		## Class Features
		As a ${classname}, you gain the following class features
		#### Hit Points

		**Hit Dice:**                    :: 1d${hitDie} per ${classname} level
		**Hit Points at 1st Level:**     :: ${hitDie} + your Constitution modifier
		**Hit Points at Higher Levels:** :: 1d${hitDie} (or ${hitDie/2 + 1}) + your Constitution modifier per ${classname} level after 1st

		#### Proficiencies

		**Armor:**   :: ${_.sampleSize(['Light armor', 'Medium armor', 'Heavy armor', 'Shields'], _.random(0, 3)).join(', ') || 'None'}
		**Weapons:** :: ${_.sampleSize(['Squeegee', 'Rubber Chicken', 'Simple weapons', 'Martial weapons'], _.random(0, 2)).join(', ') || 'None'}
		**Tools:**   :: ${_.sampleSize(['Artian\'s tools', 'one musical instrument', 'Thieve\'s tools'], _.random(0, 2)).join(', ') || 'None'}

		**Saving Throws:** :: ${_.sampleSize(abilityList, 2).join(', ')}
		**Skills:**        :: Choose two from ${_.sampleSize(skillList, _.random(4, 6)).join(', ')}

		#### Spellcasting Ability

		{{text-align:center
		**Spell save DC** = ${_.sample([6, 8, 10])} + your proficiency bonus + your ${spellSkill} modifier
		:
		**Spell attack modifier** = your proficiency bonus + your ${spellSkill} modifier  
		}}

		#### Equipment
		You start with the following equipment, in addition to the equipment granted by your background:
		- *(a)* a martial weapon and a shield or *(b)* two martial weapons
		- *(a)* five javelins or *(b)* any simple melee weapon
		- ${_.sample(['10 lint fluffs', '1 button', 'a cherished lost sock'])}

		`;
```

**Comment by calculuschild** [comment]
Yeah go ahead and submit a PR. We appreciate the contribution!

**Comment by ericscheid** [comment]
This has been implemented and deployed. No reports of errors. Closing.
