### ISSUE TITLE
Change user page default sort to descending update date

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#2227]
From [reddit](https://www.reddit.com/r/homebrewery/comments/ve5kvg/users_brew_page_sort_default_setting/):

> I would like to suggest that the default sort setting on a user's brew page be set to "Update Date" and "Descending"
> 
> This way the last brew you worked one is at the top of the page and you do not have to search for it every time you login.

**Comment by Gazook89** [comment]
Currently the site stores your last sort in LocalStorage (both the type of sort and direction).  So I suppose you would just need to set your sort once, and then you are set, unless your are clearing your localstorage.

If someone else is visiting your User Page, should the last created documents be at the top, or be alphabetical or based on views/popularity?

I have no strong feelings one way or the other.  It is simply changing listPage.jsx lines 12-13:

```js
const DEFAULT_SORT_TYPE = 'alpha';
const DEFAULT_SORT_DIR = 'asc';

```

**Comment by G-Ambatte** [comment]
As UserPage sorting is not tied to the user at all, visiting another user's page will still result in the local settings being applied. I can envisage a potential use-case where if the UserPage `req.username != account.username` then we should use a different set of local settings (e.g. `foreignUserPageSortType` and `foreignUserPageSortDir`) so the user's UserPage settings are not affected by what they choose when visiting another user's UserPage.
However this would be fairly opaque, and probably cause more confusion than it would ever create benefit - particularly when changing between sort types/directions is so simple already.

**Comment by G-Ambatte** [comment]
On the actual topic, however, I have no issue with changing the default sort type/direction. We could also expose it in the configuration file, so people running HB locally don't have to muck about in source code to change the default option on their local install.

**Comment by Gazook89** [comment]
I think just leave as is— there isn’t any mucking about on local. Just change it on the user page and it saves to local storage as well

**Comment by Gazook89** [comment]
If there is any change about the default sort I'm in favor of changing it to **Creation Date**, with most recent at top.  For many first time users that will correspond with 'most recent'.  And with a single click the sort category can be changed to 'most recent updated date' which is then saved in their local storage.

**Comment by Gazook89** [comment]
I'm all for just leaving the default sort the way it is (alphabetical) and closing this issue. Either way, just need someone else to profess a strong preference so either this can be closed, or a PR made.

**Comment by calculuschild** [comment]
@Gazook89 I agree we just leave it.
