### ISSUE TITLE
[FEATURE]: Brew security features, password, author permissions

### ISSUE THREAD

**Issue by FangirlCrazily** [naturalcrit/homebrewery#2257]
Right now, the only way to collaborate with others on the same Homebrewery document is via sharing with them the edit link. This is fine and dandy for one or two collaborators, but lacks in security for bigger groups. For example, large teams with contracted writers that come and go, or discord servers with many roles working on the doc. 

All it takes is someone sharing the wrong link: the edit link instead of the view link, for a bad faith user to wipe the doc. Or a rogue team member sharing the edit link to incite griefing. This has likely happened before, whether intentional or on accident.

My proposal is that since NaturalCrit has a working account system, to provide the option of sharing edit permissions to a specific account by entering their email. The owner of the doc can then revoke these permissions at any time, if let's say the writer is no longer working with them. This is similar to the permissions sharing of Google docs/sheets.

If the above doesn't work for whatever reason, my second proposal would be to have the ability to set passwords for docs. There is still the danger of passwords being leaked, but at least passwords can be changed, unlike the links.

I think Homebrewery is a fantastic tool, it's just that its lack of security forces me to choose between its aesthetics or the more advanced permission sharing of Google Docs. This feature is something that I feel would be very beneficial to the security aspect, and would provide a peace of mind altogether.

**Comment by ericscheid** [comment]
Naturalcrit does not store email addresses in it's account system, just usernames and passwords (hashed).

Other than that your proposal has merit, and IIRC there is work already towards that end.

A side issue, parallel, is that homebrewery doesn't currently support concurrent editing. That also is under consideration.

**Comment by Gazook89** [comment]
Is it possible to control permissions of Google Drive saved brews via the permissions controller in Drive?  I have no idea.

**Comment by calculuschild** [comment]
> IIRC there is work already towards that end.

Yep, this is part of the Stubs effort. The next step is changing the was owners/authors are added to brews so you can't just stumble onto an edit link.

**Comment by FangirlCrazily** [comment]
> Naturalcrit does not store email addresses
Ah, its been a long time since I created my account, so I suppose I was mistaken on that. Though (I think?) accounts would work as well.

> Is it possible to control permissions of Google Drive saved brews?
I'm curious to know this as well. I was under the impression that GDrive could only save the pdfs for brews

> This is part of the Stubs effort
Is this something that has a planned release date? Or is it more of something being worked on the background? Just asking to manage my expectations.

**Comment by ericscheid** [comment]
>> This is part of the Stubs effort

> Is this something that has a planned release date? Or is it more of something being worked on the background? Just asking to manage my expectations.

This is work currently in progress.

Stubs _per se_ don't have an obvious UI effect, definitely a background thing. Fairly close though.

#1987, #1840, #1838 etc.

**Comment by 5e-Cleric** [comment]
updated title to show what the issue is actually about

**Comment by calculuschild** [comment]
For a while now, we already prevent viewing edit pages of brews if you are not logged in as one of the authors. An author can add others to the document by typing in their username in the brew properties panel. If an author deletes a brew, they only delete it from their own account, not for the whole group.

My understanding then is that this feature is already implemented.

**Comment by 5e-Cleric** [comment]
This issue also mentions:
- setting passwords to brews
- Giving some authors special permissions to bring in more authors

**Comment by calculuschild** [comment]
> - setting passwords to brews

Passwords should no longer needed, since they were only proposed in case we could not find a way to limit edit page access to approved authors.

> - Giving some authors special permissions to bring in more authors (more like restricting permissions to the author)

So this seems to be the only remaining item. Currently, any invited author can invite other authors, and you can't remove another author that has already made edits.

**Comment by 5e-Cleric** [comment]
> you can't remove another author that has already made edits

Interesting, well, i don't think this is as important as to keep this issue, All authors shall keep the right to invite an author, and users should be responsible with who they invite.
