### ISSUE TITLE
The eñe character in ScalySansSmallCapsRemake (V3) is borked

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#2280]
ScalySansSmallCapsRemake is used in V3 for H5 headings.

In Legacy, the font-face is ScalySansSmallCaps, and the glyph is correct.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/2605467/185114940-c035f7be-09ea-4d7b-920f-3d8629dec9a2.png">

Put this into a V3 brew..
````
##### Gravedad del Daño in V3

##### Gravedad del Daño in Legacy
{font-family:ScalySansSmallCaps}

<style>
/* copied from 5ePhbLegacy.style.css */
@font-face {
  font-family: ScalySansSmallCaps;
  src: url('../fonts/5e legacy/Scaly Sans Caps.woff2');
  font-weight: normal;
  font-style: normal
}
</style>

````

**Comment by 5e-Cleric** [comment]
Releasing a PR to fix this right now.

**Comment by calculuschild** [comment]
We definitely do not want to use the Legacy font in V3. The V3 font fixes several other issues with that existed in the Legacy font. Just fixing one character is not a good enough tradeoff.

What we actually want to do is go into the V3 font and just add the missing character.
