### ISSUE TITLE
[FEATURE] Footnote Auto - Automatically use preceding h1 tag for text

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2289]
Suggested in the subreddit recently was the idea that using an additional tag - for example, adding the `auto` class to the existing `footnote` element could trigger the use of the contents of the nearest preceding `<h1></h1>` tags.

I believe this functionality would need to be built in to the BrewRenderer, and in some ways may border on Brew Variables, in that it also replaces arbitrary value from the Brew text with a value that is defined elsewhere in that text.

**Comment by calculuschild** [comment]
> reopening the issue to track that change.

This sounds like a separate issue. I'm going to re-close this as the original goal issue was solved.

This new idea about adding caps should be tracked in it's own issue.
