### ISSUE TITLE
Table of Contents Generator includes headers from inside Monster Statblocks

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2294]
## Description

Probably don't want "Actions, Bonus Actions, Legendary Actions... etc." showing up when using the TOC generator snippets.

![image](https://user-images.githubusercontent.com/5878534/187058691-aabe2740-f942-4f4f-a53a-325397978bb8.png)

See this reddit post: 
https://www.reddit.com/r/homebrewery/comments/wzfvtz/table_of_contents_includes_contents_of_statblock/

**Comment by ericscheid** [comment]
This might be complicated, as the current method simply searches and collates instances of headings via raw grep, but this issue would require detecting if such heading is within a monster block. Not impossible, just a little messy complexity.

**Comment by dbolack-ab** [comment]
How would you feel about adding a system for flags to the {{}} system? This could be done either via empty classes ( possibly useful in that it can be seen in the rendering ) or via a prefix that the {{}} parse uses to indicate it should drop from the configuration string in the {{}}

EX 1: ```{{monster,noH3,noH4 ....Monsterblock}}```
EX 2: ```{{monster,!noH3,!noH4 ...Monsterblock)}```

Example 1 is easier to implement but the ! in example 2 makes it easier to eyeball spot for problem solving.

**Comment by dbolack-ab** [comment]
> this should not be added to the monster stat block, but rather to the ToC generation.
> 
> That is because no header in any monster statblock should EVER be part of the ToC. (if we are following the book.

That's not a robust design.

**Comment by 5e-Cleric** [comment]
Wym? a robust design? it makes no sense to add a visible class to monster stat blocks which is never going to be removed, we are following a style determined by a book, striding away from it is not prioritary or desired unless UX is harmed.

**Comment by dbolack-ab** [comment]
> Wym? a robust design? it makes no sense to add a visible class to monster stat blocks which is never going to be removed, we are following a style determined by a book, striding away from it is not prioritary or desired unless UX is harmed.

I'm just gonna implement this to have a  working example.

Monthly reminder - my priorities here are not tied to the limitation fidelity - NOR does this impact it.

**Comment by ericscheid** [comment]
See the end of this comment for a simpler approach

https://github.com/naturalcrit/homebrewery/issues/2920#issuecomment-1901276551

> An alternative is to instead set up a css rule (with multiple selectors) that applies a custom css property, and looking at `getComputedStyle(element).getPropertyValue("--TOC")`, and filter based on that:
>
>```css
>.page:has(.frontCover), 
>.page:has(.backCover), 
>.page:has(.insideCover), 
>.page:has(.partCover), 
>.monster h3,
>.monster h4 {
>  --TOC: exclude;
> }
>```

**Comment by dbolack-ab** [comment]
> See the end of this comment for a simpler approach
> 
> [#2920 (comment)](https://github.com/naturalcrit/homebrewery/issues/2920#issuecomment-1901276551)
> 
> > An alternative is to instead set up a css rule (with multiple selectors) that applies a custom css property, and looking at `getComputedStyle(element).getPropertyValue("--TOC")`, and filter based on that:
> > ```css
> > .page:has(.frontCover), 
> > .page:has(.backCover), 
> > .page:has(.insideCover), 
> > .page:has(.partCover), 
> > .monster h3,
> > .monster h4 {
> >  --TOC: exclude;
> > }
> > ```

I don't see how that helps ToC generation ?

**Comment by ericscheid** [comment]
> I don't see how that helps ToC generation ?

Oh, an assumption on my part — I was imagining the TOC being generated from the headings in the rendered DOM. (The snippet actually scans the `brew.text` source instead).

So .. with PPR going away soon .. imagine the TOC being generated from the headings in the rendered DOM, with each heading checked with `getPropertyValue("--TOC")`.

Something like this psuedo-js:

```js
  function extractHeadingsFromPreview() {
    var iframe = document.getElementById('BrewRenderer');
    var iframeDocument = iframe.contentDocument || iframe.contentWindow.document;
    var headings = iframeDocument.querySelectorAll('h1, h2, h3, h4, h5, h6');

    headings.forEach(function (heading) {
      if ( getComputedStyle(element).getPropertyValue("--TOC") != "exclude" ) {
        console.log(heading.innerText);
        // add to the snippet output
      }
    }
  }
```

**Comment by dbolack-ab** [comment]
> > I don't see how that helps ToC generation ?
> 
> Oh, an assumption on my part — I was imagining the TOC being generated from the headings in the rendered DOM. (The snippet actually scans the `brew.text` source instead).
> 
> So .. with PPR going away soon .. imagine the TOC being generated from the headings in the rendered DOM, with each heading checked with `getPropertyValue("--TOC")`.
> 
> Something like this psuedo-js:
> 
> ```js
>   function extractHeadingsFromPreview() {
>     var iframe = document.getElementById('BrewRenderer');
>     var iframeDocument = iframe.contentDocument || iframe.contentWindow.document;
>     var headings = iframeDocument.querySelectorAll('h1, h2, h3, h4, h5, h6');
> 
>     headings.forEach(function (heading) {
>       if ( getComputedStyle(heading).getPropertyValue("--TOC") != "exclude" ) {
>         console.log(heading.innerText);
>         // add to the snippet output
>       }
>     }
>   }
> ```

This requires a redesign of the snippet, but that shouldn't be huge. 

This design embeds all of the controls into CSS which means the user 
 - Has to know what  the CSS does - and to a small degree how
 - May have to override the style if they want a different pattern than the theme designers

Neither of those seem to be particularly onerous. 

I think it comes down to which method is easier for users who want to do anything other than the stock theme(s) pattern and what level of CSS skill we assume they have.

**Comment by ericscheid** [comment]
Slightly revised js snippet:

```js
 var iframe = document.getElementById('BrewRenderer');
 var iframeDocument = iframe.contentDocument || iframe.contentWindow.document;
 var headings = iframeDocument.querySelectorAll('h1, h2, h3, h4, h5, h6');

 headings.forEach(function (heading) {
   let text = heading.innerText;
   let page = heading.closest('.page,.phb').id;
   let excluded = getComputedStyle(heading).getPropertyValue("--TOC");
   console.log({page, text, excluded});
   // add to the snippet output 
   }
  )
  ```
  
  
<img width="909" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/2605467/26d94e36-1bb4-4763-a60d-38f901bffc5f">

Based on this style rule established:

```css
.page:has(.frontCover), 
.page:has(.backCover), 
.page:has(.insideCover), 
.page:has(.partCover), 
.monster h3, 
.monster h4, 
h5, h6, 
.toc 
  { --TOC: exclude; }
```

**Comment by dbolack-ab** [comment]
I will try adapting this to my PR. Thank you

**Comment by dbolack-ab** [comment]
@calculuschild Are we satisfied this is closed?
