### ISSUE TITLE
HTML Validator flagging custom tags starting with "a" as unmatched opening tag

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#230]
In my brew, I have made use of custom HTML tags to generate small icons inline with the text.  One of these icons is named < airEl >, and the HTML validator is flagging every use of this tag as "Unmatched opening tag, 'a' tag".  There doesn't seem to be an issue on the other custom tags (such as < fireEl >)

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/SyEA7MxL (this might be temporarily changed to <bair> to avoid the issue so I can work on my brew.  Problem code is pasted below, but my HTML tags are not appearing in the code preview for some reason, so I replaced the leading < with a ( to keep them from hiding.)

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<style>
airEl {
	background-image: url(https://d30y9cdsu7xlg0.cloudfront.net/png/281535-200.png);
    background-size: 14px 14px;
    background-repeat: no-repeat;
    display:inline-block;
    width:14px;
    height:14px;
    vertical-align: text-top;
    color: transparent;
}

fireEl {
	background-image: url(https://d30y9cdsu7xlg0.cloudfront.net/png/96564-200.png);
    background-size: 14px 14px;
    background-repeat: no-repeat;
    display:inline-block;
    width:14px;
    height:14px;
    vertical-align: text-top;
    color: transparent;
}
<style>

There are two primary essences that can be extracted from potent herbs, fungus, or animal parts for use as alchemical components: (airEl>(/airEl>**air**, and (fireEl>(/fireEl>**fire**.

</pre></code></details>

**Comment by ericscheid** [comment]
This looks to be fixed in PR https://github.com/naturalcrit/homebrewery/pull/678
