### ISSUE TITLE
[UserPage] Minor Fix - Sort Container Position without Scroll Bar

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2303]
The position of the Sort Container is inconsistent when the scroll bar is removed.

![image](https://user-images.githubusercontent.com/19826659/187173960-ede328cd-4d73-4b27-b70f-9c65984803fa.png)

Solution:: change the scroll bar to an overlay and adjust the position of the Sort Container accordingly (`calc(50vw - 400px)`).

**Comment by ericscheid** [comment]
Confirmed that the 2 css changes fixes this on Chrome MacOSX and also Safari MacOSX when the Show scrollbar sysem preference is set to hidden.

Also fixes in Chrome if system preference is set to Always show scrollbar. 

In Safari OSX with system preference set to Always show scrollbar .. the sortcontainer is shunted to the right. Acceptable.
