### ISSUE TITLE
Consider use of css region polyfill for automatic pagination

### ISSUE THREAD

**Issue by Qazzquimby** [naturalcrit/homebrewery#2306]
(Suggestion)

## Description

Overflowing text between containers facilitates automatic pagination, which could save significant time, especially for evolving projects.
[https://github.com/FremyCompany/css-regions-polyfill](https://github.com/FremyCompany/css-regions-polyfill) seems to do a good job of overflowing text. 
I'm new to the codebase and had trouble setting it up, so I can't confirm it's a solution.
I think it might require manually adding the right number of pages, but will automatically flow text between them.

Please close if this is known not to work.

**Comment by 5e-Cleric** [comment]
While the features in and on itself would be amazing, the amount of work might be disproportionate, even with that package, which i might add, is not developed anymore (last change 4 years ago, most changes 9 years ago). I also see it is only a partial implementation, with some known issues related to working only with static content, and duplicating elements which has made it that they eliminate Ids. For these reasons, i think this is not going to be implemented this way, if any. Closing.

**Comment by calculuschild** [comment]
Just dropping a note here for future reference: I was suggested [paged.js](https://github.com/pagedjs/pagedjs) as a possible tool to look into.
