### ISSUE TITLE
Images with reference link are not displayed inside tables in V3

### ISSUE THREAD

**Issue by azzco** [naturalcrit/homebrewery#2307]
I figured I'd make my document more readable by converting the image links inside a table to references. Inside the table I only got text output but outside it works.

I wrote a small snippet to showcase this, when I noticed that the legacy renderer shows the image as expected.

**Share Link** : https://homebrewery.naturalcrit.com/share/YBhE6rZA3zM8

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>
```
```
# Reference style linked image
## Normal
![Monster][1]{float:right}Adding images with reference style links works as expected in normal text.
:
As evident by this little guy here: ➜
:::
## Table
It does not appear to work inside tables.

|Reference link|Full link                                                         |
|:------------:|:----------------------------------------------------------------:|
|![Monster][1] |![Monster](https://openclipart.org/download/304637/1532851673.svg)|

[1]: https://openclipart.org/download/304637/1532851673.svg
```
```
</pre></code></details>

**Comment by calculuschild** [comment]
Thanks for the report!

I think I know what's causing this. V4 of Marked.js broke reflink inside of tables and only just fixed that in v4.0.16.

Our custom Tables extension for column and row spanning was based on the older Marked code, so I probably just need to make the same fix to our extension. Shouldn't be too hard.

**Comment by calculuschild** [comment]
Fixed in V3.2.1!
