### ISSUE TITLE
Links not clickable when printing to PDF

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#2312]
With the Get PDF function (which simply invokes the browser's Print dialog), often hyperlinks in the resulting PDF are not "clickable". 

Although #2050 and #1749 suggests a CSS tweak, turns out this was just a fluke. The problem still occurs, and it occurs with other browsers, other websites, other platforms.

https://superuser.com/questions/809627/print-webpage-to-pdf-with-working-hyperlinks

This needs to be raised as a Chrome Bug if it hasn't already. We can flail around with css tweaks but that will be overall unsatisfying.

----

Also, a related bug in PDF printing is that the text of the PDF is not selectable or searcheable.

**Comment by 5e-Cleric** [comment]
Cannot replicate this issue in Windows 11 with Chrome 127, but we just got a report from someone:

> Hello everyone. Been trying to open ToC Links in exported PDFs with both SumatraPDF and Adobe Acrobat, as well as Okular, and links seem to not be clickable. I have tried exporting with both Edge v127.0.2651.105 & Chrome v124.0.6367.208. Is it an issue with export or could it be my device?

**Comment by 5e-Cleric** [comment]
Nobody responded, considering this issue as fixed, or related to the known chrome bug.
