### ISSUE TITLE
Improve Open Graph metadata on home page (and other non-brew pages)

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#2323]
Links to our home page don't make a good impression.

![image](https://user-images.githubusercontent.com/2605467/188067650-a5a70336-d2a4-4c04-add7-cac756fba783.png)
![image](https://user-images.githubusercontent.com/2605467/188067627-bac08579-5430-4d91-abe2-aaff976a5da7.png)

**Comment by Gazook89** [comment]
What is the desired data for each page?  Below is sort of what I have in mind.

| data | `homebrewery....com` | `/share/` | `/edit/` | `/source/` and `/print/` | `/user/` | 
|:---|:---|:---|:---|:---|:---|
| **Site Name** | "The Homebrewery - Make your Homebrew look legit!" | ~ | ~ | ~ | ~ |
| **Title** |  "The Homebrewery" | *brew title* | *brew title* | *brew title* - Source/Print | *username* - The Homebrewery |
| **Description** | "Homepage" | *brew description* or `''` | *brew description* or `''` | *brew description* or `''` | *USER description\** or `''` |
| **Thumbnail** | d20 logo | *brew thumbnail* or `''` | *brew thumbnail* or `''` | *brew thumbnail* or `''` | *user thumbnail* or `''` |
| **Type** | website | article | article | article | website (or profile) |

\**user description could be a future user-specific field set in Account settings to give a brief description of the user, such as contact info or marketing/promotion/bio info.  Similar deal with user thumbnail*

I don't think we really need to show the d20 logo on all brews that don't have their own thumbnail-- it's not a terribly exciting logo and just takes a lot of space.
