### ISSUE TITLE
Thumbnail URL being incorrectly added to Google Metadata

### ISSUE THREAD

**Issue by ShamelessHero502** [naturalcrit/homebrewery#2351]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/AxN03P6n6_9t"
}
```

**Comment by calculuschild** [comment]
Error log says your url is way too long. Can you by chance share the URL you are trying to use for your thumbnail?

**Comment by ShamelessHero502** [comment]
https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/b700c630-9435-4853-b567-d025115b827b/degakzn-576504c0-f8f6-40f0-b130-3a19544a0e9e.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2I3MDBjNjMwLTk0MzUtNDg1My1iNTY3LWQwMjUxMTViODI3YlwvZGVnYWt6bi01NzY1MDRjMC1mOGY2LTQwZjAtYjEzMC0zYTE5NTQ0YTBlOWUucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.yPaYT4GYrakHIDBEXastMExHC4xVn4_kUFmgvd5J7sA

**Comment by calculuschild** [comment]
Yep, that giant link is the issue. Can you possibly put the image on a different image host Imgur to get a shorter link?

**Comment by calculuschild** [comment]
This is a re-emergence of a previous issue we had with the thumbnails.

> @G-Ambatte 
> 
> After merging this I immediately found a critical error, so feel free to create a new PR here since we can't reopen PRs directly it seems.
> 
> The error is this: Google Drive has a 124-byte limit on any property added to a document. Long image urls will cause the saving step to fail, which is actually pretty common. We're going to need an alternative way to add this to the Google document.
> 
> ```
> errors: [
>     {
>       domain: 'global',
>       reason: 'propertyLengthLimitExceeded',
>       message: 'Properties and app properties are limited to 124 bytes in UTF-8 encoding, counting both the key and the value.'
>     }
>   ]
> ```
> 
> _Originally posted by @calculuschild in https://github.com/naturalcrit/homebrewery/issues/1777#issuecomment-960377433_

At the time, we did not have the ```` ```metadata```` codefence on brews to hold larger metadata items. However, when we did finally re-enable thumbnails, we never actually moved the property to the metadata codefence. Hence we are still striking the 124-byte limit on Google Drive.

In any case, now that we have Stubs, the thumbnail should be stored there instead, according to this categorization we did earlier: 

> ...In general, we want to make sure catastrophic failure of the Homebrewery keeps any google brews intact, so any vital data that makes up the brew content should remain in Google. Any property that should be community-searchable (or would appear in the "brewItem" as part of a search result) should remain (or be duplicated to) in the HB Stub. Then there are a few properties that don't really serve either purpose, but I would lean toward keeping stubs as a minimal search index as much as possible:
> 
> #### HB Stub
> - googleId
> - *shareId*
> - *editId*
> - *title (for search result)* 
> - *description (for search result)*
> - authors
> - **owner? (new)**
> - views
> - tags
> - systems
> - published
> - **social media thumbnail (new)**
> 
> #### Google Drive
> - *shareId (to redirect to stub)*
> - *editId (to redirect to stub)*
> - isStubbed
> - *title*
> - *description*
> - text
> - renderer
> - **theme (new)**
> - version
> - createdAt
> - updatedAt
> - pageCount
> 
> For instance, we need to know if a brew is published in order to search for it, and if HB dies, users probably don't mind as if the `published` status is lost. However knowing what renderer/theme it was built on will be important in rebuilding the document later.
> 
> `version` and `pageCount` I don't think are necessarily searchable parameters that need to be in the Stub, but aren't really part of the brew content either. In this case I personally prefer keeping the stub smaller and dumping those into Google Drive.
> 
> Any differing thoughts or opinions? I can update the list as needed.
> 
> _Originally posted by @calculuschild in https://github.com/naturalcrit/homebrewery/issues/2114#issuecomment-1084687003_
> 

@G-Ambatte seems like this might be up your alley as part of the work on thumbnails? Can we move the thumbnails from being stored as a Google Drive property into Stubs? @jeddai or @calculuschild can point the way to interact with the stubs if you are willing to work on this and need help.

**Comment by G-Ambatte** [comment]
I'll probably need to have a chat with @jeddai about it; I think I've got a working branch now. Down side of the current iteration is that the thumbnail on any Google brews are reset.
