### ISSUE TITLE
Metadata information on Share page

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#2364]
It might be nice to have a way to view some of the metadata for a brew from the Share page.   For example, the authors, created date, last updated date, and tags.   

A "i" inside a circle icon (the same as the icon used for the metadata editor) in the Brew Title section of the navbar could either pop up a modal on hover or click to display this information.  Further, the author names could be links to the authors user page.

This would basically be the first step toward a more "browsable" experience without really having to add a "home" or "search" page.

**Comment by ericscheid** [comment]
Some of this is available from the `Source </>` menu, where the metadata is in a codefence.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/2605467/190299068-0956a507-9465-4114-bbef-bdea7d96c284.png">

Not all metadata though, and for some brews not even at all.
<img width="265" alt="image" src="https://user-images.githubusercontent.com/2605467/190299250-af0025f6-ef2a-4c59-904d-165b6d79038c.png">

This is not ideal as UX, of course, and I second the motion for a UI widget to reveal this.

----

A separate but relevant question though: we have up to now not disclosed the author/owner of a brew from any share page, not even hidden in the source. If all you have is the `/share/mumble` url, then you can't find out. 

Maybe a quick question to the sub-reddit to poll the community as to whether they would be upset if their username got revealed on their shared brews? I don't think there's a problem, some might well welcome it, but it's an assumption that might have some negatives. Best to check first.

**Comment by Gazook89** [comment]
Going through old issues and found that this is a duplicate of #1679 .  Closing this in favor of the original, but will pull @ericscheid's comment (particularly about disclosing authors) to that one.
