### ISSUE TITLE
Tweaks to issue forms

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2376]
A few issues with #2367 

- [ ] "validations" needs to go up one level to be right under "type" instead of under "attributes"
- [ ] Some other required fields are missing from the "Feature Request" template
- [ ] Remove the default value from `title` in the `Save Issue` template. Currently it auto-populates with `Save Error:` which users will probably ignore and we'll end up with every save issue with the same title. Leave it blank so we can require users to put some thought into it with the "validations" setting.
- [ ] Add "validations" to the `Save Issue` template.
- [ ] Link from `editPage.jsx` doesn't quite work.
  - [ ] Change `labels` from "saving" to "Saving"
  - [ ] Change `template` from "template=save_issue.yaml" to "template=save_issue.**yml**"

**Comment by Gazook89** [comment]
- done
- done (namely a 'attributes' key on the checkboxes)
- done...except I can't set a validation property but a title will still be required by Github I assume.
- done
- done

PR #2377
