### ISSUE TITLE
auto saving issue encountered in natural crit

### ISSUE THREAD

**Issue by alcxander** [naturalcrit/homebrewery#2386]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/QLh75uSIHg7q"
}
```

**Comment by calculuschild** [comment]
Looks like our server just had a temporary hiccup. Should be working again after a minute or two.

**Comment by alcxander** [comment]
cool, close it off. it was just prompted on screen hence the ticket

**Comment by calculuschild** [comment]
Yep, we still like to see the tickets just in case something unusual is up, so I appreciate you doing so. :+1: It just happens this one was easy to diagnose by looking at the logs; our server provider was running an update in the background for a few minutes.
