### ISSUE TITLE
Allow paragraphs to break across columns (to avoid header / paragraph orphans)

### ISSUE THREAD

**Issue by akaddk** [naturalcrit/homebrewery#239]
It's not really a widow or an orphan but I couldn't find what it's called when a title is left behind and the paragraph body text is moved to the next column.

The only fix to this seems to be to use a div above the title to force it to the next column, but if you edit it later on above that div, you have to then go back and delete it so that there isn't a large gap between other body text.

Here's an example of what I mean:

https://i.imgur.com/2ZB6zEZ.png

https://i.imgur.com/CDj9zQE.png

So the body text, even though it's right underneath the title, is pushed into the next column, leaving the title behind. It happens with every title type from 2x# to 4x# so can be very frustrating.

**Comment by hvandesa** [comment]
I have this same issue.  In my case the orphan text is breaking to the next column really early leaving a large blank space at the bottom of the page for the first column.

**Comment by akaddk** [comment]
Yeah, it moves the entire paragraph to the next column so if the paragraph is larger than the space below the title, it'll move it, leaving a large blank space.

You have to manually split the paragraph at the right interval for the size of space after the title, or use a div to push the title down to the next column.

Which is fine for a static document, but if it's a living document it can be a real pain.

**Comment by stolksdorf** [comment]
Unfortunately, the css property [`break-after`](https://developer.mozilla.org/en/docs/Web/CSS/break-after) is not supported by Chrome, so there isn't a way for me to fix this.

**Comment by akaddk** [comment]
Ah, bum. Thanks anyway.

**Comment by stolksdorf** [comment]
It's a pain in the ass, but you can solved your problem by wrapping the header and paragraph in a div with a `break-inside:avoid` style.

```
<div style='break-inside:avoid'>
### Elminster
doot doot
</div>
```

**Comment by vlos** [comment]
Just as a note: MSWord doesn't even do this, so don't think we would want to try and solve it.

**Comment by Saikojin** [comment]
It is really unfortunate.  I am having the same case as @akaddk , where the title is halfway down the left column on a page and the text is on the right column.  Doing the workaround @stolksdorf suggested puts the title over to the right, which makes it look cleaner, however the big empty space is odd. 
![homebrewery_formatting](https://user-images.githubusercontent.com/16951298/37256546-7923f90a-2519-11e8-95c8-b444616a840e.png)

**Comment by ericscheid** [comment]
@Saikojin You have coded two lines of `<br>` between what look like paragraphs. This results in the so-called paragraphs to all be rolled together into one paragraph with some extra blank lines inserted. This mega-paragraph is now bigger than the space left at the bottom of column 1.

Remove those `<br>` between your "paragraphs" and they'll actually be rendered as individual paragraphs, and two or three will fit on the left column, with the remainer on the right.

Not that this addresses the OP issue.

**Comment by ericscheid** [comment]
`.phb h2, .phb h3, .phb h4, .phb h5 { break-after: avoid-column; }` is what we want, however this is currently unsupported in Chrome 86.

https://caniuse.com/mdn-css_properties_break-after_multicol_context_avoid-column

**Comment by Saikojin** [comment]
> `.phb h2, .phb h3, .phb h4, .phb h5 { break-after: avoid-column; }` is what we want, however this is currently unsupported in Chrome 86.
> 
> https://caniuse.com/mdn-css_properties_break-after_multicol_context_avoid-column

Thanks for the info and useful tool page :)

**Comment by calculuschild** [comment]
Another possible fix to this to remove
```
p {
  break-inside: avoid;
  -webkit-break-inside: avoid;
}
```

Which is preventing paragraphs from splitting across columns, even though this happens all the time in the PHB.

**Comment by Gazook89** [comment]
> Another possible fix to this to remove
> 
> ```
> p {
>   break-inside: avoid;
>   -webkit-break-inside: avoid;
> }
> ```
> 
> Which is preventing paragraphs from splitting across columns, even though this happens all the time in the PHB.

+1 to making this simple change; it's always been odd that paragraphs have been kept together.  This should be done with the release of v3 and only for v3.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
