### ISSUE TITLE
Mustache Div regex has exponential time for each CSS tag

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2393]
This line slows to a crawl when trying to type a space and then another character when there are 6+ separate CSS properties in a mustache div:

https://github.com/naturalcrit/homebrewery/blob/6ade9925d766ce592514d7ee1f3bebe521a417b2/shared/naturalcrit/markdown.js#L94

![image](https://user-images.githubusercontent.com/5878534/192078932-04f64133-9acb-42a3-99a5-3e848f54772f.png)

Something with this regex seems to be causing exponential slowdown with every added CSS property (five is instantaneous, six takes 1s, seven takes 5s, 8 takes 20+ seconds)

https://github.com/naturalcrit/homebrewery/blob/6ade9925d766ce592514d7ee1f3bebe521a417b2/shared/naturalcrit/markdown.js#L85

**Comment by calculuschild** [comment]
Catastrophic backtracking:

https://regex101.com/r/XyRxxl/1

**Comment by calculuschild** [comment]
Something like *this* seems to help by mimicking [atomic groups](https://blog.stevenlevithan.com/archives/mimic-atomic-groups)

`^ *{{(?:(?=(:(?:"[\w,\-()#%. ]*"|[\w\-()#%.]*)|[^"':{}\s]*))\1)* *$|^ *}}$`

**Comment by Gazook89** [comment]
> ^ *{{(?:(?=(:(?:"[\w,\-()#%. ]*"|[\w\-()#%.]*)|[^"':{}\s]*))\1)* *$|^ *}}$

Did you get a chance to test this in homebrewery, or just using something like regex101?  I test it in regex101 and it worked great, only ever 1 or 2ms wait, and no exponential growth.  So I tried putting it in HB and running it Chrome and hit the same crashing issue as the original regexp.  I simply replaced the regexp with your suggestion above, saved, and reloaded chrome--- if there are any other steps then I am not sure.

**Comment by calculuschild** [comment]
I only tested it with regex101. I assume it would work just as a drop-in replacement though. Did you apply it to both the curly Span and Div? I can't remember if the issue occurs just on Divs or not.

**Comment by Gazook89** [comment]
Yeah I just adjusted the inline span regex as well.  And I'm testing inline spans right now and not running into the crash at all.  So it's just a div/block issue.....?

**Comment by Gazook89** [comment]
Actually hold on....it was doing fine with spans, but i just started to *delete* some characters after the span and it's slowing up considerably.  It's a difficult thing to test, at least quickly...

**Comment by calculuschild** [comment]
Yeah, I don't recall at the moment... I should have just powered through and finished this when I had it all in my head at the time.

I *think* it was basically having difficulty at the step where the div becomes invalid by introducing a space, and the longer the string, the more steps the regex goes through to exhaust all options; the Spans don't have that issue since they allow spaces everywhere. But I could be mistaken if that was the actual issue.

**Comment by calculuschild** [comment]
Ah, we also use the regex to recognize spans/Divs to style then in the editor. What happens if you apply the fix to both places?  https://github.com/naturalcrit/homebrewery/blob/master/client/homebrew/editor/editor.jsx#L161

**Comment by Gazook89** [comment]
So I've replaced it in both files now, and don't see any improvement-- i still see the same observed behavior:

Observed:
- curly divs slowdown when many css properties are followed by a space and character
- curly spans slowdown when many css properties and one of the closing brackets is removed.
- curly spans *do not* slowdown when many css properties are followed by a space and character.
- curly spans, if you remove one of the closing brackets and then type it again, it results in 3 closing brackets.  The auto-closing is wonky (which is likely a totally different issue):    
  1. `{{color:red text}}`
  2. `{{color:red text}`  // remove last bracket
  3. `{{color:red text}}` // type `}` results in...
  4. `{{color:red text}}}`

For clarity, here is the regexp I'm using in each the Spans and Blocks:
Span:  `{{(?:(?=(:(?:"[\w,\-()#%. ]*"|[\w\-()#%.]*)|[^"':{}\s]*))\1)*|}}`
Block: `^ *{{(?:(?=(:(?:"[\w,\-()#%. ]*"|[\w\-()#%.]*)|[^"':{}\s]*))\1)* *$|^ *}}$`

Here is my branch on my fork with these changes.
https://github.com/Gazook89/homebrewery/tree/RegExp-Crash-in-Curly-Syntax

**Comment by calculuschild** [comment]
Hm. We may need some better regex then. Unless there's a third place the regex is running....

**Comment by Gazook89** [comment]
You or someone else should also give this a test when there is time, to be sure I'm not goofing something up and throwing false red flags.  And when better regexp is found, would it be worth pulling it out of those files and into it's own file in one place, then import where needed?  It's only two files (that we can think of) so probably not worth it...

**Comment by Gazook89** [comment]
> And when better regexp is found, would it be worth pulling it out of those files and into it's own file in one place, then import where needed?

Another thought along those lines....the 'guts' of the regexp for each of three types of curly syntax are essentially the same, right?  `/` `{` `(?:(?=(:(?:"[\w,\-()#%. ]*"|[\w\-()#%.]*)|[^"':{}\s]*))\1)*` `}}` `/g` for the *Injection*....could we define the guts separately, and then insert it inside whatever arrangement of brackets we need?
