### ISSUE TITLE
"Looks like there was a problem saving"

### ISSUE THREAD

**Issue by Whovencroft** [naturalcrit/homebrewery#2397]
Error: Forbidden

```
Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/Du_t6Sv73tAy"
}
```

**Comment by Gazook89** [comment]
@Whovencroft , were you able to save in the time since you reported this, or still sitting with the same issue?

**Comment by Whovencroft** [comment]
Ended up just copying the whole document to an external file and pasting it
back in after a refresh.  No time lost on my end and it saved fine after
the reload.  Just figured since it was asking to be reported that I should.

**Comment by Gazook89** [comment]
Okay that's no problem to report at all, we want to be sure things are reported in case there is a persistent issue.  Going to close this one out for now though.  Thanks!
