### ISSUE TITLE
[FEATURE]: Scroll Linking

### ISSUE THREAD

**Issue by dmmagic** [naturalcrit/homebrewery#241]
I'm not terribly familiar with Github, so I don't know where to suggest feature requests. Apologies if this is out of place.

It would be great if you could click a lock button to link the code on the left with the output on the right. So when you scroll to a page on the right, it moves to the appropriate section of code on the right -- and vise versa. And then you could click the lock again to unlink them for independant scrolling.

**Comment by stolksdorf** [comment]
I will probably not implement this. To do it well will be complicated and will probably lag the UI while scrolling.

**Comment by dmmagic** [comment]
Totally understand. Maybe something for the future. :)

**Comment by kilkwik** [comment]
If linking is complicated, is there a possible way to make a quick scroll hotkey... sometimes I get lost when I am looking through what I have created on the formatted side and i want to quickly find out where the code is written. Something that would generally take me to the right spot would be all I need. 

Since I am using Chrome, I'll usually try and cntl+f on a unique word that is on the right hand side, and then use the arrow keys to move to the right side. It's functional as a workaround. 

Clearly a P2/P3 request... but would probably save me some time considering I am working up something larger than a couple of pages. :)

**Comment by Gazook89** [comment]
5 year old issue, but requested again today on the reddit. Quick google search has [this SO question,](https://stackoverflow.com/questions/29255744/make-side-by-side-markdown-preview-scroll-with-its-editor) which contains a working [example of a markdown editor with live scroll linking](https://panwriter.com/).

There is also [Remarkable](https://github.com/jonschlinkert/remarkable), with fairly smooth scrolling.  [Live Demo](https://jonschlinkert.github.io/remarkable/demo/)

Also, this is similar to #846 or addresses the same basic problem (being lost in the source pane).

**Comment by calculuschild** [comment]
In my mind I imagine rather than smooth scrolling between the two, it would detect when you have entered the next page, and then the opposing view would glide into that position. That way we match page-by-page rather than trying to sync line-by-line if that makes sense.

**Comment by G-Ambatte** [comment]
Once the functionality for #2162 is in place, then I think we should be able to add a basic Scroll Linking feature, similar to that described here.

**Comment by dbolack-ab** [comment]
Do we want this to be

1.  a continuous scroll 
2.  a "Jump to my cursor hot key" ?  
3.  Both where a able to be toggled on and off?

Putting this on my radar for the release after next.

**Comment by Gazook89** [comment]
Certainly if doing (1), it should be able to be toggled. 

And to be clear what we have now:  There is the "jump to..." buttons, which either scrolls the Preview to match the page in the Editor which has the cursor in it, or scrolls the editor to match which page is in view in the preview.

We don't have a "scroll the preview to match the *page **visible** in the editor"  (and not sure we would).  But for me it's good to remind myself of what the current buttons do.

**Comment by dbolack-ab** [comment]
So it *sounds* like 3 is the choice. 

Adding a hotkey binding for the existing button in one PR then another for the toggleable scroll.

**Comment by calculuschild** [comment]
No hotkeys. Just the scroll sync.
