### ISSUE TITLE
Local - Google Auth / Service calls

### ISSUE THREAD

**Issue by JeremyVyska** [naturalcrit/homebrewery#2424]
### Renderer

- [ ] Legacy
- [X] v3

### Browser

Edge

### Operating System

Windows

### What happened?

Hallo,

I followed the Quick Start guide trying to get a local copy of Homebrewery running.  This results in an error on startup, since I've not configured my localhost to work with Google Docs.

```
> node server.js

Error: Must pass in a JSON object containing the Google auth settings.
    at AuthPlus.fromJSON (C:\homebrewery\node_modules\google-auth-library\build\src\auth\googleauth.js:298:19)
    at Object.<anonymous> (C:\homebrewery\server\googleActions.js:13:28)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (C:\homebrewery\server\homebrew.api.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
Please make sure that a Google Service Account is set up properly in your config files.
server on port: 8000
```

Additionally, when I try to use the local API to PUT changes to a Brew, I get Gaxios errors:

```
GaxiosError: Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.
    at Gaxios._request (C:\homebrewery\node_modules\gaxios\build\src\gaxios.js:130:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Any chance there can be a disabler wrapper around the various Google service calls?

**Comment by G-Ambatte** [comment]
Hey @JeremyVyska, I'm just trying to understand what the issue is here - the warning pops on start up but otherwise functionality should not be affected... However it seems that you're trying to use the local API to PUT changes to a brew? Can you share the details of the data included in that PUT request?

As I recall, the PUT requests are for updating existing brews so must include a brew ID, while a POST request is for creating a new brew so an ID is not required. However the ID is parsed to determine if it refers to a locally stored brew or one stored in Google Drive; this may be the cause of the issue that you're seeing.
If I can get some more information, I can attempt to dig further for you.

**Comment by JeremyVyska** [comment]
I mean, it is fair to say everything does work - despite saying Errors, it does continue to function.

For clarity, I downloaded Homebrewery to run locally, I'm using it based on the Quick Start setup, which does not cover (and I don't need) Google connectivity.  But, the application is not checking to see if I have or have not configured Google Drive integration before attempting to use it, so these appear.

Everything works (UI, API, etc), just the output log is super chatty about failed attempts to reach Google.

It could be that I'm also using it outside the intended use case - locally for myself, so I don't need Drive or Users.

**Comment by calculuschild** [comment]
We could probably set up a check if the required Google Drive API keys are not found (or some other config setting) we don't run any calls to Google. Might take some work since Google is not well encapsulated from the other code.

**Comment by Gazook89** [comment]
So in googleActions.js can we just log a different message if there are no `keys` returned after checking config.js?   

```
erver change detected: server/googleActions.js
  Restarting ./server.js
No Google Service Account in config files - Google Drive functionality will not function.
server on port: 8000

```

This greatly abbreviates the error message while still making it clear that google drive isn't setup, but doesn't lead someone to think they've actually made a mistake that needs to be fixed (to run locally).  

The current error would still display if there *is* a service account in config.js which isn't setup properly...and the full error message would be displayed.

This would be a huge improvement for me personally.  I have a PR for this #2528
