### ISSUE TITLE
Saving directly from Home Page does not use V3 renderer

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2427]
When a user clicks the blue "Save Now" button from the Home page, which now uses V3, the resulting saved document should also use V3. It appears this is not always the case, resulting in the users getting confused why their beautiful work is getting "scrambled" (turned into Legacy) when they hit that button.

https://www.reddit.com/r/homebrewery/comments/xy9en4/every_time_i_save_it_changes_my_homebrew_around/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by G-Ambatte** [comment]
Got it - `homePage.jsx`, the `save` function was ONLY sending the brew's text to be saved.

![image](https://user-images.githubusercontent.com/19826659/194730465-de7ccfda-94e4-4090-8359-e42c87cddd63.png)

This is resolved by sending the current state of the entire brew object to be saved.

![image](https://user-images.githubusercontent.com/19826659/194730491-1087ae75-2253-46de-9eb5-42998c143924.png)

PR incoming shortly.
