### ISSUE TITLE
Temporary save issues

### ISSUE THREAD

**Issue by asyncmeonov** [naturalcrit/homebrewery#2433]
Error: Service Unavailable

```
Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75346:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:75655:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/5nictPXqEqd1"
}
```

Saving functionality (to Google Drive) is restored shortly after but this error appears periodically.

**Comment by 5e-Cleric** [comment]
>The HyperText Transfer Protocol (HTTP) 503 Service Unavailable server error response code indicates that the server is not ready to handle the request.
>Common causes are a server that is down for maintenance or that is overloaded.

The server was probably too busy because of too many people sending requests, the better fix would be investing more in web server resources. As there are more recent cases of this, i'm closing the issue.
