### ISSUE TITLE
Images with position:absolute should not have margins applied

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2436]
### Renderer

- [ ] Legacy
- [X] v3

### Browser

Chrome

### Operating System

Windows

### What happened?

HTML images are being applied `margin-top`s when located after other elements that normally need space after. This becomes slightly annoying when images are absolutely positioned because it can throw off the expected `top: XX` positioning.

See: https://www.reddit.com/r/homebrewery/comments/y1auu2/images_getting_12_pixels_out_of_sync/

Not an issue if the images in question use Markdown because they end up getting wrapped inside their own `<p>` tag, which doesn't have the same margin rule.

May be possible to just remove all margins from images (at the cost of relative-positioned images getting shifted), or we could use a CSS attribute selector to just remove margins from images where `[style*=position:absolute]` or similar.

### Code

```gfm
#### Swift Striker
*Weapon (dagger), uncommon*
:
These two images should be positioned directly on top of each other, such that the tip of the dagger lines up in both cases. The top image (the shadow) is shunted downward by 12 pixels though because this paragraph is giving it a `margin-top`.

<img src='https://i.imgur.com/34kJJ5g.png' style='position:absolute; top:-155px; right:-95px; width:690px; filter:opacity(40%); transform:scaleX(-1)rotate(0deg);'>
<img src='https://i.imgur.com/QpQ41Kx.png' style='position:absolute; top:-155px; right:-95px; width:690px; filter:opacity(100%); transform:scaleX(-1)rotate(0deg);'>
```

**Comment by 5e-Cleric** [comment]
Yes, this should be fixed with the next CSS:

```
.page img[style*=position:absolute] {
   margin-top:unset;
}
```
This selector has a specificity [0,2,1], in case anyone wonders.

**Comment by 5e-Cleric** [comment]
i just realised, this is a legacy error, even so, the fix is right there, in case anyone needs it.
