### ISSUE TITLE
Let us choose a stable version of Homebrewery

### ISSUE THREAD

**Issue by lucastucious** [naturalcrit/homebrewery#2466]
### Your idea:

Hi,

I think it should be nice to have a beta/stable "branches" of the client. Or maybe some css changes should not be pushed to master directly (like d562308b6347d62010d8b895e9407139e51c6585 )

I'm working on a very large brew on a stable chromium build (no updates) to escape "Chrome decide to fuck everything again" and have a stable render/print workfkow.
All was fine until today. No update in the changelog, no warning, and my brew is fucked up.

I understand why you struggling to fight Google Chrome messy update, but i don't think we should follow the same path.

So, i think, for me but not only, it could be nice to have a "stay on this Homebrewery version until you finish the brew" button.

### Please confirm:

- [X] I have searched the Issues tracker for any duplicate requests and found none.

**Comment by calculuschild** [comment]
Thank you for the feedback!

It's unfortunate that changes from Google mean we have to adapt things along the way, but our recent changes were not intended to change anything other than account for Chrome's updated method of calculating table height.  Our updates *should* mean that your brews look the same as always whether you have updated Chromium or not. If you are seeing changes in your brew appearance, please give us more information (a link to your brew, screenshots pointing out the issue, etc.) so we can fix it for everyone. That would be extremely helpful in getting everyone back to the previous behavior.

That said, if you *really* don't want updates, I would direct you to just install a copy of the Homebrewery on your local machine. It takes a few steps, but you will have full control of if/when to receive updates. You can look at (our Readme)[https://github.com/naturalcrit/homebrewery#readme] for the steps.

At this time, running multiple versions of the application is something we just don't have the resources to do.
