### ISSUE TITLE
Spell List is Problematic

### ISSUE THREAD

**Issue by TheFreyNjord** [naturalcrit/homebrewery#248]
I'm experiencing an issue with The titles on the spell list. Because the spell list only increases the vertical when there needs to be more space, I run into the issue where the titles for a specific group of spells end up at the bottom of another groups list.

### Additional Details
I'm looking for a way to get it to go straight down then loop back at the top similar to the way it does at full vertical height, if that is possible.
**Share Link** :
http://homebrewery.naturalcrit.com/edit/SyeAEFPD7l
or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
CSS columns are really annoying to work with. There is currently no way to fix this. I should just remove the spell list snippet.

**Comment by TheFreyNjord** [comment]
I think it's great if you have a full table, but it's not so good if you don't. Instead I decided to use the regular table to suit the purposes I needed. I haven't done much HTML/CSS since freshman year, but I do remember the tables being annoying if you don't give them very specific instructions, so I don't blame you for them being stupid.

**Comment by ericscheid** [comment]
See #239 for general issue (css does not support needed selectors).

If necessary, add a `<br>` code to push the heading down (and thus into the next column with the spells.

Duplicate. Closing.
