### ISSUE TITLE
[Editor] Table of Contents - Whitespace removed between numbering and title

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2485]
### Renderer

- [ ] Legacy
- [X] v3

### Browser

Chrome

### Operating System

Windows

### What happened?

In the provided code, you can see that in the unstyled content titles, a space exists between the number `n` and the title `Test n`. In all cases where the title is styled, the resulting output strips the whitespace between the preceding number and the tag-wrapped title content.

I can see the following possible solutions to this issue:
1. Modify the ToC generation process so the number is wrapped in it's own tags, then add styling to create a gap of the same size as the whitespace.
2. Modify the ToC generation process to strip out all styling of content titles.

### Code

```gfm
{{toc
- [{{ 1 Test 1}}{{ 1}}](#p1)
- [{{ 2 *Test 2*}}{{ 1}}](#p1)
- [{{ 3 **Test 3**}}{{ 1}}](#p1)
- [{{ 4 ***Test 4***}}{{ 1}}](#p1)
- [{{ 5 Test 5}}{{ 1}}](#p1)
}}
```

**Comment by calculuschild** [comment]
Assuming this affects all old brews, simply changing the TOC generator will not solve the problem. I suspect this was introduced with #2438

**Comment by dbolack-ab** [comment]
Has this resolved by other means or was the suggested fix applied? 

 This is what I get pasting the above -

![HB_2485_2023_01_16](https://github.com/naturalcrit/homebrewery/assets/29744700/79823f60-5337-492d-9497-9714d5dec239)

**Comment by dbolack-ab** [comment]
Based on above, I am closing this as already fixed.

**Comment by calculuschild** [comment]
Did the fix actually get applied?
