### ISSUE TITLE
OG Metatags have duplicate entries for each route

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2497]
Possible opportunity for code cleanup. Following #2453 each route has its own OG Meta tags, but many of them are duplicated. May be worth creating a "default" object that each route can modify with its one or two unique values.

**Comment by Gazook89** [comment]
Further development of OG Meta tags could also include dynamic creation of the thumbnail:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/58999374/201382218-70eadf87-a496-4f20-88c2-d2958bba33c9.png">

CSS-Tricks uses [Social Image Generator](https://css-tricks.com/social-image-generator-jetpack/), though it seems it's availability is in question and likely we wouldn't to add "another thing".  But perhaps with HTML canvas this could be done in-house, if someone really wanted to go crazy.
