### ISSUE TITLE
Fix a few Markdown tests

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#2505]
I was just looking at some tests in `tests/markdown/mustache-span.test.js` and there are a handful with `FIXME` tags that seem like they are fixed.  "Testing" isn't something I've really looked at until now, so before I submit a PR to just clean these up I thought I'd check my work.  If I remember right, @AlexeySachkov is the person to talk about tests with.......?

```js
test('Renders a mustache span with text and class', function() {
	const source = '{{my-class text}}';
	const rendered = Markdown.render(source);
	// FIXME: why do we have those two extra spaces after closing "?
	expect(rendered).toBe('<span class="inline-block my-class"  >text</span>');
});
```

There are 4 or 5 similar tests that have the same or similar "FIXME" tags about extra spaces, and it looks like the expected result in the test has just been changed to match the undesired behavior rather than fixing whatever is causing the spaces.  But on the live site those extra spaces *aren't* present....so not sure how it passes this test since it is expecting the spaces to be there?

**Comment by Gazook89** [comment]
Hold the phone....I guess maybe the browser dev tools is just automatically removing those spaces so I think they aren't there.  But when I "fix" the test, it fails.  

Okay.

**Comment by AlexeySachkov** [comment]
Hi @Gazook89,

> I guess maybe the browser dev tools is just automatically removing those spaces

Yes, most likely this is what happening.

> There are 4 or 5 similar tests that have the same or similar "FIXME" tags about extra spaces, and it looks like the expected result in the test has just been changed to match the undesired behavior rather than fixing whatever is causing the spaces. 

My aim back than was to simply at least enable some testing and I decided that a couple of extra spaces which are not user-visible (i.e. they are in between tag arguments, not inside its "body") not require immediate bug fix. We might even decide that it doesn't worth fixing at all
