### ISSUE TITLE
Weird Text glitch/issue

### ISSUE THREAD

**Issue by Ultrachief** [naturalcrit/homebrewery#2511]
### Renderer

v3

### Browser

other

### Operating System

Windows

### What happened?

I've been having an issue where while I'm typing up a homebrew and I wanna go back to fix something when I delete a word and begin typing again the new text I'm typing just overrides the current text already there? I don't really know how else to explain it, it just types over what I've already typed instead of acknowledging the space between the new text I'm typing and the word or text I was trying to replace. It's been happening for the last two days or so, I haven't tried creating a new homebrew page maybe that will fix it? either way I figured id make a post about it to see if anyone knows what's wrong or if anyone else was having the issue.

**Comment by Ultrachief** [comment]
openned a new homebrew, seems to have fixed the issue. went back to the original page i was working on and it isn't happening there now either.

**Comment by ericscheid** [comment]
You might have triggered *overwrite mode* by pressing the <kbd>INS</KBD> key. Press it again to toggle it back.

IIRC, there might be another hotkey too.

**Comment by Gazook89** [comment]
Closing this since commenter mentioned they aren't having the problem any longer, and i suspect ericscheid was right.

If still an issue or it comes back, this can be reopened.
