### ISSUE TITLE
Account page show current Google auth status

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2520]
### Your idea:

The Account page only shows if the user has a Google ID linked to their account. It may be handy to also display if the connection is currently working. We get a lot of users who have used Google Drive in the past and the credentials expired, etc., so if we tell them to check their account page this could be handy.

- [ ] Display YES/NO if the auth check worked.
- [ ] If NO, display a link to the logout/renew credentials steps.

**Comment by G-Ambatte** [comment]
I was just looking into this, and I just discovered why the login date always seems to be the current time: if the account has a Google ID, then it performs a GoogleActions.js/authCheck, which updates the JWTToken, so the issued time is always the same as the page render time.

**Comment by G-Ambatte** [comment]
There is already an `authCheck` item passed to the AccountPage, however it appears that if the credentials have expired, the `auth.credentials.access_token` will exist, but attempting to list the files will fail...

I'll push a PR shortly.
