### ISSUE TITLE
styling {injector} is broken in Safari

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#2531]
### Renderer

v3

### Browser

Safari

### Operating System

MacOS

### What happened?

Loading any page causes Safari to fail incomplete.

An error in the console leads to this:
![image](https://user-images.githubusercontent.com/2605467/204827707-9fbf33b2-bb7e-4c4a-a190-ced8f39d36eb.png)

The source is https://github.com/naturalcrit/homebrewery/blob/ee05392d27ce76999b95bfb8f990d17a1e6d2b1a/client/homebrew/editor/editor.jsx#L142

The regex for styling `{injectors}` begins with a negative look-behind, but that is not supported in Safari per https://caniuse.com/js-regexp-lookbehind

Suggestion: this `(?<!{)` be changed to a non-capturing group `(?:[^{]?)` — that is, the `{injector}` pattern should be preceded with zero-or-one character which is not a `{`.

### Code

```gfm
# heading
{injector}
```

**Comment by calculuschild** [comment]
I suspect this needs to be "start-of-line or one non { character", rather than zero or one non { character.

**Comment by calculuschild** [comment]
See https://regex101.com/r/eRt9me/1

It's matching even though there are two `{`. This is because we are essentially matching "{, and then zero {, and then the rest of the tag"

You can do "start of line" with ^

**Comment by calculuschild** [comment]
We probably need something more like https://regex101.com/r/H674QD/1

**Comment by ericscheid** [comment]
d'oh, of course.

**Comment by Gazook89** [comment]
> /(?:^|[^{]){(?=((?::(?:"[\w,\-()#%. ]*"|[\w\-()#%.]*)|[^"':{}\s]*)*))\1}/gm

this captures the character before the injector as well.  For example, `Cat's eat Mice{sometimes}`....the style is applied to `e{sometimes}`.

**Comment by Gazook89** [comment]
I think this does it:

```js
const regex = /(?:^|[^{|\n])({(?=((?::(?:"[\w,\-()#%. ]*"|[\w\-()#%.]*)|[^"':{}\s]*)*))\2})/gm;
let match;
while ((match = regex.exec(line)) != null) {
    codeMirror.markText({ line: lineNumber, ch: line.indexOf(match[1]) }, { line: lineNumber, ch: line.indexOf(match[1]) + match[1].length }, { className: 'injection' });
}
```

[regex101 link](https://regex101.com/r/wo2yjX/1)

I'll put a PR up in a minute.
