### ISSUE TITLE
Let Table Of Contents auto-span columns

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2563]
### Your idea:

The default V3 Table of Contents is generated as:

```
{{toc,wide
...
}}
```

This is a 2-column setup, but the user has to manually break it into pieces to fit across columns due to this CSS rule:

```
.page li {
  break-inside: avoid;
}
```

That rule is nice for standard brew text because it prevents lists from breaking up unexpectedly, and you can always just start a new list in the next column if you have a really long one.  However with TOC, the list structure can get multiple levels deep and the multiple indents starts to interfere with `code block` syntax if you try to restart the TOC mid-list after a `\column`. 

Since TOCs are already wide and 2-column, seems it should just auto break? That is, add a rule:

```
.page .toc.wide li {
  break-inside: auto; //or unset
}
```

Relevant Reddit post: https://www.reddit.com/r/homebrewery/comments/znh9hu/how_do_i_add_another_column_into_the_table_of/

**Comment by dbolack-ab** [comment]
#3516 is completed and approved,  awaiting merger.
