### ISSUE TITLE
More font character

### ISSUE THREAD

**Issue by PiteGhoras** [naturalcrit/homebrewery#2579]
### Your idea:

Hello!
I love your homebrew editor. I'm from Hungary and a few homebrew what i want to create is need some special karakter:

Á   A with acute, decimal code: 193
É    E with acute, decimal code: 201
Í     I with acute, decimal code: 205
Ó   O with acute, decimal code: 211
Ö   O with diaeresis, decimal code: 214
Ú   U with acute, decimal code: 218
Ü   U with diaeresis, decimal code: 220
á     a with acute, decimal code: 225
é     e with acute, decimal code: 233
í      i with acute, decimal code: 237
ó    o with acute decimal code: 243
ö    o with diaeresis, decimal code: 246
ú    u with acute, decimal code: 250
ü    u with diaeresis, decimal code: 252
Ő   O with double acute, decimal code: 336
ő    o with double acute, decimal code: 337
Ű   U with double acute, decimal code: 368
ű    u with double acute, decimal code: 369

I would like to ask you add this character :)
I would really appreciate it, thanks in advance

**Comment by ericscheid** [comment]
1. codeblocks use `"Courier New", Courier, Monospace`
2. heading level 1 uses `MrEavesRemake`, with text transformed to uppercase
3. heading levels 2 through 4 use `MrEavesRemake`, with lowecase in the font drawn as smallcaps
4. heading level 5 uses `ScalySansSmallCapsRemake`, with lowecase in the font drawn as smallcaps
5. heading level 6 is not specifically styled by HB, so defaults to the paragraph font
6. paragraphs use `BookInsanityRemake`
7. tables use `ScalySansRemake`
8. art captions use `WalterTurncoat`, with lowecase in the font drawn as smallcaps

- **Courier New**: has all the glyphs 👍 
- **MrEavesRemake**: only U with acute is good in capitals, but áéíóöúü are good in lowercase, with double-acute characters having no glyph at all and so falling back to some other font
- **ScalySansSmallCapsRemake**: has upper and lowercase ÁÉÍÓÖÚÜáéíóöúü, but again double-acute characters have no glyph at all and so falling back to some other font
- **BookInsanityRemake**: has upper and lowercase ÁÉÍÓÖÚÜáéíóöúü, but again double-acute characters have no glyph at all and so falling back to some other font
- **ScalySansRemake**: has upper and lowercase ÁÉÍÓÖÚÜáéíóöúü, but again double-acute characters have no glyph at all and so falling back to some other font
- **WalterTurncoat**: has upper and lowercase ÁÉÍÓÖÚÜáéíóöúü, but again double-acute characters have no glyph at all and so falling back to some other font

Fixing ScalySansSmallCapsRemake, BookInsanityRemake, ScalySansRemake, WalterTurncoat should be relatively easy (clone the ÓóÚú glyphs, double the acute).

Fixing MrEavesRemake wil require more work, but we have a capital acute to model from, and the lowecase óú to work from for the double-acutes.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/2605467/210124798-c89516ce-d9e7-4108-9cf5-c26af8bc05ce.png">

**Comment by PiteGhoras** [comment]
Thanks for the tip!
