### ISSUE TITLE
Version mismatch notification and server-side forced refresh

### ISSUE THREAD

**Issue by jeddai** [naturalcrit/homebrewery#2583]
### Your idea:

So we ran into an issue when trying to deploy because of [this line in a PR](https://github.com/naturalcrit/homebrewery/pull/2561/files#diff-151ac071666591f897bb20db7bb7c4b5cb651281501f298362b9d45753400c37R234). TL;DR, we added a server-side check to make sure the version was up to date before saving. In doing so, we also added the version to the list of fields that is written back to the client on save. 

The problem with this, is many users don't refresh Homebrewery. So when this was deployed, we _immediately_ had thousands of the 409 errors. Normally we'd just let the users refresh and move on, but the error handling was _also_ in the client changes, so we would have gotten a ton of new github/reddit issues until everyone handled it. 

The solution to this moving forward isn't to stop making changes like this, instead I propose we add a few major features to Homebrewery which should solve this issue long term. 

The features are as follows:
- [ ] Send the version with the client data in its initial props, and have the client set a value for a particular cookie with that version
- [ ] Add a request handler (that triggers before others) to verify the version. 
  - If the version does not match, and this is a non-modification request (GET), then we set refresh headers to force a refresh.
  - If the version does not match and this is a modification request (PUT, PATCH, DELETE), then we response with a status code and error explaining how to resolve the issue. 
  
Best part about this one is since it's server-side, it doesn't matter if users have the new code or not, we can force a refresh so they get the new code.

**Comment by calculuschild** [comment]
Fixed by #2589
