### ISSUE TITLE
Homebrewery Not Saving

### ISSUE THREAD

**Issue by Flux008** [naturalcrit/homebrewery#2592]
### Error Code

```shell
Error: Internal Server Error


Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/zXWa5uuWmiqq"
}
```
```


### Your description of what happened:

It just gives an error that says "Opps! Looks like there was a problem saving. Report the issue here." Can't save any of the brews I have on the site. 
![image](https://user-images.githubusercontent.com/122311205/211390621-39dc915c-2fe5-4b75-a0bb-dcd992b8c10e.png)

**Comment by calculuschild** [comment]
Can you refresh the page and try again? We pushed out a small fix and you may need to reload the page to get it.

**Comment by calculuschild** [comment]
If this still isn't working you may have an old version of the Homebrewery site that is missing a recent update. If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery.  Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".
![image](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)


That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.
