### ISSUE TITLE
Cannot Save the Brew

### ISSUE THREAD

**Issue by FranAnEnbyFolk** [naturalcrit/homebrewery#2594]
### Error Code

```shell
Error: Internal Server Error


Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/qY7ygGzBvJ6Q"
}
```
```


### Your description of what happened:

I just cant save it, tried reloading and stuff but... not working

**Comment by calculuschild** [comment]
You have an old version of the Homebrewery site that is missing a recent update. If reloading the page didn't work, try Hard Refreshing the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery.  Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Refresh".

That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.
