### ISSUE TITLE
Saving to Google Drive on a Google Workspaces account

### ISSUE THREAD

**Issue by CherryNerd** [naturalcrit/homebrewery#2596]
### Error Code

```shell
Error: Internal Server Error


Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/TZ-5WAjA5P3Y"
}
```
```


### Your description of what happened:

After logging in and giving the rights, I tried to save and it crashed

**Comment by calculuschild** [comment]
You have an old version of the Homebrewery site that is missing a recent update. If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery.  Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".
![image](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)


That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.
