### ISSUE TITLE
Too many brews issue

### ISSUE THREAD

**Issue by ibminarik** [naturalcrit/homebrewery#2597]
### Error Code

```shell
Error: Internal Server Error


Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/j3BIgdoOJG1E"
}
```
```


### Your description of what happened:

Homebrewery only shows the 255 most recently edited brews. I've been able to get around this by editing the text file in google drive, then opening it up in homebrewery. Recently, though, when I try to edit files that have been modified in this way I get this error once they try to save.

**Comment by ericscheid** [comment]
> Homebrewery only shows the 255 most recently edited brews. I've been able to get around this by editing the text file in google drive, then opening it up in homebrewery. Recently, though, when I try to edit files that have been modified in this way I get this error once they try to save.

When you say "only shows the 255 most recently edited brews", is this on your user page, or in the "Recent Brews" menu?

<img width="322" alt="image" src="https://user-images.githubusercontent.com/2605467/211931689-2ab1cc02-54f1-47a7-b367-4d606aca69f9.png">

----

(This might be a quirk of the new version-checking code, which might be tricky)

**Comment by calculuschild** [comment]
You have an old version of the Homebrewery site that is missing a recent update. If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery.  Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".
![image](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)


That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.
