### ISSUE TITLE
File not saving

### ISSUE THREAD

**Issue by ghost** [naturalcrit/homebrewery#2598]
### Error Code

```shell
Error: Conflict


Error: Conflict
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76355:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76664:10)
{
  "status": 409,
  "method": "PUT",
  "url": "/api/update/HseJMcecy3Hv"
}
```
```


### Your description of what happened:

I tried to save my file for the custom homebrew Dungeons And Dragons Campaign I am creating, but it is not saving.

**Comment by calculuschild** [comment]
You have an old version of the Homebrewery site that is missing a recent update. If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery.  Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".
![image](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)


That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.
