### ISSUE TITLE
Disfunctional Brew

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#2603]
### Your description of what happened:

My brew saves a different copy of itself into drive every time i press save.
Here is a look at my google drive:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/91662974/212320114-b12125e6-d5f8-47cf-81d2-f82513ba76ce.png">
As you can see the file is triplicated, however, the first file is different:
<img width="153" alt="image" src="https://user-images.githubusercontent.com/91662974/212320241-d10ff8e1-5625-4c2c-8a86-ee37f77b5a3c.png">
This is missing from the first file, that and the edited markdown are the only difference.

Also, in my user page, i can't see this brew's views:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/91662974/212320704-cf0037b6-603c-4a47-9c73-47faf87546f8.png">

**Comment by calculuschild** [comment]
Do you see all three versions in your user page?

**Comment by 5e-Cleric** [comment]
I just opened it again, i have 4 versions of it, two published, and two unpublished.

I'm guessing the error caused the metadata of the brew to dissapear, and so HB created a new brew each time i saved, that could also explain why i can't see the view count on the original.

This is the [document](https://homebrewery.naturalcrit.com/share/1WfXgNoC4BvZcSn1Is7kZkp_eYroRZLXNhiY6cxRaB4Qh) itself.

**Comment by 5e-Cleric** [comment]
Opened my user page and i can see the view count, but i don't know if i should delete all of them or just all except one
