### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by Pololokka** [naturalcrit/homebrewery#2630]
### Error Code

```shell
Error: Precondition Failed


Error: Precondition Failed
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 412,
  "method": "PUT",
  "url": "/api/update/He8Sgkbyg2K3"
}
```
```


### Your description of what happened:

This error happened thrice in a row when autosaving.
The brew is 10 pages long, and I'm using the legacy renderer

**Comment by calculuschild** [comment]
You have an old version of the Homebrewery site that is missing a recent update. If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery.  Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".
![image](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)


That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.

**Comment by Pololokka** [comment]
It worked, thanks!
