### ISSUE TITLE
Saving problem

### ISSUE THREAD

**Issue by tahagoktekin16** [naturalcrit/homebrewery#2632]
### Error Code

```shell
Error: Precondition Failed


Error: Precondition Failed
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 412,
  "method": "PUT",
  "url": "/api/update/aJz6fVxa8CI8"
}
```
```


### Your description of what happened:

My homebrewery page stuck and it does not save the file. When I enter the page or reload the page it always goes back.

**Comment by calculuschild** [comment]
You have an old version of the Homebrewery site that is missing a recent update. This should only happen once, and then in the future you will receive a better error message explaining what is going on.

To get the update, go ahead and copy your brew text elsewhere temporarily as a backup, then reload the page. Your brew should be back to where you left it, and the website should now say "v3.6.0" in the upper left.

If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery.  Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".
![image](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)

That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.

**Comment by tahagoktekin16** [comment]
> You have an old version of the Homebrewery site that is missing a recent update. This should only happen once, and then in the future you will receive a better error message explaining what is going on.
> 
> To get the update, go ahead and copy your brew text elsewhere temporarily as a backup, then reload the page. Your brew should be back to where you left it, and the website should now say "v3.6.0" in the upper left.
> 
> If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery. Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload". ![image](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)
> 
> That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.

Thanks for the help. I copied the brew text to a new one and it worked. Old brew still has this problem but the new dont. And old brew was already v3.6.0.

**Comment by calculuschild** [comment]
If the old one still has issues, would you mind sharing the "Share" link to is and we can investigate if something has broken?

**Comment by 5e-Cleric** [comment]
OP coming back to answer is not likely, closing issue.
