### ISSUE TITLE
Can't save (after installing an extension on chrome ?)

### ISSUE THREAD

**Issue by Suzor-Antonin** [naturalcrit/homebrewery#2633]
### Error Code

```shell
Error: Precondition Failed


Error: Precondition Failed
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76373:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76682:10)
{
  "status": 412,
  "method": "PUT",
  "url": "/api/update/rel3xUkI2HS6"
}
```
```


### Your description of what happened:

I did nothing really special, I was editing a file, and now I can't save.
I usually have autosave on, this specific time I deactivated it.

I just tried on another homebrew and it doesn't work either.

The only thing I see that could have done something (I don't know the specifics) is that I installed the beyond20 extension.

**Comment by calculuschild** [comment]
You have an old version of the Homebrewery site that is missing a recent update. This should only happen once, and then in the future you will receive a better error message explaining what is going on.

To get the update, go ahead and copy your brew text elsewhere temporarily as a backup, then reload the page. Your brew should be back to where you left it, and the website should now say "v3.6.0" in the upper left.

If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery.  Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".
![image](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)

That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.
