### ISSUE TITLE
Version Error

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2641]
### Error Code

```shell
"This brew has been modified on another device."
```

### Your description of what happened:

Manually initiating a save sometimes results in the error "This brew has been modified on another device." Repeating the manual save works correctly and the error disappears.

I suspect this is due to the auto-save being in progress when the manual save is initiated, resulting in two calls to the save function with the same internal version number. The error does not seem to occur when triggering two manual saves in close proximity.

![image](https://user-images.githubusercontent.com/19826659/214685488-bb2c9bcd-adc7-4d4b-9cef-0136c7f2bb9e.png)

**Comment by 5e-Cleric** [comment]
So, a solution could be to prevent use of the manual save button until receiving an answer, "there already is a saving action in progress"

i think the biggest issue is that error telling users it is being saved in another device, that can be misleading.

**Comment by calculuschild** [comment]
I agree with @5e-Cleric .

**Comment by G-Ambatte** [comment]
That might be the issue - I tend to trigger a manual save with Ctrl-S, which may be skipping the "save in progress" check. I'll look into it some more when I'm in front of my computer again.

**Comment by G-Ambatte** [comment]
Found it - https://github.com/naturalcrit/homebrewery/blob/62d193ddd17b2282d58aaaf4041fce56e5ceda6c/client/homebrew/pages/editPage/editPage.jsx#L95 cause Ctrl-S to call `this.save()`, not `this.trySave()`. `this.trySave()` would cancel the function if a save is already in progress.

Simple fix, change `this.save()` to `this.trySave()`. I'll make the change, test it, and assuming it works correctly, drop a PR later tonight.

**Comment by 5e-Cleric** [comment]
> and assuming it works correctly, drop a PR later tonight.

You did not drop the PR, should i close this issue?

**Comment by G-Ambatte** [comment]
It took a while to come back to this one, but I believe that I've got it working correctly now. I'll drop a PR shortly.
