### ISSUE TITLE
My Homebrew page won't load at all.

### ISSUE THREAD

**Issue by sutton1990** [naturalcrit/homebrewery#2655]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

Tried to access my Homebrew page to refresh my memory on it as I haven't checked it in a while and when the page finishes loading I am left with nothing but a white blank page.
![homebrewery issue](https://user-images.githubusercontent.com/38590399/216096950-8615df6d-3516-47b1-9e3d-3fe5f1b241ec.png)

**Comment by 5e-Cleric** [comment]
I can open that link just fine, could you try a hard reload?
You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery. Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".
![image](https://user-images.githubusercontent.com/91662974/216101067-44b224e0-ed26-419c-8d2b-7de93810bd1e.png)

If this didn't change anything, could you check if the console shows anything?  (press F12)

**Comment by sutton1990** [comment]
> If this didn't change anything, could you check if the console shows anything? (press F12)

The console clued me in to one of my extensions blocking the page, so I added it to the exceptions list and it's working now. Thanks for the help.
