### ISSUE TITLE
NodestoCapsCondensed font not working

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#2663]
### Renderer

v3

### Browser

Chrome

### Operating System

MacOS

### What happened?

I can't seem to use the font `NodestoCapsCondensed` in my brew.  It's a default font, the woff2 is in the correct spot when viewed in the repo, and the `fonts.less` points to it. But `font-family: NodestoCapsCondensed;` does not work.

Digging in the dev tools (Chrome tools, which I'm less familiar with than with FF) I see in the "Sources" tab --> Filesystem --> styles.css this:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/58999374/216864098-c6515221-92ce-4787-a2c1-0768a572652d.png">

It shows the NodestoCapsCondensed portion of the styles, but not the same directory as all of the other fonts?  For reference, this is what the other fonts show:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/58999374/216864396-75849055-8d3a-4689-9023-93939645a22c.png">

**Comment by calculuschild** [comment]
@5e-Cleric created a PR that fixed the path for this font just a few days ago, and it's new merged into master.

https://github.com/naturalcrit/homebrewery/pull/264

Are you using the latest master?

**Comment by Gazook89** [comment]
Ah sorry, I was just using the live site.  Closing.
