### ISSUE TITLE
Unable to delete coauthored brew

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#2674]
### Renderer

Both

### Browser

Chrome

### Operating System

Windows

### What happened?

When trying to delete a brew with multiple authors, the current author should simply be removed from the list of authors. This appears to not be working, as reported on Reddit:

https://www.reddit.com/r/homebrewery/comments/113eoz7/cannot_remove_myself_from_a_brew_with_multi/

I was able to confirm this by adding myself as an author to the same brew and trying to delete it. The user page refreshes but the database remains unchanged.

**Comment by G-Ambatte** [comment]
I suspect that Mongoose is not detecting that the array has been modified - see https://sarav.co/understanding-markModified-in-mongoose.

The solution may be to add `brew.markModified(authors)` after the `authors` array is changed.

**Comment by calculuschild** [comment]
That could be. The other thing I was thinking is when we retrieve the brew with `api.getBrew()`, the response is no longer a Mongo object, so `brew.save()` does not do anything.

Get brew (not a mongo object)
https://github.com/naturalcrit/homebrewery/blob/7ea3ef84741fd6a55ec97c8bb9e65452560274b1/server/homebrew.api.js#L284

We eventually get the mongo object, but just merge it onto the JS object, so we still don't have a Mongo object
https://github.com/naturalcrit/homebrewery/blob/7ea3ef84741fd6a55ec97c8bb9e65452560274b1/server/homebrew.api.js#L300

Then we save using a plain JS object, which does nothing.
https://github.com/naturalcrit/homebrewery/blob/7ea3ef84741fd6a55ec97c8bb9e65452560274b1/server/homebrew.api.js#L322

**Comment by G-Ambatte** [comment]
> That could be. The other thing I was thinking is when we retrieve the brew with `api.getBrew()`, the response is no longer a Mongo object, so `brew.save()` does not do anything.
> 
> Get brew (not a mongo object)
> 
> https://github.com/naturalcrit/homebrewery/blob/7ea3ef84741fd6a55ec97c8bb9e65452560274b1/server/homebrew.api.js#L284
> 
> We eventually get the mongo object, but just merge it onto the JS object, so we still don't have a Mongo object
> 
> https://github.com/naturalcrit/homebrewery/blob/7ea3ef84741fd6a55ec97c8bb9e65452560274b1/server/homebrew.api.js#L300
> 
> Then we save using a plain JS object, which does nothing.
> 
> https://github.com/naturalcrit/homebrewery/blob/7ea3ef84741fd6a55ec97c8bb9e65452560274b1/server/homebrew.api.js#L322

This is exactly what is done in the `updateBrew` function, which does work - line 300 is identical to line 265: https://github.com/naturalcrit/homebrewery/blob/7ea3ef84741fd6a55ec97c8bb9e65452560274b1/server/homebrew.api.js#L265

**Comment by G-Ambatte** [comment]
Oh, I might have found the issue... If the author is the last one in the array, then they are not removed because the array only overwrites the elements in the array - and the new array is shorter than the previous save.

**Comment by G-Ambatte** [comment]
Deleted myself (the first author) and spotted this:

![image](https://user-images.githubusercontent.com/19826659/219490036-af62e16d-28c4-4305-a558-f8c0f97cd4b8.png)

**Comment by G-Ambatte** [comment]
Confirmed, being any position except last works to remove the author but causes a duplicate element in the saved array (the element previously in position 6 is now in position 5 AND 6), and if the author is in the LAST position then the array in the saved data is unchanged.

**Comment by G-Ambatte** [comment]
Adding `brew.markModified('authors');` to `homebrew.api.js` on line 322 appears to fix this from testing so far. Intention is to add a comment that this is necessary to make the array update properly.
