### ISSUE TITLE
CSS Layers issue in 3.6.1 update -- Broke some formatting

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#2679]
### Renderer

Both

### Browser

Chrome

### Operating System

MacOS

### What happened?

After the 3.6.1 update today there were some reddit and discord reports of broad style issues:

1. **[Monster Stat Block Table -- Legacy -- Reddit](https://old.reddit.com/r/homebrewery/comments/115msuu/error_with_stats_on_statblocks_on_v361/)**

| [Original brew](https://homebrewery.naturalcrit.com/share/xmv1ItRPncmQ) | [Backup copy](https://homebrewery.naturalcrit.com/share/vvINaT2g7Q8x) |
|:--|:--|

I think this boils down to a poor CSS selector in the Style Editor at the outset.  The brew tries to set the table row background color like this:
```css
.phb table tbody tr:nth-child(odd) {
    background-color: #c8d9d8;
    background-blend-mode: luminosity;
}
```
The complaint is that with the 3.6.1 update suddenly the stat tables in the monster blocks were getting a background color as well.   This is happening because of how table styling is normally applied first to *all* tables on a page, and then later monster stat block tables are given a more specific rule that sets the table row colors to `transparent`.  With the update, this *more specific* targeting of stat block tables is buried under the new CSS Layer of the Style Editor....and the users custom defined table styling is applied to *all tables* again without a monster stat block specific rule in that top layer.

3. **[High amount of custom styling -- Legacy -- Reddit](https://old.reddit.com/r/homebrewery/comments/115mzk4/361_update_changed_legacy_formatting/)**

| [Original brew](https://homebrewery.naturalcrit.com/share/R0sUixM7lwIj) | [Backup copy](https://homebrewery.naturalcrit.com/share/HGPTeqAB9VzH) | [Screenshots](https://imgur.io/a/QuN7kOI)
|:--|:--|:--|

I think this one can trace it's issue to the fact that many of the font sizes are set to percentages in the Style Editor.  So each font has it's size tied to the font size of the parent element.  The user did this all the way to the `.page` element which was itself set to `font-size: 100%`.  When I removed the `font-size` property of `.page` the brew pretty much returned to normal.

4. **[General report, no info](https://old.reddit.com/r/homebrewery/comments/115o3lz/la_pagina_no_me_carga/)**

5. **[v3 Monster stat block abilities - V3 - Discord](https://discord.com/channels/113801089362558983/950919905266507806/1076589178420203622)**

From Discord, someone pointed out that the Actions/Abilities in stat blocks gained extra spacing:

![image](https://user-images.githubusercontent.com/58999374/219898978-a6581174-d379-4615-a9f5-5182a82138b7.png)

This is the difference in styles (using the Staging site to test the 3.6.1 update):

|  3.6.1 CSS Layers |  pre Layers |
|-----|----|
| <img width="366" alt="image" src="https://user-images.githubusercontent.com/58999374/219899004-381b2955-e4fb-4908-ab5b-7c981abdd8e1.png"> | <img width="366" alt="image" src="https://user-images.githubusercontent.com/58999374/219899016-3b1e0ed9-47e5-46b6-a696-8150ab9132cf.png"> |

**Comment by Gazook89** [comment]
for the v3 monst stat block issue above, I think `.page .blank` just needs to move from the Blank layer to the 5ePHB layer?  Because with the update the `.page p+*` is overriding it.

**Comment by calculuschild** [comment]
Ah. Ok. We probably need to leave .blank in the Blank layer since that layer is the base of all the V3 themes, and that's what enables the `::::` syntax which should always be available for v3.

Instead we can probably just update the monster block to specifically ignore .blank elements or something.

**Comment by 5e-Cleric** [comment]
Closing this issue, we are very far from v3.6.1
