### ISSUE TITLE
mug image on home page is `http`

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#2687]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

The mug image in the example brew of the home page content is specified with an `http` url, not `https`. 

<img width="861" alt="image" src="https://user-images.githubusercontent.com/2605467/220793948-1e6a0cd9-72fc-426b-9bc9-ce1a036c9c77.png">

A warning appears in the console:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/2605467/220793767-0bd9e2b9-5965-42d4-8089-68cc7cb338e6.png">

## Solution: 

edit the url to use `https`

### Code

```gfm
![homebrew mug](https://i.imgur.com/hMna6G0.png) {position:absolute,bottom:20px,left:130px,width:220px}
```

**Comment by G-Ambatte** [comment]
`/client/homebrew/pages/homePage/welcome_msg.md` line 39:

![image](https://user-images.githubusercontent.com/19826659/220794308-2870a32f-cc48-4a09-b7cb-8f77187449c8.png)

Solution: change `http:` to `https:`
