### ISSUE TITLE
Login on locally running version does not work

### ISSUE THREAD

**Issue by jendave** [naturalcrit/homebrewery#269]
I run Homebrewery locally without any issues except when I try to login. I get re-directed to the NaturalCrit.com login page. Should the login process be self-contained? I login into the Natural Crit page and I get re-directed to my local copy but the login has failed. How do I create logins locally?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Good point. I'll have to add a dummy login page. Maybe next time I add some features. This isn't super high priority though

**Comment by granack** [comment]
this would be great. I don't actually need a user, it could actually just go to a sort of generic user page that lists all the brews in the database. or list users to select, without a password.

**Comment by JoshBrodieNZ** [comment]
Just ran into this, figured I'd chip in in case others wind up on this page. If folk are looking for a means of logging in, consider setting the JWT cookie manually, which seems to work so far for me (I'll report back if I run into issues with this approach.)

By default, the secret used to sign the token is the string "secret". I use CyberChef for quick access to a JWT signing interface (https://gchq.github.io/CyberChef/#recipe=JWT_Sign('secret','HS256')&input=ewogICAgInVzZXJuYW1lIjogIkFkbWluIiwKICAgICJpc3N1ZWQiOiAiMjAxOC0xMC0wMVQwOToyNzo1OC45MjBaIgp9).

Then, in my local version of homebrewery, I set the cookie "nc_session" to the resulting token using JavaScript "document.cookie=...". In this case, with the username "Admin" the token is "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaXNzdWVkIjoiMjAxOC0xMC0wMVQwOToyNzo1OC45MjBaIiwiaWF0IjoxNTM4Mzg2NjA1fQ.aFkl54Osmnez_C51Z9D1h75BzMLKvJH0uwAQylNvIHg". Setting this and refreshing results in the brews I create being attributed to "Admin".

**Comment by G-Ambatte** [comment]
While PR #2052 will add a local only login system, it is worth mentioning that this system does not (currently) allow for local logins to be linked to Google Drive.
Given the complexity of the configuration outside of Homebrewery that is required to achieve this, I suspect that the value of creating a login system that links to Google Drive is very limited.
