### ISSUE TITLE
Invisible images in monster stat blocks

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#2753]
| Renderer | Browser |  Operating system |
|:-----------|:---------:|:--------------------:|
| v3            | chrome  | windows                |

Images inside monster blocks with position set to absolute are rendered behind the background.

Z-index is set to -1 for all images in pages, which is causing the error.

Two possible fixes for this:

- Set z-index: 0; to all images inside blocks;
- Set the [isolation property](https://developer.mozilla.org/en-US/docs/Web/CSS/isolation) for blocks, which determines whether an element must create a new [stacking context](https://developer.mozilla.org/en-US/docs/Glossary/Stacking_context).

May be fixed by #2754

**Comment by 5e-Cleric** [comment]
just opened a brew and works fine, ill gather more info and come back

**Comment by calculuschild** [comment]
Isolation may cause other issues, since there are a few cases where we use `::before` and `::after` pseudoelements to draw graphics below the parent element (the "magic circle" decoration on Class Tables for example).

**Comment by 5e-Cleric** [comment]
Yeah, commented that on gitter but forgot to update this, z-index it is then.

I believe this would be best:

```
.page .block {
  z-index: 0;
}
```

which will override both rules:

<img width="139" alt="image" src="https://user-images.githubusercontent.com/91662974/230227203-05b8b6f8-3d82-47c6-97c7-47b489a0fec6.png">

making images go on top of blocks if they are inside of them. Unfortunately, that also places them over text.

**Comment by 5e-Cleric** [comment]
fixed in #2754
