### ISSUE TITLE
Bookmarked link not working

### ISSUE THREAD

**Issue by Sebofthesebs** [naturalcrit/homebrewery#276]
One of my larger brews is no longer working. Both the edit and share links are returning "Can't get that".

Is there any way to get my brew back?

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/r1GH5Rbkl

**Comment by vlos** [comment]
What would be a nice feature would be to "Save" the source of the Markdown document to a local file.

**Comment by ericscheid** [comment]
See #548
