### ISSUE TITLE
Landing page needs an update

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#2787]
Info in the Landing page is somewhat outdated, this issue is meant to keep track of such changes.

E.G.: "Anyone with the edit url will be able to make edits to your homebrew, so be careful about who you share it with."
That is no longer true, and should speak of multiple authors.

**Comment by 5e-Cleric** [comment]
Will be making changes in this brew:

https://homebrewery.naturalcrit.com/share/eVg6SA0tLAeT

Changes made:

- Edit info updated
- Changed Subject from I and Me to Us and We ( The team)
- New V3! --> that old legacy mode
- Adding DOMT collab into the info
- Updating old html tags into fresh markdown syntax

**Comment by 5e-Cleric** [comment]
Issue merged into #2816, new progress will be tracked there.

**Comment by calculuschild** [comment]
Reopening so we have a space to hold discussion specific to this issue until it is resolved.
