### ISSUE TITLE
Class Table

### ISSUE THREAD

**Issue by darkzomb** [naturalcrit/homebrewery#279]
Hi, I am new to this.  But I found your site very easy to use.  The one problem I seem to have is concerning class tables.  The Background Image of the table does not seem to fit table, and the table barely fits on the page.  Is there a way to adjust this issue?

Thanks!

J

### Additional Details

**Share Link** :
http://homebrewery.naturalcrit.com/share/By7BOcl8l
or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
![image](https://cloud.githubusercontent.com/assets/387742/21786719/5c1834b4-d693-11e6-96d1-d3414ac843e1.png)

It looks fine to me? What are you expecting?

**Comment by darkzomb** [comment]
Sorry, I am a new user. Hadn't coded before.  I hadn't found the preview yet, I had only seen the editing view.  

Thanks so much though!

**Comment by stolksdorf** [comment]
They should look identical. If not, there's a problem

**Comment by darkzomb** [comment]
Well, on my laptop, it all looks squished into the right column, and the data spills over the table background to the edge of the page.  However, this does not occur when I look at it on my phone, where it appears as your photo above.

**Comment by stolksdorf** [comment]
Are you zoomed in on any of your browsers? And are you using Chrome?

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @darkzomb
