### ISSUE TITLE
i can't save my hb.

### ISSUE THREAD

**Issue by Jabf13** [naturalcrit/homebrewery#2798]
### Error Code

```shell
Error: Forbidden


Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76477:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76786:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/nvTON-TZy-vs"
}
```
```


### Your description of what happened:

![image](https://user-images.githubusercontent.com/131619260/233864331-101f0168-60d0-481a-bf3a-59cfefcbd8d4.png)

**Comment by calculuschild** [comment]
Our logs show Google saying that "The user does not have sufficient permissions for this file."

Have you possibly changed the sharing settings for that file on your Google drive? Have you tried signing out and then back in using the "sign in with Google" button to refresh your credentials with Google?

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Jabf13
