### ISSUE TITLE
Problem Saving

### ISSUE THREAD

**Issue by Anerakk** [naturalcrit/homebrewery#2800]
### Error Code

```shell
Error: Internal Server Error


Error: Internal Server Error
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76477:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76786:10)
{
  "status": 500,
  "method": "PUT",
  "url": "/api/update/Fu1SwTSvSTM3"
}
```
```


### Your description of what happened:

I don't think I did anything specific. Was just writing, though I was using a lot of headers.

**Comment by 5e-Cleric** [comment]
You have an old version of the Homebrewery site that is missing a recent update. If reloading the page didn't work, try Hard Reloading the page. You can do this by pressing CTRL + SHIFT + R at the same time while at the Homebrewery. Alternatively, you can open up the Chrome Developer Console (Right-click on the page and choose "inspect"). This will add some options to the refresh button if you right-click it. Again, choose "Hard Reload".

![img](https://user-images.githubusercontent.com/5878534/211833455-7cc8f1d0-c7fd-40da-a110-3c900e33f283.png)

That should force Chrome to check for an update to the Homebrewery. Let us know if that doesn't work.
