### ISSUE TITLE
[FEATURE]: Brew navigation features

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#2812]
### Your idea:

Had the idea of trying to bring some of the features from pdf viewers to here, mostly for the share page, but also for the editor:

- [x] Page navigation (page by number input)
- [x] Zoom?
~- [ ] Sticky notes/comments~
~- [ ] Reading text out loud (might be too big of a feature)~
- [x] change view (page wide, one full page, multiple pages)

**Comment by calculuschild** [comment]
Zoom and page navigation could apply to edit page and share page.

Change view maybe.

Notes and reading out loud I think fit better just in a PDF reader.

**Comment by 5e-Cleric** [comment]
> Notes and reading out loud I think fit better just in a PDF reader.

share page IS a PDF reader, if not in name at least in functionality.

**Comment by calculuschild** [comment]
I have to disagree. The Homebrewery displays a document similar to a PDF viewer, but the Homebrewery and a PDF viewer have different purposes.

For example, you normally can't visit someone's blog and start adding sticky notes all over it, or expect a blog to have text-to-speech. You would get separate programs or browser extensions to do that for you.

If people want access to those types of features, a PDF viewer would already have them. It's not hard to just print the PDF and open it in Adobe Reader to start adding sticky notes or have it read out loud.

**Comment by Gazook89** [comment]
Also, text-to-speech may not work well if a brew isn't laid out well (as in, the html structure is poor).  It is likely that browser extensions exist that can speak selected text (or maybe a whole iframe?).  But in any case, I agree with Calc on this one.

**Comment by 5e-Cleric** [comment]
Working on this right now, i started with a UI similar to that used in the filter options in userpage:

![image](https://github.com/naturalcrit/homebrewery/assets/91662974/772c8a7e-906e-4aeb-938b-29bc9e01e7aa)

**Comment by 5e-Cleric** [comment]
Page navigation and zoom figured out in #3499, change view will be more complex, and left for later, if done.(would need to use zoom as well, which would get in the way)

**Comment by 5e-Cleric** [comment]
#3665 will do the rest

**Comment by 5e-Cleric** [comment]
Multiple pages view is the only thing left, i can give it a try. i know i have achieved it before with just css.

**Comment by Gazook89** [comment]
I have this pretty much done in a PR. I was holding it until the other zoom things were done, and they are, so I can push this up when I get a chance tomorrow

**Comment by 5e-Cleric** [comment]
Closing this issue as resolved, we can keep track of multiple pages in its original issue, #1379
