### ISSUE TITLE
WYSWIG editor like in Obsidian

### ISSUE THREAD

**Issue by T3sT3ro** [naturalcrit/homebrewery#2825]
### Your idea:

I understand that it would require a lot of work to pull of, but something like a WYSWIG editor in Obsidian for editing the text in place. The editor/visualization split would be replaced by a visualization preview only, where clicking on a paragraph/element on a preview would open an inline textbox with an underlying markdown text.

It could be implemented as a separate view mode. Some considerations would have to be made to account for layout shifts.

**Comment by Gazook89** [comment]
There is a similar app that was called [Norn and is now called Scribe](https://scribe.sauriel.net/) that you can take a look at.

**Comment by Gazook89** [comment]
I'm going to close this in favor of a discussion topic: https://github.com/naturalcrit/homebrewery/discussions/2879 or https://github.com/naturalcrit/homebrewery/discussions/2878
