### ISSUE TITLE
Crediting you

### ISSUE THREAD

**Issue by leedsl** [naturalcrit/homebrewery#283]
I really like this product. It has so freed up my time for manual making. Sooo,  I'd like you to include a preset markdown (if that's what you call it) that I can click that automatically puts your credit in the format you'd like it to be. Is the bottom of the last page okay? Maybe you even have a logo you'd like to see displayed. 

You deserve it.

**Comment by stolksdorf** [comment]
Thanks man! Neat idea. I'll probably add a 'credits' snippet in the next version.

**Comment by Gazook89** [comment]
[Here are a few thoughts, along with 'fan content policy' snippet.](https://homebrewery-stage.herokuapp.com/share/Xn4Xo_qPLdrY)

**Comment by 5e-Cleric** [comment]
Adding to this, using the books as inspiration:

Preview vs PHB:
<div style="display:grid;grid-template-columns:1fr 1fr;">
<img width="347" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/bb4fcf4f-7461-49a9-87ff-21b38c3e38b7">
<img width="387" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/91662974/5873ac99-5056-4844-a521-e5a5085245da">
<div>

We could include the HB logo too.
Could be used in combination of the options mentioned by @Gazook89

**Comment by Gazook89** [comment]
Just a note, “learning” should just be “learn”

**Comment by 5e-Cleric** [comment]
I assume this is waiting to resolve #2779 - Branding and identity, if not, we could agree on one of the already proposed solutions.
