### ISSUE TITLE
Add more information to "Brew is Open on Another Device" error

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#2866]
### Your idea:

A [user on reddit](https://old.reddit.com/r/homebrewery/comments/140u7nj/cannot_save/) recently posted about not being able to save because they were bumping into the error "Brew is open on another device", but didn't understand what that meant (or rather, they didn't think it was open on another device).  Another user suggested:

> am I right that the version is the info buried in the 'share' source's embedded json, at .brew.version (alongside various other brew and internal metadata)?
>
> Perhaps it could be useful to reveal that version number as info in the properties tab, and/or the "brew has been changed on a different device" error could provide the additional '.brew.updatedAt' information (translated to human-readable form? - eg "brew has been changed on a different device (6 minutes ago)"

**Comment by G-Ambatte** [comment]
Triggering a manual save (via the `Ctrl + S` shortcut) seems to cause the save to be re-attempted and eventually go through... I have a habit (of yet to be determined alignment) of hitting Ctrl+S often, which I believe can both cause and cure the version mismatch issue.

**Comment by G-Ambatte** [comment]
Once PR #3024 is merged, we might be able to look at adding this information to the error notification.

**Comment by 5e-Cleric** [comment]
This is the 503 error that keeps getting logged as issue saving, sometimes is as simple as a busy server, i think we could relieve some of the pressure on the server by changing the autosave time from 3s to 5s after stopping writing, or auto-saving in localStorage and triggering a save to db every 5 minutes or when closing window, what do you think?

**Comment by calculuschild** [comment]
Actually, we already merged the PR to fix this, so I'm going to close this issue.

**Comment by 5e-Cleric** [comment]
> This is not the 503 error. It has a unique error code 409.

Then we need to improve the error popup for the 503 error, and i don't think we have an issue for that.
