### ISSUE TITLE
"Looks like there was a problem saving"

### ISSUE THREAD

**Issue by Cryxok** [naturalcrit/homebrewery#2883]
### Error Code

```shell
Error: Forbidden


Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76481:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76790:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/shTVOZYNcKJ1"
}
```

### Your description of what happened:

I've been having problems saving some of my documents for about a week now. When I try to save, either manually or using the Auto-Save function, an error message appears saying "Looks like there was a problem saving". 

It has happened on both of my laptops, one running Windows and the other Kubuntu. I use Google Chrome on both. Some documents have this issue, but not all of them. All of the documents I've tried saving on have been created using V3.

**Comment by calculuschild** [comment]
Our logs say that Google is unable to save your brew because your Google Drive storage is too full.

**Comment by Cryxok** [comment]
> Our logs say that Google is unable to save your brew because your Google Drive storage is too full.

Freed up some space and is working now, thank you!
