### ISSUE TITLE
Issue Saving

### ISSUE THREAD

**Issue by gwr918** [naturalcrit/homebrewery#2932]
### Error Code

```shell
Error: Forbidden


Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76537:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76846:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/kQQXKtd2qJ7I"
}
```
```


### Your description of what happened:

I had the website up overnight and when I came back it was having an issue saving even after refreshing the page.

**Comment by calculuschild** [comment]
Google is telling us "user does not have sufficient permissions for this file."

Are you still able to access your Google drive normally? Make sure you can find this file in a "Homebrewery" folder there.

Also try signing out and then back in missing the "sign in with Google" button to refresh your Google credentials.

**Comment by calculuschild** [comment]
@gwr918 just wanted to verify whether you were able to resolve this issue. If we don't hear from you I will assume it as resolved and close this.

**Comment by gwr918** [comment]
Hey, yeah, sorry. I had changed the sharing properties on the document to
restrict it but I changed it back and it works fine now thank you!
