### ISSUE TITLE
Folding Code Button

### ISSUE THREAD

**Issue by Moth-6** [naturalcrit/homebrewery#2956]
### Your idea:

According to the documentation the folding code feature already exists and can be activated using the shortcut "Ctrl + [" and "Ctrl + ]"
this shortcut doesn't work on some keyboard layouts for example german keyboards.
i propose to have a button that can fold and unfold the code, so that it would be universally and globally available. 
This would significantly improve the readability of code and improve user experience. 

Another alternative is to have all shortcuts customizable but i would imagine that feature would be more complex and need more time implementing.

**Comment by Gazook89** [comment]
Excuse my ignorance, but what is it about the pair that prevents this hotkey?

**Comment by 5e-Cleric** [comment]
Same goes for spanish keyboard, and not only for brackets, we also can't make `Ctrl` + `/` , the shortcut for a comment.

I never used shortcuts, so i didn't thought to mention it.

For reference i attach the [full list of shortcuts](https://homebrewery.naturalcrit.com/share/1Em9UpHcoKws3xv65lWCRGzPDr3xPAWzvp9-Fp6cxI0Ac).

**Comment by G-Ambatte** [comment]
Shortcut remapping is an interesting idea; although I believe that there are a few blocking issues that would need to be resolved first.

In the interim, we might be able to expose the functions to a snippet menu? Another interesting concept that will require further investigation.

**Comment by calculuschild** [comment]
I agree for now I think just adding some buttons to the menu would be a good start.

**Comment by Gazook89** [comment]
Could this largely be solved by adding a toolbar at the top of the editor, like is commonly found in text editors?  A portion of the hotkeys are for simple things like bolding, italicizing, creating a list, etc.  Something like 'fold all code' could be included as well.

<img width="1154" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/58999374/b6f80642-7b41-4ab3-9bd8-f6085d31c03a">

I wouldn't be surprised if there is a handy codemirror extension that does at least some of this, but ultimately it's just a toolbar with buttons linked to the existing hotkey methods.  Not every hotkey would go into this bar, only the ones relevant to the editor input.

**Comment by 5e-Cleric** [comment]
Here is what i think, from all those options we should start from the ones we already have available, so:

- Undo and Redo might be moved to this new bar
- text color , font size, font family, text-align, can all be done inserting a snippet with the necessary code
- Bold, italics and underline should insert the appropiate syntax for each, we could even add a bold italics option, to make it easier for us.
- link and image options working like snippets but without content, both going for the content or alt property.
- line spacing could be a select that outputs a mustache block with the syntax too
- inserting `ol` or `ul`, easy.
