### ISSUE TITLE
ModHeader breaks the save routine??

### ISSUE THREAD

**Issue by crogonint** [naturalcrit/homebrewery#2974]
### Error Code

```shell
Error: Service Unavailable


Error: Service Unavailable
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76537:19)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at xhr.onreadystatechange (https://homebrewery.naturalcrit.com/homebrew/bundle.js:76846:10)
{
  "status": 503,
  "method": "PUT",
  "url": "/api/update/9NtH3-Ofq60x"
}
```
```


### Your description of what happened:

With ModHEader enabled (with the anti-WebP script), I can repeatedly either cause this error, or crash the whole page out to a white screen. Viewing the page source says something about there being an error so I was logged off. Let me know if I can be more help. :)

**Comment by crogonint** [comment]
Stupidly, I started working on rebuilding my brew with modheader turned on. I was pasting in the links for the chapter background images when the whole page crashed to a white page state. Looking at the source code says:
{"message":"Request for image at this URL is not supported"}
..and that's it.

**Comment by G-Ambatte** [comment]
We have some custom middleware that blocks image requests to the website; it's the only way to get to this error message - a GET request to a `https://homebrewery.naturalcrit.com` address.

**Comment by crogonint** [comment]
It's this one. This is a temple with default content, and I'm slowly filling in the foor information:
https://homebrewery.naturalcrit.com/share/Ho3aHkpFm-LX

I don't think it's the document itself, though. I have a very simple script in the ModHeader extension that (is intended to tell servers that my broswer doesn't support WebP files. It's the only reliable way I've found to get serveers to give me original image files, instead of lower quality WebP files. The script changes the Request header "accept" to:
application/json, text/plain, */*
I have verified that that is the ONLY thing that it is changing.

Sorry, I didn't grab a screenshot. It was honesty just a blank page with what I stated above. I have to run an errand right now, I'll try to replicate it when I get home. The pattern that I am seeing is that I can reliably do SOMETHING to the Homebrewery interface every time I paste an image link in to the code. Sometimes I get a white screen, sometimes it crashes the auto-save.. 

The time before the original crash above happened, it crashed to a white screen and said that it logged me off due to an error. THAT crash caaused me about a week of work on the above document, Because apparently the save routine was mucked up for the last week and I didn;t know it. It's possible that I had two tabs with the same document open at one point, because the save from two days ago is in a state from a week ago, with a rough draft of the first paragraph. I had food related content added up to about chapter 6 when it crashed. SO much typing. At one point, I had to undo a WHOLE bunch of times to copy and and paste some content off a previous page that had accidentally gotten deleted, then I clicked redo until it returned to the current state and pasted it back in. I SUSPECT it saved the document in the undo state from a week ago, and crashed out the auto-save routine when I clicked redo a few dozen times, but I can't say for sure.

**Comment by G-Ambatte** [comment]
My initial suspicion is that this is a false lead - a `503 Service Unavailable` is usually a server issue. However, the reported ability to replicate is concerning.

I have recreated the ModHeader extension rule, but haven't yet been able to replicate the reported behaviour with a clone of the brew:
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/1897865c-4490-4e43-a54d-f21d99087b17)

**Comment by crogonint** [comment]
What I reported above is what is getting reported as being sent in the request header under accept, (when I click "Test my Headers" in ModHeader).

The line of "script" ini my  profile is:
image/avif,image/apng,image/svg+xml,image/,/*;q=0.8

My apologies, I should have been more specific above. When I was checking that initially, we were concerned that there might be something messing with authentication. I don't THINK so.. but I don't have access to the server logs to say for sure. ;)

**Comment by crogonint** [comment]
![Homebrewery error](https://github.com/naturalcrit/homebrewery/assets/23371790/1e8694ad-168e-4142-8afb-44869e81caee)

..and I replicated the error for you, and grabbed a screenshot. :)

**Comment by G-Ambatte** [comment]
Ah, I see what's happening.
The Accept headers are being applied to every single request - including ones that should be return `text/json` or other types.

The image blocking middleware looks at every acceptable response type, and if they are all image formats, then the request is blocked. Because this is happening on _every_ request, the whole website is effectively not served.

Add `text/json` to the start of your Accept string, which will bypass the "all image formats" checks, and you should see everything return to normal. Alternatively, disable the ModHeaders extension for `https://homebrewery.naturalcrit.com` because we don't serve images directly, and if you want a copy of any of the images in the highest resolution possible, it can be downloaded directly from the GitHub project.

**Comment by crogonint** [comment]
Interesting! I grabbed that script er.. string.. off of a place that specifically said to use it to stop websites from trying to serve WebP files. I wonder why nobody else edited it to add the text/json to it?

Anyway, I've done as you suggested (added the text and excluded Homebrewery). I successfully added one link without it crashing to a white screen, so we're off to a good start! Sorry to be a bother. If you guys have any success recovering a useful version of that brew, do let me know. I'm dreading have to type all of that out again. :S

..still not totally about the error when it logged me out, but since the ModHeader issue DID mess up the auto-save routine, we can probably write that off as being ModHeaders fault as well.

**Comment by G-Ambatte** [comment]
If the brew is stored on your Google Drive, you can use their versioning system to recover previous versions of your document.
Unfortunately, we don't have the storage space to do the same for brews that are stored in the internal Homebrewery database, and even less available space for anything in local storage (still in the `/new` page).

**Comment by calculuschild** [comment]
I've already checked our HB backups for the last couple days, but its in the same state. I'll try going back further tonight, since he has mentioned in a Reddit chat to me that he has been working on this for multiple weeks. Perhaps I can find some partial text.

**Comment by calculuschild** [comment]
I communicated with the user via Reddit. Unfortunately even going day by day through the backups up to the day the file was created, there is only one paragraph written and no other changes.

**Comment by G-Ambatte** [comment]
I think we're safe to close this one now.
