### ISSUE TITLE
Add snippet to change column flow

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#2982]
### Your idea:

The following snippet of code is often used to change the way elements flow within columns in user's brews - commonly due to their browser not supporting column flow in the same way or extent that Chrome does (e.g. Firefox).

Adding this snippet would allow us to redirect users having these issues to an "trusted and official" Style snippet, rather than "copy and paste this code into your document" which should only carry all the trust one would normally associate with talking to a stranger over the Internet.

```
.page .columnWrapper {
  column-fill: auto;
 }
```

**Comment by calculuschild** [comment]
Is there any way we could just build in the correct behavior so Firefox users don't need this in the first place?

**Comment by G-Ambatte** [comment]
`@-moz-document url-prefix() { [...] }` is apparently a universal Mozilla detector media query, so we could change add the following to the default page styling:

```
@-moz-document url-prefix() {
    .page .columnWrapper {
        column-fill: auto;
    }
}
