### ISSUE TITLE
SRD Monster list in Homebrewery

### ISSUE THREAD

**Issue by vlos** [naturalcrit/homebrewery#300]
stolksdorf,

I have created a web page (javascript) which displays each of the SRD monsters in Markdown format.

http://miniworld.com/adnd/generators/monsterListBrewery.html

If you want to grab the code and add it to your app, you are more than welcome, though obviously you would need to adjust the selection to something that is more fitting to your app.

Note: some monsters need cleanup and I will try to get around to them (they still have HTMl mixed in).

Vlos

**Comment by stolksdorf** [comment]
Looks great! That's a really cool idea. I might have to take a deeper look at what other parts of the SRD I could mix in.

**Comment by vlos** [comment]
Well spells could be a good idea, other than that not sure how much you would want to .
I am working on a NPC generator, which could be possibly added.

**Comment by dbolack-ab** [comment]
Proposal - spin this out into an auxiliary tool that is responsible for pulling the database results and spits out results as variables. This can then be pasted into the document and used with any Monster layout Snippet that knows the variable names.

Should be able to do the same for spells, etc.

**Comment by G-Ambatte** [comment]
There was some discussion of that in PR #2132, with mention that we don't really need a NaturalCrit tool as there are existing sites for exactly this purpose. There was also some discussion of using an `API fetch` call to retrieve the data from [DnD5EAPI](https://www.dnd5eapi.co) or similar sites.

I did start to build a NC specific tool anyway, but then the OGL drama blew up and I lost all taste for the project.

**Comment by calculuschild** [comment]
I will point to https://www.monstershuffler.com/ which already provides all the SRD monsters in Homebrewery markdown format (both Legacy & V3), in addition to a GUI for creating and sharing custom stat blocks.

**Comment by 5e-Cleric** [comment]
> I will point to https://www.monstershuffler.com/ which already provides all the SRD monsters in Homebrewery markdown format (both Legacy & V3), in addition to a GUI for creating and sharing custom stat blocks.

Then i see no problem in closing this issue as solved. Should add said tool in our resource lists.
