### ISSUE TITLE
CSS Clean Up

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3012]
### Your idea:

Some styling in the Blank and 5ePHB theme stylesheets is duplicated. We should work through the theme stylesheets and eliminate any duplicate styling from the 5ePHB styling (unless we deliberately want to keep it for clarity).

I expect that this clean up will also be required on all other theme styling.

- [ ] 5ePHB
- [ ] 5eDMG
- [ ] Journal

**Comment by ericscheid** [comment]
I'm not sure that *duplication* is a dire problem, per se. I'd be wanting to avoid any unnecessary dependencies, and to also honor the possibility that some "duplication" is actually simply contemporaneous/ephemeral coincidence.

**Comment by G-Ambatte** [comment]
I think it comes down to a question of "Exactly HOW blank is Blank?" Either the styling exists for _every_ page (and thus exists on the Blank page) or it's theme specific and thus is declared only in the theme's own CSS.

**Comment by ericscheid** [comment]
I would posit that the "blank" styling would be a minimalist black & white form. Sufficient that headings can be distinguished from each other and paragraph text, that tables can be recognised as being tables and not some accidentally arranged blocks of text, etc.

There are various "normalize" or "reset" stylesheets floating about — some of them go too far though, rendering all text (i.e.even headings) to be the same size/weight. Anything that has `body, p, h1, h2, h3 {font-size: 100%}`. Hmm .. [a bit of googling suggests](https://stackoverflow.com/questions/6887336/what-is-the-difference-between-normalize-css-and-reset-css) I'm recommending a "normalize" stylesheet, and _not_ a "reset" stylesheet

At best, it might be useful as the theme/style for https://homebrewery.naturalcrit.com/account and other (very) basic UI.

It shouldn't have any rules set up for book-specific constructs, such as descriptive notes, stat blocks, etc.
