### ISSUE TITLE
Class Tables decoration

### ISSUE THREAD

**Issue by bf5man** [naturalcrit/homebrewery#302]
I've [recreated the circle](https://drive.google.com/file/d/0B5pNrOK9NG98ZWRTODEyRURZUDA/view?usp=sharing) we can see partly hidden [behind the Class tables ](https://s-media-cache-ak0.pinimg.com/736x/76/0e/d0/760ed0061511bc763471fe28752e18bb.jpg)in the PHB. You are free to include it in the tool if you want to (I can also provide the SVG file if you prefer). 

Also, setting `.phb h4 {font-weight: 400}` gives H4 titles a bit closer to what we can see in the PHB. 

Thanks!

**Comment by stolksdorf** [comment]
Thanks for the heads up!

**Comment by calculuschild** [comment]
Hey there @bf5man ! Do you still have the file for this? We are *finally* in a position to start adding in a lot of these features that have been sitting around for years.

**Comment by Gazook89** [comment]
[Here you go](https://i.imgur.com/xYVVT7e.png)

It's on my Imgur, but if you want to host it elsewhere I have the original png too.   Imgur doesn't seem to have shrunk it or anything, though, and keeps good quality at a reasonable size.

**Comment by Gazook89** [comment]
Disregard the bit about adding as a :before pseudo-element; I forgot z-index doesn't work well with pseudo-elements.  And I also reasoned that users will want to have more flexibility in positioning and thus works better as a background image (perhaps the bg image snippet should use this image instead?).

**Comment by 5e-Cleric** [comment]
@bf5man Do you still have the original file? was this created in vector form?
