### ISSUE TITLE
Ah! I can't find a Log out button!

### ISSUE THREAD

**Issue by SurrealAsh** [naturalcrit/homebrewery#303]
My friend logged in to my computer, and now I can't log out. Is this intentional? If not, where could I find the log out? Thanks!

**Comment by dmmagic** [comment]
If you deleted your cookies, it will log you out. Other than that, I don't see a logout button either.

**Comment by stolksdorf** [comment]
Yeah that was an oversight on my end. There's a logout button [here](http://www.naturalcrit.com/login). There will be a logout button on the userpage in v3.

**Comment by vlos** [comment]
Will the login be fixed for local copies?

**Comment by stolksdorf** [comment]
Yup, I've build an entire self-contained login system for v3 for development/local versions of the project.

**Comment by G-Ambatte** [comment]
Has anyone been able to find stolksdorf's self-contained login system for local installs? Or do we just go ahead and start from scratch?

**Comment by G-Ambatte** [comment]
Recording this so it is easily found for future reference:

From stolksdorf's v3 branch:-
I believe that this the login code: https://github.com/stolksdorf/homebrewery/blob/v3/server/dev.routes.js
This seems to be where a JWT token is generated for local use, although it doesn't seem to have any authentication check. Whether there *should* be a password authentication required for purely local use is another question entirely.

Logout is here: https://github.com/stolksdorf/homebrewery/blob/v3/shared/homebrewery/account.actions.js
The cookies are reset for both NaturalCrit.com and local use; I'm not certain that this is desirable behaviour.

It shouldn't be difficult to wrap these into a module and only load the fucntions when `process.env.NODE_ENV != 'production'`.
