### ISSUE TITLE
Add Darkbrewery editor theme

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3034]
### Your idea:

Now that the basic CodeMirror theme functionality is in place, we can extend that functionality to add our own themes.

I suggest that we start with the Darkbrewery theme, which has been popular on the subreddit.

DarkBrewery styling is as follows:
```
@-moz-document domain("homebrewery.naturalcrit.com") {
body {
    ;
}

/* Main BG color and normal text color */
 .CodeMirror {
    background: #293134;
    color: #91A6AA;
}

/* Brew BG */
 .brewRenderer {
    background-color: #29313;
}
/* Blinking cursor */
 .CodeMirror-cursor {
    border-left: 1px solid #e0e2e4;
}
/* Bars at the top */
 .snippetBar {
    background-color: #2F393C;
    color: white;
}
nav {
    background-color: #293134;
}
nav .navItem {
    background-color: #293134;
}
.snippetBar .snippetGroup .dropdown {
    background-color: #2F393C;
}
/* Line number stuff */
 .CodeMirror-gutter-elt {
    color: #81969A;
}
.CodeMirror-linenumber {
    background-color: #293134;
}
.CodeMirror-gutter {
    background-color: #293134;
}
/* column splits */
 .editor .codeEditor .columnSplit {
    font-style: italic;
    color: inherit;
    background-color:#1f5763;
    border-bottom: #299 solid 1px;
}
/* Colors for headings and such */
 .cm-s-default .cm-header {
    color: #c51b1b;
    -webkit-text-stroke-width: 0.1px; 
  	-webkit-text-stroke-color: #000; 
    /* ###Headings */
}
.cm-header, .cm-strong {
    font-weight: bold;
    color: #309dd2;
    /* bold points */
}
.cm-s-default .cm-link {
    color: #dd6300;
    /* Link headings */
}
.cm-s-default .cm-string {
    color: #aa8261;
    /* links */
}
.cm-s-default .cm-def {
color:#2986cc;
}           /*@import*/
.cm-s-default .cm-variable-2 {
    color: #3cbf30;
    /* Bullets and such */
}
.editor .codeEditor .block {
    color: #e3e3e3;
    /* blocks */
}
.editor .codeEditor .inline-block {
    color: #e3e3e3;
    /* inline blocks */
}
.cm-s-default .cm-tag {
    color: #e3ff00;
    /* Tags (divs) */
}
.cm-s-default .cm-attribute {
    color: #e3ff00;
}
.cm-s-default .cm-atom {
    color:#000;
}
.cm-s-default .cm-qualifier{
    color:#ee1919;
}
.cm-s-default .cm-comment{
    color:#bbc700;
}
.cm-s-default .cm-keyword {
	color:#c302df;
    background-color:#b1b1b1;
}
.cm-s-default .cm-property.cm-error {
	color:#c50202;
}

.CodeMirror-foldmarker {
	color:#f0ff00;
}

.editor .codeEditor .pageLine {
    /* New page  */
  background: #000;
    color:#000;
    border-bottom: 1px solid #fff;
}

.cm-s-default .cm-builtin {
	color:#fff;
}

}
```

**Comment by 5e-Cleric** [comment]
I haven't updated that theme since Dec 2021, it may need some changes, if you need anything just ask.

Aditional info, the @moz-document rule doesnt' work without extra help, in this specific case, stylish uses some script to support it in chrome. It wouldn't be needed anyway.

**Comment by G-Ambatte** [comment]
My thinking was that we could offer users a native option now, rather than needing to install an extension for the custom editor CSS. We could expand on this to include multiple DarkBrewery themes, e.g. `DarkBrewery v1` for the original extension CSS, `DarkBrewery v3.0.1` for the current version, and `DarkBrewery vX.XX` for any future revisions.

**Comment by G-Ambatte** [comment]
The color for the BrewRenderer has a typo: 

```
/* Brew BG */
 .brewRenderer {
    background-color: #29313;
}
```

From some of the adjacent lines, I assume that the `#29313` should be `#293134`.

**Comment by 5e-Cleric** [comment]
> We could expand on this to include multiple DarkBrewery themes, e.g. `DarkBrewery v1` for the original extension CSS, `DarkBrewery v3.0.1` for the current version, and `DarkBrewery vX.XX` for any future revisions.

The reason 3.0.1 was made is because V3 was new, and the old theme did not change those styles, the old theme is no different from the new one, just outdated. I don't think we want variations, just updates.

But yes, the ability to release new themes by ourselves would be great.

**Comment by 5e-Cleric** [comment]
Our own icons for snippets do not work like the font-awesome ones, because of that, do not change color with darkbrewery, this should be an easy fix for that:

```
.snippetBar .fac {
    filter: invert(1);
}
```

**Comment by G-Ambatte** [comment]
I've applied this fix now - this is the only theme that also targets the Homebrewery nav bars; we may wish to replicate that styling on all dark editor themes.
