### ISSUE TITLE
Correct permissions on co-author's userpage

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3036]
Other authors of a brew should be able to access the edit link of a brew or remove themselves from a brew as authors ***via another author's Userpage.***

Also, unpublished brews should be visible in the authors' Userpage if the user logged in is an author too.

**Comment by calculuschild** [comment]
I'm pretty sure all of these are already true. Are you seeing something different?

**Comment by ericscheid** [comment]
> I'm pretty sure all of these are already true. Are you seeing something different?

Yes.

This is what I see on my userpage, but Chanaranach does not get the pencil or trash icons when they view _my_ userpage.

<img width="703" alt="works for me, not for him" src="https://github.com/naturalcrit/homebrewery/assets/2605467/eaf227dc-752d-4994-9397-0632d1bfda14">

He also has a brew in his unpublished collection of which I am a co-author. When I view _my_ user page it does appear, but when I view his userpage it does not (the entire section for "Chanaranach’s unpublished brews" is not rendered).

<img width="347" alt="this works" src="https://github.com/naturalcrit/homebrewery/assets/2605467/c197c77c-2708-4c93-b048-1ab1906543ef">

<img width="766" alt="this doesn't" src="https://github.com/naturalcrit/homebrewery/assets/2605467/23432406-d096-4186-90f7-1586c4da2e86">

**Comment by calculuschild** [comment]
Ah, I misinterpreted this. @5e-Cleric you are wanting to edit brews *from the other author's userpage*. (added emphasis to your post to distinquish this).

I don't know if I agree with this. Sounds to me like a source of confusion and worry for users. ("Why can I edit other peoples' files? Can random people edit *my files*!?").

**Comment by 5e-Cleric** [comment]
> I don't know if I agree with this. Sounds to me like a source of confusion and worry for users. ("Why can I edit other peoples' files?

Authors would know they are not other people's files, but their own co-authored brews

**Comment by calculuschild** [comment]
> Authors would know they are not other people's files, but their own co-authored brews

I don't think this would be as obvious as you seem to think.

Further, this would go against the known and standard behavior for other document-collaboration apps. For example, If I were looking at another person's Google Drive folder, my only option is to view or copy the file. I can't just start editing. If that person shares a file with me to edit, I still have to open it from my own Google Drive page.


> Other authors of a brew should be able to access the edit link of a brew or remove themselves from a brew as authors via another author's Userpage.

I'm not sure I really *why* would a user want to go dig through a different person's account to edit a file? Why not just do it from your own account page?

**Comment by G-Ambatte** [comment]
I believe it's a case of "I have permissions on this document, why is it that I can only edit it from this specific page?" A solution could be as simple as popping a notification at the bottom of the screen that shows "BREWS IN VIEW MODE ONLY" so there's no potential expectation that a user can access a shared brew through one of the other author's user pages.
