### ISSUE TITLE
lockout on homebrewery

### ISSUE THREAD

**Issue by d3k4-k3rb3r0s** [naturalcrit/homebrewery#3072]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

I understand that a github issue tracker isnt necessarily the place for this but I didnt see any "forgot password" or "contact" functionality over on homebrewery. I have an old account (nipha333) that I can no longer get in to because I cant fathom the password after a two year break from homebrewing, and also have lost the email. Idk how else I would verify, but I can list the projects on the account, published and not, can point to where some of them have been published by me on DM's guild, can even show you pictures of original handwritten notes for the projects on the account. 

I really need to get back in.. the "Vespanus of Roe" document itself is over 30 pages, with images, etc. There are two class documents that have around 30 pages average as well.. for me to copy paste the pdf result back into an editor and reformat it... would be insane.  Plus, those classes still need heavy editing. Further, there are several projects that I dont even have in PDF form because they werent anywhere near ready for even playtesting.

projects include

bow of cala narain
wandslinger duelist class
potioneer class
Scale of Khalkos
Slingers Reservoir
Jar of Jorasco
Scourge of Jolan
Tome of Knowing of Alura Alouecia
Tome of Knowing of Dario la'Barra
Tome of Knowing of LIlly Greenbottle
Paper Dragon Patron
Paper Dragon Patron V2
Wandslinger subclass
Wand Patron (?)
Vespanus of Roe: Planar Architect

A couple are on DMsGuild under the name "brother dekatessera"

d3k4_k3rb3r0s@protonmail.com

and more

**Comment by 5e-Cleric** [comment]
You have been contacted with instructions to reclaim your account, as soon as you do, be sure to close this issue.
