### ISSUE TITLE
Add Share link to "Not an Author" error page

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3086]
### Your idea:

It is not uncommon for users to post their Edit page details when they intend to post their Share page information instead - this happens often when newer users are requesting support, and don't necessarily understand the difference between the two. Currently, we block Edit links on the subreddit, harking back to the days when anyone with the Edit link could access and change the brew content, but now that Authors have been enforced, it is no longer an issue.

What I suggest is that we maintain the existing error message, but incorporate a method in which the Share link for a brew can be accessed or derived from that page, primarily for support reasons.
Alternatively, we could develop some other method - perhaps using the oft overlooked Admin pages, only accessible to elevated users - to retrieve a brew's Share ID from the Edit ID to assist in troubleshooting.

**Comment by Gazook89** [comment]
It could show the error and auto redirect on 10 seconds to share page

**Comment by calculuschild** [comment]
> It could show the error and auto redirect on 10 seconds to share page

I tend to not like auto-redirects on error pages. Makes it that much harder for the user to figure out what went wrong or report the issue.

However I agree it might be helpful to provide the share link somewhere.

**Comment by 5e-Cleric** [comment]
I disagree with this idea, the share link should only be available, IF PUBLISHED = TRUE, thoughts?

**Comment by ericscheid** [comment]
Thoughts .. there's an author that has provided a link to the brew to another person, but they've provided the `/edit` link and not the `/share/` link. 

That's looks like intent (although maybe they did want to provide the edit link, but just forgot to add them as an author first).

The UI message is very clear what to do in the second case. Showing the `/share/` link on this page also supports the other case. Pity the poor author that posts a non-published brew to some forum with intent to share .. but then gets slammed with multiple unexpected "plz add me as author" requests.

**Comment by calculuschild** [comment]
Hm.... @ericscheid has a good point. If a user has arrived at this error page, it implies someone has given them this `/edit` link with intent to share *something*. In that case, it makes sense to just reveal the `/share` link.

**Comment by 5e-Cleric** [comment]
Mmhm idk, i guess that is the most probable situation..
