### ISSUE TITLE
Last row in editor not visible

### ISSUE THREAD

**Issue by sanwae** [naturalcrit/homebrewery#314]
The last row of text in the editor is not visible for me (I'm using chrome). The text is visible in the preview document and if I continue writing on the bottom row when I've moved down with the arrows on my keyboard the text appears in the preview, but I still can't see it or access it otherwise.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
Screenshot?

**Comment by AlexeySachkov** [comment]
@calculuschild, @ericscheid, I suggest that we close this one

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @sanwae
