### ISSUE TITLE
Saving Issue

### ISSUE THREAD

**Issue by TulioLeitao** [naturalcrit/homebrewery#3143]
### Error Code

```shell
Error: Client Disconnected


Error: Client Disconnected
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80394:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1966:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:80684:10)
{
  "status": 499,
  "method": "PUT",
  "url": "/api/update/DHn3N9zaEFy-"
}
```
```


### Your description of what happened:

Auto save wet off and i cant manually save

**Comment by G-Ambatte** [comment]
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/3200ccad-6746-4393-b60a-0bec8512b82b)

Currently showing a consistent version mismatch error. I would recommend you copy your text somewhere safe and then reload the Homebrewery web page.

Did this error occur during an autosave?

**Comment by G-Ambatte** [comment]
Looks like this was the original error:

![image](https://github.com/naturalcrit/homebrewery/assets/19826659/0d95b512-ccae-413c-9297-4a325c3535c6)

**Comment by calculuschild** [comment]
Sounds like either the browser was having a problem (spotty Internet connection?) or our server was dropping messages, but I don't think I've seen this one before. Might be worth scanning for other H28 / 499 errors to see if there's any clear pattern.

**Comment by 5e-Cleric** [comment]
No reports back from OP, closing this issue as a one-time-error
