### ISSUE TITLE
Add Elderberry Inn Icons to HB

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3171]
@Gazook89 found this awesome icon font with [The CC0 1.0 Universal!](https://creativecommons.org/publicdomain/zero/1.0/deed.en) License, and conversation has started on whether we could add this font to the tool for users to use on their brews.

The main discussion revolves around whether to use this font as a websafe font (WOFF2) or as an icon system, hosting the SVGs and using CSS to insert the icon itself.

The first method's syntax would probably look like this:

`{{font-family:"elderberry inn" &#E923;}}` or `{{icon &#E923;}}` if we made a specific class.

The second method would be more user friendly, its syntax would look more like:

Using the standard FontAwesome syntax: `{{fac, fa-chained-hand}}`  or using a specific syntax: `{{icon-chained-hand}}` or `{{i-chained-hand}}`.

Both are valid options, but style details still might be an important issue.

**Comment by ericscheid** [comment]
I like the approach of `{{icon-chained-hand}}`, however perhaps including an indicator of the source of the icon. Not so much for attribution (which while not required by the `CC0` licence is nonetheless polite) but just on the off chance we later find yet another interesting collection of icons .. but we'd then have to code up a new class that doesn't clash with `icon-something`.

**Comment by 5e-Cleric** [comment]
Current syntax is `{{ei,grappled}}` for that example icon.
