### ISSUE TITLE
Info Boxes are off screen

### ISSUE THREAD

**Issue by FlamboyantMisfit** [naturalcrit/homebrewery#319]
This is an amazing monster manual I would love to use, but a lot of the info boxes are coming up off screen :(

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by stolksdorf** [comment]
You need to provide a link to which homebrew you are talking about.

**Comment by FlamboyantMisfit** [comment]
http://homebrewery.naturalcrit.com/share/rJg0D0qK

**Comment by stolksdorf** [comment]
It renders fine for me. You'll need to provide more details.

**Comment by nadcraker** [comment]
Page 6, 17, 19, 22, 23, 25, 34, 38, 39, 43 ,45, 51, 58, 59, 65 has what looks to be a monster stat block being rendered off the right edge of the page.

Several pages have paragraphs that are rendered half on the page and half off the page.
![capture](https://cloud.githubusercontent.com/assets/5799503/22915575/1b8ace42-f22d-11e6-9f35-645f60fbf058.PNG)

**Comment by vangelo** [comment]
i am also having the same issue with this one and would like to know how to fix this if it helps it says on the bottom left of the screen that Partial Page Renderer enabled, because your brew is so large. May effect rendering.

**Comment by calculuschild** [comment]
Aaah. It looks like this was originally a comment meant for the author of the homebrew. We have another one #617 talking about the same brew. The statblocks are just slightly too large to fit into the desired space, so they overflow into the third column, which is off the edge of the page.

However, for this particular brew, these issues only appear at certain page zoom percents. At 90% or 100% zoom, the statblocks are being pushed off the edge. At 75% or below, the statblocks manage to fit just fine.

**Comment by AlexeySachkov** [comment]
@calculuschild, I suggest that we close this one

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.
