### ISSUE TITLE
Insert Link snippet should linkify selected text

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#3201]
### Your idea:

Currently, selecting the _Insert Link to Page_ snippet inserts `[Click here](#p3) to go to page 3`. This will appear in front of the cursor or current selection.

It would be more useful if the editor detects that some text is selected, and linkifies that text. Thus, selecting "some text" would insert `[some text](#p3)`, replacing the selection. (This is how inserting links in many editors work.)

**Comment by Gazook89** [comment]
Try the ctrl k (or cmd k) hotkey for inserting a link.  Is that what you expect the Link to Page snippet to do?  If so, i assume it can be ported over quickly.

**Comment by Gazook89** [comment]
Actually maybe it is harder.  The snippets are just text things, and the little JS involved is just for generating text strings.  I'm not sure that it is good to conflate "plain text insertions" with "buttons that manipulate your existing text", it would be unexpected.

I do think that it would be valuable to have the "normal" toolbar of functions that you get in most WYSIWYG editors, with "Underline", "Bold", "Italic" and "add link", etc.  But I think that is separate from text insertions.

**Comment by ericscheid** [comment]
Ah .. I see we do have a hot-key for insert link (ctrl-K), and it does the desired. For the life of me I couldn't remember if there was one, and the nearest thing was the Insert Link to Page snippet.

OK, don't change the insert snippet behaviour.
