### ISSUE TITLE
Chrome Crash with Inspect Tool

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#3209]
### Renderer

v3

### Browser

Chrome

### Operating System

MacOS

### What happened?

Chrome crashes when using the Inspect dev tool on *some* brews.  Noticed it Dec 24th.

Chrome Version 120.0.6099.129 (Official Build) (arm64)
MacOS, M2
Per gitter, @G-Ambatte and @5e-Cleric both have the same issue with the same brews on Windows, but only after the latest update to Chrome.

Gambatte link to a possibly linked open issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1511970&q=Inspect&can=2

Below are some brews where it crashes.  Note, you open the link, open Dev Tools, and use the Inspect tool to hover over the preview iframe and it will crash.  Notably, this doesn't happen on every brew.

- https://homebrewery.naturalcrit.com/share/10_ZaGXAzLWNcn_ybM9K1uiMZ_o31Lt4f5CxliV-7LFuV
- https://homebrewery.naturalcrit.com/share/1RfW32v-mkjlKIfrLxmSQ95n8nkEMqqVC8zZsTt2qgJ1F
- https://homebrewery.naturalcrit.com/share/1Ent-kCyGwHOnREuzivfv7QTV5wEiQJpnDZbJYLJnxHvK
- probably anything from this directory: https://homebrewery.naturalcrit.com/user/KaiburrKathHound?sort=created&dir=asc

**Comment by G-Ambatte** [comment]
It's worth noting that all the reproduction brews are stored on Google Drive.
I have also had far fewer issues with crashes after cloning the document.

The fact that the error message says "STATUS_BREAKPOINT" and is not reproducible on Chrome Canary makes me think that it's a debug feature that's accidentally made it to production.

**Comment by 5e-Cleric** [comment]
We can change my part, i have this bug now too. Haven't changed a thing.

**Comment by Gazook89** [comment]
This seems to be resolved in Chrome 121 per the linked chromium bug tracker, and my tests with the linked brews above.  closing.
