### ISSUE TITLE
Pathfinder 2nd edition (P2E) Theme

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3227]
Fonts used:

- [x] Taroca Regular (h1 & h2) /Ezcar as substitute
- [x] Roboto (template text)
- [x] Gin (h3 & h4) /Teko as substitute
- [x] FF Good (h5 & h6) /Tauri as substitute
- [x] Sabon (main text) /BookInsanityRemake as substitute

[Source](https://www.reddit.com/r/Pathfinder2e/comments/mo2onb/text_fonts_used_in_the_books/)

Snippets to do:

- Covers
  - [x] Front Cover
  - [x] Inside Cover
  - [ ] Back Cover
- [ ] ToC (p3,p4)
- [ ] Credits Red column (p3)
- [ ] Image Cards (p3, p4)
- [ ] ? Full cursive page (p7)
- [x] Page Footer (side)
- [x] Page marker
- [x] side column (p8)
- [x] chapter quote and hr (p8)
- [ ] ? Example of play (p15)
- [ ] icon font
- [x] Feat template (p37)
- [x] Tables
- [x] Alternative method block (p21)
- [ ] Step X header (p22)
- [ ] Character table (p23)
- [ ] Blue Note (p24)
- [x] Alignment table (p30)
- [ ] Backgrounds (p62)
- [ ] Class card display (p70)
- [ ] Key Ability/Hitpoints table (p72)
- [ ] Sample character (p75)
- [ ] Sample task note (p243)
- [ ] Calculus note (p275)
- [ ] Class kits (p290)
- [ ] Magical Traditions (p300)
- [ ] Spell lists (p308)
- [ ] Spell Description (p317)
- [ ] Character column display (p431)
- [ ] Index (p629)
- [ ] License (p639)

**Comment by 5e-Cleric** [comment]
The following document is some of the way there:

https://homebrewery.naturalcrit.com/share/fOjBNXK0bZXt by @G-Ambatte

**Comment by G-Ambatte** [comment]
During discussion this afternoon, the current intention is to create the PF2E Core Rulebook Theme, and potentially expanding to the PF2E Remastered styling afterwards.

The majority of the following styling has already been replicated in the previously linked Homebrewery document.

---

This image contains H1, a subtitle, a page separator, H2, H3, and a sidebar
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/1740d3fe-8bd1-45dc-9b57-21ca25f80a29)

This image contains H3 and H4 headers.
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/19f9069c-6eb9-426b-b017-d65e82a083f2)

This image contains a template for Feats, Items, Creatures, Spells, and Hazards.
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/cbdf6a3c-a260-4472-9e16-b8de18d547d9)

This image contains a table:
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/78a1e744-04a0-4adc-9256-e1cba00d4a6f)

**Comment by 5e-Cleric** [comment]
We should also replace h1 & h2 font, for a closer lookalike.

**Comment by dbolack-ab** [comment]
Is this what is being tweaked for their new version or is this a now dead end and that is tracked elsewhere?

**Comment by 5e-Cleric** [comment]
This is dead, instead, a pathfinder infinite template is being worked on, this can be closed.
