### ISSUE TITLE
[FEATURE, LOCAL]: Import brew from local file

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3229]
### Basic idea:

We save files to `.txt`, with a very specific syntax, it'd be nice if we could add some import function to the user page, to load into HB a brew using the `.txt` as base (after making sure no malware is in it, ofc) 

For future reference, the `.txt` syntax looks like this:

~~~
```metadata
title: title of brew
description: >-
    Description text
tags: []
systems: []
renderer: V3
theme: 5ePHB

```

```css
.page {
	background:blue;
}
```
# Brew text

~~~

**Comment by 5e-Cleric** [comment]
I guess what is needed is a function that takes the txt file, gives it a brew id and checks for missing metadata and fixes it, and stores it into the default db, then open that brew in edit page.

This of course would need to stop if the file will not render correctly, for example, if brew name is missing, or if some other syntax is wrong, and output an error message and not store it at all.

**Comment by G-Ambatte** [comment]
I believe last time this type of feature was discussed, the preferred outcome was populating `/new` with the result, rather than allowing direct entry to the DB. Then when the user hits SAVE, all of the usual checks take place.

**Comment by 5e-Cleric** [comment]
that is an interesting idea, but would it replace the new brew content?
