### ISSUE TITLE
Shrinking Image hides artist credit

### ISSUE THREAD

**Issue by IslandRhythms** [naturalcrit/homebrewery#3243]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

![image](https://github.com/naturalcrit/homebrewery/assets/39510674/c3dff95b-1cc4-4b12-8e83-993f4a1d5e55)
I've only reduced the image by 100px but it completely hides the artist credit on the image.

**Comment by 5e-Cleric** [comment]
The artist block is on the next column, erase some text and it will magically reappear.

If you want it to be out of the flow of the page, instead of `position:relative`, you should use `position:absolute`:

```
{{artist,position:absolute,top:730px,left:400px,margin-bottom:-30px
##### Cat Warrior
[Kyoung Hwan Kim](https://www.artstation.com/tahra)
}}
```
