### ISSUE TITLE
Linking Google Drive Images no longer works

### ISSUE THREAD

**Issue by ewirtz65** [naturalcrit/homebrewery#3257]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

ALl linked images that worked previously now fail to load.

### Code

```gfm
![Orchestra](https://drive.google.com/uc?id=171oqkbu8ExsexAo-Vujq0_EWij-dEWVZ) {width:100%,mix-blend-mode:multiply,opacity:80%}
```

**Comment by 5e-Cleric** [comment]
Google Drive has a history of blocking images if they receive too much traffic, Google does not want to be used as an image hosting service, therefore any image that receives too many requests, gets blocked from being imported.

You can check this in the console tab, it reports a 403 - Forbidden error code, the server understands the request but refuses to authorize it.

If you want to use that image be sure to host it in an image hosting service such as Google Photos, Wix, Artstation, or Imgur.

Those last two i have used and work perfectly fine for years even with thousands of views.
