### ISSUE TITLE
Print view doesn't include the Language Attribute

### ISSUE THREAD

**Issue by Blackflighter** [naturalcrit/homebrewery#3294]
### Renderer

v3

### Browser

Firefox

### Operating System

Linux

### What happened?

When opening up one of my brews in Print view (link [here](https://homebrewery.naturalcrit.com/print/aTdeRvSBTBkN)), I noticed that the `hyphens: auto` CSS that I had set up was not being made use of. As a result, none of the hyphenations appeared where they were supposed to, causing some text overflow.

Taking a quick look via the element inspector, it turned out that this was due to the Print view lacking the `lang="en"` attribute (as opposed to the regular view, where things worked as expected as can be seen [here](https://homebrewery.naturalcrit.com/share/aTdeRvSBTBkN)).

Introducing this attribute to the Print view's `<div class="pages"></div>` element (the same as the regular view) should fix that up - manually doing so in the element inspector got the hyphenation working as expected.

**Comment by 5e-Cleric** [comment]
Good catch, should have thought of adding lang attribute to print too, we'll be right on it.

**Comment by 5e-Cleric** [comment]
That Pull Request adds in the fix by setting the lang attribute on the `div.pages` element, which is high enough in the DOM  to work and low enough to be accessed easily in the current configuration of the page.

**Comment by Blackflighter** [comment]
Very nice, and looks like it was even a relatively simple fix - many thanks!

Just one thing (from just a cursory glance, so I might very well be wrong here): the current [default value](https://github.com/naturalcrit/homebrewery/blob/master/server/brewDefaults.js) for the `lang` attribute seems to be `en` as opposed to `en-US` (though that was located in a different part of the repo). Maybe that ought to be adjusted accordingly?

**Comment by 5e-Cleric** [comment]
Actually no, as defined by W3C, lang codes in html do not include the country.

https://www.w3.org/International/O-help-lang.html

**Comment by Blackflighter** [comment]
Ah! To clarify my words, perhaps the `en-US` should have been changed to `en` - looks like you made the change already.

**Comment by ericscheid** [comment]
> Actually no, as defined by W3C, lang codes in html do not include the country.
> 
> https://www.w3.org/International/O-help-lang.html

That's a very old reference. More recent specs make mention of country and dialect variations.

[https://www.w3.org/International/questions/qa-html-language-declarations](https://www.w3.org/International/questions/qa-html-language-declarations#metadata:~:text=BCP%2047%20describes%20how%20to%20compose%20language%20tags%20that%20allow%20you%20specify%20regional%20dialects%2C%20scripts%20and%20other%20variants%20related%20to%20that%20language)

**Comment by 5e-Cleric** [comment]
According to that spec:
> BCP 47 incorporates, but goes beyond, the ISO sets of language and country codes. To find relevant codes you should consult the [IANA Language Subtag Registry](http://www.iana.org/assignments/language-subtag-registry).

Checking that: 
![image](https://github.com/naturalcrit/homebrewery/assets/91662974/2c69ba4b-a3cb-438b-9047-8bd4e59400e4)
So, no country codes anyway.
