### ISSUE TITLE
Add share link to error page 401 if brew published

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3298]
As the published status boolean indicates the availability of the brew to the public, it would make sense to add a share link to the error 401 page if a brew is published.

**Comment by calculuschild** [comment]
After looking at @ericscheid 's [comment](https://github.com/naturalcrit/homebrewery/issues/3086#issuecomment-2041501408) on #3086, I think he has a point that this probably isn't necessary. A user who has an edit link should probably have the share link as well, whether the brew is published or not.

**Comment by 5e-Cleric** [comment]
If this is generally agreed, then the issue is done for, but there is still one page without share link, the PR will still be of use.

**Comment by calculuschild** [comment]
Which page is missing a share link?
