### ISSUE TITLE
Snippets should be agnostic

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3336]
we can't have agnostic themes and offer snippets RPG based in them, all tables in blank theme should be rewritten to use mundane text, and the current version moved to PHB

**Comment by calculuschild** [comment]
I think its ok if the generic table snippet still has RPG-related content. Is there some major downside you are concerned about?

**Comment by 5e-Cleric** [comment]
If we change the content of the tables, the only thing left to link it to RPGs is the system tags and the name of the tool, do we want to stay into RPGs or move into full agnostic? i write everything in this tool, even university stuff.

**Comment by calculuschild** [comment]
Well, Naturalcrit and Homebrewery have always been RPG focused (its in the name). There are other Markdown editors out there, but the RPG focus is what gives Homebrewery its unique identity.

People can of course use it for other tasks, but I don't see a big reason to move away from our RPG roots. And I don't see why "Experience points - Level - Proficiency Bonus" would be any worse than other generic text for a table.
