### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by Zarhog** [naturalcrit/homebrewery#3340]
### Your idea:

Can we add a feature that allows you to return to a previous backup of a brew, as some people are stupid like me and accidently thumb something then close there browser.

**Comment by calculuschild** [comment]
See issue #3070.

Also, note that we do store a daily backup of all files, for a week, so in the mean time, if you need a backup retrieved I can look it up for you.

**Comment by ericscheid** [comment]
Additionally, brews that are saved on google drive automatically keep versions.

<img width="823" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/2605467/16febd3a-ae80-4075-a381-d03518c7aea1">


<img width="662" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/2605467/ff6e0430-6546-4639-908b-9906b4582648">
