### ISSUE TITLE
VERY minor Table of Contents widget edit

### ISSUE THREAD

**Issue by Kaiburr-kath-hound** [naturalcrit/homebrewery#3344]
### Renderer

Both

### Browser

Chrome

### Operating System

MacOS

### What happened?

The "Table of Contents" generation button actually titles the page "Table Of Contents", with the word "Of" being capitalized. I believe the word "of" is never capitalized in any title.

Obviously super minor, but I believe every 5e book only uses the word "Contents" anyways, rather than "Table of Contents".

There's a fun minor issue, if anyone is bored and you run out of actual bugs to work on haha.

### Code

```gfm
{{toc,wide
# Table Of Contents


}}

<!---
Instead of "Table of Contents". I excel at pedantry.
--->
```

**Comment by RKuerten** [comment]
Closing this issue as #3345 got merged. Thanks for opening the issue!
