### ISSUE TITLE
Multiline Definition List term consumes Mustache Block opening text

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3378]
### Your idea:

Repro code:
```
{{color:red
:: 1
}}
```

Expected output:
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/37164ea5-97dc-4a71-8c57-fc87c252b3af)

Current output:
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/5294caa7-ed3a-42d7-b87f-f59941919c5e)

---

I suspect that a tweak of the Marked extension priority order may be all that is required to correct this issue.

**Comment by calculuschild** [comment]
You are probably right. Curly divs should have higher priority than definition lists.
