### ISSUE TITLE
Lost recent saves

### ISSUE THREAD

**Issue by cyberhawk94** [naturalcrit/homebrewery#338]
Been working on a brew for a while, making sure it saved along the way.

Somehow it reverted to about a week ago, even though it had been closed and reopened without problems several times since then

I really hope there is a way to recover previous versions, cause I lost quite a bit of work that i cant really remember. 

http://homebrewery.naturalcrit.com/edit/Hyx1kNt8dg

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by AlexeySachkov** [comment]
@calculuschild, I think this issue can be closed as "aged out"/"cannot reproduce"

**Comment by calculuschild** [comment]
Unfortunately this was never fixed when it was first reported, so there's nothing more we can do now.
