### ISSUE TITLE
CSS Nesting is highlighted as an 'error' in Style Editor

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#3387]
### Renderer

v3

### Browser

Chrome

### Operating System

MacOS

### What happened?

<img width="296" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/58999374/7ae772ea-e80e-4119-8b92-4a323b2f8769">

I'm pretty sure `tr` is highlighted red because it doesn't want to allow nesting, even though nesting is working.

**Comment by ericscheid** [comment]
the css code styling is done per css rules, not less rules?

**Comment by Gazook89** [comment]
> the css code styling is done per css rules, not less rules?

Regular css allows for nesting now. And I agree with @5e-Cleric that nothing on our end needs to be done, I just noted it because in discord a user thought nesting wasn’t possible as a result.

**Comment by 5e-Cleric** [comment]
i did point out this problem in #2793, not sure if anyone read it though.

**Comment by Gazook89** [comment]
Ah yes, I’ll close this
