### ISSUE TITLE
Proficiency Bonus in Monster Stat Blocks

### ISSUE THREAD

**Issue by Gazook89** [naturalcrit/homebrewery#3397]
### Your idea:

This lack of proficiency bonus in the monster stat block snippets is something that comes up occasionally.  We can easily add it to the snippet and leave it to users to remove if they don't want.  

My approach is to do:

#### Brew
```md
**Condition Immunities** :: groovy
**Senses**               :: darkvision 60 ft., passive Perception 6
**Languages**            :: Common, Gibberish
**Challenge**            :: 14 (7258 XP) {{bonus **Proficiency Bonus:** +5}}

```
#### CSS
```css
.monster .bonus {
  float: right;
}
```
#### Result
<img width="349" alt="image" src="https://github.com/naturalcrit/homebrewery/assets/58999374/7a7c7ee8-bf69-446a-828c-59df368b25e1">

I think fancier CSS could be used (using `:before` and `content: "Proficiency Bonus: "` for example) but that becomes less clear for non-technical authors and doesn't really match how we do other things.

**Comment by 5e-Cleric** [comment]
I think its alright if we add a padding or margin to that `.bonus`:

![image](https://github.com/naturalcrit/homebrewery/assets/91662974/4a08927c-2f36-469b-bdac-a5055bf17e52)

**Comment by Gazook89** [comment]
That seems good to me.  Also note, i shouldn't have had the colon `:` on mine.
