### ISSUE TITLE
Using Monospace Fonts with any Editor Theme

### ISSUE THREAD

**Issue by pongtaewin** [naturalcrit/homebrewery#3504]
## Feature Description
I think it is possible to allow anyone to use any editor themes with the monospace fonts.
This can be extended to any font family if it's useful, but it is quite important for monospace.

Most of the time, I have problems managing tables without using monospace themes, so I am locked to use the provided themes only (which is idea and darcula). I am also a coder, so monospace fonts are a personal preference, too.

Here's one with themes that has monospace fonts (using the idea theme):

![image](https://github.com/naturalcrit/homebrewery/assets/32708251/bb2243aa-55f8-422d-b71b-017dfd2bab05)

And here's the one without (using the default theme):

![image](https://github.com/naturalcrit/homebrewery/assets/32708251/a7b42e03-7ea1-4b49-978b-3646752084ab)

I think the option to choose can be put as a checkbox below the theme dropdown, like `[✓] Use monospace`.
Feel free to ask questions.

**Comment by 5e-Cleric** [comment]
I'm not sure of what you mean, the default theme uses a monospace font.

**Comment by 5e-Cleric** [comment]
No more info provided by OP in two months, closing this issue.
