### ISSUE TITLE
DOMpurify breaks custom html elements

### ISSUE THREAD

**Issue by marceloabner** [naturalcrit/homebrewery#3549]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

I had some quick headers was used inside a common line of text as global styles that now no longer work. For example, a tag like this

    A black text, <h7>a red text</h7> and a black text again
with a simple CSS like

    h7 {color: red}
It used to work fine, but now it seems that they are no longer recognized as headers and don't appear colored.

I don't know if there is a way to revert this change if this is a bug, or if there is a better way to define quick styles for texts inside a paragraph without requiring a lot of code.

**Comment by calculuschild** [comment]
The preferred way to do this is with the curly bracket syntax:

```
Here is {{myCustomStyle some text}}.
```

And then the CSS:
```
.myCustomStyle {
  color: red;
}
```

Or even:

```
Here is {{color:red some text}}.
```

However, your approach should still work. We will look into this.

**Comment by ericscheid** [comment]
`H7` is not a standard html element. Headings are `h1` thru to `h7`.

That said, unrecognised html elements would normally be treated the same as `span` elements as far as `{ display: inline; }`.

Looking at the html that is rendered into the preview ... and there is no trace of the `<h7>`.

The unrecognised html has been stripped out. This release has DOMPurify active, which I suspect is causing this.

**Comment by marceloabner** [comment]
Yeah, my use of headers was useful before on legacy cause typing a header with an autocomplete was quick, but I think using curly brackets is even faster and I keep using the correct standards.

Thanks all for the help and the care in explaining how it works.

**Comment by 5e-Cleric** [comment]
Reopening this to track the actual issue described in the new title
