### ISSUE TITLE
Links to Imgur and Deviant images don't | 3.13.0 

### ISSUE THREAD

**Issue by Frederlk** [naturalcrit/homebrewery#3550]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

Images from Imgur and Deviant art stopped working after the release of v3.13.0.

Console is full of 401 errors.

`Failed to load resource: the server responded with a status of 401 ()`

**Comment by 5e-Cleric** [comment]
Links from OneDrive have fallen too, we have temporarily rolled back the update until we can fix this, thanks for the heads up!

**Comment by 5e-Cleric** [comment]
Specifically our scripts delete everything inside the href starting with a `=`.

This does not come from DOMpurify, as @calculuschild has commented out that code.

**Comment by calculuschild** [comment]
Fixed by #3552
