### ISSUE TITLE
fancy drop cap is ugly if bold

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#3551]
This:
```
# Project Brief Template
**Project Overview:**
- Describe your business or service
```
Looks like this:
![image](https://github.com/naturalcrit/homebrewery/assets/2605467/bd4bbc8d-e893-4e9a-bd37-79e6a97f81f8)

Fix:
```
.page h1+p::first-letter {
  font-weight: unset;
  font-style: unset;
}
```

**Comment by dbolack-ab** [comment]
Which theme is this impacting?

**Comment by 5e-Cleric** [comment]
Not impacting any theme as we don't use it in bold, but some users have tried and the browser's forced bold interacts badly with it.

**Comment by calculuschild** [comment]
We could have the bold font-face point back to the same font so it doesn't trigger the browser generating ugly bold fonts. As a decorative drop-cap font I think it would be ok for bold and normal (and italic) to just be identical.

**Comment by G-Ambatte** [comment]
```
{{font-family:SolberaImitationRemake,font-size:48px Normal}}
:
{{font-family:SolberaImitationRemake,font-size:48px *Italics*}}
:
{{font-family:SolberaImitationRemake,font-size:48px **Bold**}}
:
{{font-family:SolberaImitationRemake,font-size:48px ***Both***}}
```

![image](https://github.com/naturalcrit/homebrewery/assets/19826659/e9c2e6b3-6aff-4c76-82d3-8d57a3745948)

---

I think this article has the kind of style settings being discussed : https://www.smashingmagazine.com/2013/02/setting-weights-and-styles-at-font-face-declaration/#style-linking

**Comment by G-Ambatte** [comment]
```
/* Fancy Drop Cap */
@font-face {
	font-family: SolberaImitationRemake; //Tweaked 5e version
	src: url('../../../fonts/5e/Solbera Imitation Tweak.woff2');
	font-weight: 100 1000;
	font-style: normal;
	font-style: italic;
}
```

Repeating the source text from the previous comment:
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/5630fbfe-71b8-4403-954e-47ce25376022)

Bolded text is still wrapped in `<strong>` elements and thus is targeted by the `.page strong` styling, so the `letter-spacing: -0.02em;` is still applied.

**Comment by G-Ambatte** [comment]
A further test:
![image](https://github.com/naturalcrit/homebrewery/assets/19826659/a0fdd7bd-4e73-46af-a232-905e85e72847)
