### ISSUE TITLE
Can't Save

### ISSUE THREAD

**Issue by ewirtz65** [naturalcrit/homebrewery#3574]
### Error Code

```shell
Error: Forbidden


Error: Forbidden
    at Request.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78344:21)
    at Emitter.emit (https://homebrewery.naturalcrit.com/homebrew/bundle.js:1954:20)
    at XMLHttpRequest.<anonymous> (https://homebrewery.naturalcrit.com/homebrew/bundle.js:78638:10)
{
  "status": 403,
  "method": "PUT",
  "url": "/api/update/TiI6h8oMyQYX"
}
```
```


### Your description of what happened:

Edited a brew and got this error

**Comment by calculuschild** [comment]
This error is coming from Google, and says "The user does not have sufficient permissions for this file."

Are you signed in to the correct Google Drive account where this brew is stored? If yes, have you changed the sharing permissions of that document? It needs to be set to "share with anyone with the link" in order for the Homebrewery to send changes.

It's also possible your Google credentials have just expired if you haven't newly logged in for a long time. In that case, you can try just logging out, and then signing back in "with Google".

**Comment by 5e-Cleric** [comment]
> This error is coming from Google, and says "The user does not have sufficient permissions for this file."
> 
> Are you signed in to the correct Google Drive account where this brew is stored? If yes, have you changed the sharing permissions of that document? It needs to be set to "share with anyone with the link" in order for the Homebrewery to send changes.
> 
> It's also possible your Google credentials have just expired if you haven't newly logged in for a long time. In that case, you can try just logging out, and then signing back in "with Google".

We should catch this error and tell the user about it in the tool.
