### ISSUE TITLE
Cant seem to access any of my saved brews. 

### ISSUE THREAD

**Issue by Burning-Sensationalist** [naturalcrit/homebrewery#358]
Once I close the homebrewery page, regardless if i'm logged in or how many times i've saved my stuff, i never seem to be able to access my stuff ever again. Not sure if this is a bug or simply user error.

**Comment by Groumy** [comment]
Have you tried to simply click on your name at top right ? I should open up a "brewlike" page with link to every brews you created (while loggued in, of course).

**Comment by MrKarch** [comment]
I have some further information on this. If B-S is like me, they used an email address as a login name, and that may be the issue.  With my old login, FIRST.M.LAST@gmail.com (not the actual login), clicking on my name just takes me to the Homebrewery example page (http://homebrewery.naturalcrit.com/).

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @Burning-Sensationalist
