### ISSUE TITLE
FAQ info panel needs info

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#3586]
https://homebrewery.naturalcrit.com/faq

<img width="880" alt="image" src="https://github.com/user-attachments/assets/b8030fec-0864-45b8-8469-860a19aa3dbf">

Updated when?

**Comment by 5e-Cleric** [comment]
There should be no info there, changelog has same issue.

**Comment by G-Ambatte** [comment]
`/faq` and `/changelog` both use the SharePage to display their data... Arguably both should be divorced from the 5E PHB styling and shifted to the UI base page styling.
However, a simpler option would be to disable the metadata window on those pages.
