### ISSUE TITLE
Theme: Themes can select themselves as Theme Source

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3614]
### Your idea:

As shown in the below image, it is possible for a brew tagged with `meta:theme` to select itself from the dropdown list. This seems incorrect.

![image](https://github.com/user-attachments/assets/78d3db51-8b29-4fd0-b133-0038578acdf5)

**Comment by dbolack-ab** [comment]
That's a regression. I remember explicitly working that exact problem. :/

**Comment by G-Ambatte** [comment]
![image](https://github.com/user-attachments/assets/367519d2-e517-4cec-9495-039a2bdae572)

**Comment by calculuschild** [comment]
I probably broke it with my revisions.

**Comment by G-Ambatte** [comment]
I've just created PR #3615 with a quick fix, now that I've identified one.
