### ISSUE TITLE
Math functions with multiple parameters cannot take variable names

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3622]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

The expectation is the reproduction code will return `2`; instead it returns `$[min(2,DexMod)]`

See reproduction brew here - https://homebrewery.naturalcrit.com/share/VE5qZsAsuAfk

### Code

```gfm
[DexMod]: 4

$[min(2,DexMod)]
```

**Comment by 5e-Cleric** [comment]
Can reproduce this issue, must mention the following does work:

```
[DexMod]: 4

$[min(DexMod)]
```

outputing 4

**Comment by 5e-Cleric** [comment]
Okay, the function might be expecting parentheses, the following works:
```
[DexMod]: 4

$[min(2,(DexMod))]
```

**Comment by G-Ambatte** [comment]
I think the split function on line 455 doesn't include `,` so it is being included in the potential variable names. It might be as simple as adding that character to the regex on the previous line.
