### ISSUE TITLE
Using scaleX or scaleY parameters causes skewing in rotated masks

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3636]
### Your idea:

Consider the following:

```
{{imageMaskEdge5,--offset:0%,--rotation:235,--scaleX:1.0
  ![](https://i.imgur.com/GZfjDWV.png){height:100%}
}}
```

which results in the following:
![image](https://github.com/user-attachments/assets/d69c339f-b0e0-46a3-8aa8-30300caa7bad)

Adjusting the `scaleX` parameter should increase the horizontal width of the mask:

```
{{imageMaskEdge5,--offset:0%,--rotation:235,--scaleX:1.5
  ![](https://i.imgur.com/GZfjDWV.png){height:100%}
}}
```

Instead, we see that the image inside the mask is skewed:
![image](https://github.com/user-attachments/assets/bb20f231-802f-468f-8be9-136e749e5209)

Altering `scaleY` results in a similar skewed result:
![image](https://github.com/user-attachments/assets/2d1db8bb-51a6-4344-9ead-0ccbcd4ee59c)

I believe that the issue stems from this block of styling:

```
.page [class*='imageMask']>p:has(img) {
    position: absolute;
    bottom: 50%;
    left: 50%;
    width: 50%;
    height: 50%;
    transform: translateX(-50%) translateY(50%) rotate(calc(-1deg * var(--rotation))) scaleX(calc(1 / var(--scaleX))) scaleY(calc(1 / var(--scaleY)));
}
```

and in particular, this line: `transform: translateX(-50%) translateY(50%) rotate(calc(-1deg * var(--rotation))) scaleX(calc(1 / var(--scaleX))) scaleY(calc(1 / var(--scaleY)));`.
Modifying this line to instead read `transform: translateX(-50%) translateY(50%) scaleX(calc(1 / var(--scaleX))) scaleY(calc(1 / var(--scaleY))) rotate(calc(-1deg * var(--rotation)));` results in the expected output, regardless of modifications to `scaleX` or `scaleY`:
![image](https://github.com/user-attachments/assets/7df82d0f-bfad-46da-94de-c9ea84323c12)

**Comment by calculuschild** [comment]
Just moving the scale to occur before rotation, looks like?
