### ISSUE TITLE
Title with shared link of a cloned brew in newpage shows up as error

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3651]
Any time a `/new/:id` page is shared, although it is a valid page, the link shows up with an error page name, we should change that, probably to something like `New Cloned Brew`, and adding a subtitle like: `clicking this link will clear your new brew page`.

Proof:
![image](https://github.com/user-attachments/assets/9b813fb1-c187-46b8-a701-50978ae7a208)

I have absolutely no idea how to change this.

**Comment by G-Ambatte** [comment]
![image](https://github.com/user-attachments/assets/540f020e-408a-47d4-b00e-7f32054fae7d)

There are `<meta>` tags already applied to the `/new/:id` route, something must be going wrong to return the error information instead.

**Comment by G-Ambatte** [comment]
Discord:
![image](https://github.com/user-attachments/assets/2e819065-560d-4d42-8d4f-7ae5512c45ef)

**Comment by G-Ambatte** [comment]
Gitter:
![image](https://github.com/user-attachments/assets/699efd35-1860-4536-9027-6a4b07f6c5f0)

**Comment by 5e-Cleric** [comment]
Seems to be working again, well, i guess it was a one time thing, although we should be warning IMO, closing
