### ISSUE TITLE
Toc generation broken

### ISSUE THREAD

**Issue by lucastucious** [naturalcrit/homebrewery#3672]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

Toc generation "up to..." is broken. When clicked, {{tocDepthH3}} appear but with nothing inside

**Comment by 5e-Cleric** [comment]
Thank you for reporting this issue, you are completely right, this is broken. We are looking into it.

**Comment by 5e-Cleric** [comment]
Actually, nevermind, after talking to the team, this is indeed expected behaviour and not a change since the last changes:
>Only the "Table of Contents" button makes a table of contents. All the "Include..." Buttons just add markers that will influence which headers will be considered when you click "Table of Contents"

**Comment by lucastucious** [comment]
Okay, so how i'm supposed to generate the toc ?
Because right now, adding the markers {{tocDepthH3}} doesnt change the generated toc

**Comment by 5e-Cleric** [comment]
Okay, so, i misinterpreted that PR, and have never used this feature, but:

If you add headers inside that block:
```
{{tocDepthH6

###### hello test test test
}}
```

Any header up to the desired depth inside that will be included.

The other way of doing this is with CSS, setting it like this:

```
.page h4 {
  --TOC: include;
}
```

I think this is the correct way. 

Btw, even if they are included, we don't have styles prepared for 6 levels of headers, so any header below 3 is styled as 3, i'm not sure how to change that.

**Comment by lucastucious** [comment]
Ok I understand now. Is there a documentation somewhere for theses features ?

And can we exclude h3 with the css snippet you shared ? So the toc generation will just generate H1 and H2 ?

**Comment by 5e-Cleric** [comment]
Yes, but specificity might be a problem if you use both the blocks and the css snippet, if it doesn't work at the first try, try adding !important.
