### ISSUE TITLE
New Jump-To hotkeys feature Conflicting with General Windows Select Behaviour

### ISSUE THREAD

**Issue by marceloabner** [naturalcrit/homebrewery#3676]
### Your idea:

The new Jump-To hotkeys feature is just conflicting with default windows behaviour of selecting entire words or text blocks, and this is a really quick way to copy and paste chunks of texts inside a same line/paragraph.

This new function, and any new hotkey combo, should have a on/off setting for those who don't want to use, like a personal setting. The best case scenario would be let the user customize the hotkey, but this is probably a lot more complex to do. In meantime, make a toggle hotkey option instead.

**Comment by marceloabner** [comment]
Fixed.

**Comment by desmeraldoo** [comment]
Hey, what was the fix here? Were you able to find a way to disable these hotkeys? I don't need this new feature and it's preventing me from using normal select behavior.

**Comment by 5e-Cleric** [comment]
> Hey, what was the fix here? Were you able to find a way to disable these hotkeys? I don't need this new feature and it's preventing me from using normal select behavior.
> 
> Edit: Looks like refreshing the page fixed it, guess I was still using a build from when the issue still existed. My bad.

Marceloabner closed this issue when they realized we had already released a fix. The key binds have been changed to `CTRL + META + SHIFT + ARROW`. META being the windows key in windows.
