### ISSUE TITLE
[DX] Stop editorThemes.json and themes.json from constantly showing as modified

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3703]
### Your idea:

Every time the build process runs, the files `themes.json` and `editorThemes.json` always show as modified, despite file checks showing that the content is unchanged.

Testing today shows that the line ending encoding is being changed - the build process creates files with `LF` line end encoding, while the pulled file shows `CRLF` line end encoding.

Further testing shows that modifying the `.gitattributes` file to include the line `*.json text eol=lf` prevents this issue from occurring.

**Comment by 5e-Cleric** [comment]
In my local themes.json does change its contents, always lowercases the journal theme for some reason, this could come from the encoding anyway.
