### ISSUE TITLE
Weapons go missing. 

### ISSUE THREAD

**Issue by Wolfskin75** [naturalcrit/homebrewery#371]
When I go to save pdf and print it, only the first item on each page shows up. 

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/SJZjv6lvnx

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

# Weapons
#  
T<font size="4">ramontane</font> 
___
```
```
- **Weapon type:** Martial Melee 
- **Group:** Martial weapons
- **Range:** Melee
- **To Hit:** +13
- **Damage type:** Piercing
- **Damage:** 1d8+3d6+8
- **Proficient:** Yes
- **Crit threshold**:@18
___

- **Properties:** Proficient, versatile +3d6 Radiant Damage, Keen: Critical on roll of 18-20 = double dice roll

# -

M<font size="4">istral</font>
___
```
```
- **Weapon type:** Martial Melee 
- **Group:** Martial weapons
- **Range:** Melee
- **To Hit:** +13
- **Damage type:** Piercing
- **Damage:** 1d8+3d6+8
- **Proficient:** Yes
- **Crit threshold**:@18
___

- **Properties:** Proficient, versatile +3d6 Radiant Damage, Keen: Critical on roll of 18-20 = double dice roll

# -

T<font size="4">win Adamantine Rapiers</font>
___ 
```
```
### Tramontane and Mistral
when wielded together......
- **Glitter Step**: Surrounded in Glittering Faerie Light and allows as a extra action, wind to teleport 30 feet 
- Extra attack per round
- Advantage on attacks and Saves
- +3 to Ac
- Immune to Necrotic
- Sheds light: Bright 10ft. then dim 10ft.
<div class='pageNumber'>1</div>
<div class='footnote'>Paladin | wind's weapons</div>

\page
# Weapons

Q<font size="4">uiver of Nariynore</font> 
___
gift of the Nariynore tribe. 
```
```

- Place normal arrows in. They become +1 arrows. 
- Can add elemental damage (5d6 Acid, Cold, Fire, Lightning, or Thunder damage)
- Can add elemental damage (3d6 Acid, Cold, Fire, Lightning, or Thunder damage) in a 5ft radius from where arrow lands. 

# -

A<font size="4">damantine dagger(+1)</font>
___ 
```
```
- **Weapon type:** Finesse, Light, Range, Thrown
- **Group:** Melee Weapon
- **Range:** Melee
- **To Hit:** +10
- **Damage type:** Piercing
- **Damage:** 1d4+6
- **Proficient:** Yes
- **Crit threshold**:@20
___

- **Properties:** Finesse, Light, Range, Thrown

# -

D<font size="4">ragon tooth chain whip</font>
___ 
```
```
- **Weapon type:** Finesse, Light, Range, Thrown
- **Group:** Melee Weapon
- **Range:** Melee/10ft.
- **To Hit:** +10
- **Damage type:** Piercing, slashing, bludeoning
- **Damage:** 1d6+6(+1d6 cold damage)
- **Proficient:** Yes
- **Crit threshold**:@20
___

- **Properties:** Finesse, reach, two handed, disarming, Entangle, special
*( hit everyone with 10ft take slashing damage/bludeoning)* 

# -

F<font size="4">ire bolt</font>
___ 
```
```
- **Weapon type:** spell attack
- **Group:** Melee Weapon
- **Range:** 120ft.
- **To Hit:** +7
- **Damage type:** Fire
- **Damage:** 2d10 (+spell points at 1d10 per)
- **Proficient:** Yes
- **Crit threshold**:@20
___

- **Properties:** Unattended flammable objects ignite 

<div class='pageNumber'>2</div>
<div class='footnote'>Paladin | wind's weapons</div>
![weap1](https://cloud.githubusercontent.com/assets/22088408/24381833/76387ae2-1320-11e7-811f-915cfba6e378.PNG)

![weap2](https://cloud.githubusercontent.com/assets/22088408/24381841/7d443e98-1320-11e7-93b0-b6e28156b834.PNG)

</pre></code></details>

**Comment by AlexeySachkov** [comment]
@naturalcrit/issue-managers, I suggest that we close this issue as an outdate one

**Comment by ericscheid** [comment]
The source has multiple instances of the column-break markup on the same page.

All that does is push the content further and further off the page.


It might be better to simplify the content.

````
# Weapons

### Tramontane

- **Weapon type:** Martial Melee 
- **Group:** Martial weapons
- **Range:** Melee
- **To Hit:** +13
- **Damage type:** Piercing
- **Damage:** 1d8+3d6+8
- **Proficient:** Yes
- **Crit threshold**:@18

- **Properties:** Proficient, versatile +3d6 Radiant Damage, Keen: Critical on roll of 18-20 = double dice roll

### Mistral

- **Weapon type:** Martial Melee 
- **Group:** Martial weapons
- **Range:** Melee
- **To Hit:** +13
- **Damage type:** Piercing
- **Damage:** 1d8+3d6+8
- **Proficient:** Yes
- **Crit threshold**:@18

- **Properties:** Proficient, versatile +3d6 Radiant Damage, Keen: Critical on roll of 18-20 = double dice roll


### Twin Adamantine Rapiers

When Trmontane and Mistral are wielded together..

- **Glitter Step**: Surrounded in Glittering Faerie Light and allows as a extra action, wind to teleport 30 feet 
- Extra attack per round
- Advantage on attacks and Saves
- +3 to AC
- Immune to Necrotic
- Sheds light: Bright 10ft. then dim 10ft.


```
```

### Quiver of Nariynore
___
Gift of the Nariynore tribe. 


- Place normal arrows in. They become +1 arrows. 
- Can add elemental damage (5d6 Acid, Cold, Fire, Lightning, or Thunder damage)
- Can add elemental damage (3d6 Acid, Cold, Fire, Lightning, or Thunder damage) in a 5ft radius from where arrow lands. 

### Adamantine dagger(+1)

- **Weapon type:** Finesse, Light, Range, Thrown
- **Group:** Melee Weapon
- **Range:** Melee
- **To Hit:** +10
- **Damage type:** Piercing
- **Damage:** 1d4+6
- **Proficient:** Yes
- **Crit threshold**:@20


- **Properties:** Finesse, Light, Range, Thrown

### Dragon tooth chain whip

- **Weapon type:** Finesse, Light, Range, Thrown
- **Group:** Melee Weapon
- **Range:** Melee/10ft.
- **To Hit:** +10
- **Damage type:** Piercing, slashing, bludeoning
- **Damage:** 1d6+6(+1d6 cold damage)
- **Proficient:** Yes
- **Crit threshold**:@20


- **Properties:** Finesse, reach, two handed, disarming, Entangle, special
*( hit everyone with 10ft take slashing damage/bludeoning)* 

### Fire bolt

- **Weapon type:** spell attack
- **Group:** Melee Weapon
- **Range:** 120ft.
- **To Hit:** +7
- **Damage type:** Fire
- **Damage:** 2d10 (+spell points at 1d10 per)
- **Proficient:** Yes
- **Crit threshold**:@20

- **Properties:** Unattended flammable objects ignite 

<div class='pageNumber'>2</div>
<div class='footnote'>Paladin | wind's weapons</div>




````
