### ISSUE TITLE
Fix: Vertical spacer in single column

### ISSUE THREAD

**Issue by bakgaard** [naturalcrit/homebrewery#374]
I had an issue regarding the built-in vertical spacer when I needed a background image - the spacer spaces *everything*, and not just one column.

And then I went ahead and made a viable fix - it's not perfect, but I'd say it's ok.

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<img 
  src='http://i.imgur.com/NYPhuEN.png' 
  style='position:absolute; top:50px; right:350px; width:470px' />

<img
  src=""
  style='position:relative; height:430px; background-color:transparent;'/>
  
  
Art by Geraud Soulie
## Riding Lizard

Long text - stuff...

```
```

___
> ## Riding Lizard
>*Large beast, unaligned*
> ___
> - **Armor Class** 12 (natural armor)
> - **Hit Points** 37 (5d10 + 10)
> - **Speed** 40 ft., climb 40 ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|14 (+2)|14 (+2)|14 (+2)|2 (–4)|12 (+1)|5 (–3)|
>___
> - **Skills** Perception +3
> - **Damage Immunities** poison
> - **Condition Immunities** poisoned
> - **Senses** darkvision 120 ft, passive Perception 13
> - **Languages** —
> - **Challenge** 1/2 (100 XP)
>___
>***Standing Leap.*** The lizard’s long jump is up to 30 feet and its high jump is up to 15 feet, with or without a running start.
>
>***Spider Climb.*** The lizard can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.
>
>***Sunlight Sensitivity.*** While in sunlight, the lizard has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.
>
>### Actions
>***Bite.*** *Melee Weapon Attack:* +4 to hit, reach 5 ft., one target. *Hit:* 11 (2d8 + 2) piercing damage.

<div class='pageNumber auto'></div>
<div class='footnote'>Version 2</div>

</pre></code></details>

**Comment by 3v3rl0st** [comment]
so, i found a workaround for this that seems to be working consistently.   by adding <br> to the line above the vertical spacing command seems to force the vertical to do its function.  thank you all for the quick response on this and willingness to help.  :)

**Comment by calculuschild** [comment]
The v3 branch now has an alternative vertical spacer. By placing any number of colons `:::::` alone on a line, they will each create a blank line, allowing easy shifting up or down.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
