### ISSUE TITLE
Column Break followed by any Header tags do not display properly in editor

### ISSUE THREAD

**Issue by paguilera** [naturalcrit/homebrewery#377]
Easy enough to reproduce. In any homebrew, insert a column break, followed by table.

In the preview, the header for the table will display correctly, but in the editor, the header will not be highlighted the way a normal table would be.

If you create a table before the column break, that table displays normally in the editor. The same is true for any table created after the first one that follows the column break.

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

##### Cookie Tastiness
| Tastiness | Cookie Type |
|:----:|:-------------|
| -5  | Raisin |
| 8th  | Chocolate Chip |
| 11th | 2 or lower |
| 14th | 3 or lower |
| 17th | 4 or lower |

```
```
##### Cookie Tastiness
| Tastiness | Cookie Type |
|:----:|:-------------|
| -5  | Raisin |
| 8th  | Chocolate Chip |
| 11th | 2 or lower |
| 14th | 3 or lower |
| 17th | 4 or lower |

</pre></code></details>

**Comment by ericscheid** [comment]
Cannot repro

Code tested (with coumn break markers replaced with •••)
```
•••
•••
### sdaaa

| Tastiness | Cookie Type |
|:----:|:-------------|
| -5  | Raisin |
| 8th  | Chocolate Chip |

```

**Comment by calculuschild** [comment]
This was probably fixed with an update to Codemirror.
