### ISSUE TITLE
Issues Saving to Google Drive: Sept 29th 2024 01:30 UTC, and again Nov 5th

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3770]
We are aware of an issue with saving to Google Drive as of a few hours ago. This error is on the side of Google; there is not a lot we can do from our end, but we have filed a report with them and they are looking into it.

Brews saved to Google Drive are not lost, you can still access them via your Google Drive interface in the `Homebrewery` folder.

If you need some workaround in the meantime, you can transfer your brew from your Google Drive to the Homebrewery database for the time being by clicking on the colored "Google Drive" icon in the top navbar:

<img width="56" alt="image" src="https://github.com/user-attachments/assets/fde75852-0033-4f76-8c14-a5057eaac447">

This will move the brew out of your Google Drive and into the HB database, where saving works without issue. You can then transfer it back to Google Drive at a later time after the Google Drive issue is fixed. 

**If you feel you are impacted by this issue** with saving, [please consider reading through and adding a +1 vote to the ticket (in the upper right of the comment thread)](https://issuetracker.google.com/issues/369788650). Adding support to a ticket can help it gain traction.

**Comment by 5e-Cleric** [comment]
We have pushed some changes and this could be fixed, can't know if it will come back (again) until traffic goes back to normal.

**Comment by calculuschild** [comment]
For future reference, here are all the things we did in an attempt to fix this, in order:

- Bumped the autosave delay from 3 to 10 seconds (this appeared to initially fix the issue, but it came back)
- Change to use the current user oAuth if they are logged in, and ServiceAccount if not - NO IMPACT
- Added a rate limiter per ip address - did not seem to catch any users UNTIL the system was already back online - NO IMPACT
- Added a 1-second delay between reading the google brew and updating it in the `/api/update` path - NO IMPACT
- Increased the autosave to 16 seconds - NO IMPACT

Issue disappeared again shortly after applying a PR with the following two changes:
- Add exponential backup retry logic for `update` calls (exists by default for `GET` calls)
- Pass the user IP address along in the Google API request header

Note, after things came back on again, two separate other people commented on our Google Bug Report, stating they had the exact same issue, with the same timeline of uptime/downtime. It is very possible coming back online again is purely coincidence given it also happened to these two other people.

Rant on the last two items:

> This morning as I should have been getting ready for work, I had one final idea. Well, two final ideas. I implemented both, and am not sure if either had an impact.
> 
> I noticed in the error logs, that they always have this `retryConfig` value:
> 
> ```
>       retryConfig: {
>        currentRetryAttempt: 0,
>        retry: 3,
>        httpMethodsToRetry: [Array],
>        noResponseRetries: 2,
>        retryDelayMultiplier: 2,
>        timeOfFirstRequest: 1727672633510,
>        totalTimeout: 9007199254740991,
>        maxRetryDelay: 9007199254740991,
>        statusCodesToRetry: [Array]
>      }
> ```
> 
> I looked up what this is, and apparently `gaxios` (google api's request handler) has built-in exponential backoff. Interestingly, `currentRetryAttempt` was always 0, meaning retries were never going through. "No problem", I thought, since we want to reduce traffic anyway.
> 
> But I got to thinking, Google seems to _really_ want us to implement exponential backoff for 429 errors. "Won't that just create _more_ requests overall?" I thought. But perhaps... perhaps there is something they are checking on their end to detect if we have such a system set up at all, and they care more about that then the actual number of requests. Some kind of pattern detection on their end.
> 
> So I looked in a little deeper into why retries might not be happening on our update calls. Turns out, there is a buried default setting to only apply retries to `PUT, GET, HEAD, OPTIONS, DELETE` HTTP methods. As G-Ambatte (Sean Robertson) noticed, our update calls use PATCH. So I added a custom `retryConfig` to the update calls. This was step 1. I _think_ retries are happening now, but then we don't get anything in our error logs so I can't prove it.
> 
> Second thing, is I found out about this `x-forwarded-for` header, where you can specify what the originating ip address is. I thought "maybe Google just needs to see the originating ip address from each user so it doesn't think it's all coming from one heroku server in virginia." So I added that header to our update requests as well.
> 
> Sent them both off, and drove to work. I am now seeing the smallest bit of traffic from the api dashboard. Can't actually test though because homebrewery is blocked at my work.
> 
> Can anyone confirm we are alive again?

**Comment by 5e-Cleric** [comment]
Thank you for writing the entire thing, i recommend keeping this open for another 24 or 48 hours, to be safe.

**Comment by calculuschild** [comment]
Sorry to say, the issue with Google Drive has resurfaced. This time, however, we are fairly confident this a Google issue and not with the Homebrewery (though for users, the inconvenience is all the same). We have an open ticket with Google on which at least two other organizations have added their similar comments, and with this latest outage one of those commenters is saying their timeline matches up with ours.

If you feel you are impacted by this issue with saving, [please consider reading through and adding a +1 vote to the ticket [(in the upper right of the comment thread)](https://issuetracker.google.com/issues/369788650). Adding support to a ticket can help it gain traction.

**Comment by Gazook89** [comment]
For record, this has started occurring again about 4 hours ago.  And in the linked google issue, at least one other org mentions they are down as well at about the same time. 

The consensus right now is that this a Google problem.

**Comment by Zarhog** [comment]
is this fixed???????? can i start editing my stuff again????

**Comment by Zarhog** [comment]
reaason im asking is that this issue is still advertised on your webpage

**Comment by calculuschild** [comment]
Google has identified the problem on their end, and they have applied a temporary bandaid, but their final solution is still ongoing.

The bandaid has made things stable for the last few days; you should be fine working for now. But we will keep the message up for a little longer just in case. I would not be surprised if the issue comes back again but crossing fingers we are through the worst of it.

**Comment by Gazook89** [comment]
Google thread seems to indicate this is fixed, and we haven't seen furhter issues. closing this.

**Comment by calculuschild** [comment]
The issue has resurfaced. Reopening.

Users: If you feel you are impacted by this issue with saving, [please consider reading through and adding a +1 vote to the ticket (in the upper right of the comment thread)](https://issuetracker.google.com/issues/369788650). Adding support to a ticket can help it gain traction.

If you need some workaround in the meantime, you can transfer your brew from your Google Drive to the Homebrewery database for the time being by clicking on the colored "Google Drive" icon in the top navbar:

<img width="56" alt="image" src="https://github.com/user-attachments/assets/fde75852-0033-4f76-8c14-a5057eaac447">

This will move the brew out of your Google Drive and into the HB database, where saving works without issue. You can then transfer it back to Google Drive at a later time after the Google Drive issue is fixed. 

Thanks for the report and sorry for any inconvenience!

**Comment by 5e-Cleric** [comment]
Issue should be fixed (again). We will wait a few more days just in case.

**Comment by 5e-Cleric** [comment]
Closing this.
