### ISSUE TITLE
brew language not applied to preview

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#3776]
### Renderer

v3

### Browser

Chrome

### Operating System

MacOS

### What happened?

Loaded a saved brew, opened the properties panel, changed the language to `es`, saved the brew, opened the preview, inspected the rendered brew.

<img width="577" alt="image" src="https://github.com/user-attachments/assets/dabef181-9107-4ffb-8147-5571a28b968b">

**Comment by 5e-Cleric** [comment]
linked to #3294
