### ISSUE TITLE
[ADMIN] Add brew script cleaning function

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3801]
### Your idea:

Currently, users are breaking their brews by saving scripts in them - Imgur embed scripts and the like. While an ideal solution would be to prevent these scripts from breaking the site, in the interim a simple tool which updates the brew content without needing to render it would allow any admin user to fix this issue.

Basically, make an Admin page function that takes in a brew's ShareID and then does a find and replace in that brew's text content to eliminate any script open or close tags.

**Comment by 5e-Cleric** [comment]
Just a search/replace function to work as the codemirror one does, right?

**Comment by G-Ambatte** [comment]
Correct, to break into Regex, something like FIND ALL: `/(<\/?s)cript/` AND REPLACE WITH: `$1` would be sufficient, as it would turn `<script>DO STUFF</script>` into `<s>DO STUFF</s>`

**Comment by ericscheid** [comment]
See also: #546
