### ISSUE TITLE
Table Colors

### ISSUE THREAD

**Issue by bigremy** [naturalcrit/homebrewery#381]
Hey all,

So I practically know nothing about coding, so Homebrew has been a godsend.  I've managed to figure out some tricks and pulled code form various places to get it to do some different things, but how does one change the background color of specific lines in a table?  I have this table: below (don't worry about the spacing I have that fixed).  Homebrew somehow autocolors every other row a light greenish color.  Is there any way to change that color?

Thanks.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

##### Ability Modifier Table
| Ability Score | Ability Modifier Bonus  |
|:-------------:|:-----------------------:|
| 1 - 2 - 3     | -3 |
| 4 - 5 - 6     | -2 |
| 7 - 8 - 9     | -1 |
| 10 - 11 - 12  | 0  |
| 13 - 14 - 15  | +1 |
| 16 - 17 - 18  | +2 |
| 19 - 20 - 21  | +3 |
| 22 - 23 - 24	| +4 |
| 25 - 26 - 27	| +5 |
| 28 - 29 - 30	| +6 |

</pre></code></details>

**Comment by ericscheid** [comment]
The `tr` stripes are set with this css: `.phb table tbody tr:nth-child(odd) { background-color: #e0e5c1; }`

You can override that by entering this into your brew:

```
<style>
.phb table tbody tr:nth-child(odd) {
    background-color: #pink; }
</style>
```
