### ISSUE TITLE
Tweak local deployment Brew Renderer background text color

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3814]
### Your idea:

The white on dark red is reportedly distracting due to the high contrast between the background color and the text. This was not the aim of PR #3688.

**Comment by Gazook89** [comment]
I assume it’s the same colors as posted in gutter, but I think it’s wise to post a screenshot when doing these visual changes, something the original PR lacked (compounded with no mention of text in addition to changing the background color).

**Comment by Gazook89** [comment]
This was meant for the associated new PR, you can post a screenshot there

**Comment by G-Ambatte** [comment]
Style Preview, from the PR:
![image](https://github.com/user-attachments/assets/13f2dbf0-2dee-419f-abdb-269b97fe07a5)
