### ISSUE TITLE
Lag when scrolling editor panel as of 3.16.0

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#3830]
## Description

See
https://reddit.com/r/homebrewery/comments/1g3pxfb/lagging_code_panel_after_3160/
and
https://www.reddit.com/r/homebrewery/comments/1g3p1ku/input_lag_after_the_recent_update/

**Comment by 5e-Cleric** [comment]
https://github.com/user-attachments/assets/fe6de5c7-33f0-425f-855d-24bc8145ce13

There are a number of issues here, all probably caused by excessive rerenders

**Comment by lucastucious** [comment]
I don't know if this is related, but i encounter a lot of slowness since the last update when scrolling code/view, even without syncing. I can link the brew

**Comment by Gazook89** [comment]
@lucastucious want you try this link with the latest update, pre-release, and see if it works better for you? https://homebrewery-pr-3829.herokuapp.com/

Copy and paste your brew in there. But note this is a temporary deployment so don’t expect any actual work to be saved, just for testing changes

**Comment by lucastucious** [comment]
It's extremely smooth. Same navigator, same computer, just a tab next to the official one. It's day & night.

**Comment by 5e-Cleric** [comment]
Nice, that means the fix that we are trying are working.
