### ISSUE TITLE
Edited Brews Not Saving as of V3.16

### ISSUE THREAD

**Issue by Ravenstar50** [naturalcrit/homebrewery#3839]
### Your description of what happened:

Whenever an existing brew is edited, it is never saved. There is no error code that I see - it just never saves (despite trying), almost like it can't contact the server. A new brew saves without issue, but once that saved brew is edited, the same issue arises.

**Comment by calculuschild** [comment]
Can you share a link to one of the brews with this issue? We can check our logs and see what's happening with it.

**Comment by 5e-Cleric** [comment]
Cannot replicate this issue right now.

**Comment by Ravenstar50** [comment]
Here is one brew that has the issue:

https://homebrewery.naturalcrit.com/edit/mPJYsasrey11

**Comment by Gazook89** [comment]
This might be a silly question @Ravenstar50 , but are you just not seeing the autosave trigger?  If you aren't sure, try making an edit and then doing `ctrl` `s` (or `cmd` `s` if on mac) when your cursor is in the editor.  That should manually save.  

If that works to save your brew, two things:  1) autosave recently had it's trigger reduced from the old 3 second delay from the last edit, to something like 10 or 16 seconds, so it might just seem like it's not autosaving as quickly, and 2) you can double check you haven't accidentally turned autosaving off in the Navbar:

<img width="209" alt="image" src="https://github.com/user-attachments/assets/a06d65a3-dfa3-405f-a1c8-4f0a2060175c">


This isn't to discount the possibility that there is something else wrong, but just throwing that info out there in case it's an easy fix.

**Comment by Ravenstar50** [comment]
I already tried that. Whether I wait for it to save or hit the save button, the issue is the same. Is it possible that it's an issue for those that don't have a homebrewery account? Not that it was issue for V3.15, but maybe something changed.

**Comment by calculuschild** [comment]
@Ravenstar50 What result do you actually see? Does it respond with any error message? Does it appear like it saved but when you come back it didn't? Does it just sit there "saving..." and never finishes?

If you could, open up the Chrome Dev tools (CTRL + Shift + i) and click on the "console" tab. Tell us if you see any errors appearing there when you try to save.

**Comment by Ravenstar50** [comment]
It just sits there saving... without ever finishing. While I do see some errors in the console while on the site, none appear while saving. The following error appears whenever I scroll up or down the brew:

Uncaught (in promise) DOMException: A mutation operation was attempted on a database that did not allow mutations.

As I said though, no error appears when attempting to save.

**Comment by calculuschild** [comment]
Are you by chance editing your brews while in incognito mode?

**Comment by Ravenstar50** [comment]
Yes. Does 3.16 not support that?

**Comment by G-Ambatte** [comment]
I've been able to reproduce a very similar state to what was described by forcing an error to occur, but I've been unable to do so without the forced error.

@Ravenstar50 : What browser are you using in Incognito mode? What device and operating system?

**Comment by calculuschild** [comment]
@Ravenstar50 We just sent out a fix that might address this. It's possible being in incognito mode was interfering in our local backup feature, thereby causing the saving action to get stuck, but it should be working now.

Please let us know if you are still having issues saving.
