### ISSUE TITLE
"defaced" gets underlined and becomes blue text

### ISSUE THREAD

**Issue by Dustfinger1** [naturalcrit/homebrewery#387]
Any time I enter the word "defaced" into the editor, it ends up formatted like a link. Its very odd... Nothing happens with just "deface" either. 

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

defaced

</pre></code></details>

**Comment by ericscheid** [comment]
Very odd. Maybe a browser plugin or malware messing with you?

The string "defaced" cannot be found anywhere in code files.
