### ISSUE TITLE
Suggestion: Code Folding

### ISSUE THREAD

**Issue by Rhaenon** [naturalcrit/homebrewery#388]
Loving the homebrewery, noticing that the lengthier pieces I want to write are harder to navigate. Would it be possible to fold the code? Maybe per page, title level or something similar? Where I think titles would be easiest to navigate since they already are their own descriptive comments usually. 

### This Title
would for example act as a spoiler for this text and also 
### This Title
>content folded

**Comment by ericscheid** [comment]
The module we are using for the editor, *codemirror*, does support code folding. https://codemirror.net/demo/folding.html

The complicated thing for HB would be defining a "block". Certainly a "page" can be a block.

Maybe by assuming each heading level is the start of a block.

**Comment by ericscheid** [comment]
A popular suggestion, someone else duped this request in #629 . Closing this issue as has fewer comments.
