### ISSUE TITLE
My link broke when i tried to add page numbers into my pdf.  How do I remedy this?

### ISSUE THREAD

**Issue by rhogarbrassdrake** [naturalcrit/homebrewery#389]
### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by rhogarbrassdrake** [comment]
http://homebrewery.naturalcrit.com/edit/SJlOYXP3Rx

**Comment by calculuschild** [comment]
Sure you didn't delete it? Do you have a user account? If so it should be listed in your profile page.

**Comment by Gazook89** [comment]
4 year old issue, no response from user and cannot reproduce.  If still an issue and more info provided, can be reopened.
