### ISSUE TITLE
Style Editor cannot change class elements

### ISSUE THREAD

**Issue by TheYellowArchitect** [naturalcrit/homebrewery#3896]
### What happened?

Using the style editor, I cannot change `h3` or `.note`. It seems the only elements I can change are those with # aka IDs.

### Code

`### Test`

Style Editor:
```css
h3
{
color: red;
}
```
The above does not work.

As for doing a note.
```gfm
{{note
Test!
}}
```

Style Editor:
```css
.note
{
color: red;
}
```

If I am doing something wrong, freely close this issue. The above element identities are from developer tools, so for an `### test` element, I clicked it and it says plain h3.

**Comment by Gazook89** [comment]
Try putting `.page` at the start of each selector. You have to override the default css, which uses that selector.

**Comment by Gazook89** [comment]
So `.page h3 {`

**Comment by TheYellowArchitect** [comment]
You are right, thank you!
