### ISSUE TITLE
naturalcrit.com/login does not use HTTPS

### ISSUE THREAD

**Issue by danielricks** [naturalcrit/homebrewery#390]
This doesn't really fit on the github, because it has to do with your specific instance of the site, but the login page of your site isn't secure. Or at least Google Chrome v57 doesn't recognize it as secure.

![insecure](https://cloud.githubusercontent.com/assets/2449536/25462050/b0200efa-2aa9-11e7-8efa-491f3d15caa6.png)

Anyway, you're a web guy, and it seems like it should be secure by default. Could you look into this?

**Comment by AlexeySachkov** [comment]
Homebrewery was switched to use https. @calculuschild, @ericscheid, we can close this now

**Comment by calculuschild** [comment]
Closing because this was solved.

**Comment by ericscheid** [comment]
`homebrewery.naturalcrit.com` does use _https_, but `www.naturalcrit.com` (where the login function resides) does not.

(the title for this issue, per the OP description, should really be more like "account login for homwbrewery is not secure")

![image](https://user-images.githubusercontent.com/2605467/102595244-63680680-416b-11eb-932b-16f90d2679e6.png)

**Comment by calculuschild** [comment]
Good eyes. Ok I can get https on the login site.

**Comment by calculuschild** [comment]
Ok _now_ this is fixed.
