### ISSUE TITLE
Page shadows checkbox in toolbar page view options is not working

### ISSUE THREAD

**Issue by 5e-Cleric** [naturalcrit/homebrewery#3919]
The page shadows checkbox currently has no effect on the actual shadow of the pages as of today. It's likely a last minute change to fix or clear some other function that broke it.

**Comment by Gazook89** [comment]
I think it needs to be fixed right here, adding a dependency to the useMemo for `displayOptions.pageShadows` to the renderPages function:

https://github.com/naturalcrit/homebrewery/blob/e28b4e8c204e36041991fea92fd350c30fa05efd/client/homebrew/brewRenderer/brewRenderer.jsx#L220
