### ISSUE TITLE
Cannot Open Brews

### ISSUE THREAD

**Issue by StriderUrbs** [naturalcrit/homebrewery#392]
To whom it may concern,
I use an iPad, and every time I have closed and reopened Chrome, the brew I have been working on has completely disappeared. This would not be a problem if I could actually press the "Edited" button in the "Recent Brews" tab. When I try, it simply keeps highlighting the "Receht Brews" tab instead of clicking the button which I am very definitively  pressing. I have tried zooming in, I have tried pressing all around, but I can press neither the "Edited" nor the "Viewed" button. Furthermore, either I was never given an Edit URL for my brew, or it was put somewhere I never would have seen it.

The Brew I lost is called "The Quintescer" and I know not the code nor link for it. If you could help me, that would be marvellous.

—Jack Urbanski

**Comment by calculuschild** [comment]
Yeah, the "Recent Brews" is broken at the moment. The Edit URL you needed was just the URL in the address bar at the time you were making your brew. If you didn't copy and paste from there it's probably lost in the nether for now.

It is much much easier to just create an account. When you are logged in, any brews you edit will be saved to your account; you will see them listed out when you view your profile page.

**Comment by calculuschild** [comment]
Closig this. Recent Brews tab was fixed some time ago.
