### ISSUE TITLE
Editor crashes when accessing Metadata Panel

### ISSUE THREAD

**Issue by G-Ambatte** [naturalcrit/homebrewery#3927]
### Renderer

v3

### Browser

Chrome

### Operating System

Windows

### What happened?

When accessing the Metadata panel, the Homebrewery edit page crashes to a white screen.

Console shows an error occurred: `values.map is not a function`.

Affected brew link: https://homebrewery.naturalcrit.com/share/bD6vc20VG9JU

**Comment by G-Ambatte** [comment]
At the surface level, the error occurs when the TagInput component is passed a `values` parameter that is a string, not the expected array. Adding parameter sanitization to the component prevents the crash from occurring.

**Comment by G-Ambatte** [comment]
The root cause of this error is that the `tags` property is loaded from the metadata contained in the brew data itself - while the `tags` field is correctly an array during initial loading of the brew, once the data is passed through the `splitTextStyleAndMetadata` function, `tags` becomes an empty string.

This is because the value for `tags` in the internal metadata is literally `tags: ''`, whereas the YAML for an array containing an empty string would be `tags: ['']`:
![image](https://github.com/user-attachments/assets/3cbfc60e-c8a9-41e3-ade6-b102d6ebc5c9)

**Comment by calculuschild** [comment]
Ok, let's correct this so its just always an array.

**Comment by G-Ambatte** [comment]
I'll push a PR shortly; my current approach is to add a sanity check at the end of `splitTextStyleAndMetadata`, if `brew.tags` is a string, check for actual content. If empty string, set `brew.tags` to `[]`, otherwise set to `[ brew.tags ]`.
