### ISSUE TITLE
Unable to Separate Statblock/Note

### ISSUE THREAD

**Issue by bobdude0987654321** [naturalcrit/homebrewery#396]
It is currently not possible to have a note beneath a statblock, as the note will appear as part of the stats. This has proven extraordinarily irritating, as I'm designing a rather lengthy monster manual wannabe using this tool, which is otherwise brilliant.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

___
> ## Adherer
>*Medium monstrosity, lawful evil*
> ___
> - **Armor Class** 15
> - **Hit Points** 46 (7d8 + 14)
> - **Speed** 30 ft., climb 10 ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|14 (+2)|16 (+3)|14 (+2)|4 (-3)|15 (+2)|14 (+2)|
>___
> - **Saving Throws** Dex +5, Wis +3
> - **Skills** Athletics +6, Perception +5, Stealth +7
> - **Senses** darkvision 60 ft., passive Perception 15
> - **Languages** knows Abyssal but can't speak
> - **Challenge** 3 (700 XP)
> ___
> ***Adhesive.*** The adherer sticks to anything that touches it. A Huge or smaller creature stuck to the adherer is also grappled by it (escape DC 15). Ability checks made to escape this grapple have disadvantage. There is no limit to the number of creatures or weapons that an adherer can grapple simultaneously.
>
>***Grappler.*** The adherer has advantage on any attack rolls against creatures grappled by it.
> ### Actions
> ***Multiattack.*** The adherer makes two attacks with its slams.
>
> ***Slam.*** *Melee Weapon Attack:* +5 to hit, reach 5ft., one target. *Hit* 10 (2d6 + 3) bludgeoning damage, and the creature is grappled.
>### Reactions
> ***Stick.*** The adherer can automatically initiate a grapple upon being hit by a melee attack. If the attack is natural from a natural weapon or unarmed strike, the creature is grappled. If not, then the creature is disarmed, and the weapon can only be unstuck by performing a DC 13 Athletics check. This check does provoke an attack of opportunity.

 
> ##### Variant: Electrocuter
>Some of the adherers on the material plane have been imbued with additional energy. These are known as Electrocuters, have a CR of 4 (1,100 XP), and gain the following features:
>* ***Death Burst.*** When the electrocuter dies, it explodes in a burst of lightning. Each creature within 10 feet of it must make a DC 13 Dexterity saving throw, taking 7 (2d6) electric damage on a failed save, or half as much damage on a successful one. Grappled creatures automatically fail this save.
>* ***Electrically Charged.*** Grappled creatures are electrocuted, and take 7 (2d6) damage on each of the adherer's turns.

</pre></code></details>

Similarly, notes forced to the very top of a page have the top portion of their graphic coming out the bottom of the page in the adjacent column. This is the code for an entire page, fair warning.
**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>
<div class='pageNumber auto'></div>
## Adherer
One of the most feared undead creatures in the world is the mummy - - typically, the sight of a humanoid shambling towards a party of adventurers spells certain doom for the would-be plunderers of ancient treasure. It is unknown what malevolent forces created the adherer, but whatever it was, it was well aware of this fear, and shaped the adherer to utilize it well to their advantage.

***Living Yet.*** The adherer was, at one point, a mortal; when this mortal died, its spirit journeyed into the Ethereal Plane, where forces strange and powerful began to subject it to alien energies. These energies, when combined with the spirit, manifested into a new consciousness, warping and absorbing the original spirit as it did so. These energies were then used to wrap the creature, stabilizing its new form with powerful magical adhesives and giving it the appearance of a mummy. Be wary not to cast healing magic upon an adherer  thinking it undead-- it is living, and you are playing directly into its hands.

The purpose for this complex creation is unknown, but adherers have sometimes been seen performing what looks to be demonic rituals. The creatures are not intelligent, and so must have been ingrained with the knowledge of how these rituals work as well as when to perform them at creation. Like their creation, the purpose for the ritual is unknown, but it is possible that an evil god thought dead lives yet in the Deep Ethereal, and is creating as many subjects as they can to return their own strength.

***Mummy Imposter.*** Adherers lurk where traffic is scarce, but existent, waiting for prey to isolate itself, and thus be marked as an easy target. Their prefered lairs are areas where mummies might stand guard, or even where a mummy does slumber, but simple caves as well as forests are recorded haunts. When the adherer sees an opportunity, it will prefer to drop on its target from above, but if this is not possible, it will shamble slowly into their field of view before exploding forward in a sudden burst of speed.

***Adhesive Touch.*** The power that binds their spirit into a stable body doubles as a powerful adhesive, and the creatures use it to their advantage. Adherers excel in close-quarters combat, thanks to this ability, and when a fight has begun they almost exclusively use a one-two combo of sticking their opponent's weapon to themselves and then grappling the opponent themself.

This adhesive sticks to any surface or material, but there are ways around it. Fire, for instance, temporarily dissolves this effect, and acid is even more effective. While this adhesive certainly sounds useful, don't waste your time hunting an adherer to obtain it-- the energies binding an adherer cease to function about an hour after the creature is deceased, releasing any objects bound by the rags as they turn to a cold white mist.

***Patient Eaters.*** Adherers, when not in combat, are incredibly patient, though this patience tends to translate into everything they do being incredibly slow, including digestion. An adherer can survive on its favored prey, humanoids, for days or even weeks, taking only one or two bites per day and leaving their victims to die a terrifying, drawn-out death. Once its food is expired, an adherer moves on, leaving what's left of its corpse to any scavengers that have learned to follow it.
> ##### Variant: Electrocuter
>Some of the adherers on the material plane have been imbued with additional energy. These are known as Electrocuters, have a CR of 4 (1,100 XP), and gain the following features:
>* ***Death Burst.*** When the electrocuter dies, it explodes in a burst of lightning. Each creature within 10 feet of it must make a DC 13 Dexterity saving throw, taking 7 (2d6) electric damage on a failed save, or half as much damage on a successful one. Grappled creatures automatically fail this save.
>* ***Charged.*** Grappled creatures take an additional 4 (1d6) electric damage from this adherer's slam.

___
> ## Adherer
>*Medium monstrosity, lawful evil*
> ___
> - **Armor Class** 15
> - **Hit Points** 46 (7d8 + 14)
> - **Speed** 30 ft., climb 10 ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|14 (+2)|16 (+3)|14 (+2)|4 (-3)|15 (+2)|14 (+2)|
>___
> - **Saving Throws** Dex +5, Wis +3
> - **Skills** Athletics +6, Perception +5, Stealth +7
> - **Senses** darkvision 60 ft., passive Perception 15
> - **Languages** knows Abyssal but can't speak
> - **Challenge** 3 (700 XP)
> ___
> ***Adhesive.*** The adherer sticks to anything that touches it. A Huge or smaller creature stuck to the adherer is also grappled by it (escape DC 15). Ability checks made to escape this grapple have disadvantage. There is no limit to the number of creatures or weapons that an adherer can grapple simultaneously.
>
>***Grappler.*** The adherer has advantage on any attack rolls against creatures grappled by it.
> ### Actions
> ***Multiattack.*** The adherer makes two attacks with its slams.
>
> ***Slam.*** *Melee Weapon Attack:* +5 to hit, reach 5ft., one target. *Hit* 10 (2d6 + 3) bludgeoning damage, and the creature is grappled.
>### Reactions
> ***Stick.*** The adherer can automatically initiate a grapple upon being hit by a melee attack. If the attack is natural from a natural weapon or unarmed strike, the creature is grappled. If not, then the creature is disarmed, and the weapon can only be unstuck by performing a DC 13 Athletics check. This check does provoke an attack of opportunity.

</pre></code></details>

**Comment by misthero** [comment]
you can separate the note from the stat block using  3 "_"

___

**Comment by bobdude0987654321** [comment]
Thanks for the quick reply. Any fix for the issue with note graphics appearing at the bottom of the opposite column?

**Comment by calculuschild** [comment]
You can put something like a `<div></div>` between the two.

**Comment by calculuschild** [comment]
We should check if this is still an issue. Having to insert extra code like this is not a good solution.

**Comment by ericscheid** [comment]
This no longer occurs - the blockquote markup used to allow blank lines (e.g. to separate paragraphs) and they'd be collected into the one blockquote.

The markedjs library no longer does this. If you want multiple paragaphs in a note you now need to enter a `>` on the blank line.

This also means a monster stat block (which is just quote marked lines preceded by a `hr`) won't attach to a following note block .. just put a blank line between them.

Closing.
