### ISSUE TITLE
Inconsistent Bolding

### ISSUE THREAD

**Issue by bobdude0987654321** [naturalcrit/homebrewery#402]
The PDFs of files are too thick and bolded in statblocks.

Example: https://gyazo.com/6059a8ee9853db4d4865b8a758e0f891

**Comment by calculuschild** [comment]
Closing since there have been many related improvements in the last years, and this has likely been fixed (cannot reproduce).

Feel free to reopen this issue if it is still a problem, @bobdude0987654321
