### ISSUE TITLE
View count on user's views reset

### ISSUE THREAD

**Issue by jimcullenaus** [naturalcrit/homebrewery#406]
Not sure exactly what happened or what caused it. But the view count on my user page for one of my published brews dropped from over 500 to under 100. I suspect something triggered it to reset entirely, and it grew back up to 82 before the next time I saw it.

May or may not have something to do with the fact that minor alterations to the brew were made. However, I could not reproduce by altering other published brews.

http://homebrewery.naturalcrit.com/user/Zagorath

http://homebrewery.naturalcrit.com/share/4kCj3fbal

**Comment by calculuschild** [comment]
This was long enough ago that I think this issue no longer exists. Closing.

**Comment by ericscheid** [comment]
See https://github.com/naturalcrit/homebrewery/issues/1221#issuecomment-812151150
