### ISSUE TITLE
Cannot delete brew that is unrederable. 

### ISSUE THREAD

**Issue by ahiddenwaffle** [naturalcrit/homebrewery#414]
Upon creating an unrenderable brew, it cannot be deleted, not even from the user page, click the trash icon simply does nothing.

Furthermore, no brews can be deleted from the user page anymore.

**Comment by calculuschild** [comment]
I can still delete brews from the user page....

**Comment by ahiddenwaffle** [comment]
Odd, both me and my friend were unable to, using Chrome.

**Comment by AlexeySachkov** [comment]
@calculuschild, @ericscheid, I suggest that we close this one

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @ahiddenwaffle
