### ISSUE TITLE
Suggestion: Option for different fonts

### ISSUE THREAD

**Issue by SANSd20** [naturalcrit/homebrewery#419]
Ability to to use fonts like Dwarvish, Elvish, ect.

**Comment by miko3ed** [comment]
There's nothing that stops you from using fonts now. Here is an example of some code that I have used in the past to customize fonts, using both google font options and custom fonts that I have uploaded to Amazon S3 (I did edit the s3 links to hide my domain, so don't expect that to just work if you are exactly copy-pastaing my code, you'll need to upload your own fonts to where ever you want to host them).

`
<link href="https://fonts.googleapis.com/css?family=PT+Serif:700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
<style>
   @font-face {
      font-family: 'splendorsregular';
      src: url(https://s3.amazonaws.com/blahblahblah/splendors.ttf) format('truetype');
      src: url(https://s3.amazonaws.com/blahblahblah/splendors-webfont.woff2) format('woff2'),
           url(https://s3.amazonaws.com/blahblahblah/splendors-webfont.woff) format('woff');
      font-weight: normal;
      font-style: normal;
   }
</style>

<style>
   h1#welcomeheader {
      text-align: center; 
      font-family: splendorsregular; 
      margin-bottom: 40px; 
      font-size: 500%; 
      font-weight: normal; 
      font-style: normal;
   }
   
   #letter {
      font-family: 'Satisfy', cursive;
      font-size: 130%;
   }
</style>

`

**Comment by vlos** [comment]
I posted a homebrewery up on how to do this along with a site for accessing the custom fonts.

https://www.reddit.com/r/UnearthedArcana/comments/5octs2/rpg_fonts_for_homebrewery_resource/

Hope this helps./

**Comment by calculuschild** [comment]
We might look into adding these fonts directly into the Homebrewery. @vlos , are these fonts made by you, or do you know where they came from? If they are open-source we could make a special snippet for this.

**Comment by vlos** [comment]
CC, most of these  I converted from free TT fonts (found on the web) to a WebFont.  For example the Espruar font, was originally a font from an Old TSR module, which I converted to a TT font back in mid 90s. You can find many versions of it on the web today, but again I had to convert it to a Webfont, which only now are becoming more popular.

**Comment by 5e-Cleric** [comment]
I believe right now, all fonts from the PHB are in the live site, including Dwarven, elvish and draconic, the ones still left are the part covers ones but that PR is almost done, so i am closing this as compñeted for now.

**Comment by calculuschild** [comment]
We still need to add some kind of snippets for these. We do have the "script table" snippets but we also need something that just applies the font to a span. Like `{{font-family:"rellanic" My Text}}`.

We are also missing some other fonts we had planned: Celestial, Demonic, etc.

**Comment by G-Ambatte** [comment]
I've been updating the "Example: Included Fonts - v3" brew that I made a while ago to include the new fonts, if and when and as I remember them.

![image](https://user-images.githubusercontent.com/19826659/235409135-90fa50e2-d753-46f9-a4f9-da2785a72e4a.png)

**Comment by 5e-Cleric** [comment]
Basic PHB language fonts are added as snippets in #3203

**Comment by calculuschild** [comment]
Yeah we can probably close this now. We can always add more fonts later but the core festure is complete now.
