### ISSUE TITLE
Request: Strikeout Text

### ISSUE THREAD

**Issue by TheSwartz** [naturalcrit/homebrewery#422]
Sorry, not an issue, but a request: ability to add Strikeout text.

I find that there is an HTML tag for this (strike), however on your latest example, you mention that v3.0.0, this tool will no longer support raw HTML input for brew code. 

I'm not smart at these things, I don't know if this is something that will be removed. But if so, please add a way to continue to do this?

Thanks for your consideration!

**Comment by calculuschild** [comment]
In the new version it sounds like you will be able to still use CSS in a separate style sheet, which should support strikeout text.

**Comment by ericscheid** [comment]
This is now possible with markdown code of `~~zapp~~`, which renders as `<del>zapp</del>` and appears as ~~zapp~~.

Done. Closed.
