### ISSUE TITLE
PDF doesn't render the same as on brew page

### ISSUE THREAD

**Issue by axe8472** [naturalcrit/homebrewery#423]
When I type the brew out, it shows on the right-hand screen that the text is arranged in two rows. However, when I click "Get PDF" the image shown there doesn't have rows. Instead, each block of text spans the entire page. How do I fix this? I tried adding column breaks but that accomplished nothing.

  Any suggestions would be fantastic.
  Thanks in advance.

**Comment by calculuschild** [comment]
If you provide the "share" link someone can see what's going on.

**Comment by witchjnr** [comment]
im having the same issue.  The PDF renders without the columns

**Comment by calculuschild** [comment]
It's really hard to help without seeing your project. Please paste the
share link.

**Comment by witchjnr** [comment]
The share link shows columns - but the pdf doesn't http://homebrewery.naturalcrit.com/share/BJLvi3ozW

**Comment by calculuschild** [comment]
I get no problems printing to PDF. I noticed trying to print in Firefox did not create a proper PDF; this site is designed _only_ for Chrome. Are you sure you are using the latest version of Google Chrome?  My PDF looks like this, with two columns:

![image](https://user-images.githubusercontent.com/5878534/27040374-c94cf350-4f5e-11e7-8e13-47732d67c780.png)

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @witchjnr , @axe8472
