### ISSUE TITLE
Idea: Ready-made templates

### ISSUE THREAD

**Issue by ProfessorPirate** [naturalcrit/homebrewery#426]
It might be helpful to have some pre-made templates for different character sheet styles/versions with a handful of standard characters like those in the basic rule guides. By doing this you could minimize the learning curve and speed up the creation process.

**Comment by calculuschild** [comment]
Are the pre-made snippets not already filling that role?

**Comment by ProfessorPirate** [comment]
The snippets do part of the job. Granted I'm new to D&D so feel free to take this with a grain of salt (or a few). I was just thinking that you might be able to group the snippets in a way to mimic a full character sheet. The idea I had was to choose a template such as D&D 3.5, D&D 5, etc.; then the related snippets would be all be added at once in an appropriate order. The user could still add/remove snippets and edit using the current system. This would only group some of the common items together instead of having to grab each individually.

Like I said, I'm new to this world so I could see how this idea might also undermine the focus on customization. As a newb its a helpful from my point of view. Fortunately I'm a programmer so it's easier for me to jump in and get an idea of how the site works, but not everyone has that skill. Again, I may be missing the point, but I thought I'd throw it out there. Let me know if I'm not being clear enough or if you need anything else from me.

**Comment by Sansd20** [comment]
When you say character sheet, do you mean the sheet with that stats that is in front of the players when they play?

**Comment by ProfessorPirate** [comment]
Yes, I was thinking about the typical character sheets. I attached a copy of one just to give a visual. I think the attachment is a little overkill, especially if the character is not a magic user. However, just having a starting point (template) to work from can help make it easier to get familiar with the environment. By no means would you have to duplicate the visual style in the attachment, just the content itself. I think the visual output you provide is fantastic. I just think a couple starting templates might be useful for newcomers. I hope I cleared that up a little, but let me know if I didn't.
[DnD_5E_CharacterSheet - Form Fillable.pdf](https://github.com/stolksdorf/homebrewery/files/1352731/DnD_5E_CharacterSheet.-.Form.Fillable.pdf)

**Comment by Sansd20** [comment]
That is what I was thinking you meant. I do like the idea; however, I think that is outside the scope of this project. Homebrewery is to give users the ability to format their homebrew content into a format that looks like the PHB.

**Comment by ProfessorPirate** [comment]
Ahh, I gotcha. Then yes. That is totally out of scope. That makes so much sense now. I guess I was just confused about how to use the site.

**Comment by Sansd20** [comment]
You don't have to use the site that way; I do use it to make player aids: http://homebrewery.naturalcrit.com/share/By1ppsLo-

**Comment by ericscheid** [comment]
Out of scope. Closing.
