### ISSUE TITLE
Cover sheet function does not center on any page after first

### ISSUE THREAD

**Issue by arcairn** [naturalcrit/homebrewery#427]
Pretty much just like I said, when trying to make a cover sheet for the first chapter (similar to parts one two and three having two full pages of images in the phb) the format is aligned to the left instead of center.

**Comment by ericscheid** [comment]
The snippet that it inserts specifically targets page 1. You can get it to target other pages by changing the `#p1` as appropriate.

```
<style>
  .phb#p1{ text-align:center; }
  .phb#p1:after{ display:none; }
</style>
```
