### ISSUE TITLE
The Class Table Spellcasting Progression is Slightly Off

### ISSUE THREAD

**Issue by swordmeow** [naturalcrit/homebrewery#429]
The default class table full spellcasting progress is slightly off from full spellcasting.  Please fix this, it's mildly infuriating to go in and tweak it.

**Comment by swordmeow** [comment]
##### The Sorcerer
| Level | Proficiency Bonus | Features | Cantrips Known | Spells Known | 1st | 2nd | 3rd | 4th | 5th | 6th | 7th | 8th | 9th |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st | +2 | Spellcasting, Sorcerous Origin | 4 | 2 | 2 | — | — | — | — | — | — | — | — |
| 2nd | +2 | Font of Magic | 4 | 3 | 3 | — | — | — | — | — | — | — | — |
| 3rd | +2 | Metamagic | 4 | 4 | 4 | 2 | — | — | — | — | — | — | — |
| 4th | +2 | Ability Score Improvement | 5 | 5 | 4 | 3 | — | — | — | — | — | — | — |
| 5th | +3 | Metamagic | 5 | 6 | 4 | 3 | 2 | — | — | — | — | — | — |
| 6th | +3 | Sorcerous Origin feature | 5 | 7 | 4 | 3 | 3 | — | — | — | — | — | — |
| 7th | +3 | Metamagic | 5 | 8 | 4 | 3 | 3 | 1 | — | — | — | — | — |
| 8th | +3 | Ability Score Improvement | 5 | 9 | 4 | 3 | 3 | 2 | — | — | — | — | — |
| 9th | +4 | — | 5 | 10 | 4 | 3 | 3 | 3 | 1 | — | — | — | — |
| 10th | +4 | Metamagic | 6 | 11 | 4 | 3 | 3 | 3 | 2 | — | — | — | — |
| 11th | +4 | — | 6 | 12 | 4 | 3 | 3 | 3 | 2 | 1 | — | — | — |
| 12th | +4 | Ability Score Improvement | 6 | 12 | 4 | 3 | 3 | 3 | 2 | 1 | — | — | — |
| 13th | +5 | Metamagic | 6 | 13 | 4 | 3 | 3 | 3 | 2 | 1 | 1 | — | — |
| 14th | +5 | Sorcerous Origin feature | 6 | 13 | 4 | 3 | 3 | 3 | 2 | 1 | 1 | — | — |
| 15th | +5 | Metamagic | 6 | 14 | 4 | 3 | 3 | 3 | 2 | 1 | 1 | 1 | — |
| 16th | +5 | Ability Score Improvement | 6 | 14 | 4 | 3 | 3 | 3 | 2 | 1 | 1 | 1 | — |
| 17th | +6 | Metamagic | 6 | 15 | 4 | 3 | 3 | 3 | 2 | 1 | 1 | 1 | 1 |
| 18th | +6 | Sorcerous Origin feature | 6 | 15 | 4 | 3 | 3 | 3 | 3 | 1 | 1 | 1 | 1 |
| 19th | +6 | Ability Score Improvement | 6 | 15 | 4 | 3 | 3 | 3 | 3 | 2 | 1 | 1 | 1 |
| 20th | +6 | Sorcerous Restoration | 6 | 15 | 4 | 3 | 3 | 3 | 3 | 2 | 2 | 1 | 1 |

Here is the correct progression

**Comment by ericscheid** [comment]
Looks about right

https://5thsrd.org/character/classes/sorcerer/
https://5thsrd.org/character/classes/druid/
https://5thsrd.org/character/classes/cleric/
