### ISSUE TITLE
Change HTML Title of 'Print' page to Brew Title

### ISSUE THREAD

**Issue by wrdclark** [naturalcrit/homebrewery#430]
The current 'print' page uses the standard page title
    <title>The Homebrewery - NaturalCrit</title>
This is then suggested as the default filename when saving to PDF. It would be more convenient if this was set to the brew title, as in my experience that is usually the desired filename.

**Comment by ericscheid** [comment]
Done in https://github.com/naturalcrit/homebrewery/pull/1075
