### ISSUE TITLE
Table of Contents issues

### ISSUE THREAD

**Issue by sorakite5** [naturalcrit/homebrewery#437]
Using the table of contents I've noticed formatting issues when you have a large amount of info for it to list.

Specifically, the table's columns act oddly whenever the information would be listed on more than one column. The first column of info will usually be pushed into the 2nd or (nonexistent in view) 3rd column, with the rest following after as normal. This is, however, fixable through adding spaces in various places and not really a big deal.

Another issue came up with any brew large enough to need a table of contents more than one page, which is that the ToC determines what page number in the document to link to when it is created. This means that when you create new pages to ensure the entire table is visible, the page numbers of the rest of the document change. This could  be fixed by putting the ToC at the end of the brew, thus making it not affect the other stuff in the document, but that would be odd to do. Potential work around for that is creating empty pages and deleting them after making the table, but I'm mentioning this in case there is a way to fix it properly rather than work around it.

**Comment by GlorianStrifle** [comment]
Sorry, could you explain how to fix the first issue by adding spaces please? Whenever I get to the bottom of a table of contents (or, in some cases, regular text), the writing ignores the divider, and if it reaches the bottom of the page, moves towards the 2nd column, leaving a blank space for the 1st. Thankyou.

**Comment by calculuschild** [comment]
V3 has significantly improved table of contents and a better generator that will read all of your headers and update page numbers.
