### ISSUE TITLE
Stat Block Bold & Italic disappears in PDF

### ISSUE THREAD

**Issue by misalo1** [naturalcrit/homebrewery#440]
When I Save as PDF the Monster Stat Block looses it's Bold & Italic fonts.

Using Crome with Windows Vista

Get PDF (Button)

Save as PDF
Layout <Portrait>
Paper Size <Letter>
Margins <Default>
Background Graphics <on>

[Hellcat (77).pdf](https://github.com/stolksdorf/homebrewery/files/1133290/Hellcat.77.pdf)

**Comment by calculuschild** [comment]
Can you provide the **share link** to your document so we can see what code might be causing the issue?

**Comment by calculuschild** [comment]
Closing for now because of no further response from the user, and the issue does not have enough information to fix.

Feel free to reopen this issue if this is still a problem for you and you can provide more information, @misalo1
