### ISSUE TITLE
Text overlapping during PDF-making

### ISSUE THREAD

**Issue by impersonater** [naturalcrit/homebrewery#448]
When I go to print the page using normal instructions, the right hand column reverts back to the left hand column and overlaps itself onto it.  Here's a link to the PDF.  The issue is on page 9.

### Additional Details

**Share Link** :
https://drive.google.com/file/d/0B_fO9drMhlUealJLdFBXTHp2OG8/view
or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

#### Bonus Proficiencies
At 1st level, you gain bonus proficiencies.  You are proficient in light and medium armor and your choice of four weapon that can be simple or martial.  Additionally, you are proficient in one weapon from the signature weapon chart below or one unique weapon that your DM approves of.

#### War Cry
At 3rd level, you can turn the tides of battle by emitting your presence in the form of a wary cry.  As a bonus action, you may emit a signature war cry.  When you do so, roll a 1d6.  You must then use your action on the same turn to attack an enemy, with the result of the die as a bonus to your attack.  If your strike succeeds, you gain half that number (a minimum of 1) as a bonus to both attack and damage rolls for 1 minute.  Additionally, if your initial strike succeeds, all allies within 60 feet that can see you hit your oponnent have a bonus on their next attack roll equal to the result of the 1d6 roll, so long as their attack is made within a number of rounds equal to your levels in noble.  You may not apply this bonus to more allies than you have levels in the noble class.   You can only use this feature once each time you roll initiative.  

#### Extra Attack
Starting at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.

#### Uncanny Grace
At 7th level, you have learned to use your majestic presense in the heat of a battle. You may reduce your majesty score by 1 to take a Dash, Disengage, or Dodge action as a bonus action.  You must have a majesty score of 6 to be able to use this feature.

<img 
  src='https://s32.postimg.org/7rgyeyuad/image.png' 
  style='position:absolute; top:0px; right:-20px; width:600px' />
  
#### Majestic Strike
At 11th level, you may now inspire yourself with your own majestic strikes.  Whenever you hit a target creature, you may reduce your majesty score by 2 to deal an additional 2d6 damage to that target with the same damage type as the weapon you struck with.  You may further reduce your majesty score by 2 to increase this by 1d6, to a maximum of 5d6 extra damage and by reducing your majesty score by 8.

#### Legendary Acrobatics
At 14th level, you may inspire yourself to new feats of acrobatics.  As a bonus action and by reducing your majesty score by 4, you enter into a state of exceptional combat prowess.  Your movement speed increases by 10, you may now take a second extra attack whenever you take the Attack action on your turn (to a total of 3), and you have advantage to Dexterity saving throws and Dexterity skill checks.  This lasts for 1 minute or until you dismiss it.  When the state is over you must reduce your majesty score by another 4 (if you can) or you gain one level of exhaustion.

#### Unrelenting
At 17th level, your own will and presence becomes so self-inspiring that you can withstand continuous combat. Whenever your hit points are above half of your maximum hit points, you may, as a bonus action and by reducing your majesty score by 1, use the healing pool of your Encouraing Words toreinvigorate your morale and heal yourself normally.

```
```

<div style='margin-top:-355px'></div>

##### Lineage of Warfare -- Signature Weapons 
| Name | Cost | Damage | Weight | Properties |
|:----|:-------------:|  :---: |   :----:  |  :----:   |
| Bola | 1gp | 1d4 bludgeoning | 1/4 lb.|  Special, finesse, thrown (range 20/60)  |
| Chakram  | 50gp |  1d6 slashing | 1 lb. | Special, finesse, thrown (range 15/30) |
| Warfan| 100gp |  1d6 slashing | 2 lb. |  Special, Finesse |
| Scourge | 5gp |  1d6 slashing | 2 lb. | Finesse |

## Bola
A large or smaller creature hit by a bola is restrained until it is freed.  A creature that is formless is unaffected.  A creature can use its action to make a DC 10 Strength check, freeing itself or another creature on a sucess.  
<div class='pageNumber auto'></div>
<div class='footnote'> THE NOBLE CLASS</div>
\page

</pre></code></details>

**Comment by calculuschild** [comment]
Closing because this appears to be solved. The linked PDF does not show the issue any longer.
