### ISSUE TITLE
Account creation problem

### ISSUE THREAD

**Issue by PaleMage** [naturalcrit/homebrewery#450]
After following the instructions on registering to Hombrewery, I ended up in an account unable to do anything. Every time I reconnect to my account I see no saved brews in my account, nor I can do anything on my profile. Still able to edit brews, but if saved they disappear at my next login.

Think there has been a problem in the account creation process, cause I know that thousands of people are currently using the Hombrewery.

Please fix and/or remove my account (fabio.monty.montanari@gmail.com)

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
there has been an issue with logging in with email addresses as a username. Can you try logging in without the @gmail.com, or make a new account being sure not to put the @gmail.com in there?

**Comment by PaleMage** [comment]
How? I cannot get a clean access to the homebrewery, nor I get any menu command to logout/remove account.
Any guess?

**Comment by calculuschild** [comment]
Try logging out on this page http://www.naturalcrit.com/login

**Comment by calculuschild** [comment]
No further info from user. Closing.
