### ISSUE TITLE
Cant view past brews!

### ISSUE THREAD

**Issue by Freekoutintro** [naturalcrit/homebrewery#459]
Whenever i click on my username in the top right it brings me back to the Homebrewery guide you see when you first get in before you create a new document. It would be very nice to see my old brews without having to have them permanently bookmarked.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by ericscheid** [comment]
Closing. Old issue resolved.
