### ISSUE TITLE
Enter code blocks

### ISSUE THREAD

**Issue by davidthegnome** [naturalcrit/homebrewery#465]
Need a way to escape characters to present code blocks.

Example: Trying to explain how to post quests in our West Marches game. THey are entered by beginning and ending post with ```, but the ` is part of the markup, so I cannot display more than one.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
Can you provide some more information or a Share Link to the document you are working on showing what you are trying to do?

**Comment by davidthegnome** [comment]
Hello Trevor,

I am no longer working on that document. I may be able to find a link if I look for awhile. I believe what I was trying to do was describe to someone how to create a block of information in Discord using ‘’’  and when typing that in, the homebrewery page though I was doing a command rather than wanting to display that as text.

**Comment by Gazook89** [comment]
I think this is solved in v3 by replacing the backtick syntax with `\column`, and now code/pre blocks can be done with the backticks.
