### ISSUE TITLE
Notes: lower in column 2 than column 1

### ISSUE THREAD

**Issue by Gadget2020** [naturalcrit/homebrewery#478]
```
> Column 1 starts here (insert column break)

```
```

> Column 2 starts here
```

I can only drop column 1 to match column 2 - I can't find a way to raise column 2.

**Comment by Rae2che5** [comment]
Oddly the default CSS adds a 13-pixel top margin for `pre+blockquote`, i.e. for notes after a column break. I assume that's there for a reason, so I'm reluctant to disable that bit of the default style; instead, you could drop the note in the first column by a matching amount. Add this to the beginning of your brew:

```
<style>
.phb>blockquote:first-child, .phb>style:first-child+blockquote { margin-top: 13px; }
</style>
```

**Comment by DoctorDan1986** [comment]
Solve one problem, create another.  I've tried to do this, but I've run into a new problem introduced:

Whenever you create a new column, trying to implement a Wide Block of text anywhere on the page (Like, say, you wanted to write a funny disclaimer on the Credits page over the cover picture)...well, you can't.  Depending on location, you'll either push the second column off the page, it will screw up the entire text alignment, or it will simply not show the text  that passes into the defined second column's space.  It'd be nice if you could create a false 'end of page' thing that would stop the column processing below a user-defined point, something like
`</column>`.

I think the issue that I'm running into is that using the column code (those six `s) seems to apply that to the entire page, with no way of stopping it without starting a new page.

**Comment by calculuschild** [comment]
We should look into the weird spacing on the second column. Now that we have access to the repo I think we can fix that weirdness.

**Comment by Gazook89** [comment]
This is a 3 year old issue, just adding an update as it is not fixed yet.

I think #1179 will fix this...?  Looking into this, the same issue exists and @Rae2che5 was right on target.  However, I'm not sure there is any reason to to hesitate in removing that style for `.phb pre + blockquote`...as the stylesheet is built now, every pre element will move the next element to the top of a column (in Chrome), and so it should never overlap any previous content.  Without using the method discussed in #1179 (translateZ), removing the top margin would cut off the top of the box decoration/shadow....but with #1179, that is no longer an issue.

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/58999374/103580016-08d6e600-4e9f-11eb-909e-dc22d0436f25.png">

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/58999374/103580062-1ab88900-4e9f-11eb-9917-8814d4bc484b.png">

So remove `.phb pre + blockquote {margin-top:13px}` and add `{transform:translateZ(0)}`

**Comment by calculuschild** [comment]
That's probably what the margin was for, you're right. Unfortunately if this moves any elements around I'm hesitant to fix it. People get very angry when their meticulously-aligned text gets bumped ever so slightly so it overlaps graphics, etc. We can keep this in mind for V3 though. Let's tag this so the fix makes it into the new CSS.

**Comment by calculuschild** [comment]
Fixed in V3. Won't fix in Legacy since it requires a lot of refactoring that would break a lot of old brews.
