### ISSUE TITLE
Lost my password

### ISSUE THREAD

**Issue by Feverdreem** [naturalcrit/homebrewery#480]
I don't know if this is the right place to send this, but I've lost my password to the homebrewery.. is there any way i can get it back? Thanks!

**Comment by jimcullenaus** [comment]
I can't help you with it, but if I might make a suggestion, using a password vault like LastPass is a very good way to have extremely strong passwords on every site and also never ever forget a password again.

**Comment by Gazook89** [comment]
Closing 4 year old issue about missing password.  It can be reopened if necessary.
