### ISSUE TITLE
Can't access My Brews page

### ISSUE THREAD

**Issue by thisismarko** [naturalcrit/homebrewery#482]
Hey there.  I have two accounts for the homebrewery.  One is my own personal use and one is an account for my d&d group.  My first account works perfectly fine but whenever I use the second account I run into an issue.

Anytime I click on my username, instead of taking me to the My Brews page, it takes me to the Create a new Brew page.

I have seen some people say that this issue occurs if you log in with an email but my account on the homebrewery is not an email address.  Is there anyway I can fix this issue?

Better yet, since my first account works, is there any way I can just change my password for the first account since I know that one works?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by westmorelandt2** [comment]
Yeah, I've been having the same issue except I only have one account. I can't get to my brews page. I know I saved them both, but I still can't access them. Anybody know what's going on?

**Comment by ramorga** [comment]
Same here. Would really like to access my brews without bookmarking each one

**Comment by ericscheid** [comment]
There was an issue with username as email resulting in redirects back to the HB home page. That issue has been fixed.

>Anytime I click on my username, instead of taking me to the My Brews page, it takes me to the Create a new Brew page.
>
> I have seen some people say that this issue occurs if you log in with an email but my account on the homebrewery is not an email address.

To track down this issue the developers need examples of usernames that don't work.

Haven't seen recent reports of similar issues for quite some time. Closing. Please re-open if you have a specific example of a username not working.
