### ISSUE TITLE
Can't access an entry from Chrome on iPad

### ISSUE THREAD

**Issue by tinkeron** [naturalcrit/homebrewery#484]
Editing from Chrome on my iPad has become impossible for two of my entries. The page doesn't open. Chrome just spins with the indicator that it's in the process of opening. I can open other pages I've edited. I thought it might be the size, but one of the large entries seems bigger than all the others. So, size doesn't appear to be a factor. Clicking the Share option similarly leaves the browser spinning in the iPad Chrome browser.

edit: An img tag src pointing to a pinterest image 'https://i.pinimg.com/564x/34/12/8b/34128b36aea319e142b454eb22ca8da3.jpg' appears to be the trigger. I moved the image off pinterest and the issue went away. 
This issue appeared only on my iPad with Chrome. Windows rendered correctly.

### Additional Details

**Share Link** :  http://homebrewery.naturalcrit.com/share/S1fxPobtW

**Comment by Gazook89** [comment]
I think this issue can be closed per the edit.  Not to mention age.  If someone strongly believes otherwise or @tinkeron is still having this problem 4 years later, it can be reopened.

**Comment by ericscheid** [comment]
Older hardware editions of iPads will continue to have various problems.

1. iOS uses webkit, not chrome, so all the usual caveats apply
2. iOS locks the version of the Safari browser to the version of the iOS on that hardware device
3. iOS won't update older hardware beyond particular iOS versions

Thus, an older hardware iOS might be limited to running only e.g. iOS 12.5.5, on which Safari won't update beyond Safari 12.1. This will cause problems when e.g. encountering javascript using [optional chaining syntax](https://caniuse.com/?search=chaining) `foo.?bar.?qaz`

The issues where the iPad JS engine is outdated can be handled via _babel_, but the issues of Safari behaving differently from Chrome are SOL.
