### ISSUE TITLE
Email as username, does not redirect correctly

### ISSUE THREAD

**Issue by damasterham** [naturalcrit/homebrewery#488]
### Additional Details
When trying to access my account it redirects me to you homepage with the example brew.
I imagine it is because it uses my email as my username, and the "@" and ".com" get parsed incorrectly in the URL.

**Share Link** :
http://homebrewery.naturalcrit.com/user/cmeisterham@gmail.com

**Comment by ericscheid** [comment]
There was an issue with emails as usernames, but has been fixed since.
