### ISSUE TITLE
Negative Margin Appears to be a Race Condition

### ISSUE THREAD

**Issue by botchedrole** [naturalcrit/homebrewery#496]
I copy pasted the last page of my doc below, but the only relevant parts is where "margin-top" is negative.  When viewing the .pdf (or after leaving and coming back to the homebrewery) the negative margins appear to stop working (or sometimes will work, sometimes wont), though they always work fine if you watch as they are typed in.  This is causing the very last bits of text on my document to go off the page to the right.

This is my first foray into html/css, so maybe this issue is stemming from stupidity - I don't think so though : /.

Thanks!

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/HkHnx925W

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div class='wide' style="margin:0;padding:0;border:0;">

### <center> Explanation and Suggestions for General Use </center>

<div style="width: 50%; float:left;">

<div style="margin-right:10px;">

### How to use these rules
<li style="line-height: 120%;margin-top:-5px"> This set of house rules is intended to make the game more fun, interesting, and flavorful.  As with all things, the DM always has the option to veto or change rules on the fly.  It is suggested that these rules only apply to Player Characters and possibly Bosses, but not the general monster population - both for speed of use and player partiality.  These tables are intentionally weaker/less permanent than most critical hit/fumble tables because of the desire to add interest without being overly punishing to players.
<li style="line-height: 120%;margin-top:-5px"> These tables are also intentionally very 'clinical' - they are descriptions of mechanics which can make the game more interesting, but it is up to the DM & Players to come up with their own descriptions of what is happening to cause these effects.  It is suggested that you read the result descriptions to your players, then allowing them to come up with the visuals: encourage their creativity, embrace their ideas, and "Yes, and" their improvisations : ).

</div>

</div>

<div style="width: 50%; float:right">

<div style="margin-left:10px;margin-top:-9px">

### A special note on multiple attacks
<li style="line-height: 120%;margin-top:-5px">It is highly suggested that characters who make more attacks per turn should have a lower DC to confirm on these tables - otherwise they will be punished more frequently or have slightly more benefit than other players.  This is the reason for giving Advantage on Critical Fumble checks for the rest of the turn after confirming a Critical Fumble.  Every time such a character rolls to confirm a Brutal Hit or a Threatened Fumble, it is suggested that you  modify the DC by +1 (for Brutal Hits) or -1 (for Fumbles) for each attack they can make beyond the first in a single round.
<br> <br> <div style="margin-left: 15px;margin-right: px;margin-bottom:10px;line-height: 120%;"> *For example: If a character can make 3 attacks in one turn, any Brutal Hit DCs they roll against should have +2 DC and any Threatened Fumbles should have -2 DC.*

</div>

</div>

</div>

</div>

<div class='wide' style="margin-top:-25px;padding:0;border:0;">

### Notes
<ol> 
<li style="padding-top: 1px;">The DM may increase or decrease a check's DC as needed to fit the current circumstances.
<li style="padding-top: 1px;">For any result which provides the Attacker with an additional attack, where the original attack was made with a spell or ranged weapon, these extra attacks do not cost additional spell slots, casts per day, or ammunition.  They are free additional casts or ammunition of the same type which was originally used.
<li style="padding-top: 1px;">Any result that applies a Condition which the entity already has will stack on top of its duration - adding a turn if necessary.
<div style="padding-left:15px">*For example: If a target is "Stunned until the beginning of their next turn" and the "Stunned until the beginning of their next turn" Condition is applied to them again, Stunned will instead last until the beginning of the following turn (having one turn where the entity takes no actions while they are Stunned).*</div>
<li style="padding-top: 1px;">Target must be no more than one size category larger than the Attacker.
<li style="padding-top: 1px;">"Normal Critical Damage" refers to the description of the weapon in the PHB or other text.
<li style="padding-top: 1px;">If a player has an adjusted critical range, this range applies to both the Fumble and Brutal Hit Checks as well.
<li style="padding-top: 1px;">For "Show of Strength", only the Target can be Grappled.  For "Brutal Strike", the maximum damage dealt is non-critical damage; and an additional attack only applies to the original Target.
</ol>

</div>

<div class='wide' style="margin-top:0px;padding:0;border:0;">

### New Feats

</div>

___
> ## Accident Prone
>You have always had bad luck - now you have learned to turn your curse into a boon. <br> You gain the following benefits:
> ___
> <menu><li style="margin-left: 15px;padding-top: 0px;line-height: 110%;"> Your attacks threaten a Critical Fumble on a roll of a 1 or 2.</li>
<li style="margin-left: 15px;padding-top: 1px;line-height: 110%;"> Any Fumble Check you roll against has its DC reduced by 4.
<li style="margin-left: 15px;padding-top: 1px;line-height: 110%;"> You have Disadvantage on Fumble Checks and can never gain Advantage on Fumble Checks, even if you have already Fumbled this turn.
<li style="margin-left: 15px;padding-top: 1px;line-height: 110%;"> When rolling on the Fumble and Magnificent Mishap tables, you may roll twice and choose one result.
<li style="margin-left: 15px;padding-top: 1px;line-height: 110%;"> You do not fall unconscious from a Catastrophic Failure; all other results still apply.
<li style="margin-left: 15px;padding-top: 1px;line-height: 110%;"> When you confirm a Fumble Check, you may use the Dodge action as a Bonus Action.
<li style="margin-left: 30px;padding-top: 1px;line-height: 110%;list-style-type: circle;"> This will apply before rolling on the Fumble or Magnificent Mishap Tables.
</menu>
>
>___

___
> ## Combat Kismet
>You have learned to read the split second opportunities of combat that most others miss.  You gain the following benefits:
> ___
> <menu><li style="margin-left: 15px;padding-top: 0px;line-height: 110%;">Any Brutal Hit or Fumble Check you roll against has its DC reduced by 2.
<li style="margin-left: 15px;padding-top: 1px;line-height: 110%;"> You have Advantage when rolling to confirm a Brutal Hit.
<li style="margin-left: 15px;padding-top: 1px;line-height: 110%;"> When rolling on the Brutal Hit and Savage Hit Tables, you may roll twice and choose one result.
<li style="margin-left: 15px;padding-top: 1px;line-height: 110%;"> Once per long rest - for either a Brutal Hit or Savage Hit roll - you may roll three times and choose two results.
<li style="margin-left: 30px;padding-top: 1px;line-height: 110%;list-style-type: circle;"> The decision to use this third die must be stated before rolling.
</menu>
>
>___

### Credits
* Created and written by <a href="mailto:BotchedRole@gmail.com?Subject=Hello%20again" target="_top">BotchedRole@Gmail.com</a>.
* S. R. Dreamholde provided feedback and suggestions.
* PDF made pretty with [The Homebrewery](http://homebrewery.naturalcrit.com/).
<br> Version 1.06 - 2017/09/18

<div class='pageNumber'>3</div>
<div class='footnote'>PART 3 | NOTES AND FEATS</div>

</pre></code></details>

**Comment by ericscheid** [comment]
Not sure why the weirdness is happening specifically, but will say it appears to be done the hard way. You've got html elements in the brew code with style attributes on those elements and so on. You probably don't need all that extra complication when you could instead insert a `<style>...</style>` snippet to apply the styling.

Also, by the looks of things you are trying to eliminate the extra space inserted before headings by moving entire blocks around instead of eliminating the margins and padding. So .. insert this instead..

```
<style>
  .phb h2, .phb h3, .phb h4, .phb h5 {
    margin-top: 0;
  }
</style>
```
