### ISSUE TITLE
Statblock Format Improvement

### ISSUE THREAD

**Issue by SergentBullock** [naturalcrit/homebrewery#509]
In the perfection process, you might want to look at rectifying the Statblock background texture. Statblocks actually have a ragged edge to them on the "parchment" section for many monsters. 

This is best seen on the Beholder statblock inside the Monster Manual. Not all monsters have it or in great quantities, (the more badass they are the more likely it is that they seem to get it. Compare the Beholder to the Cyclops for example.) but it's a very minor detail worth looking into. Possibly the wide statblocks could get this treatment, since they're usually imposing, strong monsters?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
