### ISSUE TITLE
Considering up'ing to SSL?

### ISSUE THREAD

**Issue by bakgaard** [naturalcrit/homebrewery#516]
Any chance Homebrewery can get up'ed to SSL connection.

May I suggest the Google-supported, and free, way https://letsencrypt.org/ ?

**Comment by AlexeySachkov** [comment]
Server supports SSL and requests via HTTPS. There is a PR which brings automatic redirects to a `https` version, see #815

**Comment by AlexeySachkov** [comment]
Homebrewery was switched to use https. @calculuschild, @ericscheid, we can close this now

**Comment by calculuschild** [comment]
Closing because this was solved.
