### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by Broke-Bloke** [naturalcrit/homebrewery#520]
Just a question, as i think there may be features I don't have access too. 

 Is there a way to publish your Brews, as I have looked and only the get a PDF works and the tab of Recent Brews and recent and edited brews do not work.

**Comment by dekelpilli** [comment]
https://i.imgur.com/tpWt6WR.png Yes, there's a metadata hamburger menu that opens up this form, where you can then click on publish and add a description

**Comment by ericscheid** [comment]
Watch #697 for updates.
