### ISSUE TITLE
Title for a brew not showing up on user profile

### ISSUE THREAD

**Issue by joyvgh** [naturalcrit/homebrewery#535]
Added a title page but it's not showing up the way my other brews do. 

### Additional Details

**Share Link** : 
http://homebrewery.naturalcrit.com/share/HyQD-N-0-
http://homebrewery.naturalcrit.com/user/joyful

**Comment by calculuschild** [comment]
Fyi you shared the edit link to your brew. Anyone who views it will have it
added to their profile and they could delete it without you knowing. I
recommend changing your post to show the share link instead of the edit
link.

**Comment by DoctorDan1986** [comment]
Need more information.  What do you mean, 'it's not showing up the way...etc, etc'?

It's also not a good idea to nest monster blocks inside of monster blocks.

**Comment by joyvgh** [comment]
When I added a title page to my other brews, the title was added to the view on my profile. That is not the case with this particular one and I was wondering why.

**Comment by ericscheid** [comment]
The title of the brew can be edited in the metadata for the brew .. click the hamburger menu in top-right of the editor pane.

![image](https://user-images.githubusercontent.com/2605467/99153929-08706900-2700-11eb-9006-9a075df63f75.png)


It defaults to the first heading, or the first line of text if no heading. It doesn't update automatically if you later add e.g. a title page.
