### ISSUE TITLE
Suggestion: Download Markdown text from main Brewery screen.

### ISSUE THREAD

**Issue by royalef** [naturalcrit/homebrewery#548]
It would be great if on the Main Brewery page, in addition to a Share, Edit & Delete link, there was a simple download that handed me the text file of the markdown.  It would be a lot easier than Select All, Copy, grab notepad, Paste after every significant revision for backup.

Thanks.

**Comment by ericscheid** [comment]
There exists (floating somewhere) a javascript that saves the source in one click. 

Doesn't work from the home page, but does from the /edit or /share pages. (Needs to be updated to save all from home page).

You can also click to the /share view, and from there alt-click or right-click the `</> Source` button.

We also now have the option to save to Google Drive instead, which aslo supports versioning.

Doining what you want direct from the home page is still a good idea.

**Comment by Gazook89** [comment]
4 year old feature request has been implemented.  Closing.
