### ISSUE TITLE
Continuing numbering on another page

### ISSUE THREAD

**Issue by Gadget2020** [naturalcrit/homebrewery#551]
Is there a way to continue the number sequence after a page break? (or Div tag?)

`
 1. **List item 1** 
 1. List item 2

\page

1. **this should be item 3, but lists as 1**
1.  List item 4
`

**Comment by ericscheid** [comment]
Ordered lists start with the number used for the first list item. Also, the number on subsequent list items in that group don't need to follow in order, or even be numbers. Good practice would be to use `-` to indicate list items generally, and change that `-` to `<some-number>.` when you want that list to be numbered — it makes it really easy to edit, shuffle lines around, etc.

```
1. List item 1
- List item 2

\page

3. This is item 3
- List item 4
```

**Comment by ericscheid** [comment]
Closed, advice given for starting a list at a given #
