### ISSUE TITLE
Request: Change the title of brews on user page

### ISSUE THREAD

**Issue by Gadget2020** [naturalcrit/homebrewery#552]
I occasionally have a "working title" when i set up a brew, but as it develops I change it to another title - Currently I create a new brew, copy and paste everything and save it under the new title, then delete the duplicate (old) one.
Much easier if I could just edit the title.

**Comment by Moi-Brisingr** [comment]
You can. Where the Editor, phb, tables and print menues are look to the right and you will see a sandwitch menu button. Hovering above it will display "Edit Brew Metadata". Click it and change the title there.

**Comment by ericscheid** [comment]
Closed as support question advised.
