### ISSUE TITLE
Split table in 3 columns

### ISSUE THREAD

**Issue by Gadget2020** [naturalcrit/homebrewery#554]
As far as I can tell, the following should work, (but doesn't)...

(It's in markdown, so might not show up here...)

;&gt div style='column-count:3' ;&lt
|TableA|data|
|:-:|:--|
|1| a|
|2| b|

```
```

|TableB|data|
|:-:|:--|
|1| c|
|2| d|

```
```

|TableC| data|
|:-:|:--|
|1| e|
|2| f|
;&gt/div;&lt

**Comment by Sansd20** [comment]
Try at least 3 dashes.

**Comment by Sansd20** [comment]
Oh, see. Ignore my comment.

**Comment by ericscheid** [comment]
This code works (the column breaks are unnecessary, but also works with them too)

```
<div style='column-count:3'>
| d10 | Damage Type |
|:---:|:------------|
|  1  | Acid        |
|  2  | Cold        |
|  3  | Fire        |
|  4  | Force       |
|  5  | Lightning   |

| d10 | Damage Type |
|:---:|:------------|
|  6  | Necrotic    |
|  7  | Poison      |
|  8  | Psychic     |
|  9  | Radiant     |
|  10 | Thunder     |

| d10 | Damage Type |
|:---:|:------------|
|  6  | Necrotic    |
|  7  | Poison      |
|  8  | Psychic     |
|  9  | Radiant     |
|  10 | Thunder     |
</div>
```
