### ISSUE TITLE
Site Maintenance

### ISSUE THREAD

**Issue by nivthefox** [naturalcrit/homebrewery#556]
Currently, the site has not been updated in several months, there is a massive backlog of issues including one very critical issue (XSS injection), and most importantly the certificate has expired for the SSL service to the site.

I would be interested in helping you out as a project maintainer, and a systems administrator on this project.

I have already got my own version of the site running, including naturalcrit, and am very experienced with NodeJS, MongoDB, and Javascript, and am confident I could maintain this site and keep the certificate current (using letsencrypt).

If you are interested, please contact me and I will be happy to chat about this.  I recognize that you've mostly moved on from this project, but it's a fantastic resource and I would hate to see it fall completely to disuse as a result of developer burnout.

**Comment by AlexeySachkov** [comment]
Hi @kkragenbrink, if you are still interested in the Homebrewery development - you are welcome! Meet us in [gitter chat](https://gitter.im/naturalcrit/Lobby)

**Comment by ericscheid** [comment]
Lots more motion these days.

@nivthefox the invitation to join gitter and discuss further is still open.


Closing.
