### ISSUE TITLE
Brew not exporting to PDF

### ISSUE THREAD

**Issue by NedTurner613** [naturalcrit/homebrewery#560]
Whenever I attempt to export the brew to pdf, I get a Notepad file that says the following

%%[ ProductName: Distiller ]%%
%%[ Error: undefined; OffendingCommand: mTj ]%%

Stack:
0
0
-save-

%%[ Flushing: rest of job (to end-of-file) will be ignored ]%%
%%[ Warning: PostScript error. No PDF file produced. ] %%

I'm running this in Canary, and this has only started happening in the last few days. I tried searching the offending command but didn't have any luck.

**Comment by calculuschild** [comment]
@NedTurner613 Does this issue still happen? Can you provide the *share* link to your document so we can see what's going on?

**Comment by NedTurner613** [comment]
The issue has not been a problem since I started exporting it to PDF
through the normal channels rather than through Acrobat. For some reason
Acrobat causes problems

**Comment by AlexeySachkov** [comment]
@calculuschild, @ericscheid, I suggest that we close this one

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
