### ISSUE TITLE
PDF Export Duplicates some lines 

### ISSUE THREAD

**Issue by bretlinne** [naturalcrit/homebrewery#561]
![image](https://user-images.githubusercontent.com/10578604/33235686-8d4dad6a-d1f2-11e7-8b0c-28c93c56a2e9.png)

### Additional Details

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

# NightFrost Cloak

F`rost crystals glitter upon the outside of this grey-blue cloak. In the mornings, the cloak is covered with more frost and thaws slightly as the sun rises.  It re-freezes as the day passes noon and the sun sets.  It is coldest at night and turns almost bright white with frost crystals.

```
```

<div class='wide'>
<br />
##### Powers Summary

|Name|Time|Cold Resist|Light Radius|Snow Chance(D20)|Snow Amount|Cloak Temp|Wear Damage|
|:----|:----------|:----|:-|:-|:-|:-|:-|:-|
| Day  | 9am-3pm | *none* |*none*|16+|2 oz|40° F|1D4|
| Dawn/Dusk  | 3-9 Am&Pm | +1 |10ft|9+|1/2 pound|20° F|1D6|
| Night  | 9pm-3Am | +2 |20ft|4+|2-3 pounds|0° F|1D8|

</div>

___
> ## Ability Details
> ***Cold Resist.*** The NightFrost cloak confers resistance to cold/ice/water-aligned damage from spells and spell-like abilities.  This protection increases as the sun wanes and the day gets naturally colder and darker. The actual temperature has no bearing on the cloak's ability to frost as the sun goes down.  It will be as effective in the Summer or Winter.  The cloak confers no cold resistance in midday hours.  <br /><br />
> ***Illumination.*** The enchanted frost clinging to the cloak shines with chilly, ethereal light.  The brightness it confers is dependent on how frosted the cloak is.  Its brightest at night.<br /><br />

> ***Winter Gusts.*** As an at-will effect once per 10 minutes, the wearer can swish the cloak to usher forth a blast of icy wind as if the door had been left open on a winter night. The blast has a chance of conjuring snow as well.  It has a range of roughly 20 feet and loses force as it gets further from the wearer.  This will not deal damage, but could startle or distract someone. <br />*This is potentially a source of conjuring natural snow for whatever reason the player might need or want snow in moderate quantities.*<br /><br /><br />
```
```

___
> ## Winter Gust Effects
>___
>||Chance of Snow(D20)|Amount of Snow|
>|:-|:---:|:-|
>|**Dawn/Dusk**|9+|Medium flakes;<br />1/2 lb of snow|<br />
>|**Day**|16+|Handful of tiny<br />flurries|<br />
>||||<br />
>|**Night**|4+|Large flakes;<br />2-3 lb of snow|<br />

>___

>#### Combat Effect
>It's possible to use this effect in combat, sending a forceful blast of >stinging snow into the eyes, much like hurling sand.  If snow is cast, and >the Winter Gust is used against an enemy that can see, treat it as:
>- Quick Action
>- Ranged touch attack
>- Increment: 5ft
>- Save: Fortitude DC12 (DC 8 with head protection)
>- On failure: Opponent flat-footed and dazzled for 1 round.
><br />
___

```
```
\page

# NightFrost Cloak Frost Aura

The NightFrost is very cold to the touch & will chill the wearer.  *It's not advised to sleep in this.*<br />  As such it will sap a character’s body heat while worn.
<br />**This can be negated by wearing sufficiently thick and warm cold weather gear underneath it. ** 

If the character is only wearing normal travelling clothes (or less), the DM is to use the table below and apply cold weather fortitude saves and non-lethal damage penalties to the player according to the time of day.

___
<div class='wide'>
##### Cold Exposure
|| Tempurature | Condition  |Non-Lethal <br /> Cold Damage | Save Difficulty| Save Frequency
|:----|:-------|:-|:-|:-|:-|
| Day  | 40° F | Moderate Cold | D4 | DC 15 | Every hour
| Dawn/Dusk  | 20° F | Severe Cold | D6 | DC 15 | Every 30 minutes
| Night | 0° F | Extreme Cold | D8 | DC 15 | Every 10 minutes

</div>
___

<div style='margin-top:0px'></div>

>It is entirely possible to have a character fall unconscious as from severe cold weather exposure.

*On the bright side, this cloak’s near-perpetual coldness can make very hot summer days, or time spent in hot-desert climates fairly tolerable.  Also can be used to treat heat-exhaustion, and hyperthermia. On extremely hot days or in such environments, the cloak could be worn without penalty for part of the day.*

```
```
Additionally, the wearer of the cloak leaves trails of frost in their wake.  On every footstep, ice crystals will form.  At night, at the cloak's coldest the aura is strong enough that water sources within 5ft will begin to freeze over.

___

<div class='footnote' style='position:absolute;bottom:30px;right:60px'>#### Created by Bret Linne</div>

</pre></code></details>

**Comment by Gazook89** [comment]
@bretlinne, this is a 4 year old issue with no comments on it--- I'm going to close it as I cannot reproduce it and have not seen any other new or closed issues referencing the same problem.  Unfortunately the "code to reproduce" was not inside code fences so github rendered it, and it can't be reproduced in markdown (specifically the table in question).  If you have any interest in trying to reproduce it again and can do so, we can definitely re-open this and take another look.

**Comment by calculuschild** [comment]
@Gazook89 I have the power to edit posts. I fixed the source if you want to check it out for kicks and giggles.
