### ISSUE TITLE
Bug with linking to a blank template of the homebrewery

### ISSUE THREAD

**Issue by LucasMiraB** [naturalcrit/homebrewery#564]
Wellp, I think I found a bug that is really easily repeatable. Whenever I try to link your website with a button, it leads to the wrong url. Instead of going to http://homebrewery.naturalcrit.com/ it tries to access http://homebrewery.naturalcrit.com/shre/homebrewery.naturalcrit.com/

### Additional Details

http://homebrewery.naturalcrit.com/share/rkQ94zcJM

What I wrote in that area:
" Se quiser fazer teu homebrew nesse formato, clica [aqui](homebrewery.naturalcrit.com). Saber inglês vai ajudar a entender como funciona a ferramenta. "

**Comment by ericscheid** [comment]
> What I wrote in that area:
" Se quiser fazer teu homebrew nesse formato, clica aqui. Saber inglês vai ajudar a entender como funciona a ferramenta. "

Looking at the html of that example content shows a link with `href="homebrewery.naturalcrit.com"` .. which is not what you would want here. You need to specify the protocol, like this `href="https://homebrewery.naturalcrit.com"`

Brew has been updated with (proper form) URL to the patreon. Closing.
