### ISSUE TITLE
Brew saves but when opened again changes have disappeared

### ISSUE THREAD

**Issue by Singador** [naturalcrit/homebrewery#570]
I've been having this issue recently where I add content to a brew, but after saving, closing and returning to the brew, most of the content has disappeared. I don't have any other brews open, which has never been a problem in the past anyway. I've tried manually saving through ctrl + s but it doesn't seem to have made a difference

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/source/H1-5DO_--

**Comment by Gazook89** [comment]
Issue was opened 3 years ago, and with recent dramatic changes to saving (i.e. google drive integration), can likely be closed, @ericscheid @calculuschild

**Comment by calculuschild** [comment]
Thanks Gazook. Yep we can close this now; there have been various fixes to the saving stability that should have handled most of these issues from back then.

Feel free to reopen this issue if this is still a problem for you @Singador .
