### ISSUE TITLE
Cannot edit or delete this brew

### ISSUE THREAD

**Issue by Wenneker** [naturalcrit/homebrewery#571]
The code / entry is corrupted. 
It now has the ENTIRE content as the title of the homebrew, which means the list of my HB becomes corrupted after this one's entry and so I cannot access that.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/SyKN61q2W

**Share Link** : http://homebrewery.naturalcrit.com/edit/ByeYVTJ9h-
or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

I'd rather not given that - 1) I cannot; 2) the code broke the parser already.
</pre></code></details>

**Comment by ericscheid** [comment]
It would appear that this particular brew has since been deleted. Closing.
