### ISSUE TITLE
Autosave consistantly not saving, no way to manually save

### ISSUE THREAD

**Issue by Falconloft** [naturalcrit/homebrewery#573]
Exactly what it says in the title. I've had to step away from a brew I've been working on for hours, onto to come back and try to re-open it to find a version that pre-dates anything I'd done that day. 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Singador** [comment]
I seem to have found a way around this by pressing ctril+s and refreshing the page before closing the browser, though I'm uncertain that this is a definite problem fixer. I wish this issue could be addressed soon, I can't edit any of my work for fear of losing entire sections of edits.

**Comment by Gazook89** [comment]
Issue was opened 3 years ago, and with the recent dramatic changes to saving (i.e. saving to google drive), can likely be closed, @ericscheid @calculuschild.

**Comment by calculuschild** [comment]
Thanks Gazook. Yep we can close this now; there have been various fixes to the saving stability that should have handled most of these issues from back then.

Feel free to reopen this issue if this is still a problem for you @Singador .
