### ISSUE TITLE
"Recent Brews" button is broken.

### ISSUE THREAD

**Issue by FBalerio** [naturalcrit/homebrewery#577]
I can make and save brews as normal, and when I save the links, they still work. However, they won't appear on my "recent brews" section when I click it. The menu unfolds as normal but just the "Edited" and "Viewed" titles appear without any content. 

I've already lost a couple links, and keeping them all stored in a .txt file is my only resource currently.

I don't really know why nothing is loading into those menus.

**Comment by calculuschild** [comment]
Those menus have actually been broken for several months at this point. If
you want to save files, you can either do as you are with a txt file (a
backup like that is the smart thing to do) Or you need to make an account
and log in to it. You will have a new button that takes you to your user
profile page and all of your brews you have worked on while logged in will
be saved.

**Comment by Sadras1** [comment]
Login current not working so, txt file is the best

**Comment by calculuschild** [comment]
Woo! We fixed this one! Should be working now.
