### ISSUE TITLE
All the text in only one page

### ISSUE THREAD

**Issue by GeoGranpa** [naturalcrit/homebrewery#583]
Hello,

I'm trying to format muy brew as landscape page with 3 columns. The problem is that i must insert \page or the text won't go down.

You can check line 72

Best regards.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/r1Rhi1UzM

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<style>
/* LANDSCAPE FIX */
.phb{
	column-count: 3;
	height: 210mm;
	padding: 12mm 12mm 17mm;
	width: 296.8mm;
}
.phb::after{
	height: 75px;
}
.phb p{
	break-inside: auto;
    margin-bottom: 15px;
}
.pageNumber{
	bottom: 35px !important;
	font-size: 1.2em !important;
	width: 70px !important;
	z-index: 1000;
}
/* PRINT FRIENDLY!! */
@media print{
	.phb{
		background: #FFF;
	}
}
</style>

<div class='pageNumber auto'></div>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt vestibulum sapien. Duis eu velit magna. Aenean eu est vitae neque volutpat faucibus. Nunc sed libero neque. Suspendisse at malesuada sem. Integer vehicula viverra posuere. Phasellus egestas molestie consectetur. In a erat massa. Nullam laoreet elit ac convallis tempor. Duis nec ligula vitae diam suscipit elementum vel elementum lorem. Curabitur tempus, mi in aliquet auctor, sem ante maximus erat, at volutpat leo orci consequat nunc.

Donec vel consectetur mi. Proin pellentesque vulputate laoreet. Donec fringilla ante et sem suscipit, a ornare eros aliquam. Vestibulum suscipit venenatis massa, a euismod tortor aliquet sed. Fusce ac libero ac ante blandit congue a ut lectus. Nulla facilisi. Pellentesque id lobortis metus, quis blandit elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras ut nunc id dui dictum semper sit amet et turpis. Nullam aliquam placerat erat, eget accumsan nunc aliquet sollicitudin. In purus sem, vehicula non porta sit amet, feugiat ut purus. Vivamus turpis nibh, ultricies a convallis at, congue quis nibh. Praesent sapien justo, suscipit eget dapibus sed, imperdiet vitae massa. Nam sit amet finibus leo, id condimentum libero. Suspendisse vel ex vitae est scelerisque vulputate id non sapien. Curabitur semper odio sit amet est pretium tincidunt.

Cras pellentesque dapibus odio ut faucibus. Donec id purus dignissim, condimentum est eget, consectetur ante. Etiam lorem sapien, euismod nec feugiat consectetur, ullamcorper a dui. Sed maximus varius scelerisque. Proin quis sapien mollis, iaculis mi in, blandit dolor. Sed quis urna quis enim placerat consequat. Donec dapibus vulputate tempor. Aliquam at eros eu purus molestie pulvinar. Duis dictum molestie massa sit amet tempor. Sed non ex ut purus tempor eleifend. Integer tempus finibus justo id viverra. Nulla auctor malesuada bibendum. Phasellus euismod ipsum dui, vitae lacinia nulla imperdiet quis.

Cras sed mauris porttitor, euismod quam ac, pharetra nibh. Vivamus non lacus a eros elementum varius. Proin augue enim, tincidunt volutpat lectus quis, tempus egestas eros. Sed ac tortor orci. In hac habitasse platea dictumst. Ut neque ante, fringilla eu urna vitae, interdum pellentesque quam. Praesent sagittis sem ac rhoncus accumsan. Aenean feugiat non arcu non lobortis. Donec sit amet sagittis nisl, ut facilisis risus. Aenean ipsum dolor, imperdiet quis ultrices eget, eleifend sed enim. Curabitur fermentum lorem et scelerisque sodales. Integer quis rhoncus ante, at semper ante. Mauris id egestas ligula, id fermentum nisl. Mauris facilisis ex ac urna bibendum finibus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt vestibulum sapien. Duis eu velit magna. Aenean eu est vitae neque volutpat faucibus. Nunc sed libero neque. Suspendisse at malesuada sem. Integer vehicula viverra posuere. Phasellus egestas molestie consectetur. In a erat massa. Nullam laoreet elit ac convallis tempor. Duis nec ligula vitae diam suscipit elementum vel elementum lorem. Curabitur tempus, mi in aliquet auctor, sem ante maximus erat, at volutpat leo orci consequat nunc.

Donec vel consectetur mi. Proin pellentesque vulputate laoreet. Donec fringilla ante et sem suscipit, a ornare eros aliquam. Vestibulum suscipit venenatis massa, a euismod tortor aliquet sed. Fusce ac libero ac ante blandit congue a ut lectus. Nulla facilisi. Pellentesque id lobortis metus, quis blandit elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras ut nunc id dui dictum semper sit amet et turpis. Nullam aliquam placerat erat, eget accumsan nunc aliquet sollicitudin. In purus sem, vehicula non porta sit amet, feugiat ut purus. Vivamus turpis nibh, ultricies a convallis at, congue quis nibh. Praesent sapien justo, suscipit eget dapibus sed, imperdiet vitae massa. Nam sit amet finibus leo, id condimentum libero. Suspendisse vel ex vitae est scelerisque vulputate id non sapien. Curabitur semper odio sit amet est pretium tincidunt.

Cras pellentesque dapibus odio ut faucibus. Donec id purus dignissim, condimentum est eget, consectetur ante. Etiam lorem sapien, euismod nec feugiat consectetur, ullamcorper a dui. Sed maximus varius scelerisque. Proin quis sapien mollis, iaculis mi in, blandit dolor. Sed quis urna quis enim placerat consequat. Donec dapibus vulputate tempor. Aliquam at eros eu purus molestie pulvinar. Duis dictum molestie massa sit amet tempor. Sed non ex ut purus tempor eleifend. Integer tempus finibus justo id viverra. Nulla auctor malesuada bibendum. Phasellus euismod ipsum dui, vitae lacinia nulla imperdiet quis.

Cras sed mauris porttitor, euismod quam ac, pharetra nibh. Vivamus non lacus a eros elementum varius. Proin augue enim, tincidunt volutpat lectus quis, tempus egestas eros. Sed ac tortor orci. In hac habitasse platea dictumst. Ut neque ante, fringilla eu urna vitae, interdum pellentesque quam. Praesent sagittis sem ac rhoncus accumsan. Aenean feugiat non arcu non lobortis. Donec sit amet sagittis nisl, ut facilisis risus. Aenean ipsum dolor, imperdiet quis ultrices eget, eleifend sed enim. Curabitur fermentum lorem et scelerisque sodales. Integer quis rhoncus ante, at semper ante. Mauris id egestas ligula, id fermentum nisl. Mauris facilisis ex ac urna bibendum finibus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt vestibulum sapien. Duis eu velit magna. Aenean eu est vitae neque volutpat faucibus. Nunc sed libero neque. Suspendisse at malesuada sem. Integer vehicula viverra posuere. Phasellus egestas molestie consectetur. In a erat massa. Nullam laoreet elit ac convallis tempor. Duis nec ligula vitae diam suscipit elementum vel elementum lorem. Curabitur tempus, mi in aliquet auctor, sem ante maximus erat, at volutpat leo orci consequat nunc.

Donec vel consectetur mi. Proin pellentesque vulputate laoreet. Donec fringilla ante et sem suscipit, a ornare eros aliquam. Vestibulum suscipit venenatis massa, a euismod tortor aliquet sed. Fusce ac libero ac ante blandit congue a ut lectus. Nulla facilisi. Pellentesque id lobortis metus, quis blandit elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras ut nunc id dui dictum semper sit amet et turpis. Nullam aliquam placerat erat, eget accumsan nunc aliquet sollicitudin. In purus sem, vehicula non porta sit amet, feugiat ut purus. Vivamus turpis nibh, ultricies a convallis at, congue quis nibh. Praesent sapien justo, suscipit eget dapibus sed, imperdiet vitae massa. Nam sit amet finibus leo, id condimentum libero. Suspendisse vel ex vitae est scelerisque vulputate id non sapien. Curabitur semper odio sit amet est pretium tincidunt.

Cras pellentesque dapibus odio ut faucibus. Donec id purus dignissim, condimentum est eget, consectetur ante. Etiam lorem sapien, euismod nec feugiat consectetur, ullamcorper a dui. Sed maximus varius scelerisque. Proin quis sapien mollis, iaculis mi in, blandit dolor. Sed quis urna quis enim placerat consequat. Donec dapibus vulputate tempor. Aliquam at eros eu purus molestie pulvinar. Duis dictum molestie massa sit amet tempor. Sed non ex ut purus tempor eleifend. Integer tempus finibus justo id viverra. Nulla auctor malesuada bibendum. Phasellus euismod ipsum dui, vitae lacinia nulla imperdiet quis.

Cras sed mauris porttitor, euismod quam ac, pharetra nibh. Vivamus non lacus a eros elementum varius. Proin augue enim, tincidunt volutpat lectus quis, tempus egestas eros. Sed ac tortor orci. In hac habitasse platea dictumst. Ut neque ante, fringilla eu urna vitae, interdum pellentesque quam. Praesent sagittis sem ac rhoncus accumsan. Aenean feugiat non arcu non lobortis. Donec sit amet sagittis nisl, ut facilisis risus. Aenean ipsum dolor, imperdiet quis ultrices eget, eleifend sed enim. Curabitur fermentum lorem et scelerisque sodales. Integer quis rhoncus ante, at semper ante. Mauris id egestas ligula, id fermentum nisl. Mauris facilisis ex ac urna bibendum finibus.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt vestibulum sapien. Duis eu velit magna. Aenean eu est vitae neque volutpat faucibus. Nunc sed libero neque. Suspendisse at malesuada sem. Integer vehicula viverra posuere. Phasellus egestas molestie consectetur. In a erat massa. Nullam laoreet elit ac convallis tempor. Duis nec ligula vitae diam suscipit elementum vel elementum lorem. Curabitur tempus, mi in aliquet auctor, sem ante maximus erat, at volutpat leo orci consequat nunc.

Donec vel consectetur mi. Proin pellentesque vulputate laoreet. Donec fringilla ante et sem suscipit, a ornare eros aliquam. Vestibulum suscipit venenatis massa, a euismod tortor aliquet sed. Fusce ac libero ac ante blandit congue a ut lectus. Nulla facilisi. Pellentesque id lobortis metus, quis blandit elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras ut nunc id dui dictum semper sit amet et turpis. Nullam aliquam placerat erat, eget accumsan nunc aliquet sollicitudin. In purus sem, vehicula non porta sit amet, feugiat ut purus. Vivamus turpis nibh, ultricies a convallis at, congue quis nibh. Praesent sapien justo, suscipit eget dapibus sed, imperdiet vitae massa. Nam sit amet finibus leo, id condimentum libero. Suspendisse vel ex vitae est scelerisque vulputate id non sapien. Curabitur semper odio sit amet est pretium tincidunt.

Cras pellentesque dapibus odio ut faucibus. Donec id purus dignissim, condimentum est eget, consectetur ante. Etiam lorem sapien, euismod nec feugiat consectetur, ullamcorper a dui. Sed maximus varius scelerisque. Proin quis sapien mollis, iaculis mi in, blandit dolor. Sed quis urna quis enim placerat consequat. Donec dapibus vulputate tempor. Aliquam at eros eu purus molestie pulvinar. Duis dictum molestie massa sit amet tempor. Sed non ex ut purus tempor eleifend. Integer tempus finibus justo id viverra. Nulla auctor malesuada bibendum. Phasellus euismod ipsum dui, vitae lacinia nulla imperdiet quis.

Cras sed mauris porttitor, euismod quam ac, pharetra nibh. Vivamus non lacus a eros elementum varius. Proin augue enim, tincidunt volutpat lectus quis, tempus egestas eros. Sed ac tortor orci. In hac habitasse platea dictumst. Ut neque ante, fringilla eu urna vitae, interdum pellentesque quam. Praesent sagittis sem ac rhoncus accumsan. Aenean feugiat non arcu non lobortis. Donec sit amet sagittis nisl, ut facilisis risus. Aenean ipsum dolor, imperdiet quis ultrices eget, eleifend sed enim. Curabitur fermentum lorem et scelerisque sodales. Integer quis rhoncus ante, at semper ante. Mauris id egestas ligula, id fermentum nisl. Mauris facilisis ex ac urna bibendum finibus.

</pre></code></details>

**Comment by ericscheid** [comment]
The shared brew is now landscape in 3 columns. Appears OP has worked out the necessary CSS.
