### ISSUE TITLE
Use different graphic for ::after bar at bottom of page

### ISSUE THREAD

**Issue by DoctorDan1986** [naturalcrit/homebrewery#585]
So, I want to use my own graphics for the 'bottom-of-page' graphic (::after) instead of the standard one.  I've found the web location that you use for the standard design, but I'm too much of a neophyte to figure out how to replace it with my own hosted image.

Any suggestions?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by athelu** [comment]
This can be done if you create a <style> section:

Example:
<style>
/* Footer */
	.phb:after{
		background-image: url(https://i.imgur.com/QgBMdcH.png); 
    }
</style>

**Comment by ericscheid** [comment]
Suggestion by @athelu verified. Closing.
