### ISSUE TITLE
Lists not formatting inside Descriptive block. 

### ISSUE THREAD

**Issue by tyson-nw** [naturalcrit/homebrewery#588]
I have tried replacing a Note block with a Descriptive Text block and the list contents are not formatting as lists.

### Additional Details

**Brew code to reproduce Lists not showing in Descriptive Text** : <details><summary>Click to expand</summary><code><pre>

<div class='descriptive'>
##### Forms and schools
 Some implement forms are associated with certain schools.  Here is a list of standard forms of arcane implements, the schools they are associated with 

___
* Abjuration **2**
* Conjuration **2**
* Divination **0**
* Enchantment **2**
* Evocation **1**
* Illusion **1**
* Necromacy **2**
* Transmutation **1**

___
* Uncommon 
* Rare
* Very Rare
* Legendary
</div>

</pre></code></details>

**Brew code to reproduce Lists showing in Note Block** : <details><summary>Click to expand</summary><code><pre>
> ##### Forms and schools
> Some implement forms are associated with certain schools.  Here is a list of standard forms of arcane implements, the schools they are associated with 
>___
>* Abjuration **2**
>* Conjuration **2**
>* Divination **0**
>* Enchantment **2**
>* Evocation **1**
>* Illusion **1**
>* Necromacy **2**
>* Transmutation **1**
>___
>* Uncommon 
>* Rare
>* Very Rare
>* Legendary
</pre></code></details>

**Comment by ericscheid** [comment]
I'm seeing lists inside divs working correctly — but only when writing the lists with `-` or `+` as their indicator, and not the `*` indicator. The `*` as a list item brew code is bugging out. This is not the case outside of `<div>` elements.

**Comment by Gazook89** [comment]
Adding a picture to illustrate this.  Note, the asterisk does work for the first list item inside the div *until* a second asterisk-list item is added, in which it turns the first list item to italics instead (and removes the list). 

<img width="783" alt="image" src="https://user-images.githubusercontent.com/58999374/103566181-28faab00-4e87-11eb-84b2-55d647ec0a90.png">

(No monkeys were harmed in this brew)

**Comment by calculuschild** [comment]
This is an issue with the Markdown parser. See the demo page [here](https://marked.js.org/demo/?text=%3Cdiv%3E%0A%20%20%0A*%20I%20ate%20a%20monkey%0A*%20I%20ate%20a%20monkey%0A*%20I%20ate%20a%20monkey%0A%20%20%0A%3C%2Fdiv%3E&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=0.3.19).

We are currently using Marked.js v3.19, which had a lot of issues parsing Italics/Bold with the asterisks. The new renderer will use the latest version which fixes that (in the Marked.js demo page you can select which Marked.js version to test). Unfortunately it also breaks a lot of old brews that were relying on those weird asterisk behaviors, so 3.19 will remain as the default for the "legacy" renderer.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
