### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by varenflow** [naturalcrit/homebrewery#591]
I use Crome and have had great fun making up new brews, however any time I attempt to export my brews in any manner it wont let me. It continues to load the preview for my brews and never stops somehow preventing me from either printing it or saving it as a PDF which results in the page to become non responsive. Any help would be greatly appreciated as I would really like to get my brews into PDFs to share with my fellow gamers.

**Comment by calculuschild** [comment]
I know it's been a while, but if you are still having this problem, could you provide the **share link** to your document so we can see what's going on? We would like to solve this if we can.

**Comment by AlexeySachkov** [comment]
@calculuschild, @ericscheid, I suggest that we close this one

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @varenflow
