### ISSUE TITLE
Idea: add the title of the brew into the <title/> element

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#593]
All my bookmarks look the same, as does the history auto-complete...

+ The Homebrewery - NaturalCrit
+ The Homebrewery - NaturalCrit
+ The Homebrewery - NaturalCrit
+ The Homebrewery - NaturalCrit
+ The Homebrewery - NaturalCrit

For the history auto-complete, if I'm lucky, I might remember that the url ending with _/BJek_1A5lG_ is the one I want, and not _/r1E3OF9vXz_.

**Comment by calculuschild** [comment]
Good idea. We will look into doing this.

**Comment by ericscheid** [comment]
This was recently done. Closing.
