### ISSUE TITLE
The column break no longer seems to work

### ISSUE THREAD

**Issue by CrimsonSpider** [naturalcrit/homebrewery#600]
I used to be able to use  2 rows of 3 back ticks To start a new column but it no longer works.

### Additional Details

http://homebrewery.naturalcrit.com/share/SkbdVD4uNz
or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

```
```

</pre></code></details>

**Comment by Sansd20** [comment]
Could you post the share link to your brew so we can take a look at it?

**Comment by granack** [comment]
the only 2 places with column breaks are just before `#` headings, which always start a new section anyway so they have no effect. What are you trying to get it to do?

**Comment by ericscheid** [comment]
Not seeing issue in shared brew. Closing.
