### ISSUE TITLE
Google Drive screwed up PDF... retroactively.

### ISSUE THREAD

**Issue by TheGreatWhy** [naturalcrit/homebrewery#606]
I've been using the Homebrewery "share" page to share a project with no issue. Since I could not find a way to save a project while starting a new one (now I can), I tried downloading the PDF and sharing it with Google Drive.
The PDF was perfect, like the ones from the previous version, until I uploaded and shared it with Google Drive, then one of the picture was duplicated and appeared in the middle of a table.
Now, every time I try to download a new copy of that PDF, it works fine on the Share page, but the PDF version shows the same issue, so I can't get an uncorrupted version of it.

### Additional Details

**Share Link** :  http://homebrewery.naturalcrit.com/share/r1-xM6NVM
![drive1](https://user-images.githubusercontent.com/35615184/35176193-eaaf0958-fd77-11e7-884e-fe79bb15c405.jpg)

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

# Arcane Artist (WIP)
A small crowd presses on the side of a busy street, seemingly fascinated by what they're seeing, their faces lit by occasional flashes of multicolored lights.
On a small platform, a colorful individual is giving an uncanny performance, juggling colorful bolts and streaks of light, in an amazing display of dexterity and magical prowess.
At a length, the spectacle is disturbed by sudden yelling, as some petty crook, taking advantage of the distracted crowd, is doing away with someone's purse. Without a pause, a quick beam of magical energy blazes towards the villain, freezing his feet in place. A small electric arc then sprouts towards his arm, making him yelp, and letting go of his loot. The commotion has passed, the ionized air smells fresh, and the crowd seems to relax.
The Artist takes a small bow, collects his earnings, picks up his stand and leaves, smiling.

### Happy accidents
Endless theory and study are ill-suited for the artistic mindset. Arcane Artists are former students of magic who, preferring a more hands-on approach and following their artistic interests, channeled their initial failures into their real passion and pursued performance arts. Arcane Artists practice a more instinctive use of magic power, allowing them to cast and manipulate many smaller effects, rather than a few strong spells.  

<div style='margin-top:35px'></div>

<img 
  src='https://pre00.deviantart.net/4d4d/th/pre/i/2014/364/a/8/the_juggler_by_queenofeagles-d8bqjvy.jpg' 
 -ì style='width:325px' />
Credit: queenofeagles

 <div class='classTable wide'>

| Level | Proficiency Bonus | Features | Cantrips  | Essences | Forms | Virtuoso Forms | Maestro Powers | Pulse Damage |
|:---:|:---:|:---|:---:|:---:|:---:|:---:|:---:|:---:|
| 1st  | +2 | Spellcasting | 2 | 1 | 1 | - | - | 1d8 |
| 2nd  | +2 | Flair | 2 | 2 | 2 | - | - |1d8 |
| 3rd  | +2 | Arcane Sense | 2 | 3 | 3 | - | - | 1d8 | 
| 4th  | +2 | Abiliy Score | 3 | 4 | 4 | - | - | 1d8 | 
| 5th  | +3 | - | 3 | 4 | 5 | - | -| 2d8 |
| 6th  | +3 | Enthralling Performance | 3 | 5 | 6 | - | - | 2d8 |
| 7th  | +3 | - | 3 | 5 | 7 | - | - | 2d8 |
| 8th  | +3 | Ability Score | 3 | 6 | 8 | - | - | 2d10 |
| 9th  | +4 | Hypnotic Performance | 3 | 6 | 9 | - | - | 2d10 |
| 10th | +4 | - | 4 | 7 | 10 | - | - | 2d10 |
| 11th | +4 | Virtuoso, Maestro | 4 | 7 | 10 | 1 | 1 | 3d10 |
| 12th | +4 | Ability Score | 4 | 7 | 10 | 2 | 1 | 3d10 |
| 13th | +5 | Juggle Magic | 4 | 8 | 10 | 3 | 2 | 3d10 |
| 14th | +5 | Crescendo | 4 | 8 | 10 | 4 | 2 | 3d12 |
| 15th | +5 | Warp Acrobat | 4 | 8 | 10 | 5 | 3 | 3d12 |
| 16th | +5 | Ability Score, Risoluto | 4 | 9 | 10 | 6 | 3 | 3d12 |
| 17th | +6 | - | 4 | 9 | 10 | 7 | 4 | 4d12 |
| 18th | +6 | Adagio | 4 | 9 | 10 | 8 | 4 | 4d12 |
| 19th | +6 | Ability Score | 4 | 10 | 10 | 9 | 5 | 4d12 |
| 20th | +6 | Master Juggler, Gran Finale| 4 | 10 | 10 | 10 | 5 | 4d12 |
</div>
<style>
  .phb{
    width : 210mm;
    height : 296.8mm;
  }
</style>  

  <div class='pageNumber auto'></div>\page

  
  ## Class Features
  As an Arcane Artist, you gain the following class features.
  
  
#### Hit Points  
**Hit Dice**: 1d6 per Arcane Artist, Virtuoso or Maestro level.  
**Hit Points at 1st level**: 6 + CON modifier.  
**Hit Points at higher levels**: 1d6 (or 4) + your CON modifier per Arcane Artist, Virtuoso or Maestro level after 1st.  

  
#### Proficiencies  
**Armor**: none  
**Weapons**: Dagger, Quarterstaff, Dart  
**Tools**: none  
**Saving Throws**: Intelligence, Dexterity  
**Skills**: Choose two from Acrobatics, Arcana, Athletics, Investigation, Perception, Sleight of Hand.  

#### Equipment  
You start with the following equipment, in addition to the equipment granted by your background:
- a dagger or a quarterstaff  
- one chosen from Entertainer Pack, Scholar Pack or Explorer Pack  

      
#### Quick Build
You can make a sorcerer quickly by following these suggestions.
Your highest attributes should be Intelligence and Dexterity, as they will affect your spellcasting and performance skills, followed by Constitution.
Choose the Entertainer background, then choose Prestidigitation and Light as your cantrips, followed by Electric as your first Essence and Flourish as your first Form.
    
    
### Spellcasting  

 As a former student of the Arcane, you got to learn a few basic spells, mostly small interesting tricks that caught your attention.
 
 #### Cantrips
 At level 1, you get two cantrips chosen from  Prestidigitation, Thaumaturgy, Druidcraft, Mending, Mage Hand, Light, Message, Minor Illusion.
 
 You get an additional Cantrip at level 4 and another at level 10.
 Cantrips do not need memorization or preparation.  
 
  ### Magic Pulse  

 A Pulse is a small burst of magic force of undefined nature, like a more instinctive, less refined (and less powerful) cantrip. It's what often happens when young wizard apprentices fail to cast their first cantrips, and end up breaking a lamp.  
 As an action, you can direct that half-formed magic in a small Pulse that you are then able to shape and control, depending on your skills. A Pulse requires extremely simple V and S components.  
 
 A Pulse which has not been paired with any Essence nor Form is a simple puff or streak of magic that travels in a straight line and deals magic damage to a target you hit with a Ranged Spell Attack (though some Essences allow you to hit automatically and allow your target a save). Regarding resistances and dispel attempts, Pulses are considered spells of level 0.  
 You can cast each Pulse and pair it with one Essence and one Form at will.

 
 
 #### Increase/Decrease Dice  

  When you use your Pulse to make an attack, it deals 1d8 points of damage.
  As you grow stronger, so does you magic power, and with practice you become more and more efficient in channeling your magic Pulses.
  
- Whenever a skill says to Increase Dice, increase a Pulse's dice tier by one. Where you were using d8s you now use d10s in the same amount, and so on up to d12. Do the opposite for Decrease Dice.  
- Each Pulse beyond the first you use in a turn decreases the dice's tier by one, starting with the basic tier of the first one you used (the effect of Power Pulse doesn't count). If you would drop under d4, you're tapped out and can't use more Pulses this turn.  
- Add an additional damage die at level 5, 11 and 17.  
- The type of dice your Pulses use increases by one tier when you reach level 8 and then at level 14.
  
 
#### Magic Essence  
Essences are the foundations of an Arcane Artist's magic.Without them, your performances would be limited to a few puffs of smoke and light. An Essence is the particular nature or wavelength that gives a spell its effect.
 At Level 1, you learn to change the Essence of the Pulses you cast into a type or element of your choice. This changes the magical effect of your Pulse, though not so much as to make it as strong or malleable as a cantrip.  
A Pulse paired with an Essence travels in a straight line and has its effect when it reaches a target, or a target area. A Pulse's effect is typically instantaneous.  
 You get one Essence at level 1, then one at level 2, 3, 4, 6, 8, 10.  
 You can learn them in any order, but some have requirements you must meet.  

#### Shape Magic  

 As a naturally talented artist, you learn to apply your small Pulses of magic to perform a vast array of tricks, called Forms. 
  Forms don't usually change the effect of your Pulses on their designated targets, but rather their shape and the way they're used: you may start casting them in rapid succession, or in arcs, or to diffuse or concentrate their energy to obtain a wider variety of effects.
 You can add a single Form to any Pulse you cast, whether or not it's paired with an Essence. If it is, you may apply a Form to either the attack or non-attack version of the Pulse.  

 You Learn a Form at level 1, then one at each level up to level 10.  
 You can learn them in any order, but you must have reached at least level 5 as a Magic Artist before learning Advanced Forms. Additionally, some Forms have requirements you must meet, like the mastery of a simpler Form.
 

 <div class='pageNumber auto'></div>
 \page

> ##### Quick guide to Magic Juggling
> In order to cast your Pulses quickly and efficiently, follow this easy step-to-step guide.
- Choose a Form from the ones you know, it will tell you when or how you cast your Pulse
- Add an Essence from the ones you know, it will tell you how to hit your target and what it does once it hits him.
- Roll your Pulse damage
>- Remember to reduce the tier of the dice you're rolling for each Pulse you cast beyond the first in a turn.

> You can also cast a pulse as a simple magic projectile without Essence or Form.

#### Natural Entertainer
Your path clear to you since a young age, you developed your natural talent to attract attention and entertain. At level 1, you get the Performance proficiency.

#### Adventure with Flair
A performer at heart, at times you can't resist adding some panache, even in the middle of a fight. Starting at level 2, when you attack or cast, you can take Disadvante on the attack roll or give an advantage on the saving throw, in order to add some flair to your fight, like a pirouette, a bon mot, or a more spectacular light effect. At the end of an encounter, if there were bystanders, you can make a dexterity (performance) check, with a +1 for each Flair you added during the encounter (up to a amximum of +5), which will improve the audience's disposition towards you and your group depending on your degree of success.
 
 #### Arcane Sense  
  At level 3 your instinctive, practical knowledge of magic allows you to Detect Magic (as per the level 1 Wizard spell) as part of a successful Perception or Investigation check (rule of thumb: the stronger the magic, the easier the check should be).  

#### Enthralling Performance
Starting level 6, your ability in perfornance arts, combined with your use of colorful magical effects, allows you to attract attention and bewilder your audience. 
While you're performing, roll a Dexterity (performance) check with a bonus of +1 for each Essence you mastered vs DC 15. On a success, intelligent creatures who have you in their sight have disadvantage on WIS (perception) rolls made to perceive any creature or movement other than you.

#### Hypnotic Performance
By level 9, your performance can overload your audience's senses so much it puts them in a bewildered stupor. During a performance, roll a Dexterity (performance) check with a bonus of +1 for each Essence you mastered vs DC 20. A success lets you weave your essences into an hypnotic pattern that charms your audience and incapacitates them for up to one minute, as long as they're not attacked or otherwise disturbed. If you beat DC 25, and the audience is left undisturbed to the end of your piece, their disposition towards you will improve up to levels just short of a Charm spell for a number of hours equal to your dexterity modifier.

<img 
  src='https://i.pinimg.com/736x/33/90/dd/3390dd5c09ce0c567d384fdba9169be0--character-portraits-character-art.jpg' 
  style='width:325px' />
Credit: CPUCore

 #### Abilty Score Improvement  
 You get two additional Attribute Points or a Feat every 4 levels from 4th to 16th, then at 19th level.

 
## Artistic Path  
At level 11, you must choose one of two separate specializations: Arcane Virtuoso or Arcane Maestro.
The Virtuoso keeps learning new ways to manipulate magic Pulses and control a battlefield, while the Maestro focuses his power inward, accumulating it in order to release more powerful and complex Bursts of magic force, comparable to a Wizard's spell.  
 

### Virtuoso  
 You can achieve the title of Virtuoso at level 11.
 The Arcane Virtuoso performs with exquisite grace and uncanny speed, in a flowing stream of rapidly succeeding magical effects, while relocating often in order to keep out of the brunt of the fight.  
 You get an Advanced Essence at level 13, 16 and 19, and a Superior Form each level from 11 up.
 
 #### Juggle Magic
At level 13 your magic manipulation is so advanced that, once per turn, you can use two forms on a single Pulse, but one of the two must be a Basic Form.  
   
 <div class='pageNumber auto'></div>
 \page

 #### Warp Acrobat
 By level 15, your instinctive connection has made magic a second nature, something you can access subconsciously.
 Whenever an opponent would deal enough damage to drop you, he must pass a DEX save vs your spellcasting ability. If he fails, you instead disappear and reappear on a free space within a distance of 10 feet, plus your dexterity modifier, in a direction of your choice. If that distance is insufficient to exit the area of effect of that attack, you take the damage normally.
 Every time the same opponent repeats this save, he gains a cumulative +2 bonus.

 #### Master Juggler
 At level 20, your are so trained, focused and dextrous that, once per turn, you can use two Essences on a single Pulse, but none of them can be an Advanced Essence. 
 These essences can't be of opposite types (like fire-cold or fire-plant, light-shadow or light-necro). When you hit with a double-imbued Pulse, choose the shape of one of the two, deal the damage once, but add the effects of both. 
 You can use it with any Form like a regular Pulse.

### Maestro  
 You can achieve the title of Maestro at level 11. 
  The Arcane Maestro administers magic with precision, decision and authority, like a cliff among breaking waves of magic.  
 You get an Advanced Essence at level 13, 16 and 19.
 Additionally, you get a Power Burst, and a Power Slot that allows you to use one of your Bursts, at each odd level satrting at 11. Power Bursts require an action to use, and recharge after a long rest, but you can regain a single Power Slot you spent after a short rest. Power Bursts count as 5th level spells towards resistances and dispel attempts.
 
 #### Crescendo
 
 Starting level 13, if you have not used a Burst during your turn, you can expend an extra Power Slot to use one of your Bursts as a reaction.
 
 #### Risoluto
 Starting level 15, the magic power that permeates you seeps out in an invisible aura. As long as you have at least an unused Power Slot, you have extra hit points equal to your intelligence modifier, plus the number of Essences you mastered. 
 As long as you have at least one of these HP, your Armor Class and your your Strength and Constitution saves are increased by 2. Once those extra HP are depleted, you only recover your Risoluto aura when you recover a Power Slot.

#### Adagio
Starting level 18, once per encounter you can spend an entire turn of combat without casting. If you do, you save enough magic energy to recharge a Power Slot, and in so doing, to regain your Risoluto aura.

#### Gran Finale
At level 20, whenever one of your Power Bursts reduces an opponent to 20 HP or less, a multicolored firework made of your mixed Essences hits it as a quick follow-up and reduces it to 0 instead, adding a Flair to your encounter.
```
```

 <img 
  src='https://pre00.deviantart.net/d72e/th/pre/f/2015/268/5/c/juggler_by_chinasky66-d9atymn.jpg' 
  style='width:325px' />
Credit: Chinasky66

## Magic Essences
**Acid Pulse** – 20ft  
 Acid doesn't have many purposes beyond corroding and dissolving materials.  
 Attack – Hit roll –  You project a spray of translucent, fluorescent green acid towards your target. For every die in which you get maximum damage, your target suffer one extra die of damage at the start of its next turn, but decrease the dice class each round. If you get lower than d4, the effect ends.  
 
  **Air Pulse** – 60ft  
 You send forth an air current. You can disperse fog or cloud effects in a sphere with 5ft radius, snuff out small flames, or help a fire catch.   
 Attack – STR save to negate – A target failing a STR save takes magical bludgeoning damage and is pushed away from you 4+1d6ft. You can push a willing or unresisting target without causing the damage. Effects that Increase Dice affect the distance a target is pushed, instead of the damage. Decreasing dice works normally. 
 
  **Cold Pulse** – 90ft  
 Freeze liquids in a 5ft cube or turn a wet surface with 5ft radius into Difficult Terrain.  
 Attack – Hit Roll – You project a blast of freezing power. A target without cold resistance that takes damage from it has its movement reduced by 10ft until the end of its turn. You can forego damage in order to stop a creature of large size or less from moving altogether.
 
 <div class='pageNumber auto'></div>
 \page

  **Darkness Pulse** – 60ft  
 Cast a small lingering shadow on a target, giving it advantage on a single Steath check, or giving disadvantage to a single perception check rolled to find a target item, not greater than a 5ft cube.  
 Attack – CON save to negate –  A Darkness Burst hits automatically, deals magic damage and causes Blindness to a target until the end of its next turn. Subterranean creatures are immune to the blinding effect.  
 
 **Earth Pulse** – 60ft  
 You can use turn earth and stone surfaces into difficult terrain in a 5ft radius, or remove difficult terrain in a similar area. The Pulse isn't strong enough to form a particular shape.  
 Attack 1 – Hit Roll – A stone or compressed earth projectile shoots from your hand towards a target, dealing nonmagic bludgeoning damage to a target you hit.  
 Attack  2  – DEX Save to negate –  A stone spike erupts from earth or stone terrain, hitting automatically and dealing nonmagic piercing damage to a target that fails a DEX save.  
 
  **Electric Pulse** – 120ft   
 You can electrically charge an object not greater than a 5ft cube, or cast cool looking, but hardly useful, electric arcs.  
 Attack – Hit Roll – You produce an electric arc that can shock opponets. A creature hit by an Electric Pulse has Disadvantage on its next attack roll or ability check during this turn. Electric Pulse has Advantage on attack rolls against metallic targets, or targets wearing metallic armor. 
  
 **Fire Pulse** – 90ft  
 You create a blazing flame you can use to heat or ignite objects, melt snow in a 5ft cube, or ice in a 1ft cube.
 
 Attack – Hit Roll – If you hit your target  with a Fire Pulse and get a critical hit, or roll maximum damage on at least one of your dice, in addition to the fire damage a target covered in flammable materials (fur, cloth) is ignited and must spend an action to extinguish the flames or keep taking one additional die of fire damage at the start of its turn for 1d4+1 rounds. The ignite effect doesn't stack. 
 
 **Iron Pulse** - 60ft
 Move or reshape a 1ft cube of metal into a simple form, or give a metallic weapon a d4 extra damage for its next attack.
 Attack - DEX save to negate -  cast a small hail of throwing blades at an enemy that deal magical slashing and piercing damage. Add a +1 magical bonus to each damage die. 

 **Kinetic Pulse** - 30ft 
Move an object not heavier than 50lbs at will within range, at a speed of 10ft per INT bonus.
 Attack - Hit Roll - You can wield a weapon telekinetically. With every Kinetic Pulse, you can use it to attack as if it was a ranged spell attack. Add your INT modifier to the damage it deals. The weapon must be suitable for medium-sized creatures.
 
  **Light Pulse** – 120ft  
 You can cast a flash of light, or a single beam, for a moment.  
 Attack  – Hit roll – A target hit by a Light Burst takes Radiant damage and faintly glows, revealing it and giving advantage to the next attack aimed at it during this round, except in full daylight. Undead take an extra die of damage from Light Burst. 
 
 **Necro Pulse** – 60ft  
 You give forth a wave of Necrotic energy, which can ruin and tarnish organic materials or wither small plants and snuff tiny creatures with CR 0, in a 5ft cube or on a surface with a 5ft range.  
 Attack – Hit Roll – A streak of dark light deals Necrotic damage to a target you hit. Necro Pulse deals one extra damage die to living, organic creatures and has Increased Dice against plants and vegetal based creatures.
 
  **Plant Pulse** – 30ft  
 Grow, heal or make move small plant life in a 5ft radius, or a single larger plant not bigger than a 5ft cube.  
 Attack 1 – STR save to Negate – A swift green vine swoops off of you, attempting to entwine your target. A target that fails a STR save suffers bludgeoning damage and is considered Restrained until the end of its turn, when the vine fall off by itself. You can always forego damage if you want. 
 Attack 2 - pull a target of medium size towards you by 4+1d8ft. Effects that Increase Dice affect size of your viable targets, while additional dice are added to the distance.
 
 **Poison Pulse** – 30ft   
 Contaminate enough food or liquid to poison a creature of medium size that ingests them within an hour. If that creature fails a CON save it takes 1d12 damage and is poisoned for 24 hours.  
 Attack – CON save to negate  – You give off a puff of poison that automatically hits the target and deals Poison damage. Add one die of damage for each time a creature has been previously damaged by a Poison A creature poisoned by this Pulse is nauseous and suffer a -2 penalty to attack rolls and dex and con savesfor a turn.

 **Sound Pulse** – 60ft  
 Double the volume of your voice, or shatter rigid, fragile items in a 5ft radius.  
 Attack – CON Save to negate – You focus a blast of soundwaves onto a single target, dealing Thunder damage and deafening it until the start of your next round. An inorganic creature made of rigid materials like stone, metal or crystal takes half damage on a successful save, but stil resists the deafening effect.  
 
 **Water Pulse** – 60ft  
 Create or move a 5ft cube of water.  
 Attack – Hit Roll – A quick stream of water shoots from your hands or from a nearby water source. The target must be within 60ft from you, or 60ft from a water source which is itself within 60ft of you. Water Burst deals non-magical slashing or bludgeoning damage to a target it hits.   
 
 
### Advanced Essences (Level 13 Virtuoso, Maestro) 
 Pulses used with Advanced Essences count as 3rd level spells towards resistances and dispel attempts.
 
 **Force Pulse** – 60ft  
 A beam of white magic power reaches an empty space, creating a 5ft square transparent (but visible) Force barrier facing any direction for one turn. Attacks and magical effects can't pass through it. If you use it as a reaction (like with Reflex Pulse) to stop an attack, the attacker can pass a Dexterity save to see if he manages to complete the attack or spell before the barrier forms.
  
 <div class='pageNumber auto'></div>
 \page

 **Mind Pulse** –  60ft  
You can read an opponent's surface thoughts (WIS save negates, can try again after a rest), or communicate short messages to other intelligent creatures in range.  
 Attack – WIS save to negate – An invisible energy spike hits your taget, dealing psychic damage and inducing Confusion in an intelligent creature until the end of its next turn.  
 
 **Space Pulse** – 60ft  
 A thin, silvery beam shoots from your finger. A target of medium size that fails a Dexterity save is moved 5ft in any direction in which it's free to move. Non-magic, unattended items do not get a save.  
 Space Pulse doesn't deal damage, an increase in dice class increases the distance by 5ft, while an additional die indicates an increase in the target's size.
 
 **Time Pulse** – 60ft  
 Take off simple time wear from an item that doesn't occupy a space greater than a 5ft cube, or to rapidly corrupt a similar target, giving Advantage to any attempt to break it.  
 Attack – WIS Save to negate – A golden sphere hits your target, either slowing it or hasting it until the end of its next turn. Time Pulse doesn't deal damage.  
 
 **Void Pulse** –  120ft  
 Attack – DEX Save to negate – A black globe dissipates matter wherever you aim it in a sphere with a diameter of 5ft. Void deals Force damage. You can cast Void Pulse as a continuous beam (doesn't affect damage or attacks).
 
 
## Basic Forms (level 1)

 **Flourish** – You can cast a Pulse in an arc, a spiral, or have it ricochet off a surface. Ignore up to 75% cover, Flourish doesn't get disadvantage when used with Flair.
   
 **Martial Stance** – Assume a defensive stance and charge your body and hands with an Essence you can produce. Make a melee spell attack or a regular unarmed attack, the first time you hit an opponent with an unarmed melee attack this turn add a die of the appropriate type to your unarmed attack's damage. You get +2 to AC and DEX saves against that opponent this turn.
 
 **Power Pulse**  – Adds potency to a Pulse. Increase Dice for a Pulse Attack, if a Pulse allows for a STR save, that save gets a -2 penalty. Doubles AoE of non-attack uses.  
 
 **Quick Pulse**  –  You can use your bonus action to cast a Pulse. You can also use an interposing effect (like Light Pulse or Force Pulse) to take the Disengage action instead of dealing damage. Requires level 3.

 **Sniper Pulse**  –  Doubles a Pulse's range. If a Pulse requires a ranged spell attack, you get a +2 attack bonus. If a Pulse allows for a DEX save, the target gets a -2 to save against it.  
 
## Advanced Forms (level 5)  

**Disrupting Spike** – You focus a Pulse into a single spike of magic power, and aim it at a single magical effect you are aware of within range. This Pulse sends ripples through this magic effect, possibly interupting it.  
 Make an ability check using your spellcasting ability vs DC 10 + the level of the effect you're targeting. If you succeed, the spell or effect is suspended for a number of rounds equal to your spellcasting modifier.  
You can't use an Extra Pulse in the same turn as a Disrupting Spike. It's just too long to 

**Extra Pulse** – You can cast one extra Pulse during your action. Requires level 7. 
 
 **Intercepting Shot** – As a reaction, you can fire a Pulse at an incoming physical of magical projectile. If that Pulse is suitable to stop or contrast that attack (Fire Pulse couls stop a Ray of Frost, Earth Pulse could stop an arrow, etc) you reduce the damage you take by the amount of damage that Pulse deals.  

**Lingering Pulse** - Condense a Pulse into a small sphere that floats on a point in space of your choice within range, and discharges its effect after a maximum number of rounds equal to your Intelligence modifier, or when disturbed. A creaure that activates a Lingering Pulse takes the Pulse's damage and effect automatically.
 
 **Pulse Shotgun** – You can fork a Pulse to hit a number of targets equal to your spellcasting modifier within a 60°, 30ft cone in front of you. These projectiles or beams travel in a straight line and can't hit obscured targets.  
  
**Reflex Pulse**  – You can use this Pulse as a reaction, if the Pulse you use can directly affect the action you declare as trigger. You can also use a Pulse as an opportunity attack.  

 **Ram Shot** – An opponent damaged by one of your Pulses with Ram Shot must make a STR save or be thrust prone. If your Pulse already required a STR save, add this effect to that same save. Ram Shot deals double damage to objects.  
 cast. 
 
 **Spiral Shell** – You release the power of a Pulse in a small field of particles spinning around you. You have a single die of extra HP until the start of your next turn.  
 If a melee attack exhausts these extra HP, the attacker must pass a DEX save or suffer one die of damage of the Burst you used, plus its additional effect.  
 If you're using Force Essence, you have +2 to AC and saves for as long as these extra HP last, but the shell doesn't deal accessory damage.  
 
## Superior Forms (level 11, Virtuoso) 
 Pulses used with Superior Forms count as 3rd level spells towards resistances and dispel attempts.
  
 **Cheap Shot** – If you use a Cheap Shot on an opponent who is prone, or is currently engaged in melee combat with someone else, or as an opportunity attack, and it deals damage to that opponent, it deals maximum damage.
 
 **Cover Fire** – You fire a deluge of cheap magical effects in rapid succession to provide cover. Enemies in your line of sight for 120ft that take attack actions this turn must succeed in a DEX save or take a single die of damage of a type one of your Pulse can deal, and get disadvantage on attacks this turn. Cover Fire takes up your action, bonus action and reactions for the turn. Requires Extra Shot. 
 
 **Extra Reflex Pulse** – You get an extra reaction per turn, but you can only use it to use an Extra Reflex Pulse. Requires Reflex Shot and Extra Shot.  
 
 **Floop** – You use your Space Pulse to warp instantly up to 30ft away. The Form's name comes from the sound it makes. Requires Space Pulse.  
 
 **Intense Pulse** – Add one die of damage to a Pulse. If that Pulse requires a CON save, the target suffers a -2 penalty to that save. Increases the intensity of the non-attack effects of your Pulses (might speed up a process, give more control, etc).
 
 <div class='pageNumber auto'></div>
 \page

 **Intercepting Shotgun** – You can use your reaction to fire a Pulse Shotgun at an incoming spell or attack with an area of effect. If that Pulse is of a type that can contrast that attack (like Cold Pulse against a Fireball, or Air Pulse against a Cloudkill, etc), you reduce the damage you take by the amount of damage that Pulse deals. This damage reduction also applies to any target in a narrow cone behind you. Requires both Intercepting Shot and Pulse Shotgun.  

 **Outward Burst** – Your Pulse hits every viable target within 10ft of you. You can decrease or remove dice by any amount to increase the range by 5ft each time.If the pulse requires an attack roll, it becomes a dexterity save to avoid instead instead, all other saves are unchanged.  
 
 **Pinpoint Pulse** – You can hit a specific part of your target, like his weapon arm, a wing, or an eye.  
 If you damage your target, it must pass a Constitution save or suffer a penalty relative to where you hit it (drops weapon or item, can't maintain flight this turn, has disadvantage on attacks on his round, etc).  
 If the Pulse you used already required a CON save, this effect is included in that save.  

 **Rattle Pulse** – You can use your reaction to attack a magic user while he's casting with a hard, vibrating Pulse not associated with any essence. If you deal damage to him, he must pass a concentration check to complete his spell. If he fails, he doesn't get to cast, but doesn't lose the spell nor the components and can try again next round.  

 **Subtle Pulse** – You can cast this Pulse without one of its components.  

 **Totem** – You can use a Pulse capable of creating or altering something solid, like Earth, Plant, Iron or Force Pulse (or Cold Pulse if you use it on a pool of water), to raise a small magical totem with AC 10 and HP equal to your Pulse damage. As long as you are within 100ft from it, you can have your pulses of that kind come out of it when you cast them. 
 You can't add other Forms to the Pulses you cast through the Totem, unless you are using Cross Forms. If you get farther than 100ft from it, the Totem dissipates or crumbles into nothing.

## Power Bursts (level 11, Maestro)
 
Power Bursts are the means by which the Maestro releases the magical power he progressively stores inside of him. 
You can't cast Extra Pulses nor Quick Pulses in a turn in which you use a Power Burst.  

**Barrage** – you can fork a Pulse to hit a number of targets equal to your level in a 180° arc in front of you with radius equal to the Pulse's range. If that Pulse requires an attack roll to hit or a save to negate, it turns into a Dexterity save to negate instead.  
 Aternatively, you can have the barrage converge on a a single target. If you do, the target must pass a DEX save or suffer a single die of the Pulse's appropriate damage for each attack hitting him, and its appropriate effect. On a successful save, it can dodge about half of them, so it takes half damage and negates additional effects. 
 
 <img 
  src='https://i.pinimg.com/originals/f4/a1/2b/f4a12b7ab23d2b4ccc1eebdb5b6fd806.jpg' 
  style='width:325px' />
Credit: sigu

 
**Essence Fence** – You warp a number of Essences equal to your INT modifier into semi-solid beams, then weave those into 10ft X 10ft square panels. You use 10 of these panels to construct a tight-woven fence, with any degree of inclination and curvature. It will stay in place in any position for as long as you concentrate on maintaining it.  
 Attacks, spells and spell effects can't pass through the fence, except for narrow beams (like Ray of Frost or Disintegrate), which need a ranged attack roll to hit (at a disadvantage if they already required one).  
 A creature can force its way through the fence with a STR save VS your casting DC. It takes a creature half their movement to pass through the fence, and in doing so they suffer all effects of the essences you weaved into it  (attack rolls become DEX saves to negate, all other damage and effects work normally as if  you had cast them).  
 
**Expanded Barrage** – You can hit all targets within 120ft around you with a  Pulse of your choice (no hit roll, DEX save to negate). You can expend an extra power to have a concentrated Barrage hit one of them. You can use Sniper Pulse to double the radius of this spell, but if you do you get a point of exhaution due to the stress. Requires Barrage and Expanded Blast.  

**Expanded Blast** – Range: 60ft plus the Pulse's range  – Radius: 20ft – You can have a Pulse detonate in a sphere to affect all targets within the area. If it's an attack, double the number of dice of the appropriate type you would roll for damage and add your INT modifier. If the Pulse used requires a hit roll, creatures hit by the blast must instead roll a DEX save to halve the damage they take and negate additional effects. If the Pulse requires a save, use that save to halve damage and negate effects. You can expend up to two extra Power Slots to add damage dice equal to one of your Pulses each time.

   <div class='pageNumber auto'></div>
 \page

**Hydra** - By casting a complex Pulse, you summon spectral hydra heads from the ground in any free space within 60ft, in mumber equal to your INT modifier. Each head has AC equal to 10 + your INT modifier and HP equal to your Pulse's damage (roll once for all heads). Each Hydra head is imbued with an Essence you can produce, and each can cast the relative Pulse once per round, starting with the round in which they're summoned. They are resistant to that type of damage. As a bonus action, you can sacrifice a head to move the others to a new location within 60ft.
At the start of each of your rounds, and every time you lose concentration, one head retreats undergound, until none are left.

**Magic Absorption** – You attempt to drain a magical effect by rolling your Spellcasting Ability vs 10 + the level of the spell you're trying to dissolve. If you succeed, the magical power you drained forms a shimmering aura around you. You get  temporary HP equal to your Pulse damage, plus the level of the drained spell.  
If you cast this using your reaction (using Crescendo), it can counter that spell while it's being cast. 

**Stunt Double** - You create a double of yourself made of magical essence that lasts up to one minute. This double has all of your skills, AC equal to 10 plus your Intelligence modifier, and HP equal to the maximum damage you deal with your basic Pulse. As long as your Stunt Double is active, neither you nor it can use Power Bursts nor Advanced Essences. Additionally, the Double can only use Basic Forms with his Pulses. No matter which one is destroyed first, it disappears into a puff of colorful magic Essence and the remaining one is you.

```
```

 ## Feat: Arcane Juggler
 If you are not already an Arcane Artist, you can now cast Pulses at will, like one of the same level as you, and gain access to a single Magic Essence and two Basic Forms.
 
 
### Average damage 
Maximum output intended as under the best possible conditions with highest damage build, average calculated on a hit or miss basis at 50%.

- lvl 1

-power pulse - 1d10 50% - 3

-other - 1d8 50% - 2

- lvl 5

-power, quick, reflex 2d10+2d6+2d4 50% - 10 (uses action, bonus action, reaction)

-Power, quick or reflex 2d10+2d6 50% - 8 (uses action plust either bonus or reaction)

-power - 2d10 50% - 5 (bonus action and reaction are free for other stuff)

-other - 2d8 50% - 4

- lvl 10

-Power, extra, quick, reflex - 2d12+2d8+2d6+2d4 50% - 15 (uses all actions to cast)

-Power, extra, quick or reflex - 2d12+2d8+2d6 50% - 13 (bonus or reaction are free)

-Power, extra - 2d12+2d8 50% - 10 - (bonus and reaction are free)

-other - 2d12 50% - 6

- lvl 15 Vitruoso

-Intense, power+extra, quick, reflex, extra reflex - 4d12+3d12+3d8+3d6+3d4 50% - 34 (all actions and reacions expended) 

- lvl 15 Maestro

-other, extra, quick, reflex - 3d12+3d10+3d8+3d6 50% - 28 (all actions and reactions expended, no Bursts)

- lvl 20 Virtuoso

-Intense, power+extra, quick, reflex, extra reflex - 5d12+4d12+4d8+4d6+4d4 50% - 45

- lvl 20 Maestro

-other, extra, quick, reflex - 4d12+4d10+4d8+4d6 50% - 36

  <div class='pageNumber auto'></div>

<div class='footnote'>Made with THE HOMEBREWERY at NaturalCrit.com</div>

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @TheGreatWhy
