### ISSUE TITLE
suggestion: "\column" in same manner as "\page"

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#607]
It would be nicer to simply write "\column" instead of two lines of backticks.

Would feel like less of a hack too ;-)

**Comment by calculuschild** [comment]
I agree. We will look into this as part of the v3 changes.

**Comment by brunobord** [comment]
any news about this one? I think this feature would be really great to avoid this hackish column break.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
