### ISSUE TITLE
Shadow not wrapping correctly

### ISSUE THREAD

**Issue by Smashman** [naturalcrit/homebrewery#610]
It appears that when column wrapping, the top of a wrapped stat block's shadow can be seen at the bottom of the first column.

Thanks.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/rko55LzHz

**Comment by Smashman** [comment]
Might I suggest using flexbox and flex-wrap, rather than the coumn?

**Comment by AlexeySachkov** [comment]
@naturalcrit/issue-managers, I suggest that we close this one, because we have applied a workaround in #1179
