### ISSUE TITLE
Cannot find brews

### ISSUE THREAD

**Issue by duke-of-shao** [naturalcrit/homebrewery#612]
I must be stupid because I cannot find any of my brews once I close the browser. I'm signed in to my account, and they all say they're saved, but neither the recent brews pulldown works, nor does my profile page which is supposed to be how I find projects. I didn't save the edit links thinking I would be able to get to past projects, but I cannot figure it out.

Cheers,
Charles

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
We have made any improvements to the saving system since this was posted, so the issue has likely been solved.

If not, this may be related to #807 in which case this is a duplicate anyway.

Feel free to reopen if this issue still occurs for you, @duke-of-shao
