### ISSUE TITLE
Save to PDF loses hyperlinks

### ISSUE THREAD

**Issue by darkfienixthedm** [naturalcrit/homebrewery#613]
Hi,

Fantastic tool, thank you for all your hard work.

When I use Chrome to save out the PDF the hyperlink isn't retained.  It's there in the Shared view and the styling is present on the PDF produced but the hyperlink is lost.  

Am using Chrome Version 63.0.3239.132 (Official Build) (64-bit) on macOS High Sierra Version 10.13.2.  I am using A4 page size.

Thank you !

### Additional Details

https://homebrewery.naturalcrit.com/share/HkoEY80SG

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by granack** [comment]
your link works on Chrome 64 and Linux Mint 18.3 using Xreader to look at the pdf file. what are you using to view the pdf file? maybe try something different

**Comment by darkfienixthedm** [comment]
Hi granack

I'm using Preview on macOS, Version 10.0 (944.4) to view the PDF.  The hyperlink looks to be formatted ok (blue underlined) but isn't clickable.

Also if I use Acrobat Reader on macOS (Build: 18.9.20050.254034) and the PDF viewer on my Android phone (Android 8.1.0).  I don't think it's the viewer, I think it's the generation mechanism of the PDF file using Chrome on macOS High Sierra.  

If I print the page on my Windows 10 in Chrome, then the hyperlink forms correctly and is clickable in the generated file.

**Comment by Gazook89** [comment]
This seems to work now, tested on MacOS Catalina 10.15.6 printed to PDF via Chrome, and viewed in Preview.  Links are formatted correctly and are clickable (both internal links to pages and to external links like google.com).  I think this can be closed, @calculuschild @ericscheid

**Comment by calculuschild** [comment]
If this appears to be fixed let's close it.

@darkfienixthedm If this is still an issue feel free to reopen this.
