### ISSUE TITLE
Bombchus stat block is off the page.

### ISSUE THREAD

**Issue by dopll** [naturalcrit/homebrewery#617]
### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by granack** [comment]
Add a page break.
If that isn't what's needed, please post example code to demonstrate the issue, or your brew's share link.

**Comment by ericscheid** [comment]
No further details supplied since original posting in Feb 2018. Closing.
