### ISSUE TITLE
Cannot Extract Embedded Fonts (PDF)

### ISSUE THREAD

**Issue by LaminatedPotato** [naturalcrit/homebrewery#618]
Certain embedded fonts (anything in T3Font_0, AKA most of my content) aren't rendering properly in Adobe Acrobat 8 Professional (all characters are just a series of dots), but display fine in programs like Firefox or Adobe Acrobat Reader DC. Is this simply because Acrobat 8 is older software and can't handle it? Is there any fix for this?

**Comment by calculuschild** [comment]
@LaminatedPotato Is this still an issue for you? I'm not sure it's something we can fix on our end; probably an Adobe thing if it works in DC but not Acrobat 8.
