### ISSUE TITLE
Brew page not printable

### ISSUE THREAD

**Issue by derschenki** [naturalcrit/homebrewery#633]
Hey folks,

i've been writing on a new Numenera Oneshot yesterday, but one of the pages is unprintable. Everytime I try to print via chrome, chrome gets slower and slower until it collapes. I tried everythin, even every other page is printable, but this one kills my browser.

Has anybody an idea why?

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/BkbMzkfetz

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<img src="https://image.ibb.co/eWN68S/44aa802a8be573694c075fba24ae8808.jpg" style='position:absolute;top:0px;left:0px;width:816px'/>

<img src="https://image.ibb.co/hJSg8S/VxJ8X1u.png" style='position:absolute;top:0px;left:0px;width:916px'/>

<div style='margin-top:450px'></div>

# Erster Akt: Die Suche nach dem Aeonenpriester
## Szene 01: Die Dorgemeinde
<p align="Justify">In einer kleinen Gemeinde wird die Hilfe einiger Abenteurer benötigt: Der hiesige Äonenpriester, eine Art Vorsteher des Dorfes, scheint verschwunden zu sein. Er hatte sich auf eine kleine Expedition begeben zu einer RUine etwa einen Tagesmarsch südwärts. Vor zwei Wochen ist er aufgebrochen und wollte bereits vor einer Woche zurückkehren, doch seit seinem Aufbruch hat niemand mehr etwas von ihm gehört. Die Dorfbewohner sind in großer Sorge deswegen. Die Tochter des Äonenpriesters, ein Findelkind, das von ihm aufgenommen und großgezogen wurde, leidet ganz besonders unter der Abwesenheit ihres Ziehvaters. Deswegen heuert sie die Abenteurer an, um ihn zu suchen.<br>Ansonsten hält das Dorf die üblichen Orte für die Abenteurer bereit: Es gibt eine kleine Schenke, in der der Wirt ein beachtlache Anzahl Spirituosen für den geübten Gaumen bereit hält - allerdings sind die meisten davon selbstgebrannter Natur und nur für den geübten Trinker genießbar. Darüber hinaus gibt es einen kleinen Laden im Dorfzentrum, der von den Handelsgütern der reisenden Händler lebt und diese an die Dorfbewohner und Abenteurer weiter verkauft.</p>
```
```
<p align="justify">Die Dorfbewohner selbst sind in einer schlechten Stimmung und nicht allzu gesprächig. Sie gehen ihrem Tagewerk nach, sind aber missmutig über den Verbleib ihres Oberhauptes. Einige der Dorfbewohner sprechen bereits davon, sich nicht weiter um den Äonenpriester zu kümmern und ein neues Oberhaupt zu bestimmen - vermutlich sehen viele derjenigen, die diese Gedanken äußern, dazu berufen, selbst Dorfoberhaupt zu werden, auch wenn keiner derjenigen dies aus freien Stücken zugeben würde.</p>

<p align="justify">Ansonsten sind die meisten der Dorfbewohner sehr freundlich und zuvorkommend. Es ist eine besondere Form der Höflichkeit, die den SC hier im Dorf begegnet. Selbst wenn die Bewohner etwas schlechtes über die Abenteurer zu sagen wüssten, würden sie dies niemals offen tun. Eine solche Aussage, insbesondere im Beisein desjenigen, um den es geht, betrachten die Dorfbewohner als größte Form der Beleidigung.</p>
## Szene 02: Der Tagesmarsch durch den Sumpf
<p align="Justify">Der Weg zur Ruine erstreckt sich durch ein sumpfiges Gebiet, in dem hohe Bäume direkt aus dem dunklen Schlick wachsen, der den Boden bedeckt. Kleine Pfade aus Synth-Planken, mit einem ebenfalls aus Synth gefertigten Geländer an beiden Seiten, hängen von den Ästen der Bäume und führen in einigen Metern Höhe über den Schlick hinweg. Der Wg ist alt, verwittert und rutschig, doch für den Moment ist dies der beste zur Verfügung stehende Weg.</p>
<div class='descriptive'>SC, die mit dem dunklen Schlick am Boden in Berührung kommen, erleiden eine zufällige Mutation (**1W4 + 1W100**, Charakter Options S. 45ff.).</div>
<div class='descriptive'>In den Gipfeln der Bäume hängen abseits des Pfades Nester von fremdartigen Wesen. Wer den Nester zu Nahe kommt, riskiert einen Kampf mit mehreren **Tetrahydras**.</div>
<br><br>
<img src="https://image.ibb.co/dFkMa7/0f10c3e57434f95c6b231b3e720c5da6_apocalypse_concepts.jpg" style='width:325px'/>
*Tetrahydra, aus: Numenera Grundregelwerk: Seite B138*
<div class='pageNumber'>1</div>
<div class='footnote'>SEITE 1 | Der Würfel und das Nichts, 1. Akt</div>

</pre></code></details>

**Comment by HeruAsatru** [comment]
Had no problem printing it as PDF ... can't reproduce, can you provide any more information?

**Comment by AlexeySachkov** [comment]
@calculuschild, @ericscheid, I suggest that we close this one

**Comment by calculuschild** [comment]
Closing for now because of no further response from the user, and the issue does not have enough information to fix.

Feel free to reopen this issue if this is still a problem for you and you can provide more information, @derschenki
