### ISSUE TITLE
How to force NOT indenting?

### ISSUE THREAD

**Issue by Abelhawk** [naturalcrit/homebrewery#636]
The text automatically indents after a paragraph break, but this isn't how it's supposed to look after things like bulleted lists or subtitles. For example, on a magic item entry after the line that says "Wondrous item, rare, requires attunement," it should not indent. How do you suppress the automatic indent that exists?

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by HeruAsatru** [comment]
You can either enter 2 spaces at the end of the line to make the next one not indented, like so (can't really see much, because those are 2 spaces we are talking about^^):

```
#### Adamantine Armor
*Armor (medium or heavy, but not hide), uncommon*  
This suit of armor is reinforced with adamantine, one of the hardest substances in existence. [...]
```

Adding three underscores above where you dont want the indentation does also work:
```
#### Adamantine Armor
*Armor (medium or heavy, but not hide), uncommon*
___
This suit of armor is reinforced with adamantine, one of the hardest substances in existence. [...]
```

**Comment by Abelhawk** [comment]
Thanks! The underscore solution works really well, though I can't seem to make a difference adding the two spaces. Nothing happens :/

**Comment by WormSlayer** [comment]
Put a <BR> in between the paragraphs. It cancels out the indentation of the next paragraph.

**Comment by Abelhawk** [comment]
The `<br>` thing works much better. Thanks!

**Comment by calculuschild** [comment]
We should look into making this a default behavior for the homebrew styling to better match the PHB.

**Comment by ericscheid** [comment]
There is a line in the CSS that looks like this:
> .phb p+p, .phb ul+p, .phb ol+p { text-indent: 1em; }

That's the rule that indents paragraphs which occur after either another paragraph, an unordered list, or an ordered list.

I'll go looking for it in the .scss file and simplify it to just `.phb p+p`

**Comment by calculuschild** [comment]
You can add a backslash to the end of your paragraph to prevent an indent on the next line. 

Also in v3 you can put a colon alone on a line to insert a blank line, and the next paragraph will not be indented.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
