### ISSUE TITLE
Cover Image

### ISSUE THREAD

**Issue by PariahSilver** [naturalcrit/homebrewery#640]
Hi there! Is it possible to create a cover image? I love the "PHB > Cover Page" snippet, but whenever I try to add a page before it to create a cover image my brew gets pretty confused, doesn't load properly, and sometimes doesn't load at all. I've tried several different variations, but so far no joy.

**Comment by ericscheid** [comment]
To get a full bleed image you can insert something like the following. Adjust the URL of course, and also width if your page size isn't normal.

```
<img 
  src='https://i.imgur.com/rbGEH7f.png' 
  style='position:absolute; top:-6px; right: 0px; width: 820px' />
```

If you want nothing else on the cover page your just enter the `\page` code, like this:

```
<img 
  src='https://i.imgur.com/rbGEH7f.png' 
  style='position:absolute; top:-6px; right: 0px; width: 820px' />
\page
```

Hope that helps =)

**Comment by ericscheid** [comment]
A contender for a new snippet #1096

**Comment by Gazook89** [comment]
Including this in #1673 and going to close this one out.
