### ISSUE TITLE
Only left alt key should be used for shortcuts (both are now)

### ISSUE THREAD

**Issue by ivellios** [naturalcrit/homebrewery#647]
In all applications there's a distinction between the left and right ALT key. This is due to use of the right ALT for entering special chars in some languages/keyboard layouts. In my case - Polish language - I am using it to create letters like ł, ó, ę, ą, ź...

It works fine in the case of most, but not for `R_ALT+S`, which would result in `ś` letter, but this also works (as `L_ALT+S`) for saving stuff.

Can this be fixed quickly? I can contribute.

I have found in the code, that there's only `metaKey` and `ctrlKey` is used: https://github.com/stolksdorf/homebrewery/blob/8b148b81b8e94ef9f9548994c55dce844ebd7442/client/homebrew/pages/newPage/newPage.jsx#L50-L60 Yet somehow alt is also used... AFAIK it shouldn't.

**Comment by ericscheid** [comment]
The HTML DOM KeyboardEvent doesn't make any distinction between left and right ALT keys. 
https://www.w3schools.com/jsref/obj_keyboardevent.asp

The metakey in javascript in windows refers to the windows key, not the alt key.
> metaKey read-only property returning a Boolean that indicates if the Meta key was pressed ( true ) or not ( false ) when the event occured. Note: On Macintosh keyboards, this is the command key ( ⌘ ). On Windows keyboards, this is the windows key ( ⊞ )
> https://stackoverflow.com/questions/6245868/which-key-does-the-e-metakey-refer-to-in-javascript

(Also various comments about that many browsers only return `undefined` for `metakey`)

From the code, I do not see why ALT+S is triggering anything. On mac I can press `ALT+S` to get "ß". 

What browser are you using?

**Comment by ivellios** [comment]
It is Chrome, but it's been so long ago I can't recall what was the issue. Just stopped using the tool. Sorry. 

Also, I noted that ALT is not used in the code, and yet it behaves as if it was somehow also caught.

**Comment by Gazook89** [comment]
I just tried to reproduce this in macOS Chrome, Firefox, and Safari and could not reproduce:   `alt` + `s` only created `ß` using either left or right `alt`.   Couldn't reproduce with any other keys beside `s` either.  

I'd be interested in hearing from a windows user too, but I suspect this can be closed due my experience above and age of the issue without further complaints from other users.  @ivellios if you are able to reproduce this still, let us know (I know this is like 4 years old and you aren't using HB anymore, sooo.....)
