### ISSUE TITLE
[Feature Request] Goto line in editor

### ISSUE THREAD

**Issue by Drahsid** [naturalcrit/homebrewery#652]
This is a pretty simple suggestion, in the editor render, we should be able to go to a specified area in the code. This could help speed up editing and problem solving.

**Comment by calculuschild** [comment]
This might be handled by #2162

**Comment by Gazook89** [comment]
Going to close this as solved by the brewJump PR.  Additionally, there is now a search function in codemirror (though it could be more obvious).
