### ISSUE TITLE
Not clear how to rename/edit metadata of brews

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#653]
Several users have asked how to change the title of their brews. This feature is hidden away behind the (☰) button in the toolbar. Perhaps we can find a more obvious way to do this. I suggest:

- Change the "☰" icon to a "ⓘ" info icon.
- Allow the user to edit the title of the brew by clicking directly on the title in the page heading

#622, #328

**Comment by ericscheid** [comment]
Also add to the FAQ #810

**Comment by ericscheid** [comment]
The current icon is from font-awesome using `<i class="fa fa-bars"></i>`, which is line 49 of /client/homebrew/editor/snippetbar/snippetbar.jsx

Alternatives are [fa-info-circle light](https://fontawesome.com/icons/info-circle?style=light), [fa-info-circle regular](https://fontawesome.com/icons/info-circle?style=regular), and [fa-info-circle solid](https://fontawesome.com/icons/info-circle?style=solid). The first two require FA Pro.

**Comment by ericscheid** [comment]
homebrewery is using FA Classic, not pro, so this is what the solid info-circle looks like:

![fa-info-circle](https://user-images.githubusercontent.com/2605467/99919866-24b17d00-2d74-11eb-9851-64d695aa9b8d.png)

**Comment by calculuschild** [comment]
I feel like maybe we need to straight up add some text there as well. We have space. Just make it a complete "brew info" button.

**Comment by ericscheid** [comment]
> I feel like maybe we need to straight up add some text there as well. We have space. Just make it a complete "brew info" button.

Seems doable, lemme tweak my tweak

**Comment by ericscheid** [comment]
The brew-meta button is now an "Properties" button with an "i" in circle icon:
![image](https://user-images.githubusercontent.com/2605467/111172179-b67e1800-85f9-11eb-985c-4983b775f53f.png)

This should go a good way towards fixing the original issue.
