### ISSUE TITLE
Issues with brews not saving

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#654]
## Description

We seem to be getting a lot of issues with lost work, brews not saving, brews getting reset to earlier states, accidentally overwriting a brew and autosaving over it. etc. This may have several causes.

One of these is the Homebrewery seems to be loading brews from the cache (#603, #311 ) rather than the actual saved version when restoring a browser session (pressing `ctrl+shift+t` or having chrome automatically reload all recent tabs when opening the browser) for example.

Possible solutions?

- Do not load from cache when refreshing or reloading the edit page
- Implement a document backup/versioning system?
- Post a notice urging users to backup files on their local machines
- Save/load from local drive

#278, #603, #615 , #650

**Comment by AsteronCalypse** [comment]
This also happens to me ALL THE TIME!

**Comment by calculuschild** [comment]
@AsteronCalypse Do you have any specific details? Do you notice it happening in certain situations, or do you know what steps to take that cause this problem to show up?

**Comment by calculuschild** [comment]
Brews are now always reloaded from the latest saved version, preventing accidental data loss when visiting a brew via the back button. 

Fixed in commit 77973f0. Closing.
