### ISSUE TITLE
Preview renderer crashing due to invalid HTML

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#655]
## Description
This is a well-known bug with one or more of the following symptoms:
- The preview renderer shows only a blank blue area
- The version number is displayed as v0.00
- The brew cannot be edited or deleted from the edit page
- The brew becomes jumbled upon saving
![image](https://user-images.githubusercontent.com/5878534/38677815-59be0cb8-3e2d-11e8-96b0-57cd97133b62.png)

This is due to invalid HTML somewhere in the brew code (usually unclosed tags). A temporary fix is to copy the code into a new brew so you can edit it, find the typo, and save the new version.  The old broken version can then be deleted in your user profile page. Occasionally, the actual HTML in your document is fine, but the markdown parser inadvertently combines adjacent lines in the wrong order. Adding some blank lines between `<div>` tags and `#` headers or other elements usually solves the issue.

With v3 these issues should be mostly taken care of.

#637,

**Comment by ericscheid** [comment]
Issue of editor crashing due to invalid html in brew has been recently address.
