### ISSUE TITLE
Confusion on how to get the PDF

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#656]
## Description
While it seems obvious to most people, there are several users who are confused about how to get the PDF file, since it opens the print dialog rather than providing a PDF download directly. There may be a better way to handle this, as it is obvious not all users are familiar with the Print-to-PDF feature.

If you are having trouble with this issue, simply change your printer to something similar to "Print to PDF", and you will get a digital .pdf file rather than a paper printed copy.

Possible solutions:
- Add some instructions to the "home" page explaining how this works.
- Change the print page to a "PDF preview" page with a download button.
- Change the PDF print button to a direct download (although it is nice to see the PDF preview)

#598

**Comment by ericscheid** [comment]
Something to add to a FAQs page #810

**Comment by Gazook89** [comment]
Is this solved by the following instruction on the welcome page?

```

    PDF Exporting

    PDF Printing works best in Chrome. If you are having quality/consistency issues, try using Chrome to print instead.

    After clicking the "Print" item in the navbar a new page will open and a print dialog will pop-up.

        Set the Destination to "Save as PDF"
        Set Paper Size to "Letter"
        If you are printing on A4 paper, make sure to have the "A4 page size snippet" in your brew
        In Options make sure "Background Images" is selected.
        Hit print and enjoy! You're done!

    If you want to save ink or have a monochrome printer, add the Ink Friendly snippet to your brew before you print
```

Will let you close if so.   But my opinion is that direct downloads are bad-- I want to see the preview first.

**Comment by calculuschild** [comment]
@Gazook89 I agree, this is solved via the instructions.
