### ISSUE TITLE
Placing a <div> on the same line as a # header or directly below another <div> causes invalid HTML

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#657]
## Description
This is a specific instance of the invalid HTML bug which I think might have a better solution, since the code typed in the editor doesn't have anything visibly wrong. There is some conflict with Markdown and the generated HTML creating invalid tags such as:

`<h1><div>Hello</h1></div>`

This seems to happen when placing a `<div>` tag on a line with any Markdown tag such as a `#` header, or when placing sets of `<divs>` directly underneath each other.

#529

**Comment by ericscheid** [comment]
Closing because bug appears to have been fixed.

```
## Heading 2B
<div></div>
This brewcode now works and isn't getting mangled.

## heading here
<div class='foo'>
Everyone be foo fighting
</div>
```
