### ISSUE TITLE
A Magic Item Template

### ISSUE THREAD

**Issue by PurpleMagi** [naturalcrit/homebrewery#671]
## Description

This would be a useful template for any dungeon master that would want to create custom magic items. When I first started, I had to figure out how to format it on my own. I personally believe it would be a great help to everyone.

**Magic Item Template** : <details><summary>Click to expand</summary>

<pre><code>

#### Doorknob of Niceness
*Wondrous condiment, quite rare (requires attunement)*

This knob is pretty nice. It opens the door you put it on.

#### Longsword of Leering
*Weapon (toy sword), really common (requires attunement by a child)*

This sword makes you scowl at anyone you see. Completely harmless.

</code></pre></details>

**Comment by HeruAsatru** [comment]
Thank you for posting this. 

To be more inline with the DMG, where the first line of text is not indented, you would need to do a little more.

You can either add 2 spaces at the end of the italic line:
```
#### Doorknob of Niceness
*Wondrous condiment, quite rare (requires attunement)*  
This knob is pretty nice. It opens the door you put it on.
```

This is impossible to see and hard to figure out, so you might use the three underscores method:
```
#### Doorknob of Niceness
*Wondrous condiment, quite rare (requires attunement)*
___
This knob is pretty nice. It opens the door you put it on.
```

The most precise replication of the DMG requires a little html/css knowledge, but also looks the most authentic:
```
#### Doorknob of Niceness
*Wondrous condiment, quite rare (requires attunement)*
<div style='margin-top:-2px'></div>
This knob is pretty nice. It opens the door you put it on.
```

**Comment by calculuschild** [comment]
Yes, I think we can add this in as a snippet.

**Comment by chrisbrickhouse** [comment]
Pull request #842 implements this feature, though we may want to give some consideration to the formatting. I used the styling with the `<div>` tags and it looks a bit strange to me as there's a rather large gap between the item specs and description text, but maybe that's the look we're going for?

**Comment by HeruAsatru** [comment]
Check out the DMG's item descriptions. They, too, have a rather large gap between the item specs and description text.

**Comment by ericscheid** [comment]
Mentioning for snippet epic #1096
