### ISSUE TITLE
Problems saving

### ISSUE THREAD

**Issue by Burrchan** [naturalcrit/homebrewery#688]
## Things happen when i save

When i save my brew the right side of the brew disappears and im not sure how to stop this from happening

![screenshot_2](https://user-images.githubusercontent.com/39185735/39914884-ebf913ac-54cb-11e8-8550-5aede31a8072.png)

**Comment by calculuschild** [comment]
Issues like this resulting from invalid code in the editor should be fixed now with v2.10.3.
