### ISSUE TITLE
Increasing font across the document?

### ISSUE THREAD

**Issue by Minakie** [naturalcrit/homebrewery#689]
Hey guys.

It just so happens that the Homebrewery's default font size makes me and my friends have to squint. Increasing it to size 2 barely makes a difference so my mission is to have the font across all pages of my PDF be size 3. (source: https://homebrewery.naturalcrit.com/share/SkopYFbRf)

This could easily be achieved by individually adding the `<font size='3'></font>` to each page individually. However, it seems to be messing up the rest of my format coding. I tried adding it to my Prologue page and it ended up removing the capitular letter and all the inward paragraphs (aligning each paragraph to the left side instead of having the first line start a bit further ahead from the margin).

However, I remembered that I have pieces of coding that define the properties from all the Tables and Footers across the document. Similarly, is there any way to also have a unique piece of coding on the front page, to make the font size 3 across the entire document without having to post an individual line of coding for each page?

**Edit**: I managed to make the code work OK on most pages simply by trying to place the `<font size='3'></font>` code in different places on the page. However, it's still not working in some places (like page 5, where it's breaking the title codes and showing the #s instead) so my question still stands.

**Edit 2:** Actually, I just realized that, even in the Prologue page, the 2nd and last paragraphs are still being aligned to the left, even though I used the exact same coding for all paragraphs. Weird and annoying...

**Edit 3:** Ok, after messing with the coding for several hours (yay trial and error) I think I found a way to apply the font size code to each page individually without breaking the alignment of the paragraphs (it needs to be placed on a specific place and you can only open the code, but not close it). However, if anyone knows a way to simply code this in the front page, I'll be very grateful.

**Comment by calculuschild** [comment]
This issue seemed to have dropped off our radar. It looks like you mostly got it figured out, so I'm closing this for now.

If you have more issues with this, feel free to reopen the issue @Minakie .
