### ISSUE TITLE
Reconsider Docker support

### ISSUE THREAD

**Issue by dljsjr** [naturalcrit/homebrewery#692]
## Description

I was tracking through this project's history and noticed that there used to be rudimentary Docker support maintained by contributors but because of the labor behind it, it was removed.

Maintaining Docker support has become much, much simpler since 2016. I was able to make a fork and set up a full Docker service collection with data persistence, Dockerized MongoDB, and Dockerized Homebrewery in about 45 minutes. It's become a much easier thing to manage and it can really help with running Homebrewery locally, especially for people that are worried about how heavyweight things like MongoDB and NodeJS can be.

If this is a feature that you think would be useful I'd be more than happy to make a PR.

You can find the fork here: https://github.com/dljsjr/homebrewery

**Comment by calculuschild** [comment]
We now include Docker setup config files and steps in the documentation to get it running. See [README](https://github.com/naturalcrit/homebrewery/blob/master/README.md) and [README.DOCKER](https://github.com/naturalcrit/homebrewery/blob/master/README.DOCKER.md).
