### ISSUE TITLE
Preview of Share option not matching the Editor preview

### ISSUE THREAD

**Issue by Minakie** [naturalcrit/homebrewery#696]
I recently noticed that when I preview my latest PDF everything is out of place, even though it is looking just fine for me when I'm editing it. I would like to know if more people are having this issue and what I can do to solve it.

PDF: https://homebrewery.naturalcrit.com/share/BkRMlRTCf

**Comment by Joebing69** [comment]
I too just had this happen between yesterday morning and tonight. I looked at my brew that hasn't changed in over a year, to update it to MBoF, and everything is all over. Like yours, some things have jumped off the page to the right.

This is actually a product I have for sale on DMGuild, so not being able to update it to a revised version is killing me.

**Comment by Joebing69** [comment]
It looks like, at least for the column adjustment, the column break is bugged. I removed mine and things are falling back into place.

**Comment by Minakie** [comment]
I tried removing the column break and replacing it with a bunch of `<br>` instead, but it still made no difference. The preview of the PDF still doesn't match what I see when I'm editing the text.

**Comment by Minakie** [comment]
I have checked again and there seem to be 3 different versions of the same document: the one I see on the editor, another one on the preview and a different one if you try to get the PDF version to print the document.

Since I have no control over what the final version looks like, this makes it impossible for me to share my documents by uploading them to other websites so that people can download them and print them. I love the Homebrewery but if I can't find a way to fix it I'll just have to give up and use only Microsoft Word instead. :(

**Comment by ericscheid** [comment]
Over time various bugs are fixed and updates to underlying modules occur, and this can sometimes have knock-on effects.

Epic #1093 will likely help, in that old brews will get locked to a version of rendering code.

**Comment by ericscheid** [comment]
Closing for now, changes in brew rendering can be fixed by editing the brew (frustrating as that is).

**Comment by calculuschild** [comment]
BTW, this particular issue can be solved by replacing the set of `<br><br><br><br>` used to split the columns on pages 2 and 3 with an actual column-break entity:

<pre>
<code>
```
```
</code>
</pre>

Looks like the spacing of the <br> elements is slightly different between the edit page and the resulting pdf?
