### ISSUE TITLE
Login button isn't working

### ISSUE THREAD

**Issue by AmarisWilson** [naturalcrit/homebrewery#703]
When i go to log in and go to click on the log in button it is darkened and also has a do not enter sign on it. I also tried to make a new account and clicked sign up and it still wouldn't work for me.

**Comment by calculuschild** [comment]
Can you post a screenshot of this?

**Comment by HeruAsatru** [comment]
You have to enter username and password first, then the Login button is clickable.

**Comment by Gazook89** [comment]
Closing due to no response from user, cannot reproduce.  

@AmarisWilson, if this is somehow still an issue, we can re-open.
