### ISSUE TITLE
Log in issues, Password recovery, Log out issues

### ISSUE THREAD

**Issue by ValorsLady** [naturalcrit/homebrewery#710]
In order of issues:

- My log in credentials no longer work, even though I'm certain that they are correct.

- There is no button for password recovery, ostensibly because there is no contact information is required to have an account. This is frustrating, and a feature should be added so that ones documents are not lost.

- There is no button to Log Out, and so two users cannot share a single computer. This is frustrating because my husband and I both DM, and we play in the others campaigns and need to keep our home-brewed information separate.

**Comment by HENAWARTO** [comment]
I'm having the exact same issue as far as the first part.

**Comment by JakeKikin** [comment]
I had a lot of Home-brews but now i'm having the same problem with my login credentials no longer working

**Comment by thisgeek** [comment]
Workaround for logout: clear cookies for the naturalcrit.com domain and refresh the page.

There is also a logout link at the bottom of https://www.naturalcrit.com/login, though I haven't tested it. Note: At the time I wrote this comment, naturalcrit.com had an invalid SSL certificate. Your browser may report a privacy error when you visit naturalcrit.com.

Also note: Session management issues are actually issues with the "parent" webapp, stolksdorf/naturalcrit, not naturalcrit/homebrewery.

The developer [has said](https://github.com/naturalcrit/homebrewery/issues/412#issuecomment-306064475) that they will not be adding a recovery option.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @ValorsLady
