### ISSUE TITLE
Editor issues with touch screens

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#715]
When editing on iOS (iPad, Safari) and I press the shift-key, it behaves as if it is locked on (despite being displayed as a normal shift-enabled state - i.e. not solid up-arrow with underbar).

That is, if I press this sequence of keys: <kbd>shift</kbd><kbd>t</kbd><kbd>i</kbd><kbd>t</kbd><kbd>l</kbd><kbd>e</kbd> the editor will then contain `TITLE`, and not `Title`. 

Oh, the number of times I've written a title like `#HERE is THE magic OF the THING` (which is meant to be word-capped), or simply `HERE IS A SENTENCE WHERE I HAVE TYPED MUCH WORDS VERY CAPS BEFORE REALISING IS ALL CAPS ARGH `<kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd>.

As noted above, the shift key has the appearance of one-tap-enabled, but behaves as if caps-locked. (Well, technically shift-locked, as <kbd>Shift</kbd><kbd>,!</kbd> actually produces the `!`). If I had to guess, the page is consuming the keypress but not reflecting as having been typed, and thus the keyboard isn't releasing the shift-once state.

This behaviour does not happen on MacOS in Chrome.  
Does this happen on other mobile platforms?

I'd like to fix this behaviour as it is incredibly annoying, but I'm guessing it's more a case of react/javascript shenanigans than simply tweaking html5 `autocapitalization` attribute value.

**Comment by ericscheid** [comment]
Found mentions of this being an issue with React Native and causing issues with other projects.

**Comment by Gazook89** [comment]
@ericscheid I just tried this on iOS (iphone) Safari and Firefox and do not have the same issue.  Want to double check and see what happens now?

**Comment by calculuschild** [comment]
I know Codemirror has issues with mobile devices, specifically touch-interaction. Was this using touch or a separate keyboard? If touch, eventually when Codemirror 6 releases we can switch to that which solves a lot of the problems with touch screens.

**Comment by Gazook89** [comment]
All I'm hearing is @calculuschild enthusiastic support for responsibe, mobile friendly redesign

:)

**Comment by ericscheid** [comment]
Tested on iPad IOS 12.5.4 with touch keybord — still occurs.

**Comment by dbolack-ab** [comment]
Is this still occurring?

**Comment by calculuschild** [comment]
Fixing this requires upgrading to Codemirror 6.

**Comment by 5e-Cleric** [comment]
Rather, this is not our bug at all, this is a codemirror bug, we have nothing to fix, and we already have a codemirror 6 issue. #3511 . Closing this.
