### ISSUE TITLE
Cant access File

### ISSUE THREAD

**Issue by AhmadDM** [naturalcrit/homebrewery#718]
I have a homebrewery and one of my files doesnt appear. When i click on it its just a blue screen and says verson 0.00

**Comment by AlexeySachkov** [comment]
Looks like a well-known issues with invalid html syntax, see #655

**Comment by ericscheid** [comment]
This issue was recently addressed and the editor environment is now more tolerant.

@AhmadDM Please re-open if this is still an issue for you.
