### ISSUE TITLE
Problems with cache and saving

### ISSUE THREAD

**Issue by Rikart1397** [naturalcrit/homebrewery#727]
I usually use Google Chrome to create my files. 
I find no problems at all while creating and saving my homebrews, the problem comes the day after. When I start my pc and open Google Chrome, the homebrew I find open in my tabs is the one of yesterday BEFORE doing any edits to it. A quick refresh usually fixes the problem. 
Unluckly, today I forgot and lost around 12 pages of content. Is they any way to see a chronology of the edits or something like that?

**Comment by calculuschild** [comment]
This should be fixed now. Brews should always be loaded from the database now instead of cached.
