### ISSUE TITLE
work with "table of contents"

### ISSUE THREAD

**Issue by marcuswallace1991** [naturalcrit/homebrewery#730]
Hello .
I need to help to improve the index, or table of contents. Infact, when I click to do that, it opens on the right side of the page (cause it's very long) and I have strong difficultes to separate in 2 differents part, for the left and right part of the digital paper. 
And when i click to make a space or work with this, it seems impossible.
Can you help me ? 
Ty

**Comment by ericscheid** [comment]
The table of contents inserted by the Editor option is simply yet more markdown brew code.

You can edit that brew code like any other, as well as apply css styles to it.

It can be long and messy, but steady editing will get you there.

**Comment by ericscheid** [comment]
Nothing to do here. Closing.
