### ISSUE TITLE
Aligning Right / Horizontal Spaces

### ISSUE THREAD

**Issue by OctopusMacbeth** [naturalcrit/homebrewery#732]
## Aligning Right

With a large pyramid-shaped image in the bottom-center of my homebrew, I need the text in the bottom of my right column to either align right, or to step down and indent right with each successive line. Any advice on how to achieve this?

A code to insert horizontal breaks would serve the same function.

Danke schoen!

**Comment by athelu** [comment]
Is there  a way to +1 this? I am trying to put some images in the center and/or right column and having this exact issue. I have tried playing with column breaks and using css DIV to accomplish this but then lose the PHB style formatting.

**Comment by ericscheid** [comment]
This might be possible with some advanced CSS, specifically shape-outside and clip-path.

https://medium.com/@nicke920/wrapping-content-around-images-using-css-shapes-2fb17c8fde4e

**Comment by ericscheid** [comment]
As of today, `::nth-line()` is still not a thing in CSS, but there is some talk of it. Maybe in a few years =(

**Comment by ericscheid** [comment]
Would be nice to have a tutrial tips/techniques writeup. Pinging usual suspects.

**Comment by ericscheid** [comment]
See also #380 where `shape-outside: url('...')` seems to do the trick for simple images.
