### ISSUE TITLE
Not saving or updating when invalid tags used

### ISSUE THREAD

**Issue by thistlemilly** [naturalcrit/homebrewery#746]
I'm finding the document is not updating as i'm putting new information in and the auto save function is sitting on "saving..." without actually completing the action. http://homebrewery.naturalcrit.com/edit/rJ45QcAXrX

**Comment by misthero** [comment]
now it works, you have to be extra careful with opening and closing <div> tags

**Comment by calculuschild** [comment]
This is curious that the faulty tags could affect the saving system. We will keep this in mind as we work on keeping the site stable even when invalid code is entered.

**Comment by misthero** [comment]
> 
> 
> This is curious that the faulty tags could affect the saving system. We will keep this in mind as we work on keeping the site stable even when invalid code is entered.

not that much, the document is saved as an unique javascript string. Wrong characters can make the string unintelligible by the system and will give an internal javascript error while saving or loading it. that prevent the execution of the rest of the script.

**Comment by calculuschild** [comment]
Invalid code should not affect functioning of the site anymore as of v2.10.3!
