### ISSUE TITLE
Wide monster stat block error in pdf print

### ISSUE THREAD

**Issue by SzegaX** [naturalcrit/homebrewery#750]
## Description

The wide monster stat block block displays properly while editing, but when exporting to pdf (with the latest Chrome), the row describing creature type and the divider below it are shifted to the top of the second column.
I have two wide monster stat blocks in my document, on the same page. One of them displays this error, while the other does not.

**Share Link** : http://homebrewery.naturalcrit.com/share/SJZNxL_UdX

**Comment by KindredWolf78** [comment]
I'm having a similar issue with the wide monster block not rendering correctly when saved as PDF.
Page 3 of the document is all one single monster block.  The bottom end renders fine for web viewing, but saving as PDF causes the bottom to "drop out" off the end of the page.

https://homebrewery.naturalcrit.com/share/BkPuppetf

**Comment by Gazook89** [comment]
The share links are nice, but just in case they go away, here are some images to illustrate issue from SzegaX's brew. From Chrome on macOS:

## Print page, legacy:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/58999374/132924622-12df8345-3eb7-412b-ada4-967552fd5d99.png">

## Print Preview (Chrome printer), legacy
<img width="863" alt="image" src="https://user-images.githubusercontent.com/58999374/132924683-d5ef9886-79ce-4bb6-9f50-68448a918071.png">

_*note the thin red strip at top of second column_

## Print page, v3:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/58999374/132926699-d676bc1d-6d8b-44b2-8ad7-7f86ea650a1d.png">

## Print Preview (Chrome printer), v3
<img width="863" alt="image" src="https://user-images.githubusercontent.com/58999374/132926678-1512c7e0-5433-4112-b862-567792695363.png">

Note, the v3 version does not have a discrepancy between what is previewing and what is shown in print preview, but regardless I don't think it should split across columns?  I tried reducing some of the left column text by one sentence to get the `<hr>` entirely on the left and by using `\column` in a few spots, to see if it would split into the right column, and didn't see any issue.

-----

**So I think for legacy this may still be a rare problem.**

**For v3, I suggest adding `break-inside:avoid;` to `.monster hr`** if you want to prevent it from splitting across columns.

**Comment by calculuschild** [comment]
@Gazook89 Do you still have brews for these? I don't see this issue anymore in the original posted link.

**Comment by calculuschild** [comment]
It's been a long time since I have been able to reproduce this issue. I'm assuming Chrome has since fixed something on their end.
