### ISSUE TITLE
Some weird spaces after exporting PDF. Also never ending save process.

### ISSUE THREAD

**Issue by RainGray** [naturalcrit/homebrewery#753]
The pages look fine while I'm working. But after export to PDF there are strange shifts and huge gaps.
Also, the save icon always rotates in place and does not actually save the file.
I tried to copy the code into a new document, but every time it's the same trouble.
When you copy old code to a new document, there are also breaks in the page, but they disappear after a couple of deleted blank lines between blocks of code.

While im working:
[http://images.vfl.ru/ii/1536845324/452b602b/23319602.png
](http://images.vfl.ru/ii/1536845324/452b602b/23319602.png)

After export:
[http://images.vfl.ru/ii/1536845376/2ba595a9/23319606.png
](http://images.vfl.ru/ii/1536845376/2ba595a9/23319606.png)

My brew:
http://homebrewery.naturalcrit.com/share/By-SEkkOO7

**Comment by calculuschild** [comment]
At first glance it looks like you might be printing to the wrong document page size (A4 vs US Letter).

Also, I removed your "edit" link since that would let anyone see and delete your brew if they click on it.

**Comment by calculuschild** [comment]
It's been years with no followup from the user. Closing.
