### ISSUE TITLE
[FEATURE]: Add folders/tags to organize brews...

### ISSUE THREAD

**Issue by ctgilley** [naturalcrit/homebrewery#758]
## Description

I've got a lot of brews, and I imagine others do as well.  It would be great to be able to organize these into folders that I can drill into for specific brews.  For example, I might want to have one folder for each campaign that I'm running, or one to hold my custom magic items, or another to hold my custom races and classes.

**Comment by ericscheid** [comment]
I would suggest tags instead of folders.

**Comment by ctgilley** [comment]
Sure, tags would be fine -- any way to structure/filter/organize.

**Comment by jeddai** [comment]
Discussion from #697:
> > Side note: the homebrew data model and UI does include a "tags" field, but it is commented out and undeveloped.
> > There is interest in tags for organising reasons too. #758
>
> I was just thinking about that; I have about a dozen brews that I made to help out someone in the subreddit; I've taken to giving them a title that starts with "Example:" so that they appear in one place in the list, but it'd be even better if I could dump them in an "Examples" folder where I don't actually have to look at them.

@G-Ambatte what if we handled the document filtering via tags, but also addressed the visibility concern by making the user page a dashboard of sorts? 
1. Set up documents to allow for tags, 
2. Add a section to the user page that allows users to filter their documents based on the tags they have on their documents.
    * This would contain a unique list of all the tags present on a user's documents
3. When you click a tag, it filters the user's documents so only documents with that tag are showing
4. When you change which tags/sort method are being used, that gets stored in local storage
5. When you visit that page, it defaults to whatever is in local storage

**Comment by jeddai** [comment]
Smart folders would be easily doable using the tag system, thanks to NASA from the Discord of Many Things for this idea.

**Comment by ericscheid** [comment]
A question on "folders" (aka views) .. would authors want a folder where some of the brews are for everyone to view, and other brews only for the author to view (e.g. DM only, vs all players). And of these player-viewable brews, can some of them not be marked as "Published" (i.e. discoverable via the homebrewery public content search facilities).

I would want to a) create a container for a purpose (e.g. Friday Game Group), b) toss in all the relevant brews, c) mark some as me-only brews, d) have a link I can send to all my players. And maybe have sub-folders there too.

This can _kinda_ be done via tags, there are definite overlaps. But also not. Food for thought.

**Comment by ericscheid** [comment]
> Smart folders would be easily doable using the tag system, thanks to NASA from the Discord of Many Things for this idea.

See also #1858

**Comment by calculuschild** [comment]
Tags are now able to be added to brews! Still need to make the searchable on the My Brews page but that should be trivial.

**Comment by ericscheid** [comment]
Free text searching undifferentiated from title/description would be trivial, just add an extra test here (noting yes, would be a search of an array of strings, not just a string — don't simply `array.join() though, as you'd get false matches).

https://github.com/naturalcrit/homebrewery/blob/0811da79c45853d4ba98655617bee08b0950d666/client/homebrew/pages/basePages/listPage/listPage.jsx#L145-L148

Next step would be a search syntax like `tag:tag-keyword1 words to find in description/title tag:tag-keyword2`. The syntax would be slightly complicated by the fact that spaces are allowed in tags.

**Comment by G-Ambatte** [comment]
I've added this issue to the current UserPage modifications checklist (#2295) - expanding filtering to the tags was already in the list, but not linked to any specific issue.

I was anticipating adding it to the filter in exactly the same way we did the Brew Titles and Descriptions, but now that it's a larger list, some slight refactoring might be necessary to keep things elegant.

**Comment by ericscheid** [comment]
Maybe this, but with better names.

````javascript
	getSortedBrews : function(brews){
		const testString = _.deburr(this.state.filterString).toLowerCase();
		const searchTestString = (string) => _.deburr(string).toLowerCase().includes(testString);
		brews = _.filter(brews, (brew)=>{
			return searchTestString(brew.title) || 
				searchTestString(brew.description) || 
				brew.tags.findIndex(tag => searchTestString(tag));
		});
	},
````
----

NOTE: we should likely raise a separate issue for #758, as tags ≠ folders, and repoint #2295.

> - [ ] expand filter to include tags (https://github.com/naturalcrit/homebrewery/issues/758)

**Comment by G-Ambatte** [comment]
> When you click a tag, it filters the user's documents so only documents with that tag are showing

Reading back through the history on this, we never actually created this functionality. I believe we can probably do so by making the tags automatically link to the current URL with a `?filter=${URL.encode(tag content)}`.

**Comment by ericscheid** [comment]
The name of this issue started being about folders, but quickly morphed to being about tags, and much very good work was done on the tags front, with an end result of being able to filter the user-brews by tags (by clicking them there).

Discussion in multiple places show that folders is still an important and useful concept, and one which cannot be entirely solved via tags. A lot of the discussion has been collated onto a [wiki page](https://github.com/naturalcrit/homebrewery/wiki/Folders-etc).

For clarity,, creating a new issue for the original issue (rebooting it essentially).

**Comment by ericscheid** [comment]
With that new issue to handle actual folders, closing this issue (using tags) as completed.
