### ISSUE TITLE
Brew Names/Labels Too Small

### ISSUE THREAD

**Issue by Cobbke01** [naturalcrit/homebrewery#760]
## Description
I am both reporting a feature issue, and requesting a feature.

The issue I am reporting is the fact that when a Brew is made without a name, it becomes really inconvenient to click the edit button, and impossible to actually click the delete button.  This is resolvable by editing the HTML and forcefully putting in a title. However, this is temporary and only lasts as long as nothing is refreshed. 

If I may make a suggestion, a  few possible fixes are:
Set a random Title to an empty title
Set a permanent vertical size.
Set a vertical size that has a minimum and changes depending on Title
Create a button that allows the changing of the name, in a location that is accessible if there is no name.

Though I don't know how hard or easy these changes may be, I do think that it is a required issue that needs to be fixed.
If i missed another issue that covered this, sorry.

**Attached Images** : <details><summary>Click to expand</summary><code><pre>

![example1 2](https://user-images.githubusercontent.com/31631182/45853951-07a13f80-bd0e-11e8-852c-5fa9e34bd59a.png)
![example2 2](https://user-images.githubusercontent.com/31631182/45853952-0a9c3000-bd0e-11e8-94c3-ac93e55a216b.png)
![example3 2](https://user-images.githubusercontent.com/31631182/45853954-0f60e400-bd0e-11e8-8dc3-ae38db54fa53.png)
![example4 2](https://user-images.githubusercontent.com/31631182/45853959-125bd480-bd0e-11e8-83df-2e200452cd25.png)
![example5 2](https://user-images.githubusercontent.com/31631182/45853962-14be2e80-bd0e-11e8-9b10-176f1385717e.png)

</pre></code></details>

**Comment by calculuschild** [comment]
This has now been fixed!
