### ISSUE TITLE
Cannot Create a new document without the webpage crashing

### ISSUE THREAD

**Issue by Dovakinian** [naturalcrit/homebrewery#762]
When I attempt to make a new document with the "Create your own button" it crashes the website. I have tried it on multiple computers and with not signing in and being signed in.

**Comment by ericscheid** [comment]
What happens when you go to http://homebrewery.naturalcrit.com/new ?

**Comment by calculuschild** [comment]
Closing for now because of no further response from the user, and the issue does not have enough information to fix.

Feel free to reopen this issue if this is still a problem for you and you can provide more information, @Dovakinian
