### ISSUE TITLE
Cut the code in hopes of pasting into word to spell check, now i've lost everything.

### ISSUE THREAD

**Issue by Us3rN0tF0und** [naturalcrit/homebrewery#770]
I cut all of my content in a specific brew in hope of pasting it into word so that i could spell check everything, due to the nature of homebrewery it saved immediately after. I tried pasting the content into word but it didn't paste, so i went to paste it back into the codeing section of the cite but it still didn't paste. Now i've lost everything, is there a way to get it back to the way it was before it cut all the content??? i worked really hard on it. 

The user name for my account is __User_Not_Found__ and it was my "Hot Springs Island Beastiary" brew. Please help, I am begging you.

**Comment by Falconloft** [comment]
It's far too late for this now, but always copy, not cut.

However, even if you cut it all and it saves to a blank slate, you can still undo your last action using ctrl+z, and it will all be back. Just don't close your brew until you're sure you're good.
