### ISSUE TITLE
Create boxes for Titles of the Chapters. How? 

### ISSUE THREAD

**Issue by marcuswallace1991** [naturalcrit/homebrewery#781]
Hello. 
I'd like create Boxes for Titles of the chapters. 
1 Example: https://scontent-atl3-1.cdninstagram.com/vp/7aec2d446abd07f47156e73bae9a4ef4/5C564427/t51.2885-15/e35/41543022_481576215675930_3881813429846212507_n.jpg (The box: Episodio 1: Greenest burn"). 
And I like create a box for Section, as in player book or DM book etc (Part 1).
Is there a way to do this? 
Ty to all for the help, you are very pretty!

**Comment by DreadBoy** [comment]
Markdown supports any HTML so it's easy to create what you want with a little bit of HTML tags and custom CSS.

**Comment by marcuswallace1991** [comment]
I don't know HTML and CSS, so I ask for this reason =)

**Comment by marcuswallace1991** [comment]
Almost create a lane or a simple table?

**Comment by KingGorillaKong** [comment]
I was having a bit of a similar issue. Managed to get an image in and get the code to work to properly display content beneath the absolute positioned image.

The screenshot here shows the preview and code page, I hope that this helps you out @marcuswallace1991 
https://imgur.com/8grkHE1

**Comment by calculuschild** [comment]
We will keep this in mind. I think this could easily be added as a built-in snippet.

**Comment by Gazook89** [comment]
I would like to include this (or the spirit of it) in a rollout of pre-made "Page Layouts".   Basic page formats such as 'half image half text', 'cover page', 'credits page', etc.  Ideally after the implementation of #1489, if that ever comes to fruition.

As-is, though, the original request 4 years ago has been answered 3 years ago, and has been made easier by the new v3.

**Comment by calculuschild** [comment]
@Gazook89 Sounds like a good idea for some new snippets. #1489 will still probably take a while though. If you want to create a new issue specifically for implementing those snippets then we can close this out.

**Comment by Gazook89** [comment]
Added in #1673, closing this.
