### ISSUE TITLE
Is there a way to get privacy in my homebrewer?

### ISSUE THREAD

**Issue by marcuswallace1991** [naturalcrit/homebrewery#782]
Hi, 
I see that in my pdf I can click and other people can see my original Homebrewer. Is there a way to have a privacy or secret profile, to avoid this? Or I must delete all my job, after I finish it? 
I want to sell my job on DMSGuilde, so it's a problem for me

**Comment by HeruAsatru** [comment]
What exactly do you mean by "I see that in my pdf I can click and other people can see my original Homebrewer."? What do you click? What's the link that opens up?

**Comment by Marcobertini6** [comment]
If i click in the bottom of the page there is a link that open my Homebrew in the naturalcritic syte. I don't know the reason because I don't put any types of links in document. I find a solution saving 2 or more times or deleting my original work

**Comment by calculuschild** [comment]
Closing for now because of no further response from the user, and the issue does not have enough information to fix.

Feel free to reopen this issue if this is still a problem for you and you can provide more information, @marcuswallace1991, @Marcobertini6
