### ISSUE TITLE
Not Secure

### ISSUE THREAD

**Issue by PSDNDFUN** [naturalcrit/homebrewery#784]
It might be something small but I noticed when I update one of my homebrews it goes from saying not secure to giving me an exclamation mark in a red triangle.  Probably nothing but it freaks me out to see a red warning sign.

**Comment by AlexeySachkov** [comment]
If I understand correctly, it happens because homebrewery doesn't use https.

The issue were already reported in #516, but looks like it is much more critical right now. AFAIK, Chrome is going to completely block non-https sites in feature releases

**Comment by PSDNDFUN** [comment]
Wow levirosol.  Thanks for the response.  I guess I owe the founder more money on patreon because I said I would give him more if it was secure.  Thank you for dissuading my fears a little bit.

**Comment by AlexeySachkov** [comment]
@PSDNDFUN, it would be really nice if you could contact @stolksdorf.

We are trying, but failed so far. There are some people (@calculuschild, @Rae2che5) who have enough permissions to commit to the repository, fix bugs and accept pull requests with new features, but no one except @stolksdorf can update the actual site.

**Comment by PSDNDFUN** [comment]
AlexeySachkov.  I have been unable to get a response.  So far I'm just donating to the patreon.  I was hoping to get a response but unfortunately that hasn't been happening so far.

**Comment by LeviRosol** [comment]
There are alternatives to HB you might consider as well. The folks @ /r/unearthedarcana have put together a pretty good list:

https://www.reddit.com/r/UnearthedArcana/wiki/resources

**Comment by AlexeySachkov** [comment]
Hi, @PSDNDFUN 

Glad to inform you: the server is actually configured to work with SSL & HTTPS, so you just need to change the `http` to `https` in the homebrewery address. There is a PR #815 which brings automatic redirects to a `https` version

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
