### ISSUE TITLE
problem with press not solved

### ISSUE THREAD

**Issue by Marcobertini6** [naturalcrit/homebrewery#804]
Hi, I try to insert the code you said to me, but it doesn't solve any problems. 

Photos of new press:

![problema](https://user-images.githubusercontent.com/44923954/48315599-96c52800-e5d8-11e8-96e5-8d273f6f1a32.jpg)--> PDF 
![prolema2](https://user-images.githubusercontent.com/44923954/48315604-a17fbd00-e5d8-11e8-852a-95061068afc8.jpg) --> PRESS

Can you help me?

**Comment by Marcobertini6** [comment]
I solve the problem of white edges, with an option in the press (avoid edges), but there is a small edge white in the bottom of the page that it's very bad. Can someone help me to avoid this?

**Comment by calculuschild** [comment]
Have you tried printing to a PDF file? Does the PDF also have a white space at the bottom?

How big is the space left at the bottom?

**Comment by Marcobertini6** [comment]
I tried, no the printing is ok! Finally! I'm happy, ty very much for the help! Finally, after a lot of times, hours, months behind this project (I started to the story of my campaign 1 year ago!!!!!!!!!) will be end!!!!!!!! Great!
The only little problem remains in the pdf document, there is that little white space that you can see in the first picture with black background

**Comment by calculuschild** [comment]
Try adjusting the `height` value in the page size snippet. A value of 297mm might be more accurate (which we need to change in the code). See if that's enough to get rid of the small white space.

**Comment by marcuswallace1991** [comment]
I solved problem if press normally, but if I press Both/sides I have the problem of white space in edges... Can you help me?

**Comment by marcuswallace1991** [comment]
Sorry for other post that I opened, you can close.
