### ISSUE TITLE
[Feature] External storage for brews

### ISSUE THREAD

**Issue by AlexeySachkov** [naturalcrit/homebrewery#808]
Currently brews are stored in mongodb on server, but it is always better to have a backup. So, the proposal is to add support of external storage for brews like GitHub Gists, Google Drive, browser Local Storage, Dropbox, etc.

There are few related issues: #346, #196, #162

**Comment by ericscheid** [comment]
Also useful would be a one-click download-text-file button.

**Comment by hypergig** [comment]
I will easily pay $100 for this feature

**Comment by calculuschild** [comment]
Google Drive storage is now supported as of v2.10.0!  Other storage may come later, but closing this issue for now.
