### ISSUE TITLE
Problem with press 

### ISSUE THREAD

**Issue by marcuswallace1991** [naturalcrit/homebrewery#813]
Hello, 
I tried to print my Homebrew but it didn't work. 
You can see the option with edge and without edge. In first case I have a bad not symmetric white edge. In second case I have a little part cut by print.... So someone can help me? I'd like to print my Homebrewery with my print but now it's impossible. 
Ty 
1 Both sides with no edges (pdf option)
![47108115_298288824226654_3728386179658153984_n](https://user-images.githubusercontent.com/42306281/49110700-7959b480-f28e-11e8-8315-9f2724cb64a2.jpg)
2 Both sides with no edges (pdf option)
![46876908_515318355634880_7414150834742624256_n](https://user-images.githubusercontent.com/42306281/49110703-7a8ae180-f28e-11e8-850d-93553a5ad382.jpg)
1 side with edges (white)
![46902132_257986714896105_2553630293974056960_n](https://user-images.githubusercontent.com/42306281/49110704-7bbc0e80-f28e-11e8-97fc-e4f1a79b5610.jpg)

**Comment by ericscheid** [comment]
What make & model is your printer?

**Comment by marcuswallace1991** [comment]
HP Envy 4520

**Comment by marcuswallace1991** [comment]
I need go 2 side because the work it's born for this reason. I hope my print  is the problem, but I have some difficultes to avoid white edges or not cut the edges... the problem is to have a good and accurate press..

**Comment by calculuschild** [comment]
1) If you create a PDF file does the file have white edges?

2) Are you able to print without edges on other documents?

3) Can you print one-side all of the odd pages, then flip the paper over and print 1-sided the even pages?

**Comment by marcuswallace1991** [comment]
Ok. I tried the problem is not 2 or 1 sides. The fact is that withouht no edges (in print option) there's a piece of test that is cut. Instead with normal press, there are white edges... I have no idea how solve this :S

**Comment by calculuschild** [comment]
Looking back at your other opened issues, did you ever do:

> Try adjusting the height value in the page size snippet. A value of 297mm might be more accurate (which we need to change in the code). See if that's enough to get rid of the small white space.

You can try an even higher number until the white space is gone.

**Comment by marcuswallace1991** [comment]
Ok, I try today to do this!

**Comment by calculuschild** [comment]
Closing because this appears to be solved.
