### ISSUE TITLE
Login not working (cookies expired)

### ISSUE THREAD

**Issue by calculuschild** [naturalcrit/homebrewery#819]
The NaturalCrit site has a hardcoded date to expire cookies, set to December 18, 2018. This has prevented anyone from logging in since this morning.

The issue is on the NaturalCrit repository, so only @stolksdorf has access to edit the code.

Please be patient with us until the problem is corrected. Thanks!

**Comment by stolksdorf** [comment]
Just pushed out the fixed for this. Apologize for the delay.
