### ISSUE TITLE
Dropdown button for thumbnail script.

### ISSUE THREAD

**Issue by resonant-gamedesign** [naturalcrit/homebrewery#820]
I noticed that many users don't know how to set the thumbnail in their brews. Perhaps this can be one of the options in the dropdown menus?

`<meta property="og:image" content="LINKTOIMAGE" />`

**Comment by ericscheid** [comment]
Where does this thumbnail appear?

**Comment by sonaplayer** [comment]
Reddit.

**Comment by calculuschild** [comment]
Repopening since we had to revert #1777
