### ISSUE TITLE
Login does not redirect to the Homebrewery

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#821]
As the title says, when using the Login button in the homebrewery and logging in, it does not redirect the user to the homebrewery. This should be fixed.

**Comment by 5e-Cleric** [comment]
Update, this PR https://github.com/naturalcrit/naturalcrit/pull/36 will fix this

**Comment by dbolack-ab** [comment]
Was this released?

**Comment by calculuschild** [comment]
Merged but not released live yet.

**Comment by dbolack-ab** [comment]
This is now live. Closing.
