### ISSUE TITLE
[Suggestion]Make Partial Brew Renderer Notification Collapsible/Closable

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#822]
The notification that informs you when the Partial Brew Renderer is active, gets in the way sometimes. You could make it so that the message can be collapsed or closed alltogether. 

More information on this suggestion can be found here: [REDDIT](https://old.reddit.com/r/homebrewery/comments/a7ugb7/disable_this/)

**Comment by ericscheid** [comment]
The preview pane does not refresh with any changes unless the html error is resolved, so hiding it won't be particularly helpful.

The most you can do is sit there and stare at the preview. Maybe take a picture.

Closing as not a huge issue and seems counterproductive.
