### ISSUE TITLE
No Scroll bar on the "My Brews" page

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#832]
As per the title, the "My Brews" page (the one where you see your unpublished/published brews), doesn't have a scrollbar on the site (anymore?). Brews that don't fit on the page can only be accessed by zooming out.

**Comment by calculuschild** [comment]
I just pushed a fix for this. Can you verify?

**Comment by HeruAsatru** [comment]
Yup, is fixed. Thanks.
