### ISSUE TITLE
This site can't provide a secure connection

### ISSUE THREAD

**Issue by dolfijn3000** [naturalcrit/homebrewery#835]
i try to run the local version of the homebrewey but when i try to connect to localhost i get this 

This site can't provide a secure connection

ERR_SSL_PROTOCOL_ERROR

How to fix this ?

**Comment by AlexeySachkov** [comment]
Hi @dolfijn3000,

As you can see in https://github.com/naturalcrit/homebrewery/commit/21b83ead882eb8a0f87007c769ab86b04b0cd4bb, all routes are not automatically redirected to https

To fix this error, just comment or remove the following line of code in `server.js`
```js
app.use(require('./server/forcessl.mw.js'));
``` 

Join our [gitter chat](https://gitter.im/naturalcrit/Lobby) - I think you will get answers for technical questions faster in chat than on github

**Comment by calculuschild** [comment]
Question answered. Closing this.

**Comment by datdamnzotz** [comment]
Another answer is to set an environment variable to:
NODE_ENV: local
