### ISSUE TITLE
Some capital letters disappear when printing to PDF

### ISSUE THREAD

**Issue by AlexeySachkov** [naturalcrit/homebrewery#837]
Reported on reddit: [HERE](https://www.reddit.com/r/homebrewery/comments/altw3c/issue_when_attempting_to_save_as_pdf_capital)

Brew example: https://homebrewery.naturalcrit.com/share/BkHW5PWY74

When I'm trying to print it to PDF using Chrome and Foxit Reader PDF Printer I see the following:

![image](https://user-images.githubusercontent.com/6417047/52162195-3dedc300-26e1-11e9-8127-2b98fd1aa6d2.png)

While the original brew looks like:

![image](https://user-images.githubusercontent.com/6417047/52162203-4f36cf80-26e1-11e9-98aa-4d11c32f5c89.png)

**Comment by HeruAsatru** [comment]
This is a Google Chrome issue. I didn't have this problem yesterday (Version 71.0.3578.98 (Official Build) (64-bit)) and just updated my chrome (Version 72.0.3626.81 (Official Build) (64-bit)) and now I have it too.

**Comment by NathanMainwaring** [comment]
I have this issue too. Is it affecting all users or just some?

Is there any work around for this? I've spent months creating a large brew and I'd be gutted to see it go to waste.

**Comment by RKuerten** [comment]
@NathanMainwaring You can download Chromium version 71 and life goes on. Your brew isn't going to be wasted really, it is a browser problem. Homebrewery is fine on version 71 and below.

**Comment by calculuschild** [comment]
Just updated my Chrome here. So weird... It only happens on particular letters and custom fonts it looks like.

The issue also exists on GMBinder, so it's definitely not just us.

Someone else reported this on [Chrome's bug reporting](https://bugs.chromium.org/p/chromium/issues/detail?id=928718&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=).

**Comment by NathanMainwaring** [comment]
Does anyone have a safe link for downloading Chrome v71?

**Comment by calculuschild** [comment]
According to the report [here](https://bugs.chromium.org/p/chromium/issues/detail?id=926885), the fix has already been applied to Chrome Canary which you can download. It sounds like they are planning to apply this fix to Chrome soon as well.

**Comment by HeruAsatru** [comment]
This issue seems to be fixed? Can't find any vanishing letters on Version 72.0.3626.121 (Official Build) (64-bit) of chrome...

**Comment by calculuschild** [comment]
Yep. This is fixed.
