### ISSUE TITLE
Deleting a brew should only remove you as an editor, and only delete the brew when you are the last editor

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#838]
![image](https://user-images.githubusercontent.com/10881828/52403146-56d1ec00-2ac6-11e9-8573-a2733be0ecf1.png)

**Comment by HeruAsatru** [comment]
Will be fixed with this: https://github.com/naturalcrit/homebrewery/pull/839

**Comment by calculuschild** [comment]
All fixed!
