### ISSUE TITLE
Remove "Report Issue" button from Share view

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#840]
The "Report Issue" button should be removed from the Share view of brews, so that Issues like [THIS ONE](https://old.reddit.com/r/homebrewery/comments/aynmoo/shaman_class_page_text_overlapping_leveling_table/) (and many others like it) can be prevented in the future.

Reporting an issue is only really useful for creators anyway, so we don't need to have it in Share view.

**Comment by calculuschild** [comment]
Hahahaha. Those are always funny.

You propose an interesting solution though. Makes sense. I will take a look at fixing that.

**Comment by calculuschild** [comment]
Done and done.
