### ISSUE TITLE
Feature request: page indicator for the source pane

### ISSUE THREAD

**Issue by ericscheid** [naturalcrit/homebrewery#846]
When the author has a large document, they can scroll the preview pane and there is displayed a page indicator widget in the bottom left:

    <div class="pageInfo">7 / 13</div>

However, over on the left side the source pane has no equivalent indicator. Further, since that pane only displays an extract of the actual source, an author can't use in-browser-find to locate particular a section of content. They have to scroll and scan, scroll and scan.

It would be useful to see an indicator of which page the source will get rendered to. Possibly as a widget in the same style, or maybe even insert the information in a `<span style="float:right;"> 7 / 13</span>` just after the `<span role="presentation" style="padding-right: 0.1px;">\page</span>`

**Comment by HeruAsatru** [comment]
Maybe it would be useful to be able to click on certain elements (like headers, or bold/italic text, or...) of the brew (in the render view) and jump directly to that position in the source code?

**Comment by Gazook89** [comment]
PR #1586 would add page numbers to the source pane

**Comment by calculuschild** [comment]
Handled in a slightly different way in #1586 , which adds a page number onto the end of each `\page`
