### ISSUE TITLE
Feature Request: Smart quotes option

### ISSUE THREAD

**Issue by sjml** [naturalcrit/homebrewery#849]
Would it be possible to use the marked library's smartypants option so that quotes and dashes get rendered into a more pleasing typography?

**Comment by ericscheid** [comment]
https://marked.js.org/using_advanced#options

This sounds simple. I can't imagine what could possibly go wrong. #tweak

Worst case, we uncover a bug in _markedjs_ that they would care about to fix and we can disable in the interim.

**Comment by calculuschild** [comment]
This is now functioning in the v3 renderer on commit https://github.com/naturalcrit/homebrewery/commit/8bd09e58cb41be7f2e3468ac67b9fea9981395f0

I'm hesitant to apply it to Legacy since any slight change in spacing as a result is bound to ruin somebody's brews.

**Comment by calculuschild** [comment]
Added to the V3 changelog finally. Closing.
