### ISSUE TITLE
Current master doesn't allow client connections with npm start

### ISSUE THREAD

**Issue by rgejji** [naturalcrit/homebrewery#851]
Ran instructions all the way through in an ubuntu and a windows 10 environment. npm start would work fine. But neither environment would connect to the server for either chrome or firefox. Changing the connection port also didn't help, nor would turning off firewalls or antivirus.

The browsers would report connection interrupted and connection refused errors like "ERR_SSL_PROTOCOL_ERROR" or "SSL_ERROR_RX_RECORD_TOO_LONG"

Reverting back to the last tagged release was the easiest way to fix these problems.

**Comment by rgejji** [comment]
This is most likely related to the forced forwarding to https. However, there is currently no way to bypass this forced forwarding nor clear instructions on how to get https to work for new forks.

**Comment by calculuschild** [comment]
See [this issue](https://github.com/naturalcrit/homebrewery/issues/835) for disabling the forced SSL. I will update the readme page with this instruction for future users!
