### ISSUE TITLE
Can Not view other's shared work in chrome

### ISSUE THREAD

**Issue by yourmemehell** [naturalcrit/homebrewery#856]

**Comment by calculuschild** [comment]
Hi! Can you provide more details? What happens when you try to view another shared work. Do you have the link to it so we can test on our end?

**Comment by yourmemehell** [comment]
Any link I open that is shared work comes up with a blank page. I've tried with multiple links and allowing flash on chrome, but it shows up as a blank page on chrome for my laptop.

**Comment by calculuschild** [comment]
Flash isn't used so that shouldn't make a difference. Can you provide a specific link here so I can check it?

**Comment by calculuschild** [comment]
Can you provide any more info on this? We'd like to help, but there's not enough information to go on here.

**Comment by calculuschild** [comment]
Closing for now because of no further response from the user, and the issue does not have enough information to fix.

Feel free to reopen this issue if this is still a problem for you and you can provide more information, @yourmemehell
