### ISSUE TITLE
Problem with monster stats wide block

### ISSUE THREAD

**Issue by marcuswallace1991** [naturalcrit/homebrewery#858]
Hello,
I have the problem with stats monster when I create PDF, I attach the photo.
The alignment ends in the right column, I have no idea why. Can anyone help me?
![versione di prova lich (1)_page-0025](https://user-images.githubusercontent.com/42306281/68091230-66c40400-fe7d-11e9-8c64-f8127d055f11.jpg)

**Comment by marcuswallace1991** [comment]
That's the code

___
___
> ## Lich Initiate
>   *Medium humanoid, chaotic evil*
> ___
> - **Armor Class** 15 (natural armor)
> - **Hit Points** 68 (9d8 + 27)
> - **Speed** 30 ft.
>___
>|STR|DEX|CON|INT|WIS|CHA|
>|:---:|:---:|:---:|:---:|:---:|:---:|
>|10 (0)|13 (+1)|16 (+3)17 (+3)|14 (+2)|12 (+1)|
>___
> - **Skills Arcana** +5, History +5, Religion +5
> - **Saving Throws** Con +5, Int +5
> - **Damage Resistances** cold, necrotic
> - **Senses** passive Perception 12
> - **Languages** Abyssal, Common, Infernal
> - **Challenge** CR 5 (1,800 XP)
> ___
> ***Fanatic Advantage.*** Once per turn, if the lich initiate can see its lich master, it makes a spell attack with advantage on the attack roll. On a successful hit, the target takes an extra 10 (3d6) damage of the same type damage of that spell.
>
> ***Lich Fanatic.*** The lich initiate has advantage on saving throws against being charmed or frightened. 
>
> ***Spellcasting.*** The lich initiate is a 7th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 14, +6  to hit with spell attacks). It has the following wizard spells prepared:   
> Cantrips (at will): *chill touch,* ***frostbite,***  *ray of frost,* ***toll the dead***    
1st level (4 slots): *cause fear, chromatic orb, magic missile, shield*    
2nd level (3 slots): *blindness,* ***mind spike,*** *ray of sickness*     
3rd level (3 slots): *counterspell, fireball*    
4th level (1 slot): *blight*    
***from Xanathar’s Guide to Everything***
>
> ### Actions
> ***Grave Bolt.*** *Ranged Spell Attack:* +5 to hit, range 120 ft., one creature. *Hit:* 9 (1d8+5) necrotic damage. 
>
> ***Decay Burst (Recharges 5-6).*** As a bonus action, a burst of black energy radiates from the lich initiate in a 15-foot-radius centered on it. Any creature that isn’t an undead or construct must make a DC 14 Constitution saving throw. On a failed save, the affected creature is vulnerable to necrotic damage until the start of its next turn.

**Comment by calculuschild** [comment]
Hi there. This is an issue with a recent Chrome update. I submitted the bug report to them a while back and it should be fixed now, so make sure you have the latest version of Chrome installed. If it's still not working, you can try the workaround located on Reddit [here](https://www.reddit.com/r/homebrewery/comments/d6rbhw/psa_wide_monster_stat_block_broken/).

**Comment by marcuswallace1991** [comment]
it's solved, ty!

**Comment by ericscheid** [comment]
Issue solved by Chrome bump, confirmed by OP.
