### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by csylos** [naturalcrit/homebrewery#861]
## Description

Getting a message saying that there's an "application error" and that the logs need to be checked.

Here is the error I'm receiving:

 Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by 3v3rl0st** [comment]
i'm getting the same error. started 1/4/20 around 1pm cst
![app error](https://user-images.githubusercontent.com/26887487/71775699-fbfd7a80-2f4a-11ea-82b9-3ede26d01604.PNG)

**Comment by calculuschild** [comment]
Yup, we had an auto-updater mistakenly upgrade some dependencies and I didn't catch it in time. Those issues have been reverted.
