### ISSUE TITLE
colour of tables

### ISSUE THREAD

**Issue by Marcobertini6** [naturalcrit/homebrewery#865]
hi, I have a problem with the colors of the table. I have used this code, but it colors all the tables, including those of the monsters, resulting in a bad result (I attached photos). 
Can you help me make sure that only the normal tables are colored and not those of the monsters?

Code: 

<style>

/* Background */
  .phb{ background-image: url('https://gmbinder.com/images/KN1O92T.png') }
  .phb{ background-size: cover }

/* Notes */
  .phb section blockquote {background-color: #f6e5d4}
  .phb hr + section blockquote tr:nth-child(odd) td {background-color: transparent;}

/* Tables */
  table tr:nth-child(odd) td {background-color: #cccccc} 

/* Footer */
  .phb .pageNumber {color: rgba(0, 0, 0, 0.5)}
  .phb .footnote {color: rgba(0, 0, 0, 0.5)}
  .phb:nth-child(odd):after{ 
    content          : '';
    position         : absolute;
    bottom           : -3px;
    left             : 10px;
    z-index          : -1;
    height           : 336px;
    width            : 100%;
    background-image : url('https://gmbinder.com/images/p7wvb4z.png');
    background-size  : cover;
}

.phb:nth-child(even):after{ 
    content          : '';
    position         : absolute;
    bottom           : -3px;
    left             : -10px;
    z-index          : -1;
    height           : 336px;
    width            : 100%;
    background-image : url('https://gmbinder.com/images/p7wvb4z.png');
    background-size  : cover;
}

/* Page Number */
.phb .pageNumber{
    position   : absolute;
    bottom     : 30px;
    width      : 50px;
    text-align : center;
}
.phb:nth-child(even) .pageNumber{
    left      : 12px;
}
.phb:nth-child(odd) .pageNumber{
    right      : 12px;
}

.phb .pageNumber.auto{
    position   : absolute;
    bottom     : 41px;
    width      : 50px;
    text-align : center;
}
.phb:nth-child(even) .pageNumber.auto{
    left      : 12px;
}
.phb:nth-child(odd) .pageNumber.auto{
    right      : 12px;
}

</style>

![Documento0_page-0002](https://user-images.githubusercontent.com/44923954/72222834-60cb5d00-3569-11ea-939b-e74e989d217c.jpg)
![Documento0_page-0001](https://user-images.githubusercontent.com/44923954/72222835-6163f380-3569-11ea-8f2b-be17e53bca48.jpg)

**Comment by ericscheid** [comment]
change the css for your custom `tr` to be this:

**`:not(blockquote) >`**`table tr:nth-child(odd) td { background-color: #cccccc }`

This says to format your n-odd rows only if the table is not contained by a block quote.

**Comment by Marcobertini6** [comment]
It's solved, ty very much!

**Comment by AlexeySachkov** [comment]
@Marcobertini6, can we close this issue then?
