### ISSUE TITLE
Why would you couple your entire application with your custom build tool?

### ISSUE THREAD

**Issue by tenthirtyone** [naturalcrit/homebrewery#885]
See the title. 

Why would you release an open source tool if you very clearly had no intention of anyone else ever working on it because you invented your own build tool to force your back end and front end into one codebase and then use less because obviously anyone who shows up to help fix this broken codebase just loves dealing with that change.

Really?

**Comment by tenthirtyone** [comment]
It is impossible to work on one part of this app without breaking half the damn thing. No wonder you abandoned your project.

**Comment by calculuschild** [comment]
What kind of response do you expect here? There _are_ others working on the project. You are free to contribute any PRs if you see things to fix, or build your own separate project the way you want it. Nobody is forcing you to contribute.

**Comment by AlexeySachkov** [comment]
Hi @tenthirtyone,

> because you invented your own build tool to force your back end and front end into one codebase and then use less because obviously anyone who shows up to help fix this broken codebase just loves dealing with that change.

I think the reason is that originally, this whole project was started and lead by @stolksdorf, who seems to be a JavaScript developer and for some reason (I don't know them), invented his own build system for his projects.

I was wondering about the reason by myself, but didn't pay a lot of attention to it since I'm not really familiar with JavaScript ecosystem.

As @calculuschild, you can always improve things by submitting a PR

**Comment by tenthirtyone** [comment]
@AlexeySachkov Yes, exactly. 

This is a decent front end application that is spiked into the dirt because it's endlessly coupled with a broken build tool that shoe horns mustache and LESS into react/webpack and is impossible to make it useful as anything more than an appliance without a non-trivial amount of work.

The only silver lining to this repo is that it is MIT licensed and anyone stuck doing this work can immediately re-license it to themselves. 

@stolksdorf couldn't have made worse decisions that ran counter to the majority of people using React. This is the same garbo that companies like IBM do when they take over an open source repo. It's a crappy thing to do to other developers and doesn't earn the lead title at all.
