### ISSUE TITLE
Markdown Broken

### ISSUE THREAD

**Issue by HeruAsatru** [naturalcrit/homebrewery#894]
There seems to be a problem with markdown, see several posts on reddit:

* https://www.reddit.com/r/homebrewery/comments/eyji4u/issue_describe_your_issue_here/
* https://www.reddit.com/r/homebrewery/comments/eyk0nc/monster_stat_blocks_stopped_working/
*  https://www.reddit.com/r/homebrewery/comments/eyk5xs/issue_statblocks_and_some_tables_are_broken/
* https://www.reddit.com/r/homebrewery/comments/eyl3uv/issue_table_formatting_broke/
* https://www.reddit.com/r/homebrewery/comments/eyldmk/issue_help_my_home_brews_are_broken/

**Comment by HeruAsatru** [comment]
The issue seems to arise when a html/markdown entity is directly above a markdown entity. The second markdown entity then doesn't work.

Examples:

1 - Breaks:
```
>|19 (+4)|22 (+6)|22 (+6)|17 (+3)|20 (+5)|18 (+4)|
>___
```

1 - Works:
```
>|19 (+4)|22 (+6)|22 (+6)|17 (+3)|20 (+5)|18 (+4)|
>
>___
```

2 - Breaks: 
```
<br/>
___
___
> ## Vampire
```

2 - Works: 
```
<br/>

___
___
> ## Vampire
```

**Comment by GaiusCoffee** [comment]
Version upgrade of dependency `marked` here: ac58833adfc46eee6885120e426361f12f144330 may be the cause of this issue.

**Comment by HeruAsatru** [comment]
@GaiusCoffee's answer is correct, Markdown Update has been reverted, Issue can be closed.
