### ISSUE TITLE
[feature] Use less data-uri

### ISSUE THREAD

**Issue by tcyrus** [naturalcrit/homebrewery#897]
less has a [`data-uri`](http://lesscss.org/functions/#misc-functions-data-uri) function which will take the file provided and make it into a base64 uri as part of the build step. This makes the source files easier to edit and makes resources easy to replace without changing the css result.

I have successfully tested this in another project of mine (https://github.com/tcyrus/homebrewery-standalone/blob/master/client/homebrew/phbStyle/phb.assets.less).

**Comment by calculuschild** [comment]
This is a good idea. Would you be interested in making a Pull Request for this?

**Comment by tcyrus** [comment]
I'll try to port over my work from the other repo and make a new PR for this.

**Comment by calculuschild** [comment]
Thanks! As you have seen, progress here isn't always as fast as we want (it's basically just me and occasional volunteers like you... the owner is missing...) so PRs are super welcome.

**Comment by calculuschild** [comment]
This has been done for a while now. Closing.
