### ISSUE TITLE
big fyle

### ISSUE THREAD

**Issue by marcuswallace1991** [naturalcrit/homebrewery#907]
Hi,
I will create a big fyle (150 pages), I read that it could be a problem because Homebrewery doesn't support big fyle. Is it true? If yes, how can avoid this problem? 
I'd like prefer to create a single fyle to use markdown, content hyperlink etc (If I split up in 2 parts, I lost hyperlinks).

**Comment by calculuschild** [comment]
Large files should work fine. I think there are several brews of 200+ pages that people have made.
