### ISSUE TITLE
how to remove color from the statistics bar

### ISSUE THREAD

**Issue by marcuswallace1991** [naturalcrit/homebrewery#909]
hello, I would like to remove the color from the statistics bar (but not from normal tables), what can I do?
Example (green bar with numbers):
<img width="595" alt="52" src="https://user-images.githubusercontent.com/42306281/76271454-dd806c00-6278-11ea-9d94-0439ca59f0f8.png">

**Comment by ericscheid** [comment]
Have you changed the brew code somehow, or are you not using the homebrewery monster-stat-block template? Normally, a monster stat block appears in a box with orange top/bottom borders and a peach background.

**Comment by marcuswallace1991** [comment]
yes, I used the normal code by removing the "<" command and adding red bars. This is the code I use:

## Death Hag

*Medium fiend, neutral evil*

<hr class='my-red-line'>


<div style='margin-top:5px'></div>

**Armor Class** 17 (natural armor)    
**Hit Points** 97 (13d8 + 39)      
**Speed** 30 ft. 

<hr class='my-red-line'>

<div style='margin-top:10px'></div>


|STR|DEX|CON|INT|WIS|CHA|
|:---:|:---:|:---:|:---:|:---:|:---:|
|16 (+3)|12 (+1)|16 (+3)|16 (+3)|14 (+2)|14 (+2)|

<hr class='my-red-line'>


<div style='margin-top:6px'></div>

**Skills** Arcana +5, Deception +4, Insight +4, Perception +4, Religion +5, Stealth +3    
**Senses** darkvision 90 ft., passive Perception 14  
**Languages** Abyssal, Common, Infernal, Sylvan   
**Challenge** 4 (1100 XP)

<hr class='my-red-line'>

<div style='margin-top:15px'></div>

***Innate Spellcasting.*** The hag’s spellcasting ability is Charisma (spell save DC 12, +4 to hit with spell attacks). She can innately cast the following spells, requiring no material components:  

<div style='margin-top:px'></div>

At will: *chill touch*, *minor illusion*    
1/day each: *hex*, *inflict wounds*. 



<div style='margin-top:px'></div>


***Magic Rune (10 souls).*** As long as the death hag is within 20 feet of her magic rune, she can cast animate dead as many times as the number of souls imprisoned inside the rune, or until it’s destroyed.  

<div style='margin-top:px'></div>

***Mimicry.***. The hag can mimic animal sounds and humanoid voices. A creature that hears the sounds can tell they are imitations with a successful DC 14 Wisdom (Insight) check. 

<div style='margin-top:5px'></div>



### ACTIONS
***Claws.*** *Melee Weapon Attack*: +5 to hit, reach 5 ft., one target. *Hit*: 12 (2d8 + 3) slashing damage.     

<div style='margin-top:px'></div>

***Illusory Appearance.*** The hag covers herself and anything she’s wearing or carrying with a magical illusion that makes her look like another creature of her general size and humanoid shape. The illusion ends if the hag takes a bonus action to end it or if she dies.   
The changes wrought by this effect fail to hold up physical inspection. For example, the hag could appear to have smooth skin, but someone touching her would feel her rough flesh. Otherwise, a creature must take an action to visually inspect the illusion and succeed on a DC 20 Intelligence (Investigation) check to discern that the hag is disguised.

<div style='margin-top:px'></div>
 
***Necrotic Curse (1/day).*** The hag targets a creature within 15 feet of her that she can see. Summoning foul and evil power from the Shadowfell, the hag channels it in a maleficent whisper that hits the target and drains its vitality. The target must roll a DC 14 Constitution saving throw. On a failed roll it takes 28 (7d8) necrotic damage, or half as much damage on a successful save. Constructs and undead are immune to this effect.



<div style='margin-top:100px'></div>

<img 
  src='https://s-media-cache-ak0.pinimg.com/736x/4a/81/79/4a8179462cfdf39054a418efd4cb743e.jpg' 
  style='width:1px' />


<div style='margin-top:600px'></div>

Death hags are foul creatures of extreme evil, whose main goals are to gain power and destroy life. A death hag doesn’t care for others and rejoices in pain and ruin. They study for long years to discover the secrets of the afterlife. They carry with them a powerful magic item, made after years of intense study, called a *magic rune*, which grants them power and renown with other hags. The *magic rune* usually takes the form of a black stone with a circular shape and is used by the hag to imprison the souls of those she has killed, magnifying her magical powers. In order to free the trapped souls, it’s necessary to destroy the rune. The hag is strongly tied to this magic item and will do anything to protect and preserve it. After they have created their *magic rune*, each hag starts to hunt victims to trap their souls.
  

<div style='margin-top:px'></div>


<div class='pageNumber'>53</div>
<div class='footnote'>APPENDIX B: MONSTERS</div>



<img 
  src='https://i.imgur.com/qKfYA3O.jpg
' 
  style='position:absolute; top:-40px; right:-45px; width:520px; mix-blend-mode:darken' />
  
  
<div class='footnote' STYLE="position:absolute; TOP:1101px; LEFT:85px; WIDTH:520px; color:#B89A67;">*Not for resale. Permission granted to print or photocopy this document for personal use only.* </div>

**Comment by marcuswallace1991** [comment]
can no one help me?

**Comment by ericscheid** [comment]
The stats table appears to immediately follow a `<hr>`, so you could try this:
````
<style>
.phb hr+table tr { background-color: none !important;}
</style>
````

**Comment by marcuswallace1991** [comment]
It seems not to work

**Comment by ericscheid** [comment]
I'd need to see the relevant section of code - if you link the share page I can look there.

**Comment by marcuswallace1991** [comment]
I did it.

**Comment by marcuswallace1991** [comment]
or https://homebrewery.naturalcrit.com/edit/6Oq4PiF3e

**Comment by ericscheid** [comment]
OK, I see what's happening now .. there's a `div` between the `hr` and `table` for spacing reasons. Also, I realise now that there's a big awful fancy border treatment for any `table` preceded immediately by a `hr`.

But since you are inserting custom html (for other reasons) that gives me the idea that you can tweak that for better targeting. Also helps to use valid CSS (either `background:none` or `background-color:transparent`, but not `background-color:none` as invalid — mea culpa ;-)

````
<style>
.phb div.monsterstats { margin-top:10px; }
.phb div.monsterstats+table tr { background: none; }
</style>

<hr class='my-red-line'>

<div class='monsterstats'></div>

|STR|DEX|CON|INT|WIS|CHA|
|:---:|:---:|:---:|:---:|:---:|:---:|
|16 (+3)|12 (+1)|16 (+3)|16 (+3)|14 (+2)|14 (+2)|

<hr class='my-red-line'>
````

**Comment by marcuswallace1991** [comment]
Not it's works! Thank you very much!

**Comment by calculuschild** [comment]
We should possibly add a new snippet to handle these "out of box" monster stat blocks.

**Comment by marcuswallace1991** [comment]
Sure, it would be great!
