### ISSUE TITLE
Less Files Not Updating CSS on Website

### ISSUE THREAD

**Issue by GilesPenfold** [naturalcrit/homebrewery#925]
I'm running a local version of Homebrewery on my computer, and am attempting to update the phb.style.less file to change some parts of the descriptive text box. It seems that any changes I make to the .less file do not update on the site. From what I can see, .less files are basically .css files using LessJS. Am I missing something with this? (I'm a C++ developer and JS/webdev stuff isn't my strong suite)

**Comment by calculuschild** [comment]
You may need to rebuild the project for changes to show up (`run script build`).

**Comment by GilesPenfold** [comment]
That seems to have fixed it, thank you!
