### ISSUE TITLE
[FEATURE]: Support for Static Page generation

### ISSUE THREAD

**Issue by Deastrom** [naturalcrit/homebrewery#956]
## Description

I would love to be able to maintain a campaign site for my adventures and love the formatting you are maintaining here.  When I found this tool I was looking for ways to do static page generation and hosting on github and/or gitlab.  Your markdown support and pdf generation is amazing and is exactly what I'm looking for.

Could you add support for generating static sites/pages for such campaign sites?  i.e. Hugo or Jekyll

**Comment by paige404** [comment]
Being able to generate that static page from a git repository would have a lot of potential for community development. 

For instance, if I have different chapters of my homebrewery spread across markdown files in a git repository, it would allow people to submit pull requests to suggest edits, add polish, what have you. Having an option to use homebrewery as a build tool to generate the resulting page/pdf would be _very_ powerful.

**Comment by paige404** [comment]
This may actually be similar functionality to #802

**Comment by calculuschild** [comment]
Closing, as this is covered by two other issues.

- Downloadable HTML + CSS bundle: #661 
- Auto-building from CLI: #802
