### ISSUE TITLE
Error with docker-compose startup

### ISSUE THREAD

**Issue by rjbprime** [naturalcrit/homebrewery#976]
Hi all,

Was hoping to get the docker version of this running on my laptop, for when I don't have internet access. Managed to clone the repo, then went into the folder and ran the ``docker-compose up -d`` command, and the terminal reported that during the ``Validating packages.json...`` section, it errored out saying that:

``error homebrewery@2.8.2: The engine "node" is incompatible with this module. Expected version "12.16.x". Got "8,17.0".
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this commond.
ERROR: Service 'homebrewery' failed to build: The command '/bin/sh -c yarn install --ignore-scripts' returned a non-zero code: 1``

It then drops me back to the terminal input.

What can be done to rectify this?

Kind regards.

**Comment by xerxes333** [comment]
As a temporary fix, change the Dockerfile node version `FROM node:12.16` 

(Side Note: I had to add `restart: always` on the line after `image: homebrewery` to my docker-compose.yml to get it to work on my machine but my docker knowledge is limited so YMMV)

**Comment by rjbprime** [comment]
Sorry I have left this so long. Coming back to it, just had to set up a new instance, so I follwoed this guide, but selected ```FROM node:14``` as the dockerfile node version. Seems to work. Closing this issue for now.
