### ISSUE TITLE
Suggestion of title of page mirror brew name

### ISSUE THREAD

**Issue by Mikle103** [naturalcrit/homebrewery#989]
Hi

I just checking if possible to have the <title></title> of the edit page set to the name of the Brew.

As I normally have many on my brews open at the same time and it gets cumbersome open each to find one you are looking for.

Just a suggestion.

Thanks in advanced.

**Comment by ericscheid** [comment]
The `<title>` element is set in https://github.com/naturalcrit/homebrewery/blob/master/client/template.js .. and is set to a static string.

Changing that line to `<title>Homebrewery: ${props.brew.title}</title>` might do the trick — I can't test that here.

**Comment by calculuschild** [comment]
This feature request is now live!
